### ISSUE TITLE
Mock up left nav for project details

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1002]

**Comment by MillenniumFalconMechanic** [comment]
Mock pushed to master branch in CZI Abstract. See Explore `Explore - Project Detail - 1600 - Project Information` artboard in `2.7 Explore data - Project Detail Nav` page.

![mock-left-nav.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/8087e373-ddfe-4067-879f-c171bcaba0f1)
