### ISSUE TITLE
Mock up citations page for project detail tab

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1003]

**Comment by MillenniumFalconMechanic** [comment]
Mock pushed to master branch in CZI Abstract. See `Explore - Project Detail - 1600 - Data Citation` artboard in `2.7 Explore data - Project Detail Nav` page.

![mock-data-citation.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/ad82ad19-e884-463c-8224-cb5bd74f65ee)
