### ISSUE TITLE
Update the Data Use Footer Banner text

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1013]
On the data browser footer:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/12425f13-7e2a-4b77-a445-d7b92cd6efa9)

Update the policy acceptance text:

From:

"By downloading any data I accept the HCA Data Use Policy."

To:

"By downloading data from the HCA DCP, you agree to the guidelines specified in the HCA Data Release Policy."

**Comment by NoopDog** [comment]
@lauraclarke wanted to check in with you on the language above. I felt the text we had in place as a bit rough so modified so that:

1. Changed from "I agree" to "you agree"
1. Changed from "Data Use Policy" to "Data Release Policy" as thats the name of the linked document. 

Do you have any objections to the change above or would you like to propose an alternative/clarification?

Cheers,
Dave

**Comment by lauraclarke** [comment]
Happy with the use to release change.

From a readability perspective, I to you makes sense.

I am less sure if I to you changes the legal nature of the statement, you might want to ask a suitable legal rep for that
