### ISSUE TITLE
On project detail page add file size to file counts

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1016]
For this section below add in the total file size for the format. 

E.g. Fastq      32/16.5GB
Consider adding labels for format Count/Size

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/0e9a45ab-a077-4354-885b-7b094c203594)

**Comment by MillenniumFalconMechanic** [comment]
Not needed.
