### ISSUE TITLE
For the tables and project detail, take disease from specimens (not samples) 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1026]
See https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/data-browser/901

**Comment by NoopDog** [comment]
This is part of the fix for #901

**Comment by MillenniumFalconMechanic** [comment]
@theathorn, @hannes-ucsc, further to our conversation during standup yesterday, I would like to confirm that no change is required in the DB for handling `Disease Status (Specimen)` in the data tables and the `Disease Status` term facet grouped under the `Specimen` facet.

We are currently taking disease from `hits[].samples[].disease` for the data tables, and from `termFacets.disease` for the term facet.

**Comment by hannes-ucsc** [comment]
Change that to `hits[].specimens[].disease` and `termFacets.specimenDisease` but only after https://github.com/DataBiosphere/azul/issues/1591 is addressed.

**Comment by MillenniumFalconMechanic** [comment]
Got it, thank you @hannes-ucsc.

**Comment by MillenniumFalconMechanic** [comment]
Ready for PR on branch `specimen-disease`.

**Comment by hannes-ucsc** [comment]
Can be deployed to `dev`
