### ISSUE TITLE
Add donor diseases (in addition to the current specimen disease) to the tables

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1027]
Donor disease status/
Specimen disease status

Be sure to take disease from specimen not sample.

**Comment by hannes-ucsc** [comment]
Let's leave this until we are officially permitted to deploy new features to HCA.

**Comment by theathorn** [comment]
@MillenniumFalconMechanic This is ready to go..

**Comment by NoopDog** [comment]
@theathorn @hannes-ucsc this is on staging and just about ready to go to prod. We have tested this against prod but I just want to confirm that we want this deployed to V1 Prod and that Azul is already setup to handle this. (It looks like Azul is but I just want to be sure. 

We have a separate ticket for the inability to sort by either field in a multi field table column. 

Cheers,
Dave
