### ISSUE TITLE
March 2020 Small "r" Release

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1039]

**Comment by theathorn** [comment]
1/30/20 call with Laura, Zina, Tim & Kylee:
  - All DCP Matrix Service output (loom) files need metadata edits before passing to Cumulus
  - SCP provides a UI for single file downloads and a curl command for bulk downloads
  - User downloadable matrices should contain cell annotations; these could be copied from SCP to a DCP S3 bucket or the Data Browser could provide a link to the SCP matrix download.

**Comment by theathorn** [comment]
test

**Comment by theathorn** [comment]
March 2020 release has been abandoned.
