### ISSUE TITLE
Can't navigate to page 2 if sorted by "Analysis Protocol" or "Disease Status"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1063]

**Comment by theathorn** [comment]
Go to Explore in prod and sort ascending in either "Analysis Protocol" or "Disease Status".
Navigate to bottom of page and arrow to navigate to page 2 is grayed out.

**Comment by MillenniumFalconMechanic** [comment]
Ready for PR on branch `null-search-after`.
