### ISSUE TITLE
Update Xena release links

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1106]

**Comment by theathorn** [comment]
Jing  10 hours ago
Problems:
2020-Mar-FetalMaternal-Adult-Blood-SS2 should go to https://singlecell.xenabrowser.net/datapages/?cohort=HCA%20Fetal%20Maternal%20Interface%20Smart-seq2

Jing  10 hours ago
2020-Mar-FetalMaternal-Fetal-Placenta-10x should go to https://singlecell.xenabrowser.net/datapages/?cohort=HCA%20Fetal%20Maternal%20Interface%2010x
