### ISSUE TITLE
Singlecell browser is using humancellatlas summary on index page

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1111]
## Software version (git hash, date, branch)

https://dev.singlecell.gi.ucsc.edu/

## Expected behavior

Singlecell browser index page should use summary from  https://service.dev.singlecell.gi.ucsc.edu/repository/summary

## Actual behavior

Singlecell browser index page is using humancellatlas.org summary 
https://service.explore.data.humancellatlas.org/repository/summary

## Steps to reproduce the behavior

go to https://dev.singlecell.gi.ucsc.edu/

<img width="1468" alt="Screen Shot 2020-03-24 at 2 42 59 PM" src="https://user-images.githubusercontent.com/46407464/77480477-06f3d880-6ddf-11ea-82a3-a4668936dd02.png">

**Comment by NoopDog** [comment]
@danielsotirhos can this be closed?

**Comment by dsotirho-ucsc** [comment]
@NoopDog Approved. The fix has been verified on https://dev.singlecell.gi.ucsc.edu/
