### ISSUE TITLE
Release - Direct link to Global gene search

### ISSUE THREAD

**Issue by TimothyTickle** [DataBiosphere/data-browser#1115]
## Expected behavior
Clicking on global gene search goes to the global gene search tab of SCP not the study search.

## Actual behavior
Clicking on global gene search goes to the study search tab.

**Comment by NoopDog** [comment]
Hi @TimothyTickle is there an update to the URL for the search we can use to go to the desired page in SCP?

**Comment by theathorn** [comment]
@TimothyTickle The Data Browser needs a separate URL for the "Search Genes" tab. The URL provided defaults to the "Search Studies" tab.

**Comment by theathorn** [comment]
March 2020 release has been abandoned.
