### ISSUE TITLE
Clarify the meanings of "Supplementary Links" vs "External Resources"

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1124]
Feedback is that these are confusing.
Let's add text descriptions, consider renaming or merging to the same page with headings.

Let's also figure out what to do when these are empty as they often are. Consider not showing or de-selecting the link.

**Comment by theathorn** [comment]
How about moving "Supplementary Links" into the "External Resources" tab which would then have 2 sections: "Supplementary Links" and "Analysis Portals". If one of these is empty don't show the associated section title. If both are empty don't show (or grey out) the "External Resources" tab itself.

Add some explanatory text to each section (if present):
  - Supplemental Links are contributor provided links to additional information
  - Analysis portals are external resources providing further analysis, such as visualizations
