### ISSUE TITLE
Replace/add "Publications" links in "Project Information" for datasets in the March release

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#1135]
please update the following datasets:

For dataset:
https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7
Publication:
Replace existing preprint link: with the recent publication:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1906-x

For the following dataset:
https://data.humancellatlas.org/explore/projects/f83165c5-e2ea-4d15-a5cf-33f3550bffde
add publication link: https://www.nature.com/articles/s41586-018-0698-6

For the following dataset:
https://data.humancellatlas.org/explore/projects/091cf39b-01bc-42e5-9437-f419a66c8a45
replace preprint link with the publication: https://www.nature.com/articles/s41587-019-0068-4

For the following dataset:
https://data.humancellatlas.org/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803
add publication link:https://www.nature.com/articles/s41467-019-12464-3

For the following dataset:
https://data.humancellatlas.org/explore/projects/f8aa201c-4ff1-45a4-890e-840d63459ca2
change publication link to: https://www.sciencedirect.com/science/article/pii/S0092867418311681?via%3Dihub

(apologies for free form ticket)

**Comment by theathorn** [comment]
@NoopDog The existing links are taken directly from the metadata, correct? So this ticket is asking for some sort of hard-coded override of the metadata?

**Comment by theathorn** [comment]
@NoopDog wrote:  We would have to add “Publications” to the json config and then look in the config instead of or in addition to the json that comes down from Azul for the project detail view.

**Comment by zperova** [comment]
@theathorn @NoopDog From the last call I thought this was feasible to update the publications. I don't exclude the possible that I misunderstood.

**Comment by NoopDog** [comment]
@zperova this is on ux-dev for your review.

**Comment by theathorn** [comment]
Links look good to me.
