### ISSUE TITLE
Implement social sharing cards for project detail pages

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1146]
Unfurl links in slack, twitter etc. 

https://www.michaelbromley.co.uk/blog/enable-rich-social-sharing-in-your-angularjs-app/

but maybe there is a newer way to do this

**Comment by MillenniumFalconMechanic** [comment]
Will resolve in DX.

**Comment by MillenniumFalconMechanic** [comment]
Will resolve in DX.
