### ISSUE TITLE
Remediate High minimist vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [DataBiosphere/data-browser#1164]
GitHub reports the following High severity vulnerability in HumanCellAtlas/data-browser. Please remediate by the end of Q2 Milestone 2.

**Description**
minimist

**Suggested Remediation**
Upgrade minimist to version 1.2.3 or later.

**Details**
minimist before 1.2.2 could be tricked into adding or modifying properties of Object.prototype using a "constructor" or "proto" payload.

**Comment by MillenniumFalconMechanic** [comment]
This requires upgrading Angular to the latest version, which includes breaking changes. See #1177.

**Comment by NoopDog** [comment]
Fixed by upgrade to Angular9.

```
 "minimist": {
      "version": "1.2.5",
      "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz",
      "integrity": "sha512-FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==",
      "dev": true
    },
```
