### ISSUE TITLE
10x integration test visible in the Explore projects

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#1183]
## Expected behavior 
10x 1 Run Integration Test should not be visible in the Data browser in prod
## Actual behavior 
10x 1 Run Integration Test should is visible in prod
## Steps to reproduce the behavior
Go to https://data.humancellatlas.org/explore/projects
Observe 10x 1 Run Integration Test appear in the first line in Projects 

![Screenshot 2020-05-14 at 15 16 24](https://user-images.githubusercontent.com/38244059/81945332-e59cb500-95f5-11ea-8375-7a8897bef099.png)

**Comment by theathorn** [comment]
I don't see any integration tests in the Data Browser.
I see 23 human projects, 28 overall, as expected.
Have you tried reloading your browser page?

**Comment by zperova** [comment]
@theathorn it was still visible earlier today but I can not see it now. Whatever it was, it has been fixed. Closing issue.

**Comment by hannes-ucsc** [comment]
To clear up the mystery: The integration test project will pop up *while* the integration test is running. It should disappear after the test is finished.
