### ISSUE TITLE
Change `/repository` to `/index` in Azul endpoint URLs

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-browser#1193]
`/repository` endpoints on the service lambda are being renamed to `/index` 
These endpoints would need to be updated in the data-browser. 

`/repository/files` -> `/index/files`
`/repository/bundles` -> `/index/bundles`
`/repository/samples` -> `/index/samples`
`/repository/projects` -> `/index/projects`
`/repository/summary` -> `/index/summary`
`/repository/files/order` -> `/index/files/order`

**Comment by hannes-ucsc** [comment]
@MillenniumFalconMechanic, @NoopDog

Arrg! Contrary to what I announced in stand-up today,  I accidentally merged the blocker DataBiosphere/Azul#1724 which will break https://dev.singlecell.gi.ucsc.edu/explore. I think we can live with a breakage for a couple days but no longer. Let me know if you don't have the bandwidth to solve this in that timeframe and I will revert.

**Comment by MillenniumFalconMechanic** [comment]
No worries @hannes-ucsc, I'll be able to make a start on this tomorrow morning at the latest.
