### ISSUE TITLE
Deploy data browser to cgl-dev environment via CGL GitLab

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1205]

**Comment by NoopDog** [comment]
HI @hannes-ucsc looks like this one is still failing as well.

0.4.8 python-dateutil-2.8.1 rsa-3.4.2 s3transfer-0.3.3 six-1.15.0 urllib3-1.25.9
 $ export BUCKET=s3://dev.explore.singlecell.gi.ucsc.edu
 $ if [ "$MAINTENANCE" = "true" ];then export SRCDIR=maintenance/; else export SRCDIR=dist/; fi
 $ aws s3 sync --acl public-read $SRCDIR $BUCKET --delete
 upload failed: dist/explore/3rdpartylicenses.txt to s3://dev.explore.singlecell.gi.ucsc.edu/explore/3rdpartylicenses.txt An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

https://gitlab.dev.singlecell.gi.ucsc.edu/clever-canary/data-browser/-/jobs/3832

**Comment by hannes-ucsc** [comment]
See https://github.com/humancellatlas/data-portal/issues/698#issuecomment-648323670

**Comment by NoopDog** [comment]
Working now.
