### ISSUE TITLE
improved error messages for withdrawn projects

### ISSUE THREAD

**Issue by lauraclarke** [DataBiosphere/data-browser#1209]
## Improved error messages for withdrawn projects

* As a data consumer
* I want that a project has been withdrawn rather than just disappeared
* so that can decide what I should do with the data I still have from a project

The project https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774 was withdrawn due to GDPR constraints but if someone goes to this URL the only message they get is a standard 404

Can this be changed to an error message that makes it clear it was removed at the request of the contributor? Even better would be a point to a contributor contact but I appreciate that is a stretch and would require a lot more work

## Definition of done

This ticket will be fulfilled when a withdrawn project returns a page which lets people know that the project was withdrawn rather than the standard not found 404 error message

**Comment by theathorn** [comment]
It would be nice to give the original title of the project and a reason, e.g. "withdrawn due to a GDPR request".
