### ISSUE TITLE
Handle gateway timeouts during manifest downloads

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#121]
How do we handle gateway timeouts when serving a manifest? If the client is slow, we will likely not be able to send the entire manifest in 30s. Similarly, if the manifest is larger than 10MB, another limit imposed by API gateway, the request will fail also.

The only solution is to store the manifest in S3 and redirect the user agent to a signed URL. This will also enable download resumption in browsers that support it.

**Comment by hannes-ucsc** [comment]
I misunderstood this issue during when we looked at it in the previous planning. I will not be able to implement it in this sprint.

It is not a bug, in my opinion, but a limitation of the architectural choices we made.
