### ISSUE TITLE
Front page search doesn't return results for "Precursors of human CD4 cytotoxic T lymphocytes identified by single-cell transcriptome analysis"

### ISSUE THREAD

**Issue by lauraclarke** [DataBiosphere/data-browser#1210]
# Front page search doesn't return results for "Precursors of human CD4 cytotoxic T lymphocytes identified by single-cell transcriptome analysis" 

- Software version - https://data.humancellatlas.org/ on 2020-06-03

The project https://data.humancellatlas.org/explore/projects/90bd6933-40c0-48d4-8d76-778c103bf545 with the title "Precursors of human CD4 cytotoxic T lymphocytes identified by single-cell transcriptome analysis" is offered as an autocomplete title on the front page and when selected should return the project selected on the main explore tab

e.g 
![Ischaemic sensitivity project selection](https://user-images.githubusercontent.com/8376192/83611355-c3ed7880-a578-11ea-962d-b8e614248b80.png)

But when you go to 
![front page screen shot](https://user-images.githubusercontent.com/8376192/83611203-90aae980-a578-11ea-9f39-b245638d0f5d.png)

You then get 

![Missing project](https://user-images.githubusercontent.com/8376192/83611447-e384a100-a578-11ea-967d-e275c9d8e5b8.png)

You should be able to reproduce this by typing cytotoxic or cd4 into the front page search box

This is the URL which produced this behaviour
https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22projectTitle%22%2C%22terms%22%3A%5B%22Precursors+of+human+CD4++cytotoxic+T+lymphocytes+identified+by+single-cell+transcriptome+analysis%22%5D%7D%5D

**Comment by MillenniumFalconMechanic** [comment]
Hi @lauraclarke,

I can see the Portal is not encoding the `+` correctly in the URL when it creates a link to the Browser. 

I will let you know when we have fixed this issue.

**Comment by NoopDog** [comment]
Hi @lauraclarke looks like we forgot to tell you this is fixed. You can now to to the portal search and type in "cyto" and select a project or publication and the project will be found. This was an error encoding the "+" in the project name on in the URL on the portal.

**Comment by theathorn** [comment]
Verified.

**Comment by lauraclarke** [comment]
thanks for fixing it
