### ISSUE TITLE
On browser table cells with ellipses "..." click to expand in the cell and push cell height instead of hover to reveal contents. 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1243]
- [ ] hand cursor on hover
- [ ] slightly darker on hover
- [ ] examine light underline normally and darker underline on hover (or just the latter)
- [ ] clicking expands to show all content.
- [ ] for multi value cells show content from both columns

**Comment by MillenniumFalconMechanic** [comment]
Resolved in DX.
