### ISSUE TITLE
Remove trailing comma of list values in data tables and project detail

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1250]

**Comment by MillenniumFalconMechanic** [comment]
Currently in the data tables:

1. `null` values are displayed as `Unspecified`
2. empty arrays are displayed as `Unspecified`
3. singleton arrays containing `null` are displayed as `Unspecified`
4. non-singleton arrays containing `null` drop the `null` value and only display the non-null values (causing the trailing comma problem - see screenshot below)

![Screen Shot 2020-07-14 at 10.52.43 AM.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/38055874-730f-4a3a-89d6-b48b768c3aaa)

For all four cases, `null` values are included in the facet term lists (displayed as `Unspecified`) and are included in the column distinct value counts.

This is long-standing behaviour in the Data Browser and we have only just noticed the trailing commas problem.

I initially masked the trailing comma by removing the `null` values from the non-singleton arrays. However, this resulted in an inconsistency where `null` was included in the facet term list and column distinct value count but missing from the data table column value.

I have rolled back my fix and would like to investigate this further.

An example is as follows (https://data.humancellatlas.org/explore/files?filter=%5B%7B%22facetName%22%3A%22genusSpecies%22%2C%22terms%22%3A%5B%22Homo+sapiens%22%5D%7D%2C%7B%22facetName%22%3A%22fileFormat%22%2C%22terms%22%3A%5B%22fastq.gz%22%5D%7D%2C%7B%22facetName%22%3A%22libraryConstructionApproach%22%2C%22terms%22%3A%5B%2210x+v3+sequencing%22%5D%7D%5D):

1. View the `Files` tab
2. Select `File Format` -> `fast.qz` and `Library Construction Method` -> `10x v3 sequencing` 

Note: 

1. `Paired End` facet lists `false` and `Unspecified` terms
2. The `Paired End` column distinct value count is `(2)`
3. `false` is the only value displayed in the `Paired End` column (in addition to the trailing comma)

The `hits` value returned from the endpoint looks like:

![Screen Shot 2020-07-14 at 10.47.19 AM.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/e70af867-7338-459f-b730-de057f9cc615)

To maintain consistency between the facet term list, column distinct value count and data table values, we can display `Unspecified` for `null` values in non-singleton arrays.

However, if we do this, it will add quite a number of `Unspecified` values to the data tables. We would like to validate that the `null` values in the non-singleton arrays are expected. @hannes-ucsc @theathorn

**Comment by hannes-ucsc** [comment]
In my opinion the translation from service response to display column value should be

- `[]` -> `""`
- `null` -> `"Unspecified"`
- `[null]` -> `"Unspecified"`
- `[null, false]` -> `"No, Unspecified"`
- `[null, true, false]` -> `"Yes, No, Unspecified"`

I agree that having many "Unspecified" values would visually clutter the table. Could we render it in a gray font, or replace it with an icon, like a white-on-gray question mark?

**Comment by NoopDog** [comment]
HI @hannes-ucsc the question is:

> We would like to validate that the null values in the non-singleton arrays are expected.

It seems to me that this is an error in Azul. Can you take a look and see if the unspecified in the given example should really be there?

I do not remember this being an issue before so I am curious if some recent change has caused the extra null values in the Azul response.

Cheers and Thanks,
Dave

**Comment by hannes-ucsc** [comment]
You are welcome!

Right, I guess I missed the question. In general, `null` values are to be expected, obviously, but in this case it seems odd that each file lists `null` in addition to `false`. I'll have @danielsotirhos investigate. https://github.com/DataBiosphere/azul/issues/2043

**Comment by hannes-ucsc** [comment]
I don't need to be assigned. We track this in the blocker.

**Comment by theathorn** [comment]
The Azul blocker ticket 2082 has been merged and will be available in dev soon.

**Comment by NoopDog** [comment]
@MillenniumFalconMechanic we are now unblocked to use unspecified when we have a null as in Hannes definition above for the CGL flow. 

For the current prod flow we need to just let the extra comma's display as we do now. So let's use the feature toggle for the 2.0 to replace null with Unspecified for the non singleton arrays.
