### ISSUE TITLE
Singlecell browser is not using Singlecell Azul API

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1252]
## Software version (git hash, date, branch)

https://dev.singlecell.gi.ucsc.edu/

## Expected behavior

Singlecell browser should be using the API of the Singlecell Azul.
e.g. https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=15&sort=projectTitle&order=asc

## Actual behavior

Singlecell browser is using the API of the Humancellatlas Azul.
e.g. https://service.dev.explore.data.humancellatlas.org/repository/projects?filters=%7B%7D&size=15&sort=projectTitle&order=asc
*Note domain (`humancellatlas.org` vs `singlecell.gi.ucsc.edu`) and endpoint (`/repository/projects` vs `/index/projects`)

## Steps to reproduce the behavior

Goto https://dev.singlecell.gi.ucsc.edu/explore/projects
Right click -> Inspect -> Network tab

![Screen Shot 2020-06-30 at 12 51 56 PM](https://user-images.githubusercontent.com/46407464/86171579-ca1c3980-bad1-11ea-93f1-a2054aef7386.jpg)

**Comment by NoopDog** [comment]
![image](https://user-images.githubusercontent.com/3239697/86173827-714ea000-bad5-11ea-8574-e330681cc524.png)

Hi @danielsotirhos this should be fixed.

**Comment by NoopDog** [comment]
@danielsotirhos can this be closed? Thanks

**Comment by dsotirho-ucsc** [comment]
Confirmed that the issue has been resolved. Closing ticket.
