### ISSUE TITLE
Updating withdrawn message on https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774

### ISSUE THREAD

**Issue by lauraclarke** [DataBiosphere/data-browser#1253]
### Updating the withdrawn message on https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774

Is there any chance the withdrawn message here could also point to the new location for the data https://ega-archive.org/studies/EGAS00001004375

thanks

**Comment by theathorn** [comment]
@NoopDog @MillenniumFalconMechanic : please apply fix to DCP/1 a.s.a.p.

**Comment by NoopDog** [comment]
HI @theathorn  Taking a look at this one. Will let you know today when we think we can get this out the door.
