### ISSUE TITLE
Data Browser has some missing table columns, filter dropdowns.

### ISSUE THREAD

**Issue by happyimadesignr** [DataBiosphere/data-browser#126]
Data Browser - Double check the table columns, filter dropdowns, and counts. Ex specimen missing things, experimental approach, molecule

┆Issue Number: HCAB-54

**Comment by happyimadesignr** [comment]
Looking at this I've pointed it out already in the last audit of the Data Browser filters and table columns, can you look at the designs @NoopDog?

**Comment by happyimadesignr** [comment]
@NoopDog was working on this, I'm going to take myself off this item. Lmk if you have questions.

**Comment by NoopDog** [comment]
duped by #161 closing
