### ISSUE TITLE
Create inventory of Azul response elements actually in use

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1271]
I would like to eliminate response elements from the Azul response that aren't used by the browser and have no general use for programmatic clients of the Azul API. To do this we would like to know which response elements DB uses and for what. This could be a simple spreadsheet that lists every reponse element and where in the UI it's being used. Something like

|endpoint|path|UI|
|---|---|---|
|/index/*|termFacets.organ|Facets - Tissue Type - Organ|
|/index/files|hits.files.name|Files tab - File Name column|

as a baseline for negotiating the scope of this ticket. I don't want to create a lot of work.

The inverse, a list of response element that are not used would also work.

**Comment by MillenniumFalconMechanic** [comment]
@hannes-ucsc, I have taken a first pass at the inventory. Let me know if there is any further information you require. The inventory is located at https://docs.google.com/spreadsheets/d/1Mp3KFins5fkxq-Xc4hXgrfFPL9prW6zTEL1BYUDM6Fw/edit?usp=sharing.

**Comment by hannes-ucsc** [comment]
Excellent. Thank you, Mim. To be triaged again for next steps.

**Comment by hannes-ucsc** [comment]
Question re [cell B25](https://docs.google.com/spreadsheets/d/1Mp3KFins5fkxq-Xc4hXgrfFPL9prW6zTEL1BYUDM6Fw/edit#gid=0&range=B25): What does `=== *` indicate?

Question re [cell C45](https://docs.google.com/spreadsheets/d/1Mp3KFins5fkxq-Xc4hXgrfFPL9prW6zTEL1BYUDM6Fw/edit#gid=0&range=C45): Is it intentionally empty?

Could you [@MillenniumFalconMechanic] make it so I can comment directly in the spreadsheet?

**Comment by MillenniumFalconMechanic** [comment]
Hi @hannes-ucsc, you should now be able to comment directly in the spreadsheet.

**Comment by hannes-ucsc** [comment]
Thank you. Effort continues in https://github.com/DataBiosphere/azul/issues/2356.
