### ISSUE TITLE
Update metadata manifests to contain "cell_suspension.biomaterial_core.biomaterial_id" field

### ISSUE THREAD

**Issue by ESapenaVentura** [DataBiosphere/data-browser#1288]
## User story

As a user, I would like to link the original's author IDs provided in the HCA's loom file with the cell suspension they come from so that I can link the metadata from that cell suspension to the actual cells/gene expression.

This field's name should be consistent with the output of the conversation here https://humancellatlas.slack.com/archives/C01360XN04S/p1595966378198200 (Conversation still in progress)

## Definition of done
- [ ] The metadata manifests include a field with the user-provided ID, named consistently with the name of the field in the  output matrix files

**Comment by theathorn** [comment]
@ESapenaVentura : This ticket has been moved to the Azul repo under https://github.com/DataBiosphere/azul/issues/2090.
