### ISSUE TITLE
Ascending and descending sort by cell count always has Unspecified at the end

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1296]
Steps to reproduce:

1) Visit: https://dev.singlecell.gi.ucsc.edu/explore/files?filter=%5B%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22Ischaemic%20sensitivity%20of%20human%20tissue%20by%20single%20cell%20RNA%20seq%22%5D%7D,%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22fastq.gz%22%5D%7D,%7B%22facetName%22:%22specimenOrgan%22,%22terms%22:%5B%22esophagus%22%5D%7D,%7B%22facetName%22:%22biologicalSex%22,%22terms%22:%5B%22male%22%5D%7D%5D&catalog=dcp1

2) Sort by cell count estimate ascendingly

3) Page forward to last page (3)

Rows with `Unspecified` cell count values are listed on the last page.

4) Sort by cell count estimate descendingly

5) Page forward to last page (3)

Actual: Rows with `Unspecified` cell count values are listed on the last page.

Expected: In one of the sort directions, preferably the descending direction, the Unspecified values be listed on the first page.

**Comment by hannes-ucsc** [comment]
Probably an Azul bug.

**Comment by dsotirho-ucsc** [comment]
Cannot reproduce the issue. `Unspecified` appears in sorted results as would expect for a value of `0`.

https://dev.singlecell.gi.ucsc.edu/explore/projects

### Tab: `Projects`, Sort: `Cell Count Estimate` Ascending:
![sort-asc](https://user-images.githubusercontent.com/46407464/90440137-939f7b80-e08b-11ea-8f41-0bfd83265aed.jpg)

### Tab: `Projects`, Sort: `Cell Count Estimate` Descending:
![sort-desc](https://user-images.githubusercontent.com/46407464/90440148-97330280-e08b-11ea-9e14-9c6543cca321.jpg)

### Azul `/index/projects`, Sort: `cellCount` Ascending

```
(.venv) daniel@Crispin ~/azul.sc $ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=1000&sort=cellCount&order=asc&catalog=dcp2' | jq '.hits[].cellSuspensions[].totalCells'
0
0
0
0
0
0
0
0
0
0
0
0
0
3185
3274
180
5355
1961
10561
1151
4149
951
1432
1718
1923
5862
2464
7115
2663
1638
981
1580
1391
865
2244
2544
3514
4000
9500
12404
44615
15175
16893
19916
20000
30952
27083
54166
30000
30000
93267
40025
66553
44000
230800
253910
274182
339089
1330000
1480000
```

### Azul `/index/projects`, Sort: `cellCount` Descending

```
(.venv) daniel@Crispin ~/azul.sc $ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=1000&sort=cellCount&order=desc&catalog=dcp2' | jq '.hits[].cellSuspensions[].totalCells'
1480000
1330000
339089
253910
274182
230800
44000
93267
40025
66553
30000
30000
30952
27083
54166
20000
19916
16893
44615
15175
12404
9500
4000
3514
2544
2244
5355
1961
10561
1151
4149
951
1432
1718
1923
5862
2464
7115
2663
1638
981
1580
1391
865
3185
3274
180
0
0
0
0
0
0
0
0
0
0
0
0
0
```

### Azul `/index/samples`, Sort: `cellCount` Ascending

```
(.venv) daniel@Crispin ~/azul.sc $ http 'https://service.dev.singlecell.gi.ucsc.edu/index/samples?filters=%7B%7D&size=1000&sort=cellCount&order=asc&catalog=dcp2' | jq '.hits[].cellSuspensions[].totalCells'
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
11
13
18
24
29
31
35
39
46
47
47
48
...
39249
49200
63100
480000
500000
500000
640000
690000
```

### Azul `/index/samples`, Sort: `cellCount` Descending

```
(.venv) daniel@Crispin ~/azul.sc $ http 'https://service.dev.singlecell.gi.ucsc.edu/index/samples?filters=%7B%7D&size=1000&sort=cellCount&order=desc&catalog=dcp2' | jq '.hits[].cellSuspensions[].totalCells'
690000
640000
500000
500000
480000
63100
49200
39249
...
48
47
47
46
39
35
31
29
24
18
13
11
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```

**Comment by hannes-ucsc** [comment]
My repro is for the files tab.

Some of the service responses you list  don't appear to be sorted:

```
(.venv) daniel@Crispin ~/azul.sc $ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=1000&sort=cellCount&order=asc&catalog=dcp2' | jq '.hits[].cellSuspensions[].totalCells'
0
0
0
0
0
0
0
0
0
0
0
0
0
3185
3274
180
5355
1961
10561
…
```

That's not sorted numerically and may warrant another issue.

**Comment by dsotirho-ucsc** [comment]
> My repro is for the files tab.

My mistake. Issue reproduced on `/index/files` endpoint and Azul ticket https://github.com/DataBiosphere/azul/issues/2174 created.

> Some of the service responses you list don't appear to be sorted:
> That's not sorted numerically and may warrant another issue.

This is due to the `/index/projects` endpoint containing hits with multiple `cellSuspensions` per hit. To solve this we might need `/index/projects` to sort on a new project field containing the sum of cell counts in all cell suspensions in the project. I'll open a ticket for this issue.
