### ISSUE TITLE
Move the catalog chooser to the top

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1297]
Could we move the catalog chooser UI to the top left or right? I'm currently comparing the catalogs and it turns out that scrolling to the bottom, selecting a different catalog and being sent to the top of the page disrupts the user experience. Ideally, I would like to click back and forth between catalogs with the top of the UI being visible because that's were the summary and column stats are.

**Comment by NoopDog** [comment]
done
