### ISSUE TITLE
Manifests generation fail on humancellatlas.org due to `catalog` parameter

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1301]
On HCA dev ( https://dev.data.humancellatlas.org/ ) and prod ( https://data.humancellatlas.org/ ) all 3 types of manifests ( Compact, Terra.bdbag, Full) fail to generate due to a `catalog` parameter being added to the call to Azul's `/fetch/manifest/files` endpoint.

Compact Manifest -> Select project, `Export Selected Data` button, `Request a File Manifest`
Terra.bdbag Manifest -> Select project, `Export Selected Data` button, `Export to Terra` 
Full Manifest -> Select project, Click download link in `Metadata` column

![manifest-fail](https://user-images.githubusercontent.com/46407464/90537659-6f4aaa00-e132-11ea-80cc-350d3752fb56.jpg)

**Comment by NoopDog** [comment]
Thanks Daniel, will take a look.
