### ISSUE TITLE
Add `dcp2ebi` to catalog choice UI

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1308]
Either hard-code that additional entry or derive the list from the `/openapi` endpoint

```
$ http https://service.dev.singlecell.gi.ucsc.edu/openapi | jq '.paths["/index/files"].get.parameters[]|select(.name=="catalog").schema.enum'
[
  "dcp2",
  "dcp1",
  "it2",
  "it1"
]
```

Could post-pone the dynamic approach until a simpler (and cheaper, /openapi is quite slow) endpoint is made available in https://github.com/DataBiosphere/azul/issues/2066.

**Comment by hannes-ucsc** [comment]
Azul `dev` is being reindexed right now.

**Comment by hannes-ucsc** [comment]
https://dev.singlecell.gi.ucsc.edu/explore/projects?filter=%5B%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D%5D&catalog=dcp2ebi

is showing results so it should be OK to go ahead with this ticket.

**Comment by NoopDog** [comment]
@hannes-ucsc this is on cgl-dev

https://dev.singlecell.gi.ucsc.edu/explore/projects?filter=%5B%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D%5D
