### ISSUE TITLE
No Data Found Message in Search Bar

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#131]
- [ ] Show no terms match.
- [ ] Show no last search result that had terms.
- [ ]  Wrap Text  for Search Terms

![Screen Shot 2018-06-26 at 10.06.19 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/381bfa55-4203-4156-a1a3-3d0e3e655458)

┆Issue Number: HCAB-153

**Comment by theathorn** [comment]
Fixed.
