### ISSUE TITLE
Download of HCA generated and contributor generated expression matrices using new Azul APIs

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1315]
Update design in https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?disco=AAAAKPFYQaE

**Comment by MillenniumFalconMechanic** [comment]
https://invis.io/SHNFL7IBF32#/437624556_02-Db-Explore-1440-Facet-Filter-Result-00_-2-
