### ISSUE TITLE
Move donor and specimen disease each to its own column

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1326]

**Comment by MillenniumFalconMechanic** [comment]
### Test Plan

For each data table:

1. Confirm both `Disease Status (Specimen)` and `Disease Status (Donor)` columns are displayed.
1. Confirm `Disease Status (Specimen)` no longer displays a split column value (eg a `(Specimen) / (Donor)`).
1. Confirm `Disease Status (Specimen)` column count no longer displays a split count value (eg `(Specimen) / (Donor)`).
1. Confirm tooltip descriptions for each column are correct.
1. Confirm counts for both columns are correct.
1. Confirm both columns are sortable.
