### ISSUE TITLE
Data download/export usage report

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1329]
From Ruchi,

Recently I'd given an update on the HCA DCP 2.0 work on the Broad side and one of the questions they asked was really interesting. Of the hundreds of unique visitors who land on the HCA Data Browser page -- I'm curious to learn what % of them end up:
1. downloading data
2. Using the matrix service
3. Exporting to Terra
4. Other?

**Comment by MillenniumFalconMechanic** [comment]
https://docs.google.com/document/d/1caxBaCSXV7LUMw9_FHMMfNG1AaATJg1oY-MgdCopWo8
