### ISSUE TITLE
Single file download from TDR

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1333]

**Comment by theathorn** [comment]
Consult with @hannes-ucsc on changes required.

**Comment by theathorn** [comment]
No Data Browser changes required as per @hannes-ucsc  for Databiosphere/azul#1764.

**Comment by hannes-ucsc** [comment]
But see https://github.com/HumanCellAtlas/data-browser/issues/1340

**Comment by MillenniumFalconMechanic** [comment]
Superseded by #1341.
