### ISSUE TITLE
Values of '0' displayed as 'Unspecified' instead of '0'

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1334]
Specifically when a `totalCells` field is specified with a value of `0` it is being displayed in the column `Cell Count Estimate` with a value of `Unspecified`.

This is problematic as it conflates cases where the field is present with a value of `0`, where the field does not exist (e.g. no cell suspensions), and where the field is present with a value of `null`.

![Screen Shot 2020-09-15 at 4 16 14 PM](https://user-images.githubusercontent.com/46407464/93274945-6a4c3b00-f770-11ea-83ae-2767077446c8.png)

**Comment by NoopDog** [comment]
Thanks Daniel! Yes looks like we are probably testing for a falsy value and not null explicitly. Will take a look.

**Comment by NoopDog** [comment]
@danielsotirhos this should be on CGL Dev, can you confirm this is now behaving as expected? Thanks!
D

**Comment by dsotirho-ucsc** [comment]
@NoopDog Fix looks good. Thanks!
