### ISSUE TITLE
Terra export screen shows file size unit as `undefined`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1337]
https://github.com/DataBiosphere/azul/issues/2225#issuecomment-694993446

**Comment by MillenniumFalconMechanic** [comment]
Total file size for error case is 719423031577868800000. Review `FileSizePipe` for formatting of file sizes greater than PB.

**Comment by theathorn** [comment]
That seems like an incorrect value (719 Exabytes?!). The total size of files in DCP2EBI is 11.55TB. We're a long ways from getting to even 1PB of data. @hannes-ucsc  Is this an Azul bug?

**Comment by hannes-ucsc** [comment]
I think this is primarily an issue with Azul. 

https://github.com/DataBiosphere/azul/issues/2285

Nevertheless, it might be useful to add those astronomic multipliers.

**Comment by NoopDog** [comment]
This is on CGL dev for review @MillenniumFalconMechanic

**Comment by theathorn** [comment]
LGTM.
