### ISSUE TITLE
Switch from /fetch/dss/files to /fetch/repository/files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1340]
Add `catalog` parameter and drop the `fileName` and `replica` parameters. While the latter two are are still supported, their main purpose is to override the defaults. Their current values ARE the defaults, which is redundant and limits our ability to change the defaults in the future.

**Comment by MillenniumFalconMechanic** [comment]
Hi @hannes-ucsc, the Data Browser uses `hits.files.url` in the Azul response as the base of the file download link. I can remove the `fileName` parameter that we append to this base.

The path (`/fetch/dss/files`) as well as the `replica` param are contained within the `hits.files.url` value (see screenshot below). It looks like the switch from `/fetch/dss/files` to `/fetch/repository/files` and the drop of the `replica` param need to happen Azul.

<img width="1190" alt="Screen Shot 2020-10-01 at 9 37 42 AM" src="https://user-images.githubusercontent.com/2446424/94838520-90a5e380-03ca-11eb-8116-557282e636aa.png">

**Comment by NoopDog** [comment]
@hannes-ucsc Yes, we can add the "catalog" parameter as well to the URL, however, what do you think about having Azul add this? 

This response is the answer to to a request that contained the catalog number. Having Azul add this makes it so the response can never get out of sync with the request.  If the URL is a "spec" for the file it seems to me at the moment that it likely should contain the catalog used to generate it. 

Having Azul crate the full URL would also make one less rule for other clients to use to interpret this response simplifying the API.

**Comment by hannes-ucsc** [comment]
How embarrassing. I forgot that we actually hand you the URL. Then there is nothing for you guys to do here. Sorry for wasting your time.

**Comment by hannes-ucsc** [comment]
@MillenniumFalconMechanic pointed out that DB is adding the fileName parameter to the download URLs. That's not necessary and I created #1341 to track the removal of that addition.
