### ISSUE TITLE
On DCP/1 "Export Selected Data" button disappears when pdf files selected

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1353]
On DCP/1, select "pdf" in the File Format menu. The "Export Selected Data" button will then disappear.

**Comment by MillenniumFalconMechanic** [comment]
Hi @theathorn, I believe this has been fixed by #1237. The fix is currently on staging and we can deploy to production once we have validated it is working correctly in staging.

**Comment by MillenniumFalconMechanic** [comment]
Hi @theathorn, can we close this ticket? The fix for #1237 has been deployed to production.

**Comment by theathorn** [comment]
This is fixed now.
