### ISSUE TITLE
Add "development_stage" to list of donor facets

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1364]
Derived from donor_organism.development_stage.ontology_label.

**Comment by kbergin** [comment]
Hi @theathorn any update on this?

**Comment by theathorn** [comment]
@kbergin This ticket is dependent on the web service work in progress:
  - https://github.com/DataBiosphere/hca-metadata-api/issues/26
  - https://github.com/DataBiosphere/azul/issues/2382
