### ISSUE TITLE
Exception when sorting by "Disease Status" column

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1392]
In the UCSC dev environment, click on the "Disease status" column and see the following error:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/ef3c9330-b693-48d7-a557-a241be4894cd)

**Comment by MillenniumFalconMechanic** [comment]
Add sortColumnKey to disease table config for v2 environments.

**Comment by NoopDog** [comment]
@theathorn this is on cgl dev for your review. 

https://dev.singlecell.gi.ucsc.edu/explore/projects?filter=%5B%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D%5D

Cheers,
D

**Comment by theathorn** [comment]
It doesn't crash any more, but doesn't appear to sort in any ascending or descending order that I can discern..
