### ISSUE TITLE
Manual setup of dcp2.data.humancellatlas.org instance for data browser

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1393]

**Comment by hannes-ucsc** [comment]
Gitlab: https://gitlab.azul.data.humancellatlas.org/clever-canary

Azul: https://service.azul.data.humancellatlas.org/

I'll start an email thread about AWS access.

Please review https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/blob/prod/terraform/gitlab/gitlab.tf.json.template.py#L523 and file Github ticket against Azul about what the DB-specific IAM permissions should look like on the `prod` instance of Gitlab.

**Comment by hannes-ucsc** [comment]
Please keep me advised about any changes you make to the `data.humancellatlas.org` hosted zone on the old AWS prod account.

**Comment by hannes-ucsc** [comment]
Scratch that. Sanger just switched the NS record so to make changes to that domain please file PR against https://github.com/DataBiosphere/dcp2/blob/develop/prod/route53.tf.json.

**Comment by NoopDog** [comment]
Got it thx. 
D

**Comment by NoopDog** [comment]
@hannes-ucsc I have created pr https://github.com/DataBiosphere/azul/pull/2578 for the updates to the resource.
