### ISSUE TITLE
On project list for DCP2  determine presence of matrices on a project from project response instead of bucket head requests. 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1399]

**Comment by NoopDog** [comment]
@hannes-ucsc @theathorn  we will need a way on the Azul projects response (if its not there already) to determine if a project  has CGMs or HCA matrices. 

Would be great to just have a boolean for each e.g. hasCGMs and hasProjectMatrices  or similar. 

A single "hasMatrices" would also work. 

We do not need the list of matrices just information about the existence so we can show or not the matrix download icon.  

Can you indicate if this exists on the DCP2 projects response and what the fields are or create a blocking ticket in Azul  and block this ticket with it?

Thanks, Dave

**Comment by MillenniumFalconMechanic** [comment]
Use `hits[*].projects[0].contributorMatrices` and `hits[*].projects[0].matrices` to determine existence on project list.
