### ISSUE TITLE
Integrate with system logging

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-browser#14]
Contact Matt Weiden for information

┆Issue Number: HCAB-10

**Comment by theathorn** [comment]
Related to #29 and #30.

**Comment by theathorn** [comment]
Dave to talk to Matt Weiden.

**Comment by theathorn** [comment]
MattW: Just generate logs in a CloudWatch logs group.

**Comment by NoopDog** [comment]
Hi @mweiden , @theathorn Is this what we need?
I have made this for dev and can enable for the other environments if this is sufficient.

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/elasticbeanstalk/HCA-DataBrowser-Dev/

Cheers,
D

**Comment by mweiden** [comment]
@NoopDog Yes, looks great. The one wrinkle here is that, without configuration, the [log retention policy enforcer](https://github.com/HumanCellAtlas/logs/tree/master/apps/log_retention_policy_enforcer) currently will change your log group retention policy to the default 90 days. If you would prefer to keep your current TTL, I can change the enforcer to not change TTLs less than the default.

Thoughts?

**Comment by NoopDog** [comment]
OK so we have:

Dev
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/elasticbeanstalk/HCA-DataBrowser-Dev/

Integration
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/elasticbeanstalk/HCA-DataBrowser-Integration/

Staging
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/elasticbeanstalk/HCA-DataBrowser-Staging/

Prod
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/elasticbeanstalk/HCA-DataBrowser-Prod/

@mweiden Is there anything else I need to do to close this ticket?

Cheers,
D

**Comment by mweiden** [comment]
Nope.
