### ISSUE TITLE
Setup Prod catalogs 

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1403]
The Prod Data Browser should show only 2 Catalogs: "DCP1" and "DCP2", with DCP2 pre-selected as the default.

"DCP1" will contain all DCP/1 primary and analysis data, and pre-generated project matrices from the Matrix Service.

"DCP2" will contain all primary data from DCP/1 (28 projects) and newly submitted data (16 projects), contributor-generated matrices, and new analysis for all projects.

**Comment by NoopDog** [comment]
@theathorn what milestone is this? This is tagged as 1a but includes "new analysis for all projects" for the DCP2 catalog.

>"DCP2" will contain all primary data from DCP/1 (28 projects) and newly submitted data (16 projects), contributor-generated matrices, and new analysis for all projects.

**Comment by theathorn** [comment]
"DCP2" initially will contain just primary data and CGMs. New analysis data will follow in phases.
I put the milestone as "Phase 1a" since you need a prod DCP1 catalog, but strictly this could be "Phase 1b" if you are going to auto-select the DCP1 catalog for Phase 1a.
