### ISSUE TITLE
LungMAP instance of Data Browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1407]
Setup URL at e.g. lungmap.net/explore, or similar, that auto-selects the LungMAP catalog.

**Comment by theathorn** [comment]
@NoopDog @MillenniumFalconMechanic Can we schedule this work in the next couple of weeks?

We would want a Data Browser instance at data-browser.dev.lungmap.net with minimal branding:
  - replace the HCA logos at the top and bottom of the page
  - remove the DCP 1.0 / DCP 2.0 Preview banners
  - I think it is OK to leave the Explore/Guides/Metadata/../APIs links with the HCA content for now

**Comment by MillenniumFalconMechanic** [comment]
@theathorn, we will prioritize this.
