### ISSUE TITLE
In metadata dictionary Indicate array data types.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1417]
https://dcp2.data.humancellatlas.org/metadata/dictionary/project/project#contributors

# Included Modules

Project contributors for example  is an array of contacts but we only list "contact"
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/44296ffa-c6bb-4815-85bb-f733992ebdd3)

# Simple Properties

Show type of array e.g "string array"
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/b4672d95-ecd3-44b8-9de3-0446739adf73)

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog, recreate in DP.
