### ISSUE TITLE
Modify donor organism age format

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/data-browser#1450]
A hit response from Azul will look as follows …
```
{
    "hits": [
        {
            "donorOrganisms": [
                {
                    "organismAge": [
                        {
                            "value": "8",
                            "unit": "week"
                        }
                    ],
                   …
                }
            ]
        }
    ]
…
}
```
… making the `organismAge` entry a dictionary with `value` and `unit`. 
This will happen once [Azul#1907](https://github.com/DataBiosphere/azul/issues/1907) lands.

**Comment by hannes-ucsc** [comment]
We should coordinate the rollout, @MillenniumFalconMechanic. Are you planning on supporting both formats (old and new) or do we need to essentially deploy this in lock-step with the Azul changes?

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Let's focus on this as a high priority after the holidays."
