### ISSUE TITLE
Remove v1-specific tags, triggers and dimensions from GTM/GA

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1455]
#### Dimensions
* `fileType`
* `releaseName`

###### Dataset Download

- Category: "Dataset"
- Action: "Download"
- Label: `datasetName`

- Entity URL: `http://path/to/download`
- File Format: `relatedEntityType`
- File Name: `relatedEntityId`
- File Type: `fileType`
- Release Name: `releaseName`

###### Dataset Copy to Clipboard

Copy to Clipboard events are configured as:

- Category: "Dataset"
- Action: "Copy to Clipboard"
- Label: `datasetName`

- Entity URL: `http://path/to/download`
- File Format: `relatedEntityType`
- File Name: `relatedEntityId`
- File Type: `fileType`
- Release Name: `releaseName`

###### Dataset Visualize

Visualize events are configured as:

- Category: "Dataset"
- Action: "Visualize"
- Label: `datasetName`

- Entity URL: `http://path/to/visualization-tool`
- Release Name: `releaseName`
- Tool Name: `toolName`

**Comment by NoopDog** [comment]
Complete
