### ISSUE TITLE
Point dev.data.humancellatlas.org to cgl-dev instance

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1470]

**Comment by theathorn** [comment]
Redirect cgl-dev to dev.

**Comment by theathorn** [comment]
We are going to switch from using dev.singlecell.gi.ucsc.edu back to dev.data.humancellatlas.org instead.

**Comment by MillenniumFalconMechanic** [comment]
Superseded by #2235 (and see Portal [#1355](/HumanCellAtlas/data-portal/issues/1355)).
