### ISSUE TITLE
Expose Dockstore link to pipeline used for analysis

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1472]
Benedict brought this up during demo. Will fill in details later.

**Comment by melainalegaspi** [comment]
@hannes-ucsc Spike:1 to fill in details

**Comment by hannes-ucsc** [comment]
@kbergin, my PI suggested this. It makes total sense but it is a long game feature since it may require a metadata schema change, most likely to `analysis_protocol`. Is there a even a Dockstore image that we can point to for the pipelines that you use for analysis?

**Comment by MillenniumFalconMechanic** [comment]
Hi @theathorn, is there a blocker in Azul for this?

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
