### ISSUE TITLE
Accessing Project Matrices Download Script

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1477]
See https://humancellatlas.slack.com/archives/C51A8EDQQ/p1608573983025200

The links such as https://data.humancellatlas.org/project-assets/project-matrices/8185730f-4113-40d3-9cc3-929271784c2b.homo_sapiens.loom are no longer provided.

**Comment by theathorn** [comment]
Dup of #1435?

**Comment by NoopDog** [comment]
Slack question answered.
