### ISSUE TITLE
'catalog' parameter not sent to Azul after switching sort order

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1480]
## Software version (git hash, date, branch)

Dev - https://dev.singlecell.gi.ucsc.edu/explore/
Prod - https://data.humancellatlas.org/explore/

## Expected behavior

Clicking to reverse a column's sort order should preserve the catalog selection.

## Actual behavior

Clicking to reverse a column's sort order drops the 'catalog' parameter from the Azul request. 

## Steps to reproduce the behavior

- Go to https://data.humancellatlas.org/explore/files?catalog=dcp1
- Note 35,768 pages after Browser makes request to Azul with `catalog=dcp1` included.
- Click to change sorting from File Name ascending to descending.
- Note 18,971 pages after Browser makes request to Azul without `catalog=dcp1`

**Comment by dsotirho-ucsc** [comment]
![Screen Shot 2021-01-04 at 7 10 32 PM](https://user-images.githubusercontent.com/46407464/103602629-5bc19500-4ec1-11eb-915d-5a17045cb6ce.png)

**Comment by NoopDog** [comment]
Thanks @danielsotirhos will take a look. Cheers, D

**Comment by dsotirho-ucsc** [comment]
Confirmed issue has been resolved on https://dev.singlecell.gi.ucsc.edu/explore/
