### ISSUE TITLE
Dynamically determine the list of available catalogs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1491]
Azul will provide an endpoint to determine the list of catalogs and to which atlas each catalog belongs.

**Comment by MillenniumFalconMechanic** [comment]
As per @hannes during standup:

1. DB defines its own `atlas` configuration variable per instance. 
1. Catalogs across all atlases are always returned from `/index/catalogs` and DB will filter the response according to its `atlas` configuration variable.
1. If the set of catalogs for the configured atlas contains the `default_catalog` returned from `/index/catalogs`, use `default_catalog` as the default catalog value.
1. If the set of catalogs for the configured atlas contains the `default_catalog` returned from `/index/catalogs` and the set length is greater than one, throw an error.
1. If the set of catalogs for the configured atlas contains the `default_catalog` returned from `/index/catalogs` and the set length is one, default catalog is the only catalog in the set.

**Comment by MillenniumFalconMechanic** [comment]
1. Catalogs flagged as internal are visible in the catalog chooser on dev only
1. If catalog is not specified in query string:
   1. if atlas is `hca` and set of catalogs returned from Azul contains `dcp1`, default to `dcp1` (ie prod)
   1. otherwise use default catalog as per Azul response

**Comment by NoopDog** [comment]
2 above, can simplify once it is decided how the dcp1 catalog, and project versions in general will be handled moving forward.
