### ISSUE TITLE
Write unit tests for the indexer

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#15]
We should have a set of tests for the indexer

**Comment by alex-hancock** [comment]
There are three types of unit tests we'd like to run:
1. Consistency check - does the indexed data resemble the input data?
2. Update verification - new bundles overwrite old bundles, old bundles have no effect on new bundles. 
3. Concurrent specimen indexing - if two different bundles are submitted that apply to the same specimen, does the result in the index reference both bundles?

Each of these tests are covered in their own issue:
1. Consistency check - #158
2. Update verification - #159
3. Concurrent specimen indexing - #160
