### ISSUE TITLE
Remove default species selection

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/data-browser#1501]
The default species selection is making discovery of the non human files more difficult and also making the discovery of files that are not tagged with species more difficult. 

An alternative is to move the species selection to the export step and force species selection by the user (if species is not selected already),  before allowing export to Terra, the file manifest download, or the bulk download curl command.

**Comment by melainalegaspi** [comment]
@theathorn to consult with HCA leadership.

**Comment by NoopDog** [comment]
@theathorn I updated the description with some background.

**Comment by theathorn** [comment]
OK to remove the default species selection and add user selection to the export steps.

**Comment by NoopDog** [comment]
Thank you!
