### ISSUE TITLE
Explore DragEvent typing in Safari 13.1

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1503]
#### DragEvent Typing Errors
* https://stackoverflow.com/a/58439985
* https://github.com/NationalLibraryOfNorway/ngx-mime/issues/238 and https://github.com/NationalLibraryOfNorway/ngx-mime/commit/78f5049935b4f02510ba3081c8e9e3268036091b

#### Safari 13.1 Usage
[0.85%](https://caniuse.com/usage-table)

**Comment by NoopDog** [comment]
User is reporting that there is  a problem on Chrome 87 as well:

https://www.whatsmybrowser.org/b/MHITN

**Comment by MillenniumFalconMechanic** [comment]
I am unable to reproduce this defect on Catalina/Chrome 87.

#### Steps:
1. Navigate to the projects tab
1. Click on “Tissue Type” drop down in facet browser
1. Click on “immune system” checkbox under “Organ” in the menu

#### What happened:
1. DB filters projects to “Census of Immune Cells”.

#### What I expected:
1. DB filters projects to “Census of Immune Cells”.
