### ISSUE TITLE
Generalize HttpState to handle client-side error state

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1504]
* Move to separate, general `ErrorModule`
* Refactor naming of actions, effects, state, reducer to match generalization
* Create specific `HttpModule`
* Review locations of `ErrorComponent` and `ErrorEffects`
* Move ErrorComponent, ErrorLayoutComponent and NotFoundComponent to error module

**Comment by NoopDog** [comment]
superseded by dx
