### ISSUE TITLE
Add metadata fields to file manifest and metadata tsv

### ISSUE THREAD

**Issue by ESapenaVentura** [DataBiosphere/data-browser#1508]
## User story

* As an end-user that wants to use the HCA data
* I want to understand how fastq files are grouped together and understand the distribution of the barcodes in the files
* so that I can run my analysis pipelines automatically, extracting the information from the metadata

## Definition of done

- [ ] The following fields are added to both the file manifest and the project metadata tsv:
    - `cell_barcode.barcode_read`
    - `cell_barcode.barcode_offset`
    - `cell_barcode.barcode_length`
    - `cell_barcode.white_list_file`
    - `umi_barcode.barcode_read`
    - `umi_barcode.barcode_offset`
    - `umi_barcode.barcode_length`
    - `umi_barcode.white_list_file`
    - `sequence_file.lane_index`

**Comment by theathorn** [comment]
Incorrect repo - closing,
Replaced by DataBiosphere/azul#2781.
