### ISSUE TITLE
"Sample Id" value not fully visible for long strings

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1514]
Project: https://data.humancellatlas.org/explore/files?catalog=dcp1&filter=%5B%7B%22facetName%22:%22projectTitle%22,%22terms%22:%5B%22Single%20cell%20profiling%20of%20human%20induced%20dendritic%20cells%20generated%20by%20direct%20reprogramming%20of%20embryonic%20fibroblasts%22%5D%7D%5D

On the Files tab some "Sample Id" values such as "specimen_from_organism_116965f3-f094-4769-9d28-ae675c1b569c" for "sample type" = "specimens" show only part of the value in my browser (Chrome on Windows 10). If I drag select the value and right click then I can see/copy teh whole string.

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/400d9da7-8362-4382-9d91-8f97e83a2e0d)

**Comment by NoopDog** [comment]
@theathorn This is on dev for your review. 


For both the samples tab and files tab the sample ID now shows an elipsis when it is larger than the available space and hovering over the cell shows the whole id in a tooltip.

**Comment by theathorn** [comment]
LGTM.
