### ISSUE TITLE
Move "Organ" and "Model Organ" each to their own column in the tables

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1529]

**Comment by MillenniumFalconMechanic** [comment]
### Test Plan

For each data table:

1. Confirm both `Organ` and `Model Organ` columns are displayed.
1. Confirm `Organ` no longer displays a split column value (eg `Organ / Model Organ`).
1. Confirm `Organ` column count no longer displays a split count value (eg `(Organ Count) / (Model Organ Count)`).
1. Confirm tooltip descriptions for each column are correct.
1. Confirm counts for both columns are correct.
1. Confirm both columns are sortable.
