### ISSUE TITLE
Add support for `hits[].samples` grouped by sample entity type

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1534]
Currently the Azul response for the `/index/projects` and `/index/files` endpoints contain a `hits[].samples` field that is a polymorphic aggregate of the samples attached to each hit (a project or file).

When different types of samples (e.g. cellLines & specimens) are aggregated together the `hits[].samples` field ends up with extraneous `null` values due to a field existing for one sample type and not another. Example: `cellLines` have a `cellLineType` field but `specimens` do not, so aggregating these together produces a `cellLineType` value such as `['primary', null].

![Screen Shot 2021-02-17 at 3 15 52 PM](https://user-images.githubusercontent.com/46407464/108283279-dbd15080-7137-11eb-994d-d54a1b372e79.png)

Azul ticket https://github.com/DataBiosphere/azul/issues/2071 will change the `hits[].samples` field so that the aggreation is grouped by `sampleEntityType`, similar to how `hits[].protocols` is grouped by protococl type.

![Screen Shot 2021-02-17 at 3 17 22 PM](https://user-images.githubusercontent.com/46407464/108283376-06bba480-7138-11eb-9a88-d744f0b4d3a3.png)

This will result in `hits[].samples` changing from a list of 1 dictionary with the combined set of fields for the hit's sample entity types into a list of N dictionaries, 1 per sample entity type, with each having only the fields relevant to that sample entity type.

If this change is not currently supported, the Data Browser will need to:
    - Look over all dictionaries in `hits[].samples` when obtaining field values (e.g. the first dictionary in `hits[].samples` could be for one or more `cellLines` sample entity type and would not have a `disease` field, but the next dictionary could.)
    - Combine values from `hits[].samples` (e.g. if there are 2 `hits[0].samples` dictionaries, then both `hits[0].samples[0].effectiveOrgan` and `hits[0].samples[1].effectiveOrgan` would need to be comma-string concatenated for the display result.
    - Coordinate with the Azul team on the release of #2071 if the DB change can't go out live before the Azul change.

Note that the Azul response for the `/index/samples` endpoint will not be affected by this change as the `hits[].samples` field for each hit will remain a singleton.

**Comment by dsotirho-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/2071 has been deployed to dev.
Data Browser appears to be reading the `hits[].samples` values correctly with the new grouping by sample type.

![Screen Shot 2021-04-20 at 1 27 12 PM](https://user-images.githubusercontent.com/46407464/115460567-43aa2300-a1dd-11eb-8c22-5577e771ef7b.png)

**Edit**: Note that screenshot is actually incorrect in indicating the `organ` value is populated from the `hits[].samples[].organ` response field. Instead the value is currently populated from the `hits[].specimens[].organ` response field.

**Comment by MillenniumFalconMechanic** [comment]
Thanks @danielsotirhos. I'll take a look as well.

**Comment by dsotirho-ucsc** [comment]
Hi @MillenniumFalconMechanic , after your investigation please confirm if this does or does not require code changes to the Data Browser. Your response will effect whether we can deploy https://github.com/DataBiosphere/azul/issues/2071 independently (to prod) or if we need to coordinate its deploy with you.

**Comment by MillenniumFalconMechanic** [comment]
Hi @danielsotirhos, it looks like the Data Browser does not require any code changes to support the updated grouped format of hits[].samples. However, in your screenshot [above](https://github.com/HumanCellAtlas/data-browser/issues/1534#issuecomment-823583683), you have connected the organ column to a subvalue of hits[].samples[] whereas we bind this value from hits[].specimens. Is this intentional, that is, does the Data Browser now need to update how we bind the organ (and organ part) values to take from hits[].samples[] and not hits[].specimens?

**Comment by dsotirho-ucsc** [comment]
> you have connected the organ column to a subvalue of hits[].samples[] whereas we bind this value from hits[].specimens.  ... does the Data Browser now need to update how we bind the organ (and organ part) values to take from hits[].samples[] and not hits[].specimens?

Hm, I'm not certain. Azul uses the samples organ for the `organ` facet, and specimen organ for the `specimenOrgan` facet. Using the organ value from `hits[].specimens.organ` does have the benefit of providing an `organ` value for the row especially on the  `Samples` tab where unless the sample being listed is a specimen it wouldn't have an organ value.

@hannes-ucsc do you have thoughts on this?

**Comment by dsotirho-ucsc** [comment]
After discussion with @hannes-ucsc we decided not to request the Data Browser to change the binding of `organ` from `hits[].specimens`.
