### ISSUE TITLE
File download stats report

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1535]
If it's easy, I wonder if you could pull me some stats for use of the DCP portal.  I'm interested in the following:
* Downloads of raw sequence data (fastqs), processed sequence data (aligned BAMs), and DCP matrices from the DCP1 site
* Downloads of raw sequence data, processed sequence data, DCP matrices, and contributor-generated matrices from the DCP2 preview site.

I want to look at each category separately (so 3 items from the first bullet and 4 items from the second, total of 7 separate things).  For the DCP2 preview site, we obviously only go back to mid-December.  If we can go back further on the DCP data (to whenever we started collecting metrics) that'd be god.   If it makes sense to show totals by month, that's helpful but not necessary.  I'd like you to not put a lot of effort into this.

**Comment by MillenniumFalconMechanic** [comment]
https://docs.google.com/document/d/1Lk9Npa4QQUgfSL27QNZTdYXhq2V49C2UQjTpfbrhKDY
