### ISSUE TITLE
Button to copy curl command has misleading label 

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1543]
![image](https://user-images.githubusercontent.com/5143256/108932610-834df780-75fe-11eb-904a-e1b5d2af851e.png)

Should be "Copy command" not "Copy link"

**Comment by MillenniumFalconMechanic** [comment]
@hannes-ucsc, got it, thank you.

**Comment by MillenniumFalconMechanic** [comment]
Related to #1532 and humancellatlas/data-portal#852.
