### ISSUE TITLE
Change manifest flow to yield Azul URL as opposed to signed manifest URL

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/data-browser#1587]

**Comment by NoopDog** [comment]
Hi @theathorn should this ticket be titled "Change `curl` manifest flow to yield Azul URL as opposed to signed manifest URL?

Also, can we get an explanation of the requested change to the way we use the API

Thank you!
D

**Comment by theathorn** [comment]
No change to the Data Browser is required except the expiration wording specified in #1565.
