### ISSUE TITLE
Prepend `/fetch` to file URLs

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1596]
As part of https://github.com/DataBiosphere/azul/issues/2908 we will be removing the `/fetch` part from the URL of data files because most users will want the regular (non-fetch version) URLs. Any `/repository/files/{uuid}` URL can be converted to its `/fetch` counterpart by prefixing the URL path.

**Comment by hannes-ucsc** [comment]
To avoid a deployment co-dependency between this and the blocking Azul issue (https://github.com/databiosphere/azul/issues/2908), we should implement this in a way that prepends `/fetch` unless that prefix is already present. That way we can deploy this first and then deploy the Azul change.

**Comment by hannes-ucsc** [comment]
I'll invert the blocking relationship to reflect this better.

**Comment by MillenniumFalconMechanic** [comment]
Hi @danielsotirhos, can you clarify what you mean by a "regular URL", and how is it different from a URL that includes `/fetch`?

**Comment by dsotirho-ucsc** [comment]
Updated ticket description. "Regular URL" was intended to mean a URL specifying the non-fetch version of the repository files endpoint. (`/repository/files/{uuid}` instead of `/fetch/repository/files/{uuid}`)

**Comment by MillenniumFalconMechanic** [comment]
#### Test Plan

I have updated the fetch URLs for direct downloads and project matrix downloads; confirm both downloads work as expected.
