### ISSUE TITLE
[BUG] Search by project title doesn't appear to work

### ISSUE THREAD

**Issue by mshadbolt** [DataBiosphere/data-browser#1627]
## Software version 
Current live version of the browser

## Expected behavior
When typing keywords or the exact project title one would expect that project to be available to be selected

## Actual behavior
When typing the exact title the message 'oops we can't find that project..' appears

## Steps to reproduce the behavior
1. Go to the main data.humancellatlas.org browser or in the search bar of the 'explore tab'
2. Start typing the exact project title such as 'Ischaemic sensitivity...'

![Screenshot 2021-03-30 at 11 03 32](https://user-images.githubusercontent.com/13007987/112914394-9ac15880-9147-11eb-818e-267d50e9da7d.png)

![Screenshot 2021-03-30 at 11 03 22](https://user-images.githubusercontent.com/13007987/112914398-9d23b280-9147-11eb-8d55-f3d43ad350b8.png)

![Screenshot 2021-03-30 at 11 03 09](https://user-images.githubusercontent.com/13007987/112914401-9eed7600-9147-11eb-95f3-c59c1fa8f9c8.png)

I think this kind of search used to work but I am not really sure when it stopped working

**Comment by theathorn** [comment]
It would be very useful to search by either the "Project Title" or the "Project Label" (e.g. TissueStability).
