### ISSUE TITLE
Bad dcp2 link in banner

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#1628]
1) Visit https://data.humancellatlas.org/explore/
2) Click "View DCP 1.0 Data" in the banner
3) Click "View DCP 2.0 Data Preview" in the banner

Expected:

dcp3 catalog is displayed

Actual:

![image](https://user-images.githubusercontent.com/5143256/113100840-caf11180-91b0-11eb-8f40-7c498662dd3f.png)

**Comment by hannes-ucsc** [comment]
This probably went unnoticed until today because today I deleted the dcp2 catalog to make space for upcoming dcp4 catalog.

**Comment by MillenniumFalconMechanic** [comment]
~~Dupe of humancellatlas/data-portal#891.~~ Reopening; humancellatlas/data-portal#891 is a separate issue.
