### ISSUE TITLE
Provide cellxgene link for project gompertsLungSarsCov2

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1629]
https://data.humancellatlas.org/explore/projects/2a64db43-1b55-4639-aabb-8dba0145689d
Project Title: Direct exposure to SARS-CoV-2 and cigarette smoke increases infection severity and alters the stem cell-derived airway repair response
cellxgene link: https://cellxgene.cziscience.com/collections/cdfb9ead-cb58-4a53-879d-5e4ed5329e73/private
[CGMs spreadsheet](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY) row 250.

**Comment by MillenniumFalconMechanic** [comment]
Resolved in #1598 (#1755).
