### ISSUE TITLE
Auto-select single-option species selection for export

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1654]

**Comment by NoopDog** [comment]
@theathorn This is on dev for your review.

**Comment by theathorn** [comment]
It is working for species.
It might be good to generalize this to auto-select any single-option selection. e.g. for "Select Export File Types":
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/ec8decc4-0be6-48ff-99cf-a61745d905f1)
