### ISSUE TITLE
Indicate projects not accessible to user on projects tab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1662]
## Need
For managed access projects some or all data for the project may be inaccessible to the user. 

One common case will be that some data (CGM and DCP matrices) will be available to the user and the project's sequencing and alignment files are managed-access files and unavailable to the user. 

We need a way to indicate:

1. That the project contains "managed access" data.
1. Potentially we may wish to indicate that depending on the query the project is not contributing files to the query result set. 

### Alternative 0
The initial Suggestion: Project text is grayed out and prompts the user to log in, or apply for access (if already logged in). Prevent selection of project from project list as well as from project detail page. However, this will prevent users from exporting the non-managed access files via the export data flow (e.g. export matrices for multiple projects where one project is a managed access project).

### Alternative 1 

* Indicate if the project or file is managed access with a column "Access Type" or similar with values "Managed Access" and "Open Access".  

* Add an "Access Type" facet over the projects and files.

#### File Browsing
* If the file matches the filter and the user can access it, show the download link as normal.
* If the file matches the filter, and the user can not access it, show a lock icon on the download section with an explanation on hover.
TODO: how can the user reduce clutter and see only files they have access to?

#### Project  Browsing
* Allow users to select the project as normal as long as it matches the filter.

#### Download via CURL
* Only include files the user has access to in the download curl command

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
