### ISSUE TITLE
Warn that data is not normalized on bulk download

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1677]
There could be confusion when a user downloads data from multiple experiments - in particular, they may feel batch effects have been corrected for.  Add  a notice to guide the unwary and to inform them that they need to be careful with interpretation.

Go to here for example:
https://data.humancellatlas.org/explore/get-data?filter=%5B%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%2274b6d569-3b11-42ef-b6b1-a0454522b4a0%22,%227027adc6-c9c9-46f3-84ee-9badc3a4f53b%22%5D%7D%5D

And then select Start for Download Selected Data Using "curl

On that page, we need a warning to indicate the above.

Text worksheet is here:
https://docs.google.com/document/d/18YmDFCcoeSeXBG98wBrYWQWHiwBYQ-q0IxmoMqAvXS8/edit#

**Comment by NoopDog** [comment]
We will add this warning to the DCP Project level matrices downloads as well.
It is also possible to download from the files tab so will take a look at how this can be implemented there too.

**Comment by MillenniumFalconMechanic** [comment]
I have added separate tickets for adding the warning to the files tab (#1720) and the project-level matrices downloads (#1721).

**Comment by MillenniumFalconMechanic** [comment]
The UI updates are currently implemented as follows:

#### Download Selected Data Using curl - Request
<img width="1404" alt="Screen Shot 2021-04-30 at 12 29 04 PM" src="https://user-images.githubusercontent.com/2446424/116745471-fafa2300-a9af-11eb-98ae-2177ad4968e8.png">


#### Download Selected Data Using curl - Completed
<img width="1100" alt="Screen Shot 2021-04-30 at 12 30 00 PM" src="https://user-images.githubusercontent.com/2446424/116745478-fdf51380-a9af-11eb-9335-356fe950e705.png">

**Comment by NoopDog** [comment]
@theathorn This is on staging for your review.

**Comment by theathorn** [comment]
LGTM

**Comment by NoopDog** [comment]
This is now in production.
