### ISSUE TITLE
Rename references to pipelines to remove HCA as this implies endorsement 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1702]
Reword the project detail pages and also scan the pipeline documentation pages on the browser to look for opportunities to update the wording? Namely to remove calling them "HCA" and to be more inclusive to the possibility of community pipelines becoming part of the DCP standard analysis offerings. We can address WARP documentation later.

For example, see the project detail page:

https://data.humancellatlas.org/explore/projects/74b6d569-3b11-42ef-b6b1-a0454522b4a0/m/project-matrices

**Comment by ekiernan** [comment]
See this PR: https://github.com/HumanCellAtlas/data-portal/pull/927

**Comment by ekiernan** [comment]
Suggested change to DCP Matrix Description is:

From:
DCP Generated Matrices are those produced with HCA standardized pipelines. All DCP Generated Matrices include quality control metrics.

To:
"DCP Generated Matrices are those produced with standardized pipelines approved by the HCA Analysis Working Group. All DCP Generated Matrices include quality control metrics."
