### ISSUE TITLE
Explore removal of "back" breadcrumbs and addition of explicit cancel buttons to file type and species selection forms in get data flow 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1704]
#### Current State
The file type selection form allows exploration of the selected data in real time. That is, as a user selects a file type term, the corresponding summary data is updated. The species selection form does not currently update the corresponding summary data on select of a species term. 

#### Desired State
* The file type and species selection forms have the same behavior and allow real-time exploration of the data. 
* On "cancel" of the file type or species form, the search state is reset to the state previous to entry to the form. This may require the addition of explicit cancel buttons and the removal of the "back" breadcrumbs. Cancel of the file type form returns the user the species selection form, cancel of the species selection form returns the user the main get data page.

**Comment by NoopDog** [comment]
handled in dx
