### ISSUE TITLE
Provide cellxgene link for project HumanFoveaRetinaScheetzSheffield

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1713]
project_uuid = 4bec484d-ca7a-47b4-8d48-8830e06ad6db
DCP matrix file =GSE130636_RAW.tar  - row 254 of [contributor_matrices_metadata](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY)
cellxgene link = https://cellxgene.cziscience.com/collections/7edef704-f63a-462c-8636-4bc86a9472bd

**Comment by MillenniumFalconMechanic** [comment]
Resolved in #1598 (#1755).
