### ISSUE TITLE
Add Avro/PFB option for hand-off to Terra

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1714]
Retain the current "BdBag" mechanism as the default, but provide an "Avro/PFB (Beta)" as a selection option.

Add a radio button group in front of the "Request Export" page on the export to terra flow on the select file type page.

Give two options, PFB or bdbag. 
Make the field required to enable and submit the form.

Enable in dev only. In other environments use bdbag like we do now.

Take the selection and add it to the first request (on select of the button) for the format parameter like:

```https://service.azul.data.humancellatlas.org/fetch/manifest/files?catalog=dcp7&filters=%7B%22pr[…]is%22%3A%5B%22fastq%22%5D%7D%7D&format=PFB```

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/6ee9c7c9-5dc1-4d4d-9164-178213d345f8)

**Comment by theathorn** [comment]
@jessebrennan Does this ticket's description look correct to you?

**Comment by NoopDog** [comment]
@jessebrennan I have updated the requirement above according to my understanding of what we need to do to enable this feature in dev. Can you please take a look and let me know if I am missing out on anything?

**Comment by jessebrennan** [comment]
The format should be "terra.pfb" not "PFB". This was meant to parallel the "terra.bdbag" option with a similar name.
