### ISSUE TITLE
Remove confirmation of species when navigating to manifest download from bulk download completed notification

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1725]
##### Component Hierarchy

Map `/get-data(/*)` routes to the following hierarchy:

```
GetData
    PopLayout
        title
        tabs
        content: get-data-export
```

```
GetDataExport
    - dispatch fetch files facets
    switch
        loaded
            flex container/class
                router-outlet
                get-data-summary
                data-use-notification
        !loaded
            swirl
```

```
GetDataSummary
    selected-search-terms
    selected-data
        - dispatches fetch summary
        - refactor inputs to local state
```
  
##### State Updates
* Move species selection required state to store (from component).
* Add distinct operator to manifest summary effect. 
* Move manifest and bulk download components from inheritance to HOC pattern.

##### Spec Updates
* See pending tests in `GetDataLayoutComponent`.
* See pending tests in `GetDataOptionsComponent`.

**Comment by NoopDog** [comment]
Obsolete
