### ISSUE TITLE
Warn that data is not normalized on manifest download

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1727]

**Comment by NoopDog** [comment]
https://dev.singlecell.gi.ucsc.edu/guides/consumer-vignettes/matrices/#matrix-normalization-and-batch-correction

Approved text is:

Please note: data normalization and batch correction may differ between projects and processing methods. For details see [Matrix Normalization and Batch Correction](https://data.humancellatlas.org/guides/consumer-vignettes/matrices/#matrix-normalization-and-batch-correction).
