### ISSUE TITLE
Add Donor Count and Estimated Cell Count Totals to the Summary API and Summary

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#173]
![Screen Shot 2018-07-18 at 11.26.32 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d93df4ed-a1a3-481e-8bd0-ea5d2de5855c)

Summary was updated in the mocks to this just before or slightly after the June Demo.
Will need a back end ticket as well to sync.

┆Issue Number: HCAB-163

**Comment by theathorn** [comment]
The back end API work is in https://app.zenhub.com/workspace/o/databiosphere/azul/issues/54, and https://app.zenhub.com/workspace/o/databiosphere/azul/issues/89
(and perhaps https://app.zenhub.com/workspace/o/databiosphere/azul/issues/47?).

**Comment by NoopDog** [comment]
@frano-m the back end is ready for this one. WE can add donors and estimated cells to the summary.
