### ISSUE TITLE
Horizontal scroll bar exists regardless of window width

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/data-browser#1733]
I'm using Firefox 88.0 for Ubuntu. Here's some screenshots to illustrate.

A small browser window
![browser-small](https://user-images.githubusercontent.com/10734740/117324889-14ceb680-ae45-11eb-8c7f-496554df3bdd.png)

A wide browser window:
![browser-wide](https://user-images.githubusercontent.com/10734740/117325051-3a5bc000-ae45-11eb-9800-42162c2cd8d0.png)

This screenshot might be hard to make out, but I also tried making the browser window so wide that all of the column would fit. The table scrollbar disappeared, but the "globa"l one remained:
![browser-super-wide](https://user-images.githubusercontent.com/10734740/117325070-3def4700-ae45-11eb-98f1-dc84308abffe.png)

**Comment by jessebrennan** [comment]
This goes away If I click on a facet drop down.

**Comment by NoopDog** [comment]
Obsolete
