### ISSUE TITLE
Add support for response field `hits[].files[].isIntermediate`

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1759]
Azul ticket https://github.com/DataBiosphere/azul/issues/2860 plans to add field `hits[].files[].isIntermediate` to Azul's `index/files` endpoint response. Possible values are `true`, `false`, and `null`.

This field will also be added to the `index/projects` and `index/samples` response in the form of `hits[].fileTypeSummaries[].isIntermediate`, however there are two possible options. Currently `fileTypeSummaries` contains aggregated values grouped by `fileType`.

Option 1 is to add the field to the existing structure. This means `hits[].fileTypeSummaries[].isIntermediate`  could have a value like `[true, false]` if the grouping  contains 1 or more files that are matrices and 1 or more files that are intermediate matrices.

Option 2 is to add the field and change the grouping from `fileType` to the combination of `fileType` and `isIntermediate`. This means `isIntermediate` would be a single value (not a list of values), however since the grouping is based on two fields there could be two groups for the same `fileType` for example `{"fileType": "loom", "isIntermediate": true, ...}` and `{"fileType": "loom", "isIntermediate": false, ...}`. This option is the preferred implementation by the  Azul team.

**Question for Data Browser team**: Are the values in `hits[].fileTypeSummaries[]` currently being used, and if so would you be able to support the change in grouping as specified for option 2? 

Example of current `fileTypeSummaries` structure:
```
"fileTypeSummaries": [
  {
    "fileType": "fastq.gz",
    "count": 24,
    "totalSize": 338046608747,
    "source": [
      null
    ]
  },
  {
    "fileType": "loom",
    "count": 13,
    "totalSize": 23501487940,
    "source": [
      "DCP/2 Analysis",
      null
    ]
  },
  {
    "fileType": "bam",
    "count": 12,
    "totalSize": 502542672157,
    "source": [
      null
    ]
  },
  {
    "fileType": "csv.gz",
    "count": 6,
    "totalSize": 9007924686,
    "source": [
      "GEO"
    ]
  }
]
```

Option 1: Add `isIntermediate` to existing grouping
```
"fileTypeSummaries": [
  {
    "fileType": "fastq.gz",
    "count": 24,
    "totalSize": 338046608747,
    "isIntermediate": [
      null
    ]
    "source": [
      null
    ]
  },
  {
    "fileType": "loom",
    "count": 13,
    "totalSize": 23501487940,
    "isIntermediate": [
      true,
      false,
    ]
    "source": [
      "DCP/2 Analysis",
      null
    ]
  },
  {
    "fileType": "bam",
    "count": 12,
    "totalSize": 502542672157,
    "isIntermediate": [
      null
    ]
    "source": [
      null
    ]
  },
  {
    "fileType": "csv.gz",
    "count": 6,
    "totalSize": 9007924686,
    "isIntermediate": [
      null
    ]
    "source": [
      "GEO"
    ]
  }
]
```

Option 2: Add `isIntermediate` & group by combination of `fileType` and `isIntermediate` (Note 2 groups for `"fileType": "loom"`)
```
"fileTypeSummaries": [
  {
    "fileType": "fastq.gz",
    "count": 24,
    "totalSize": 338046608747,
    "isIntermediate": [
      null
    ]
    "source": [
      null
    ]
  },
  {
    "fileType": "loom",
    "count": 1,
    "totalSize": 3914763654,
    "isIntermediate": [
      false,
    ]
    "source": [
      "DCP/2 Analysis",
    ]
  },
  {
    "fileType": "loom",
    "count": 12,
    "totalSize": 19586724286,
    "isIntermediate": [
      true,
    ]
    "source": [
      null
    ]
  },
  {
    "fileType": "bam",
    "count": 12,
    "totalSize": 502542672157,
    "isIntermediate": [
      null
    ]
    "source": [
      null
    ]
  },
  {
    "fileType": "csv.gz",
    "count": 6,
    "totalSize": 9007924686,
    "isIntermediate": [
      null
    ]
    "source": [
      "GEO"
    ]
  }
]
```

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
