### ISSUE TITLE
Replace full manifest with compact manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1766]
The full manifest is confusing because it omits the artificially generated sequencing_process.provenance.document_id field which is included in the metadata of DCP generated matrices.
The short term solution is to replace the full manifest with the compact one for the project metadata download links.
The long term solution is to implement DataBiosphere/azul#2693.

**Comment by NoopDog** [comment]
Our short-term solution is to make the project manifest use the compact manifest format. However, the compact manifest file names are not user-friendly in the single project case. We are waiting for DataBiosphere/Azul#3077 to push this.

**Comment by theathorn** [comment]
The above-referenced Azul ticket is now deployed to dev.

**Comment by NoopDog** [comment]
Thanks will check it out.
D
