### ISSUE TITLE
Refine Requirements for Projects Tab to API Functional Spec

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#177]
┆Issue Number: HCAB-166

**Comment by NoopDog** [comment]
I have started this doc to collect the Projects Tab requirements.

https://docs.google.com/document/d/1GllbMBdS_BNOsQcepf-j4siYqK26v_DW0WAeKd0ny1g/edit#

Lets review and see if this is enough to get going on the projects tab.

**Comment by NoopDog** [comment]
@hannes-ucsc please review and let me know if we need to add anything to this before we can start to implement the back end API for the projects tab:

https://docs.google.com/document/d/1GllbMBdS_BNOsQcepf-j4siYqK26v_DW0WAeKd0ny1g/edit#

Thanks!

**Comment by kozbo** [comment]
@briandoconnor please review

**Comment by hannes-ucsc** [comment]
I am done with my review. My most consequential change suggestion was where we define the response format.

**Comment by theathorn** [comment]
Complete metadata mapping for Project Detail page (consult with @malloryfreeberg).

**Comment by NoopDog** [comment]
@malloryfreeberg thanks for updating the document!

**Comment by NoopDog** [comment]
@hannes-ucsc do you have what you need now from this document? Thanks.

**Comment by hannes-ucsc** [comment]
Looking good. Thank you, @NoopDog and @malloryfreeberg!
