### ISSUE TITLE
In "Confirm Species" screen of the Export Selected Data flow show the selected flow name instead "Export Selected Data"

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1774]
#### Need
In the export selected data flow, in the species confirmation page the context of what flow you are in (Export to Terra, Download Manifest, or Get curl command is lost. 

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/8be2fd7b-857d-4017-9805-6ec4acd495bb)

#### Approach
Fix this by showing the flow name as we do on the next screen.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/1bcc3b2f-9162-49ff-9061-c7bb052e889d)

#### Definition of Done
- Specific export data flow name is maintained in all intermediate screens once the flow is entered.

**Comment by MillenniumFalconMechanic** [comment]
Resolved in #1531.
