### ISSUE TITLE
In export flows explain why the final button is dimmed when no file types are selected

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1775]
#### Need
For example, when the  "Request curl Command" is disabled, It may not be immediately obvious to users why it's disabled preventing the user from completing the flow.

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e02aa005-2d32-473f-98e2-556d7a09024f)

#### Approach
Indicate on the form that the user needs to select a file type to proceed. This could be as simple as adding (Please select a file type) below the disabled download button. 

#### Definition of Done
We indicate on the form what to do to proceed (select a file type) for all three flows. (Manifest, CURL, and Terra exports)

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
