### ISSUE TITLE
Show all non-zero `File Format` values under `File Counts` on `Project Information` tab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1798]
Currently we display counts for:

- Fastq
- Bam
- Matrix
- Other
- Total

There are currently 24 possible `File Format` types.
We should show any non-zero counts for all file formats, (perhaps with a dropdown for large lists?).
The "matrix" file format is used for "zattrs" files, and is not worthy of special distinction.

**Comment by NoopDog** [comment]
@theathorn this one is on dev for your review

Cheers,
D
