### ISSUE TITLE
Add capability to the indexer to handle different file versions

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#18]
As an administrator, I would like to handle different versions of each metadata file. 

Right now the indexer assumes that all the files inside a bundle belong to a single version. However, as specified by the metadata group, we will have bundles with metadata files of mixed metadata versions. 

As such, we need to add the capability to the indexer to detect the version for each file, and index accordingly.

DOD: The indexer takes bundles, detects the version of each metadata file, and indexes accordingly to a specified class for each metadata file and version combination. Includes Unit test

┆Issue Number: HCAB-89

**Comment by theathorn** [comment]
Superseded by #116.
