### ISSUE TITLE
Setup auto deploy in gitlab for new environments

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1805]
## Lungmap Prod

**Portal**
s3://data-browser.lungmap.net/

**Browser Bucket**
s3://data-browser.explore.lungmap.net/

**CloudFront**
E22L661MUAMMTD

## Lungmap dev
** Portal Bucket**
s3://data-browser.dev.lungmap.net/

## ux-dev 
 **Portal Bucket**
s3://ux-dev.singlecell.gi.ucsc.edu/

**Browser Bucket**
s3://ux-dev.explore.singlecell.gi.ucsc.edu/

**Cloudfront**
E3FFK49Z7TQ60R

**Comment by NoopDog** [comment]
HI, @achave11 can this be closed? Cheers, D

**Comment by achave11-ucsc** [comment]
> HI, @achave11 can this be closed? Cheers, D

@NoopDog Yeah, I think so.
