### ISSUE TITLE
Add instructions for Excel users on Export Selected Data flow

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/data-browser#1807]
[Discussion on Azul tix](https://github.com/DataBiosphere/azul/issues/3129#issuecomment-862697683)

A temporary solution would be to offer users [instructions](https://www.trainingconnection.com/excel/lessons/opening-excel-files.php) like…
![Screen Shot 2021-06-16 at 1 50 49 PM](https://user-images.githubusercontent.com/19215510/122291661-eadbcb80-cea9-11eb-9fca-93eb032249b5.png)
… and allow the users to select the UTF-8 encoding for the file encoding.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
