### ISSUE TITLE
Remove duplicate `File Format` values under `Project Details` on `Project Information` tab

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#1822]
`hits[].fileTypeSummaries` contains information about files in the project, grouped by the fields `fileType` and `isIntermediate`. Because two fields are used to group by, it is possible for a `fileType` value to occur more than once in the list. Example:
```
[
  {
    "fileType": "loom",
    "count": 12,
    "totalSize": 19586724286,
    "matrixCellCount": null,
    "isIntermediate": true,
    "source": [
      null
    ]
  },
  {
    "fileType": "loom",
    "count": 1,
    "totalSize": 3914763654,
    "matrixCellCount": null,
    "isIntermediate": false,
    "source": [
      "DCP/2 Analysis"
    ]
  }
]

```

When using the list of `fileTypeSummaries` to display the `File Format` on the `Project Information` tab, duplicate file formats should be removed.

![Screen Shot 2021-06-30 at 3 37 17 PM](https://user-images.githubusercontent.com/46407464/124040333-919b8e00-d9b9-11eb-88ec-8cb563b9676b.png)

**Comment by NoopDog** [comment]
Hi, @danielsotirhos thanks for pointing this out. Will take a look. Cheers, D

**Comment by dsotirho-ucsc** [comment]
Fix confirmed working on dev https://dev.singlecell.gi.ucsc.edu/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803 and prod https://data.humancellatlas.org/explore/projects/7027adc6-c9c9-46f3-84ee-9badc3a4f53b
