### ISSUE TITLE
Login/logout/login sequence results in auto login with the original login account

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1842]
Chrome browser.
Select "Login" and get a dialog to select which Google account to use.
After login, select "Logout".
Re-select "Login" and get auto-logged in to the account used for the original Login, with no option to select a different account.
Using the "Other profiles" feature in Chrome works around this issue.

**Comment by MillenniumFalconMechanic** [comment]
This is standard Google API behavior.
