### ISSUE TITLE
Unregistered Terra user gets "unauthorized" error on Samples and Files tabs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1844]
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/f555d230-99ea-4b67-9917-e8f307634967)

Prior to login the data browser should check if the user is registered with Terra and, if not, redirect them through that process.

**Comment by theathorn** [comment]
Also see Databiosphere/azul-3253.

**Comment by theathorn** [comment]
Following up on https://github.com/DataBiosphere/azul/issues/3253#issuecomment-885244655 - the proposed solution for that will allow all _registered_ Terra users to see public snapshots.

However, logged-in-but-not-registered-with-Terra-users would still not have access. The Data Browser should check if the user is registered with Terra and, if not, redirect them through a Terra registration workflow. A logged-in-but-not-registered user should not be able to select any of the project/samples/files tab (and so would not see the "unauthorized" error - they would only be able to logout (go back to being an anonymous user) or complete the Terra registration workflow.

**Comment by NoopDog** [comment]
##APIs to explore 

Dev endpoints worth exploring: https://firecloud-orchestration.dsde-dev.broadinstitute.org/#/Profile/me (check registration status), 

creating a profile (https://firecloud-orchestration.dsde-dev.broadinstitute.org/#/Profile/setProfile)

Determining if a user has a Terra account
https://sam.dsde-dev.broadinstitute.org/#/Users/getUserStatus
