### ISSUE TITLE
Navigating to dev intermittently displays blank page

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#1848]

**Comment by achave11-ucsc** [comment]
This is reproducible by adjusting cookies settings for a given browser. 

For Chrome (not in incognito mode):
 
* setting `Block all cookies (not recommended)` will automatically (and always) disable the rendering of the explore landing page.
* setting `Block third-party cookies` occasionally disables rendering (sometimes it renders other times doesn't).

* setting `Allow all cookies` and `Block third-party cookies in Incognito` always display the landing page. 

This was based on my observation and I am not sure that the cookies are the problem. I also saw this problem with the Terra page when I attempted to import data from the browser.
