### ISSUE TITLE
Review Google Analytics wrt managed access data

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1892]
## Need 
We need to be sure that any information sent to third parties conform to our controlled-access data handling requirements.

The data browser sends user actions to Google Analytics in order to support understanding of user behavior on the site.  For example when searching for data the browser currently sends the facets selected and any search terms to Google Analytics. 

If PII did make it into Google Analytics it could prove difficult to delete it.

## Approach

One approach is to switch to a different analytics provider such as https://plausible.io/  for example that is open source and supports self-hosting and to host this within our security perimeter.

The Broad team uses Mixpanel on Terra so perhaps there is a self-hosting or privacy agreement in place there for us to investigate. 

Another approach would be to review the requirements and privacy capabilities with Google Analytics and determine if there is a way to stay on the platform.

**Comment by theathorn** [comment]
GCP is largely [FedRAMP certified](https://cloud.google.com/blog/topics/customers/google-cloud-platform-is-now-fedramp-high-authorized), so I wouldn't expect we would need to switch analytics platforms.

We should seek clarity on whether a search query with facets involves PII.
Are search results logged in Google Analytics?

**Comment by NoopDog** [comment]
Hi @theathorn no search results are sent to GA at the moment, only the queries.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
