### ISSUE TITLE
`Genus Species` values inconsistent between `Projects` and `Samples`/`Files` views

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#1895]
Copied from DataBiosphere/azul#3152:

From @theathorn on 6/16/21:
Go to https://data.humancellatlas.org/explore/projects and from the "Projects" tab click on the "Donor" dropdown; note that "Unspecified" is not present. Click on the "Samples" or "Files" tab and then the "Donor" dropdown - "Unspecified" is now present.

I originally ran into this issue on https://data-browser.dev.lungmap.net/ :

- Select "File Format" = "LOOM"
- On Files tab, select "Donor" = "Unspecified"
- The Projects tab is now empty

From @danielsotirhos on 6/22/21:
> The issue stems from the case when an entity (e.g. file or sample) is part of a subgraph without a donor_organism entity. In this case the "/index/samples" or "/index/files" endpoint would return an empty list in the corresponding hit's "donorOrganism" field (causing "Species" to be listed as "Unspecified"), however the response from the "/index/projects" would have a "donorOrganism" (and "Species") value since there is a donor in the project, just not connected to the file or sample entity.

> Currently when Azul aggregates values for the "/index/projects" endpoint, it traverses the graph starting from all specimen and files to find all the donor entities, and then aggregates those together. Since it is aggregating what it found, the lack of finding a donor from the file or sample entity is not represented in the aggregated results.

From @theathorn on 7/20/21:
> A suggestion discussed was for the Data Browser to auto-remove any filter selections on a tab for which that filter selection does not apply (e.g. in this case by removing "Genus Species = Unspecified" when viewing the Files tab).

From @hannes-ucsc on 8/20/21:
> This is not a bug in Azul but the intended behavior. The project does have donors so it would be incorrect to pretend that it does not. It does have files that don't have donors but that's not the same. What if it has files that have donors, and samples that don't? Should we pretend that the project has no donors?

> This may be counter-intuitive to users but we don't want to bend reality to address that, we need to help the user in understanding what's going on. As hinted by Trevor, I think the UI should highlight any currently active filters for which the termFacets part of the response indicates no hits. The highlighting indicates that a filter causes the response to be empty and that disabling it and all other highlighted filters would remedy that.

> As an extension of this mechanism, the set of disabled (not removed) filters could be maintained per tab, so that switching tabs re-enables them. This requires implementing a distinction between removed and temporarily disabled filters.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
