### ISSUE TITLE
Add required fonts to HCA figma file

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#1912]
Figure out what we need to do for this even if we all need to do something locally. What is the secret?

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/6746ce3f-c966-48e9-8590-a0b7854a60ab)

**Comment by frano-m** [comment]
[https://app.zenhub.com/files/124946326/1fceccb3-0909-479d-bc02-eb6611fd0396/download](https://app.zenhub.com/files/124946326/1fceccb3-0909-479d-bc02-eb6611fd0396/download)
