### ISSUE TITLE
Create https://PROD.data.humancellatlas.org/ Gitlab and Cloudfront setup for the Data Portal

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#193]
Hi @parthshahva we need to set up one last environment for the data portal, the prod environment from a push to master.

We want to keep this off the root url (data.humancellatlas.org) till we are ready to go live and but want a place where we can review the latest content/data for testing before the launch.

Do you have bandwidth to set this up? This should be the last one!

Cheers and Thanks,
Dave

┆Issue Number: HCAB-180

**Comment by theathorn** [comment]
@NoopDog Is this done or you need more from @parthshahva ?

**Comment by NoopDog** [comment]
Need help please. @theathorn @parthshahva

**Comment by parthshahva** [comment]
I have things I need to take care of tomorrow and am off rest of the week. If this is urgent for this week, someone else will have to take this on. Hannes should have access/knowledge to do this as well, but I'm sure he is swamped as well. cc @mweiden

**Comment by theathorn** [comment]
@parthshahva This can wait until next week. It would be good to complete it by end-of-sprint (8/31).

**Comment by hannes-ucsc** [comment]
IIRC, Travis should not have credentials for deploying to production. So I think this can't be done using `.travis.yml` anyways. I propose that @NoopDog ports `.travis.yml` to `.gitlab-ci.yml` and adds the fourth deployment (prod) there.

Maybe @xbrianh can give @NoopDog up access to our Gitlab instance?
