### ISSUE TITLE
Add Imaging Method Facet

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#194]
┆Issue Number: HCAB-182

**Comment by NoopDog** [comment]
- Not in current Mini Schema/Accessor Library
![Screen Shot 2018-08-09 at 12.49.02 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/be0231ee-07f1-46da-bc0f-78ea64c20541)

**Comment by theathorn** [comment]
Daniel to provide name of facet and guidance.

**Comment by dsotirho-ucsc** [comment]
The name of the imaging method facet is "assayType".

See: https://github.com/databiosphere/azul/issues/885#issuecomment-484571833

**Comment by NoopDog** [comment]
Obsolete
