### ISSUE TITLE
PFB redirect URL is missing `format=PFB` query parameter

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/data-browser#1993]
In `dev` I requested a PFB manifest. The re-direct URL was `https://bvdp-saturn-dev.appspot.com/#import-data?url=https%3A%2F%2Fservice.dev.singlecell.gi.ucsc.edu%2Fmanifest%2Ffiles%3Fcatalog%3Ddcp2%26format%3Dterra.pfb%26filters%3D%257B%2522projectId%2522%253A%2B%257B%2522is%2522%253A%2B%255B%252260ea42e1-af49-42f5-8164-d641fdb696bc%2522%255D%257D%252C%2B%2522genusSpecies%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522Homo%2Bsapiens%2522%255D%257D%252C%2B%2522fileFormat%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522fastq.gz%2522%255D%257D%257D%26objectKey%3Dmanifests%252F920202e8-ac29-510a-a20c-a73dd3a276ed.avro`

which doesn't work. Terra complains:
![import-error](https://user-images.githubusercontent.com/10734740/136872232-e354e77a-1beb-4fd0-958c-987c6aaa1651.png)

**Comment by NoopDog** [comment]
Thanks @jessebrennan will take a look.

**Comment by MillenniumFalconMechanic** [comment]
Hey @jessebrennan, can you give me the steps to reproduce this defect in dev? I am seeing the `format=terra.pfb` param included in the initial request the Data Browser sends to Azul when I attempt an export to Terra. 

Also, is the `format%3Dterra.pfb` param in the redirect URL you shared above separate from the `format` param you are missing?

**Comment by jessebrennan** [comment]
Yes. When redirecting to Terra they require a format=PFB param to distinguish from bdbag imports. This param should not be encoded, and should be part of the Terra URL. In other words:

`https://bvdp-saturn-dev.appspot.com/#import-data?url=https%3A%2F%2Fservice.dev.singlecell.gi.ucsc.edu%2Fmanifest%2Ffiles%3Fcatalog%3Ddcp2%26format%3Dterra.pfb%26filters%3D%257B%2522projectId%2522%253A%2B%257B%2522is%2522%253A%2B%255B%252260ea42e1-af49-42f5-8164-d641fdb696bc%2522%255D%257D%252C%2B%2522genusSpecies%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522Homo%2Bsapiens%2522%255D%257D%252C%2B%2522fileFormat%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522fastq.gz%2522%255D%257D%257D%26objectKey%3Dmanifests%252F920202e8-ac29-510a-a20c-a73dd3a276ed.avro`

should be changed to

`https://bvdp-saturn-dev.appspot.com/#import-data?format=PFB&url=https%3A%2F%2Fservice.dev.singlecell.gi.ucsc.edu%2Fmanifest%2Ffiles%3Fcatalog%3Ddcp2%26format%3Dterra.pfb%26filters%3D%257B%2522projectId%2522%253A%2B%257B%2522is%2522%253A%2B%255B%252260ea42e1-af49-42f5-8164-d641fdb696bc%2522%255D%257D%252C%2B%2522genusSpecies%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522Homo%2Bsapiens%2522%255D%257D%252C%2B%2522fileFormat%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522fastq.gz%2522%255D%257D%257D%26objectKey%3Dmanifests%252F920202e8-ac29-510a-a20c-a73dd3a276ed.avro`

To reproduce this, just do a Terra PFB export from the dev browser, from a project for example, and log into Terra dev and try and complete the import. For me it failed with the error above, until I corrected the URL.
