### ISSUE TITLE
Create Stress test for indexer

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-browser#20]
As a system administrator I would like to be confident that the indexer can handle a 5 -10 million bundle indexing job so that we can be confident in the design of the indexer for the next 6-12 months.

DOD:
Index 5 and 10 Million bundles (we expect growth to be incremental so there isn't a speed requirement here.)
Verify reasonable search response time (<30 s?)
Run Index search stress test (needs to be created)

┆Issue Number: HCAB-90

**Comment by caaespin** [comment]
The test should have simulated events running in parallel to account for potential concurrency issues.

**Comment by caaespin** [comment]
UPDATE: Jim and Jyo will create a fixed dataset to use for shared testing.

**Comment by caaespin** [comment]
UPDATE: Setting ES and loading data into it.
