### ISSUE TITLE
Replace use of `hits[].projects[].contributorMatrices` with `contributedAnalyses`

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#2002]
After https://github.com/DataBiosphere/azul/issues/3420 has been deployed to `prod`, please replace usage of the deprecated response field with the replacement. There are no changes to the content of the field, only the name of the field has changed.

```
Deprecated : hits[].projects[].contributorMatrices
Replacement: hits[].projects[].contributedAnalyses
```

**Comment by NoopDog** [comment]
Thanks for the heads up @danielsotirhos

**Comment by NoopDog** [comment]
Hi, @danielsotirhos @theathorn this update is deployed to prod. You can remove the deprecated fields in dev and all should still be good. Thanks! D
