### ISSUE TITLE
Remove/Replace wildcard SSL certs in hca-platform-dev

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2004]
## Need

The wildcard is a security/compliance risk

## Approach 

There is a wildcard SSL cert for  *.dev.lungmap.net in our AWS account hca-platform-dev.
Check if this is used and if not delete it.
If this is used, then replace it with a cert that does not have a wildcard.

**Comment by NoopDog** [comment]
@theathorn the *.dev.lungmap.net SSL cert has been deleted and replaced with:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e5e5416e-e280-4868-b789-ec0866348e9e)

What is the next step to get someone to verify so we can close this? Cheers and Thanks, Dave

**Comment by theathorn** [comment]
@danielsotirhos should be able to help as part of DataBiosphere/azul#3587.
FYI @hannes-ucsc.
