### ISSUE TITLE
Fill in November demo script

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/data-browser#207]
See https://app.zenhub.com/workspace/o/humancellatlas/data-store/issues/1511

And see the script doc I've started: https://docs.google.com/document/d/1EAulvcSrOrT1Z58lYquyZuz1Zg2iWqGo3qiD3zL7nBc/edit#

For status see https://app.zenhub.com/workspace/o/humancellatlas/dcp/boards?repos=106337233&showPRs=false

┆Issue Number: HCAB-192

**Comment by lauraclarke** [comment]
New plan exists here Laura/Tony -  Challenges around loading “real” data into DCP
Review Demo plan - https://docs.google.com/document/d/1PV3XoDxYHXQvLU4i6gcbaLBVT0Blq_5TjbOTenfI2v8/edit?usp=sharing

**Comment by theathorn** [comment]
Successful demo given on Nov 1.
