### ISSUE TITLE
Only init google  auth in dev (not ux-dev)

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2088]
Currently, the google auth is prohibited from loading in prod. It needs to be prohibited in ux-dev as well. Only develop should load the auth code. Otherwise we geat a blank page with a console error saying:

`idpiframe_initialization_failed', details: "Not a valid origin for the client: https://ux-dev.…egister this origin for your project's client ID."}`

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
