### ISSUE TITLE
Migrate the Web Service to AWS Lambda

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#21]
As a developer, I want to ensure that my RESTful web service scales nicely.

Right now the web service is a flask docker container. We need to migrate to a chalice AWS Lambda web service to ensure the service scales with increased use

DOD: The webservice is deployed to AWS Lambda via chalice

┆Issue Number: HCAB-91

**Comment by theathorn** [comment]
Jim to do PR and re-assign to Hannes.
