### ISSUE TITLE
Add "indexing in progress" banner to home page

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#2101]
Hello, for your consideration:

## User story

* As a viewer of the https://data.humancellatlas.org/ home page (before going to the `/index/projects` page)
* I want to be informed when a reindex is in progress
* so that I know the summary counts listed on the home page are temporarily low.

## Definition of done

A banner or other visual indication is added to the https://data.humancellatlas.org/ home page when a reindex is in progress

![Screen Shot 2021-11-18 at 5 26 43 PM](https://user-images.githubusercontent.com/46407464/142538425-8b247373-e28f-440f-b7b8-a4ed6bf49244.png)

**Comment by NoopDog** [comment]
Thanks, @danielsotirhos adding this to the backlog.

**Comment by bvizzier-ucsc** [comment]
Already done.
