### ISSUE TITLE
Multiple requests to download files causes errors

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/data-browser#2108]
Browser Used: Firefox 94.0.2 (64-bit) Mac and Firefox 94.0 (64-bit) Linux (Chrome seems to work with no issues...)
Expected Behavior: get a download prompt for each clicked download icon in the files tab.
Actual Behavior: One download prompt for the first file is returned, for the next file we are redirected to an error page.
Steps to Reproduce: see video attachment.

https://user-images.githubusercontent.com/1947534/143311118-fe68b155-9a40-4e66-9ef9-76894b05994f.mov

**Comment by amarjandu** [comment]
We checked the Cloudwatch for the service endpoint and did not find any errors. Might be due to how FireFox handles downloads.

**Comment by NoopDog** [comment]
Thanks, @amarjandu will take a look. 
D

**Comment by MillenniumFalconMechanic** [comment]
Address in DX.
