### ISSUE TITLE
`Update Date` shows as `Unspecified`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2116]
..and sorting by descending value puts Unspecified projects at the top of the sort order.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc:

> We've implemented https://github.com/databiosphere/azul/issues/3679 (except for the ability to sort by non-aggregate date fields). Once we fix that, our recommendation is:
> 
> On the projects tab, display two columns: *Submission Date* and *Last Modified*. Display `contents.projects.submissionDate` in the former, and `contents.projects.aggregateLastModifiedDate` in the latter.
> 
> We recommend that you do not display `contents.projects.aggregateSubmissionDate` because the entities belonging to the project might have a negligibly earlier submission date. What counts for submission date is the date in the project.json
> 
> On the other tabs, display the same two columns. Display `contents.{samples, files}.submissionDate` in the first column, and `contents.{samples, files}.lastModifiedDate" in the second column.

**Comment by dsotirho-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/3679 has been completed and is currently on dev (not yet on prod), however there have been some changes to Azul's handling of date fields that should be noted.

In Azul's response, the date fields previously found in each entity (hits[].projects, hits[].samples, etc.) have been removed. Instead, a `dates` entity can now be found in each response hit (`hits[].dates`) which will contain six date fields:

- `submissionDate`: The submission date of the primary entity (the project on the `projects` endpoint, a file on `files` endpoint, etc).
- `updateDate`: The update date of the primary entity (Optional, could be NULL).
- `lastModifiedDate`: The larger (later) value between submissionDate and updateDate.
    
Aggregate date fields will only have (non-NULL) values on the `projects` and `bundles` endpoints:

- `aggregateSubmissionDate`: The smallest (earliest) date between all entities in the project or bundle.
- `aggregateUpdateDate`: The largest (latest) date between all entities in the project or bundle.
- `aggregateLastModifiedDate`: The larger (later) value between `aggregateSubmissionDate` and `aggregateUpdateDate`

Example response from `projects` endpoint:
```
    "protocols": [
        ...  # No date fields
    ],
    "projects": [
        ...  # No date fields
    ],
    "dates": [
        {
            "aggregateLastModifiedDate": "2021-05-19T17:27:50.758000Z",
            "aggregateSubmissionDate": "2021-04-28T16:20:03.613000Z",
            "aggregateUpdateDate": "2021-05-19T17:27:50.758000Z",
            "lastModifiedDate": "2021-05-19T17:03:15.610000Z",
            "submissionDate": "2021-04-28T16:20:03.613000Z",
            "updateDate": "2021-05-19T17:03:15.610000Z"
        }
    ],
    ...
```

For sorting, all of the six date fields are available as sort keys:

```
/index/projects?catalog=foo&sort=lastModifiedDate&order=asc
/index/projects?catalog=foo&sort=aggregateLastModifiedDate&order=asc
...
```
