### ISSUE TITLE
Tool Tip on Table Overflow Elements "..." is hard to Trigger

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#212]
![Screen Shot 2018-08-21 at 11.25.18 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/70e48cbc-1ca4-497e-8681-b4d51fc4ae83)

Can we make this easier to trigger?

┆Issue Number: HCAB-195

**Comment by NoopDog** [comment]
I see.. its not position its time.. like about 3 sec. What would be a shorter number that opens quickly but does not make them all flash. Or what about a target we can hover directly on to make it go.

**Comment by theathorn** [comment]
Follow whatever hover over times browsers and other web apps use.

**Comment by frano-m** [comment]
gmail tooltip is 150ms
Material Design behaviour spec also 150ms
https://material.io/design/components/tooltips.html#behavior
