### ISSUE TITLE
HCA logo is not a link on "Explore" pages

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/data-browser#2132]
Copy of DP #1254.

The `HUMAN CELL ATLAS DATA PORTAL` logo (top left of page) is a clickable link back to the root page ( https://data.humancellatlas.org/ ) on all pages except the `/explore` pages (e.g. https://data.humancellatlas.org/explore/projects )

![Screen Shot 2021-12-14 at 11 28 31 AM](https://user-images.githubusercontent.com/46407464/146066575-4e6514c5-39fc-4ea2-848c-998c0344d719.png)

**Comment by NoopDog** [comment]
Hi, @danielsotirhos the fix for this is on prod. if this looks ok to you, feel free to close this ticket. Cheers, D

**Comment by dsotirho-ucsc** [comment]
Verified the fix. Thanks!
