### ISSUE TITLE
Retire the "DCP 1.0 Data View"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2150]
See this [Slack thread](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1641336835134700).
All projects in the dcp/1 catalog that have DCP analysis now have DCP analysis in dcp/2.
Th exception is this [organoids](https://data.humancellatlas.org/explore/projects/005d611a-14d5-4fbf-846e-571a1f874f70?catalog=dcp1) project which won't be processed in dcp/2.

**Comment by theathorn** [comment]
Let's target this for the dcp13 release.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
