### ISSUE TITLE
Review Scroll Bar Appearance on Windows

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/data-browser#217]
The final behavior is:

### Chrome

┆Issue Number: HCAB-199

**Comment by theathorn** [comment]
Need to review under Windows.

**Comment by frano-m** [comment]
Let's discuss

**Comment by MillenniumFalconMechanic** [comment]
* Modify `-ms-overflow-style` on `facet-term-list` elements.  ` -ms-autohiding-scrollbar` hides scrollbar unless actively scrolling. `none` never shows scrollbar even if actively scrolling.
* Must emulate scrollbar with JS to style.

**Comment by NoopDog** [comment]
The solution chosen for this was to hide the "ugly" windows scroll bar until the user is actually scrolling. This now works the same way as the other browsers. Its just that the other browsers now a pretty scroll bar when we start scrolling. 

We could completely restyle the scroll bar and emulate it in JS, but I am not sure its worth it at this time. We can review that against other priorities. With this fix you only see the scroll bar when scrolling.

**Comment by theathorn** [comment]
Not working for me for Edge or Chrome on Windows.

**Comment by MillenniumFalconMechanic** [comment]
##### Webkit on Mac
* Scrollbar visible only on scroll 

##### Chrome on Windows
* Scrollbar always visible where content overflows

##### Edge 
* Scrollbar only visible on scroll

**Comment by theathorn** [comment]
Counts obscured by scrollbar on Edge browser.
