### ISSUE TITLE
Big Red Button

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#220]
See https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/67

┆Issue Number: HCAB-201

**Comment by NoopDog** [comment]
Working in dev...
![Screen Shot 2019-03-06 at 11.02.29 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/a30b1627-cd6a-4989-9f81-f1cd5864d47b)
