### ISSUE TITLE
Use gitlab for deployments

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#221]
See https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/77

┆Issue Number: HCAB-202

**Comment by theathorn** [comment]
@xbrianh Can you assist @NoopDog with this?

**Comment by xbrianh** [comment]
@NoopDog please attempt to log in to the build box and then ping me to unblock your account:
https://allspark.dev.data.humancellatlas.org

**Comment by NoopDog** [comment]
@xbrianh ok.. done.. says my account is blocked ;( thanks!

**Comment by xbrianh** [comment]
@NoopDog unblocked! You should be ready to go.

**Comment by NoopDog** [comment]
Hey Thanks!
