### ISSUE TITLE
Register docker images with UCSC GitLab instance

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2296]
Here are the registries for your group on GL dev and prod

https://gitlab.dev.singlecell.gi.ucsc.edu/groups/clever-canary/-/container_registries
https://gitlab.azul.data.humancellatlas.org/groups/clever-canary/-/container_registries

The documentation is linked from there.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
