### ISSUE TITLE
Message about manifest expiration is incorrect

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/data-browser#2300]
@hannes-ucsc: "Expiration is 7 days not 24 hours but @noah-aviel-dove will confirm in a spike."

**Comment by nadove-ucsc** [comment]
Manifest is still accessible after 24 hours. Currently accessible after 45 hours.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "That only leaves the possibility that the link expires when the manifest object is removed by the lifecycle rule on the bucket. So the correct message should mention a 7 day expiration."
