### ISSUE TITLE
Create Runbook of Data Browser release and operations procedures

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#235]
See https://app.zenhub.com/workspace/o/databiosphere/azul/issues/318

┆Issue Number: HCAB-210

**Comment by NoopDog** [comment]
https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Data-Browser-Runbook

**Comment by NoopDog** [comment]
Diagram updated with correct prod url.
