### ISSUE TITLE
LungMAP Data Browser refers to "HCA data"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2359]
In "Export Selected Data", the text under "Analyze in Terra" states "To make the most out of HCA data with Terra...".

**Comment by theathorn** [comment]
Also see HumanCellAtlas/data-portal#1156.

**Comment by NoopDog** [comment]
We found another spot where this text occurs (in the project-specific Terra export). Will create a second PR to address this.
