### ISSUE TITLE
Safari Filter Menu Apply Button Missing

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/data-browser#237]
Safari - apply button missing and user can see partial footer and table
![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/1283b2fb-adf4-4cd1-aa93-e1fe7ae2a2f0)

┆Issue Number: HCAB-212

**Comment by NoopDog** [comment]
![Screen Shot 2018-10-01 at 10.21.53 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/f817c51c-5ac0-4611-8321-4dd93beba6e5)

@theathorn the apply button now shows properly on safari on dev. This can be closed.
