### ISSUE TITLE
"Cell Count Estimate" column doesn't list effective cell count value.

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#2372]
## Expected behavior

On the `Projects` tab, the `Cell Count Estimate` column should list the effective cell count for each project, which is the larger value between the project's estimated cell count and a sum of the project's cell suspension(s) cell counts.

## Actual behavior

On the `Projects` tab, the `Cell Count Estimate` column is listing the project's estimated cell count if it exists, else the sum of the project's cell suspension(s) cell counts.

## Steps to reproduce the behavior
- Go to https://data.humancellatlas.org/explore/projects
- Sort by `Cell Count Estimate` descending.
- Observe displayed values.

![Screen Shot 2022-03-29 at 2 09 29 PM](https://user-images.githubusercontent.com/46407464/160708906-fdbb7a60-c185-4941-a361-cc2a9fb64854.png)

**Comment by NoopDog** [comment]
Thanks @danielsotirhos will fix.

**Comment by NoopDog** [comment]
Hi, @danielsotirhos a fix for this has been deployed to prod and looks good to me so far. Can you verify?

Cheers,
Dave

**Comment by dsotirho-ucsc** [comment]
Verified. The fix looks great. Thanks!

![Screen Shot 2022-04-04 at 9 25 00 AM](https://user-images.githubusercontent.com/46407464/161590179-9e9cfe61-4140-4cf2-87c0-e318003f119a.png)

**Comment by NoopDog** [comment]
Thanks @danielsotirhos !
