### ISSUE TITLE
Data Browser "use banner" prior to login

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2391]
[FedRAMP SSP AC-8 System Use Notification](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.319y80a):
From Mariano Serquina: "This control will have an alternate implementation. Need to know if there is any sort of use banner for UCSC that is seen before users log into HCA."

**Comment by NoopDog** [comment]
@theathorn what is a "use banner", do we need one, and what are the requirements if we do? I have requested access to the doc linked above.

**Comment by nolunwa-ucsc** [comment]
@NoopDog i gave you access to the SSP

**Comment by nolunwa-ucsc** [comment]
@theathorn kindly share update in this ticket, this is implementation effort for AC-08

**Comment by NoopDog** [comment]
@nolunwa @theathorn Is there a requirement for a banner here? If so can you provide the text? Thanks! D

**Comment by NoopDog** [comment]
@nolunwa @theathorn Checking back in on any update/requirements fo the "Use Banner". Thanks, D

**Comment by NoopDog** [comment]
@bvizzier-ucsc @nolunwa-ucsc do you feel this notice on the login form satisfies this requirement?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWVuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--915ff12da82f78ca26505580bb599d2a5951475e/image.png)

**Comment by bvizzier-ucsc** [comment]
Looks good to me.

**Comment by nolunwa-ucsc** [comment]
looks good to me too thanks
