### ISSUE TITLE
Provide cellxgene team with list of all DCP projects contained in cellxgene

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#2411]
Prepare a google sheet with all cellxgene datasets that also exist in the DCP.
We can do this manually in this ticket and then look for ways to make this easier with any automation.

As the project edits JSON has been recently updated, we can use this as a source of data for the spreadsheet.

Let's make columns
- DCP title
- DCP Project ID
- Link to the cellxgene collection page.

**Comment by MillenniumFalconMechanic** [comment]
https://cellxgene.cziscience.com/collections/b52eb423-5d0d-4645-b217-e1c6d38b2e72
https://cellxgene.cziscience.com/collections/a238e9fa-2bdf-41df-8522-69046f99baff
https://cellxgene.cziscience.com/collections/558385a4-b7b7-4eca-af0c-9e54d010e8dc
https://cellxgene.cziscience.com/collections/cdfb9ead-cb58-4a53-879d-5e4ed5329e73
~~https://cellxgene.cziscience.com/collections/7edef704-f63a-462c-8636-4bc86a9472bd~~ Withdrawn.
https://cellxgene.cziscience.com/collections/c9706a92-0e5f-46c1-96d8-20e42467f287
https://cellxgene.cziscience.com/collections/db468083-041c-41ca-8f6f-bf991a070adf
~~https://cellxgene.cziscience.com/d/fetal_maternal_interface_10x-22.cxg/~~ No collection associated with cxg.
https://cellxgene.cziscience.com/collections/c114c20f-1ef4-49a5-9c2e-d965787fb90c
https://cellxgene.cziscience.com/collections/24d42e5e-ce6d-45ff-a66b-a3b3b715deaf
https://cellxgene.cziscience.com/collections/af893e86-8e9f-41f1-a474-ef05359b1fb7
https://cellxgene.cziscience.com/collections/48d354f5-a5ca-4f35-a3bb-fa3687502252
https://cellxgene.cziscience.com/collections/6e067060-f7e4-466c-86f3-ec3dd33c0381

**Comment by mrtopsyt** [comment]
Made a spreadsheet [linked here](https://docs.google.com/spreadsheets/d/1nPXhG-mCy6jN1MN1Au12w2g_5JDGSfNrIiBK6wXzc1c/edit?usp=sharing)! In case this has to be done again you can use this very basic script to get the links

```
import json
with open("spa/src/app/files/project-edits/project-edits.json", "r") as f:
    j = json.load(f)
output = []
for entry in j:
    if "analysisPortals" in entry:
        for i in entry["analysisPortals"]:
            if i["name"] == "CELLXGENE":
                output.append(f"{entry['entryId']},{i['url']}")
print("\n".join(output))
print(len(output))
```
