### ISSUE TITLE
Switch `dev` LungMAP instance to Azul dev

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#2448]
We added the `lungmap` and `lm2` catalogs to Azul `dev` in  DataBiosphere/azul#3956. The [dev](https://data-browser.dev.lungmap.net/explore/projects) instance of the LungMAP DB  therefore can and should be using the `dev` instance of Azul.

**Comment by theathorn** [comment]
Dup of #2371.
