### ISSUE TITLE
Technical Design for Direct Download

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#249]
My understanding of the direct download api is as follows:

1. from the web browser hit `GET /files/$uuid` in DSS. It will send a bunch of 302 redirects to itself and finally a 301 to a signed URL to the file in the checkout bucket.
1. Use the signed url returned to allow the user to  request the download 

I need some clarification on what a "checkout bucket" is and how long the file will remain in the S3 bucket once the request is made.

┆Issue Number: HCAB-222

**Comment by hannes-ucsc** [comment]
Checkout bucket expiration should be handled transparently by DSS and should not be an issue.

Azul needs to add a response field to specify the DSS URL to a file: https://github.com/DataBiosphere/azul/issues/453
