### ISSUE TITLE
Proposal for additional "Cell" or "Library Prep" views

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#250]
UX feedback from @adriennes suggests that the current implementation of the Specimens Tab is confusing when there is one bundle per 10X specimen but potentially thousands of bundles per SmartSeq2 specimen.
Also the definition of what exactly is meant by "Specimen" (it's currently "Biomaterial ID") is unclear (could add a hover-over for this).

One suggestion is to aggregate specimens at the plate level which would reduce the number of bundles per  "specimen" by a factor of 96.

Alternatively the Specimens Tab could be replaced by "Cell" and "Library Preparation" Tabs (suggested by @willrockout, @claymfischer and @NoopDog).

┆Issue Number: HCAB-223

**Comment by NoopDog** [comment]
Closing as specimens tab is implemented and other tabs ore in flight.
