### ISSUE TITLE
Incorrect cell count/specimens displayed in staging UI

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#252]
In the staging Browser, I am viewing the project "Healthy and type II diabetes pancreas" which is a SmartSeq2 experiment that has data from 10 pancreas tissue samples from which 3,514 cells were sequenced. Because this is a SS2 experiment, each cell suspension contains a single cell. In the view of this project (screenshot below), the 10 pancreas tissue samples are displayed, but each tissue is shown to have 1 cell in the Cell Count (Estimated) column. This is incorrect. Each tissue produced many cells, although you'd have to aggregate (sum) the number of cell suspensions linked to each tissue to get the count. They likely are not all the same count.

Not sure if this is a bug or whether this view is an intermediate step towards figuring out how to display SS2 experiments in the Browser. Though I'd make a ticket anyway :grinning:

![screen shot 2018-10-04 at 11 52 18](https://user-images.githubusercontent.com/10993501/46469689-10911700-c7cc-11e8-99b8-22ab637226ce.png)

┆Issue Number: HCAB-225

**Comment by theathorn** [comment]
Need to wait for the fixes to https://app.zenhub.com/workspace/o/databiosphere/azul/issues/366 and https://app.zenhub.com/workspace/o/databiosphere/azul/issues/368.

**Comment by hannes-ucsc** [comment]
@achave11, please investigate if this duplicates any existing issues on the Azul repo. If so, link them as blocking this issue but leave this one open.

**Comment by achave11-ucsc** [comment]
This is still a bug https://github.com/DataBiosphere/azul/pull/460 did not fix the Estimated Cells field.
@hannes-ucsc for further review. 

**Estimated Cells 3,514** 
Should be our response when project *Healthy and type 2 diabetes pancreas* is selected. 
**Cell Count (Estimated)**
For each specimen_id column should have the independent number of contributing cells to each specimen.  The other summary fields should remain the same. 

Thanks @malloryfreeberg

**Comment by hannes-ucsc** [comment]
@malloryfreeberg AFAICT, this is also an issue with one of the demo data sets:

https://staging.data.humancellatlas.org/explore/specimens?filter=%5B%7B%22facetName%22%3A%22project%22%2C%22terms%22%3A%5B%22Single+cell+transcriptome+analysis+of+human+pancreas%22%5D%7D%5D

Do you concur?

**Comment by malloryfreeberg** [comment]
@hannes-ucsc yes, it looks like the same issue.

**Comment by hannes-ucsc** [comment]
I can confirm that this is fixed in `dev`.
