### ISSUE TITLE
Remove project-assets origin and related bucket from dev and prod dcp cloudfronts as they are not used

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2556]
These were set up when we transferred dcp1 to the UCSC AWS originally but are no longer needed for DCP2. They held a cache of the matrix service output for each project and this service no longer exists.

**Comment by NoopDog** [comment]
Validated that these do not exist in prod and have also been deleted in dev.

### Prod
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/51f916f6-aa2c-46f1-8e28-c4b0d0d98d3f)

### Dev
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/34bf7fc0-6b5b-4919-b5c3-275c71a2aefc)

**Comment by MillenniumFalconMechanic** [comment]
Completed.
