### ISSUE TITLE
Add AWS Managed SecurityHeadersPolicy to all behaviors on all cloudfront distributions to address the "HTTP Strict Transport Security (HSTS) Policy Not Enabled" security scan finding.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2557]
See the policy here:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-response-headers-policies.html

# Dev

- [x] HCA DCP Dev
- [x] Lungmap Dev
- [x]  UX Dev

# Prod

- [x] Lungmap
- [x] HCA DCP

**Comment by NoopDog** [comment]
## Dev

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e7f13c5a-c170-4ee4-92c7-dd7717fb57e8)


![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/791a8bbe-d4ae-4fcc-8803-3ab751628361)

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/11487b4a-1552-4df6-b186-60ba1761b64f)

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/3cb7d436-70b6-4163-97ed-c18101266082)

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/6ad389d6-b19b-477a-89f1-fa367637c24c)

**Comment by NoopDog** [comment]
## Prod

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/cfab78b3-f57d-4e1f-ae3a-b693ab6f97d9)


![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/37f26a5d-7b1b-4dfd-8426-73fb8c871469)

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d89f06ba-3aad-4c26-9b35-aaf3bf5b0742)

**Comment by NoopDog** [comment]
![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/279e26c0-4aa9-474f-8aab-b2b5774a9f83)

**Comment by NoopDog** [comment]
@theathorn let's review and see if we can close this once the security scan is re-run.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
