### ISSUE TITLE
Retry Azul requests when it returns a 503

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#2559]
Upstream services (services to which Azul is a client) sometimes take too long to respond. Azul time-boxes those requests to 5s (configurable) in order to ensure that it can respond within a time frame that is adequate for a service backing an interactive user interface. Azul can't retry the upstream requests since its serverless architecture only leaves each request 30s to process. 

We need to push the retries all the way to the client. That way, Azul get a another full 30s to process the request.

A minimal implementation would retry an Azul request if it returns a 503, The retry should be done after waiting the time specified in the `Retry-After` response header or immediately if that header is absent.

Optionally, the user should be given a visual indication that the system is slow to respond and that a retry is in process.

Work on this could start now, but can't complete before Azul actually returns those 503s (https://github.com/DataBiosphere/azul/issues/3968).

**Comment by melainalegaspi** [comment]
@theathorn to discuss this with CleverCanary.

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog, see https://github.com/clevercanary/data-browser/issues/857.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
