### ISSUE TITLE
Add the main .zarray file (and not the others) to the links.json so Azul can index the file and use this as a marker for a matrixable bundle.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#257]
@hannes-ucsc you were going to reach out to green to communicate this to them I believe. 

What is the ticket in the green repo we can track so we know they know they need to do this?

Thanks!

┆Issue Number: HCAB-230

**Comment by mckinsel** [comment]
I believe `links.json` is not generated by the green box but by ingest.

**Comment by theathorn** [comment]
Marcus, I think you are driving this with Green (@kbergin)?
Do we have a bundle in integration or staging with a ".zarray" file of type "matrix" available for @NoopDog to test with?
The plan is to dry run this on 10/22 prior to Nov 1-2 GG demo.

**Comment by theathorn** [comment]
Kylee on slack: "We are hoping to have the required code changes merged in today to be promoted to staging tomorrow. There is a plan to run a scale test tonight, if it is run after we get the changes in it will produce the outputs he needs in integration".

Dave on slack: ".zarray.matrix uuid is 21454ad9-8e5a-48a8-b2e6-bb4dcf125c5b".
I'm not sure to which bundle he is referring.

**Comment by NoopDog** [comment]
My understanding is that 21454ad9-8e5a-48a8-b2e6-bb4dcf125c5b is a hand made bundle on DSS integration that  has the .zarray file included in the links.json. This is meant to be an example of how a bundle is tagged to be "matrixable".

**Comment by theathorn** [comment]
Does https://app.zenhub.com/workspace/o/databiosphere/azul/issues/397 make this redundant?

**Comment by theathorn** [comment]
This is an azul issue - see various tickets there.
