### ISSUE TITLE
Summarize users "getting to value"  (downloads) on the analytics reports

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2648]
We have the answers to many of these questions buried in the report. Let's extract some answers to key questions in a summary at the top o the report.

In the last month:

Traffic Summary
1. x many users came to the site x many times.
1. x many users came to the data browser x many times.

Download / Export Summary
1. x many users requested or performed, x many downloads
1. x many users requested or performed x many matrix downloads.
1. x many users requested or performed x many DCP-generated matrix downloads.
1. x many users requested performed x many contributor matrix downloads.
1. x manny users downloaded or requested alignment files (BAMs)
1. x manny users downloaded or requested sequencing files (FASTQs)
1. x many users downloaded or requested metadata.

Project Specific Downloads
1. x many users downloaded x many project files
1. x many users downloaded x many project matrices.
1. 

Cross Project (Bulk ) Downloads
1. 

To be continued and refined

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
