### ISSUE TITLE
Find cellxgene links that link to the data browser and make sure the data browser links to cellxgene

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#2688]
Also, check the link back seems correct.

**Comment by frano-m** [comment]
Confirm the existing corresponding link between data browser and cellxgene:
- [Single-cell RNA-Seq Investigation of Foveal and Peripheral Expression in the Human Retina](https://data.humancellatlas.org/explore/projects/4bec484d-ca7a-47b4-8d48-8830e06ad6db) confirm corresponding [cellxgene](https://cellxgene.cziscience.com/collections/7edef704-f63a-462c-8636-4bc86a9472bd) link.

Confirm these existing links are correct:
- [A single-cell reference map of transcriptional states for human blood and tissue T cell activation](https://data.humancellatlas.org/explore/projects/4a95101c-9ffc-4f30-a809-f04518a23803) to [Single-cell transcriptomics of human T cells reveals tissue and activation signatures in health and disease](https://cellxgene.cziscience.com/collections/24d42e5e-ce6d-45ff-a66b-a3b3b715deaf).
- [A multi-omics atlas of the human retina at single-cell resolution](https://data.humancellatlas.org/explore/projects/9c20a245-f2c0-43ae-82c9-2232ec6b594f) to [Single-cell transcriptomic atlas for adult human retina](https://cellxgene.cziscience.com/collections/af893e86-8e9f-41f1-a474-ef05359b1fb7).

Confirm this (newly mapped) link between cellxgene and data browser is correct:
-  [scRNA-seq assessment of the human lung, spleen, and esophagus tissue stability after cold preservation](https://cellxgene.cziscience.com/collections/4d74781b-8186-4c9a-b659-ff4dc4601d91) to [Ischaemic sensitivity of human tissue by single cell RNA seq](https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7).
