### ISSUE TITLE
Spec out Paging for the web service

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#27]
The current webservice has paging implemented. However, as more data is added, the current paging method used, by using ElasticSearch `from` and `to` will not scale. We need spec out the following:

- Should the user be able to randomly go to arbitrary pages (will be pretty complicated. May actually be unnecesary).
- Should the user be able to only continually scroll through pages forward and backwards (easier to implement, but will require changes to the UI and the response from the Web Service)
- Should we only display the current paging when user selects facets that bring down the selected number of entries to a certain level?
- More options?

┆Issue Number: HCAB-92

**Comment by theathorn** [comment]
Paging implemented as next/prev page only.
