### ISSUE TITLE
Change "Download" button text to "Select files"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#270]
Raised by @adriennes as https://app.zenhub.com/workspace/o/humancellatlas/data-portal/issues/256.

@jodihir to review word choice.

┆Issue Number: HCAB-240

**Comment by theathorn** [comment]
I think "Download Manifest" is more precise. @briandoconnor ?

**Comment by adriennes** [comment]
In user testing, most users didn't know what a manifest was.  I think this is not a common enough term to fix the issue

**Comment by theathorn** [comment]
Look at https://portal.gdc.cancer.gov and add some items to the cart. You then get an option to "Download Manifest" (see attached screenshot).
![gdc_cart.JPG](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/5180bf84-7145-490f-a9ac-a710cd9b6e35)

**Comment by adriennes** [comment]
We're not the only site to use this term, but it is not commonly understood.  In the two rounds of user research, this was one of the most consistently confusing issues, with almost every participant misunderstanding.  
Some of the misconceptions about "manifest" are outlined here: https://docs.google.com/presentation/d/15Kq21-ItlvLemJDZepU3IKZaF83ZOliohxww6z17nyQ/edit#slide=id.g41de12c875_0_390

**Comment by NoopDog** [comment]
Yes, "Manifest" is a bit of an internal term.

The thing we want to get across is that there is a 3 step process:

1. Select Data
1. Download a list of files for the selected data.
1. Use the list of files to download the data with the HCA CLI.

So, what other terms can we use for manifest? Or, should we try to teach what a manifest is with a tooltip?

Jodi, has recently added a description of manifest to the download page and we can supplement that with a hover card/tooltip for the "Download Manifest" button with text such as:

```
To download the selected data:
1) First download a manifest of the selected files.
2) Use the manifest along with the HCA CLI to download the data and associated metadata"
```

In any case we need to

1. Decide on a name for the`list of files`. (if its not manifest then what do we call it?)
1. Feed forward/educate/signify the concept of the `list of files` and how to use it.

**Comment by NoopDog** [comment]
@adriennes looking at your feedback in the report, looks like we have a few challenges to address. Thanks for bringing these up.

Looks like "fear of downloading a large file set" is key.

**Comment by NoopDog** [comment]
Maybe "Request File Manifest" this will match our soon to come "Request Expression Matrix" with hover text:

"Request a file manifest for downloading the selected data with the HCA CLI"

**Comment by adriennes** [comment]
I can get onboard with that, @NoopDog .  Let's give that wording a try and follow up with users  in the beta.  

I think you better articulated than me that the issues are: 1. Download implies immediate action; and 2. "Manifest" is a bit obscure.  Let's see if "file manifest" does better.  

Can we also remove the download icon on the button?

**Comment by NoopDog** [comment]
Nice @adriennes. Yes, was also thinking to remove the download button. Will get the above implemented.

**Comment by NoopDog** [comment]
@adriennes this flow has been updated please take a look.

Mods are:

1. indicate download file manifest and button
1. Changed text on "Select File Types" page to hint on how the manifest is used.
1. Changed text on download page from "Congrats! to indicate download has only started and what to do when it completes.
1. Changed "Get Download Instructions"  to "Get HCA CLI Instructions"
