### ISSUE TITLE
Request `openid` scope during authentication

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#2720]
For details, see https://github.com/DataBiosphere/azul/issues/3833#issuecomment-1190516562

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "@NoopDog , we discussed this briefly in today's meeting and I said that you don't need to act on any of these token-related issues. However, this one you could work on immediately. It just needs requesting an additional scope during the auth flow."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Will re-triage when @theathorn is back. Team can work on it immediately."

**Comment by NoopDog** [comment]
The `openid` scope is already requested.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to specify a method to verify resolution.

**Comment by hannes-ucsc** [comment]
To verify, steal a fresh token from the Data Browser UI in `anvildev` and `anvilprod` and use the `https://www.googleapis.com/oauth2/v3/tokeninfo` endpoint to determine the scope of said token. See also

https://github.com/DataBiosphere/azul/blob/98c05d254e4598277dcceba0c07e9832605fad8f/src/azul/oauth2.py#L96

**Comment by nadove-ucsc** [comment]
`anvildev`:
```
$ curl https://www.googleapis.com/oauth2/v3/tokeninfo -H "Authorization: Bearer $anvildev_token" | jq -r .scope | tr ' ' '\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   456    0   456    0     0   2023      0 --:--:-- --:--:-- --:--:--  2026
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile
openid
```

`anvilprod`:
```
$ curl https://www.googleapis.com/oauth2/v3/tokeninfo -H "Authorization: Bearer $anvilprod_token" | jq -r .scope | tr ' ' '\n'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   458    0   458    0     0    843      0 --:--:-- --:--:-- --:--:--   843
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile
openid
```

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to ensure that there isn't another blockee that we can now start to work on.
