### ISSUE TITLE
Create instance in `platform-anvil-dev`; set up CI/CD for it

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#2756]
- [x] Meet training requirements for AnVIL (@theathorn can provide details)
- [x] Ask Erich for access to AWS account `platform-anvil-dev` and Google Cloud project of the same name cc'ing Trevor and me
- [x] Manually create Data Browser instance in that account/project
- [x] Prepare VPN certificate request for `anvildev.gitlab` (same procedure as for `dev.gitlab`)
- [x] Create VPN connection for `anvildev.gitlab` when you certificate from me
- [x] Request access to GitLab
- [x] Set up build on GitLab to automatically deploy the instance created manually

**Comment by melainalegaspi** [comment]
@theathorn to discuss with Clever Canary

**Comment by hannes-ucsc** [comment]
https://anvil.gi.ucsc.edu/explore/datasets
