### ISSUE TITLE
NIH Security Training

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2761]
[Security Training and Awareness Appendix 1](https://docs.google.com/document/d/18_UoOkT84AlbMrovhnV93aNjjlsv7SAkw3InZdmUeQc)

Per the [Data Access](https://ucsc-cgl.atlassian.net/wiki/spaces/DEV/pages/1774714882/Data+Access) requirements, Complete the [NIH INFORMATION SECURITY AND INFORMATION MANAGEMENT TRAINING COURSES](https://irtsectraining.nih.gov/publicUser.aspx):

### 1) Take Training Courses
1.   - Information Security Awareness for New Hires
2.   - Information Management for New Hires
3.   - Information Security and Management Refresher 
4.   - Secure Remote Computing

Collect the PDF certificate of completion for each of the courses above.

### 2) Sign and Date the documents listed below

- Sign in context if possible
- Save as PDF
- Open in a PDF viewer and sign and date if there is no way to sign in the doc.
  

1. - [NIH Genomic Data Sharing Policy Agreement](https://giwiki.gi.ucsc.edu/images/1/1b/NIH_GDS_Policy.pdf)
2.   - [dbGaP APPROVED USER CODE OF CONDUCT](https://dbgap.ncbi.nlm.nih.gov/aa/GWAS_Code_of_Conduct.html)
3.   - [NIH Security Best Practices for Controlled-Access Data Subject to the NIH Genomic Data Sharing (GDS) Policy](https://osp.od.nih.gov/wp-content/uploads/NIH_Best_Practices_for_Controlled-Access_Data_Subject_to_the_NIH_GDS_Policy.pdf)
4.   - [National Institutes of Health Genomic Data Sharing Policy](https://giwiki.gi.ucsc.edu/images/1/1b/NIH_GDS_Policy.pdf) (Dupe of 1)

### 3) Complete the Survey Monkey Quizzes
 **_(Save a PDF of your completed quiz before exiting)_**
You can use an incognito browser to take the test again if you forgot to save the PDF or want to retake.

  - [dbGaP Code of Conduct quiz](https://www.surveymonkey.com/r/HKXNYD7)
  - [NIH Security Best Practices for (CAD) Subject to NIH (GDS) Policy quiz](https://www.surveymonkey.com/r/FG3C63T)

**Comment by NoopDog** [comment]
Thanks for the detail @theathorn

**Comment by NoopDog** [comment]
@theathorn security training is complete and all training documents and artifacts are uploaded to the team drive.

**Comment by theathorn** [comment]
Confirmed all required trainings have been completed.
