### ISSUE TITLE
Aggregate SmartSeq2 data in Data Browser at Plate level

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-browser#277]
SmartSeq2 data should appear at the plate level in a given row of the browser, rather than at the single cell level.
Plate information is available in the metadata.

This better corresponds to 10X row format and is more interpretable than 1 cell per row

┆Issue Number: HCAB-247

**Comment by malloryfreeberg** [comment]
I want to clarify that while plate information is required in the metadata (`cell_suspension.plate_based_sequencing.plate_id`), it is not always known. When not known, the term "not provided" or something similar is used. So, cell counts can be aggregated by this field, but they might not always represent a "true" grouping of cells on a single plate. 

Usually 96-well or 384-well plates are used in plate-based sequencing (like SmartSeq2). So, aggregating on this field will usually result in these counts (or a few under if some of the wells didn't work). Seeing a count over these values (e.g. 500) is an indication that the actual plate IDs were not known.

**Comment by NoopDog** [comment]
Obsolete closing.
