### ISSUE TITLE
Add sentence about unchecked state in download file selector

### ISSUE THREAD

**Issue by adriennes** [DataBiosphere/data-browser#278]
In download flow, pop-up file selector: Add a sentence when no file boxes are selected under "Download Manifest" button. 
Suggested wording: "All files selected"

┆Issue Number: HCAB-246

**Comment by theathorn** [comment]
Initially, all check boxes should be checked. If no check boxes are checked, the Download button should be disabled. This avoids the ambiguity that both "no checked boxes" and all checked boxes" mean "everything".

[edited by Hannes]

**Comment by theathorn** [comment]
Will be covered by #435 proposal.
