### ISSUE TITLE
Restore auth functionality on AnVIL deployment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#2802]
… so we can undo the workaround detailed on https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1660970621071359?thread_ts=1660951768.212979&cid=C705Y6G9Z

**Comment by hannes-ucsc** [comment]
… so we can undo the workaround detailed on https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1660970621071359?thread_ts=1660951768.212979&cid=C705Y6G9Z

**Comment by theathorn** [comment]
@theathorn to discuss with Clever Canary

**Comment by NoopDog** [comment]
@hannes-ucsc @bvizzier Can this be closed? If not, can we add more detail? Cheers, D

**Comment by hannes-ucsc** [comment]
The ticket was opened based on your comment in the Slack thread that's linked to in the description.

> Interesting, we have not implemented authentication.

It appears that since then, sign-in functionality was added to the [rewrite](https://github.com/DataBiosphere/data-browser/tree/main/explorer). Because of blocker DataBiosphere/azul#4398 and its blockers, that functionality doesn't work end-to-end in `anvildev`. @NoopDog, for the record, could you please post the hashes of the commit(s) that added sign-in functionality? I would like to leave this open until the blockers have been resolved and we can show that sign-in is working end-to-end. After you point to the commits as I requested, I am happy to be assigned this issue for review and place it in the *Review requested* column.

**Comment by bvizzier-ucsc** [comment]
@NoopDog: "Auth functionality was restored."  

Closing ticket.
