### ISSUE TITLE
Selecting `1M Immune Cells` under Project facet crashes the browser

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#282]
1) Visit browser without filters
2) Change the Project facet to `1M Immune cells`
3) Browser crashes, table view is not updated
4) Hit refresh. Table view is updated but empty

![](https://user-images.githubusercontent.com/5143256/47318166-34dc5880-d600-11e8-8103-1d9afeb61318.png)

Note the cancelled requests and the stack trace in the console.

~I originally mentioned the cancelled requests as a separate issue in this morning's stand-up, but I think they are causally related to this issue.~ Update: They are not: https://github.com/HumanCellAtlas/data-browser/issues/284

┆Issue Number: HCAB-250

**Comment by NoopDog** [comment]
@hannes-ucsc   This should be fixed on stage now. Thanks D

https://staging.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22project%22%2C%22terms%22%3A%5B%221M+Immune+Cells%22%5D%7D%5D
