### ISSUE TITLE
It always shows 0 or 1 bam when hovering over the checkmarks

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/data-browser#285]
I've noticed that no matter the number of fastqs it will always show 1 for the bam count if there are any bams in the data store. @hannes-ucsc  said this seems like a bug.

![image](https://user-images.githubusercontent.com/9449764/47392713-5bc38900-d6eb-11e8-92b0-a67faf15e998.png)

Example ^ on staging browser

┆Issue Number: HCAB-253

**Comment by hannes-ucsc** [comment]
Related but not causative: https://github.com/DataBiosphere/azul/issues/486.

**Comment by theathorn** [comment]
Over to @NoopDog for triage.
