### ISSUE TITLE
AnVIL: Change current columns titled "Dataset Id" to use the value of `dataset.title`

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/data-browser#2850]
**Current Behavior**
The first column of the Dataset tab is the Dataset Id, which is a UUID and not humanly usable.  
The same is true for other tabs currently displaying a Dataset Id column.

**Requested Behavior**
The first column of the Dataset tab should display the value of `dataset.title`.  
Other tabs displaying a Dataset Id column should also be updated accordingly.

The `dataset.title` is currently expected to contain the name of the source AnVIL data workspace.

**Considerations**
The name of the column heading is open for consideration.  
"Dataset Id" works from a usability perspective, although it is does not actually represent the `dataset_id` field of the Findability subset and is therefore a misnomer.  
Simply "Dataset" works, IMO.  
I don't particularly like "Dataset Title", although I am not strongly opposed to it.

**Comment by NoopDog** [comment]
Completed
