### ISSUE TITLE
AnVIL: Add a search facet for the Dataset Title

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/data-browser#2851]
**Current Behavior**
There is no search facet for the Dataset Title (`dataset.title`).

**Requested Behavior**
Add a search facet for the Dataset Title.

**Considerations**
Please see considerations regarding the display name of this field in this ticket:
https://github.com/DataBiosphere/data-browser/issues/2850

**Comment by NoopDog** [comment]
Completed
