### ISSUE TITLE
AnVIL: Display and add search facet for `dataset.registered_identifier`

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/data-browser#2852]
**Current Behavior**
The Dataset registered_identifier value (commonly the dbGaP PHS id) is not currently displayed in the Dataset tab, nor is there a search facet for it.

**Requested Behavior**
* Display the Dataset registered_identifier value as column on the Dataset tab.
* Add a search facet for the Dataset registered_identifier

**Comment by NoopDog** [comment]
Completed
