### ISSUE TITLE
AnVIL: Display and add search facets for Dataset `consent_group` and `data_use_permission`

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/data-browser#2853]
**Current Behavior**
The Dataset `consent_group` and  `data_use_permission` values are not currently displayed in the Dataset tab, nor are there search facets for them.

**Requested Behavior**
* Display the Dataset `consent_group` and  `data_use_permission` values as columns on the Dataset tab.
* Add a search facets for Dataset `consent_group` and  `data_use_permission`

**Considerations**
Although the values of these two fields are similar, they are not necessarily the same.  
My understanding is:  
* The `consent_group` is most commonly understood and used by researchers today.  
* The `data_use_permission` will see increasing use with DUOS in AnVIL going forward.  
Therefore, I expect both are important, yet this may warrant verification/discussion.

**Comment by NoopDog** [comment]
Completed

**Comment by NoopDog** [comment]
Completed
