### ISSUE TITLE
AC-11 Implement session inactivity logout

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2885]
..after 15 minutes.
Silently log out the user and clear the screen display (to prevent a passerby gaining access to the info).

**Comment by NoopDog** [comment]
@bvizzier-ucsc @hannes-ucsc do you see any back-end dependency here? I am thinking we can log out after 15 minutes of inactivity purely on the client. Anything we need from Azul here?

**Comment by hannes-ucsc** [comment]
No and no.

**Comment by NoopDog** [comment]
Complete
