### ISSUE TITLE
Metric suffix for kilo (10**3) is `k` not `K`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#290]
![](https://user-images.githubusercontent.com/5143256/47477832-0915ca00-d7dc-11e8-99c5-7874d77cc441.png)

┆Issue Number: HCAB-256

**Comment by NoopDog** [comment]
@frano-m lets make sure this is dong k and not kilobytes (1024 based) rounding that is used for file size.
