### ISSUE TITLE
Rename "Author List" to "Contributors" in Project view

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#291]
In the Project display, contributors to the dataset are listed below under the heading "Author List". The term "Author List" is inaccurate as it implies a publication which is not always present. The title of this section should be changed. I suggest "Contributors" but there might be better options (@gabsie @adriennes ). 

Also, the HCA wranglers should **not** be listed here. Wranglers are indicated in the metadata by the field:value `"project_role": "Human Cell Atlas wrangler"` in the `project.json` schema. Wrangler organization affiliations should not be included in the "Collaborating Organizations" section.

![screen shot 2018-10-25 at 10 56 18](https://user-images.githubusercontent.com/10993501/47492644-61cd7d00-d845-11e8-84a8-4a2006f0c2cd.png)

┆Issue Number: HCAB-257

**Comment by NoopDog** [comment]
@malloryfreeberg thanks for the clarification on this. These will be quick changes. Cheers, D

**Comment by frano-m** [comment]
@NoopDog we will need API for project_role...

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/88977fd6-440a-4df9-ba8d-c6b580ef557b)

**Comment by hannes-ucsc** [comment]
I am uncomfortable with hard-coding a filter on `Human Cell Atlas wrangler` in the Azul source. We try to avoid coding to specific free-form strings. We'll implement it this way but it is a hack and I think in the long term this field should really have an ontology.

**Comment by NoopDog** [comment]
@hannes-ucsc can you just send the role field through and let the front end filter the contributors based on  the role field value? The front end is already highly specific to HCA so no loss there.

**Comment by gabsie** [comment]
> I am uncomfortable with hard-coding a filter on `Human Cell Atlas wrangler` in the Azul source. We try to avoid coding to specific free-form strings. We'll implement it this way but it is a hack and I think in the long term this field should really have an ontology.

@hannes-ucsc @malloryfreeberg 
I think it is worth considering in the future that this wrangler/curator information is just entered separately from the submitters' names altogether, to make it cleaner for you, I agree.

**Comment by malloryfreeberg** [comment]
> We try to avoid coding to specific free-form strings. 

Currently, this field is an enum (so there is a restriction on the strings that are valid), which is slightly better than just free text. If @NoopDog can implement a filter from the front-end, this is an acceptable fix for now.

I also agree with @gabsie that we might be better off implementing a different way to indicate the curators/wranglers so that it's easier to separate them from the other contributors.

**Comment by NoopDog** [comment]
Hi @malloryfreeberg these updates have been promoted to staging. Would love to have your feedback.

 https://staging.data.humancellatlas.org/explore/projects

Thanks,
D

**Comment by malloryfreeberg** [comment]
- [x] s/Author/Contributors/ (I would actually remove the word "List" and have the title just say "Contributors", but this is a minor tweak)
- [ ] Filter out wranglers from Contributors

**Comment by frano-m** [comment]
- Rename Contributors
- Rename Organisations to USA spelling

**Comment by NoopDog** [comment]
@malloryfreeberg this update is now on:

https://staging.data.humancellatlas.org/explore/projects 

Does this look ok to close?

Cheers,
D

**Comment by malloryfreeberg** [comment]
The Contributors name looks good!

I still see wranglers listed, though. Should I make a new/separate ticket for that?
