### ISSUE TITLE
Request Expression Matrix button displaces File Size summary item

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#292]
I guess wrapping can't be avoided but to have a single orphaned summary item on the second line looks odd. A couple suggestions: 

1) Rename _Request Expression Matrix_ and _Request Manifest_ to _Get Expression Matrix_ and _Get Manifest_.

2) Wrap the button labels:

```
     Request         Request
Expression Matrix    Manifest
```

3) Also wrap the _Files_ summary item so it is on the same line as the _File Size_ item.

┆Issue Number: HCAB-259

**Comment by NoopDog** [comment]
@hannes-ucsc can you upload a screenshot? What browser and OS are you using? 
https://www.whatsmybrowser.org/

Thanks,
D

**Comment by NoopDog** [comment]
Can you also explain this one with an image or perhaps a 2nd ticket?
>Also wrap the Files summary item so it is on the same line as the File Size item.

**Comment by NoopDog** [comment]
Ok you mean this.

<img width="782" alt="screen shot 2018-10-26 at 4 49 13 am" src="https://user-images.githubusercontent.com/3239697/47523070-84f63c00-d8da-11e8-8224-2d8062d50a40.png">



Yes, looks like there is some style that we worked on but was not committed that will solve this.  Stay tune...
