### ISSUE TITLE
Table view width is fixed (or capped) and summary never unwraps even on wide screens

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#293]
![](https://user-images.githubusercontent.com/5143256/47522764-4cf3e800-d84b-11e8-98c6-7bd192039788.png)

I tried both Chrome and Firefox.

┆Issue Number: HCAB-258

**Comment by NoopDog** [comment]
Yes we have been wanting to make this full screen since inception. Glad to see others concur.

**Comment by frano-m** [comment]
@hannes-ucsc yes!  This was part of the original design specification (max width set at 1200).  Dave and I discussed yesterday after issue of wrapping of summary... stay tune!
