### ISSUE TITLE
Describe internal Google Workspace accounts

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2931]
Update the [Google Workspace account](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit?disco=AAAAizSpRU4) description in the "Authentication & Authorization for the UCSC Data Browser" document to describe account handling for Clever Canary's internal users. Minimal requirements are 2FA (virtual or hardware).

**Comment by hannes-ucsc** [comment]
Obsoleted by https://github.com/databiosphere/azul/issues/4954.
