### ISSUE TITLE
S3 Block Public Access setting should be enabled at the bucket-level

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#2964]
There are two instances of this finding that relate to buckets managed by Clever Canary. I tried to fix them by manually blocking all public access but had to revert that since it broke the Data Browser. Now, buckets backing CloudFront distros don't need to be public:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

so there is more work for Clever Canary. They need to implement the configuration described in the CF developer guide linked to above and then enable the "block all public access" setting on these buckets.

_Originally posted by @hannes-ucsc in https://github.com/DataBiosphere/azul/issues/4691#issuecomment-1314561236_

**Comment by theathorn** [comment]
@NoopDog :"this should be done in anvil-dev".

**Comment by NoopDog** [comment]
Complete
