### ISSUE TITLE
Finalize the V5 Table columns and facets for March 28th

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/data-browser#3]
┆Issue Number: HCAB-84

**Comment by caaespin** [comment]
UPDATE: Wrote a mockup of the table API : https://docs.google.com/document/d/1yvFqxTMbfOQnWNika5aA-amz_bHRB6snuohJ_hO9dFY/edit

The facets are captured by Jenns mockups: https://projects.invisionapp.com/d/main#/console/13717510/285958430/preview

**Comment by caaespin** [comment]
Closing since we did the demo already
