### ISSUE TITLE
"No Data" in "Cell Count (Estimated)" column inconsistent with "Unspecified"

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#300]
In conversations with @NoopDog about the Known diseases field when there is no information in the metadata, we decided that entering "Unspecified" was a solution as this term is used elsewhere to convey that the information is not known ([GH issue](https://github.com/HumanCellAtlas/data-browser/issues/274)).

On the main Browser landing page (defaults to Project view), missing Cell Count (Estimated) data is shown as "No Data", which is not consistent with the rest of the site. I suggest keeping this consistent and displaying "Unspecified" if cell counts are missing from the metadata.

![screen shot 2018-10-26 at 13 22 23](https://user-images.githubusercontent.com/10993501/47566006-34a2cc80-d922-11e8-88cc-5ceea2bd197d.png)

┆Issue Number: HCAB-263

**Comment by NoopDog** [comment]
Hi @malloryfreeberg these updates have been promoted to staging. Would love to have your feedback.

 https://staging.data.humancellatlas.org/explore/projects

Thanks,
D
