### ISSUE TITLE
Display AnVIL diagnosis/disease attributes in the v4 schema and populated in current snapshots

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/data-browser#3005]
Several of the AnVIL v4 snapshots available as of 11/4/22 populate the following disease attributes:
* `anvil_diagnosis:disease` # represented as _ontology_id_:_ontology_number_
* `anvil_diagnosis:phenotype` # represented as human meaningful text string

Please index and display this information in the AnVIL Data Explorer.
The handling and display(?) of the ontology value may warrant discussion/elaboration/refinement.

These values are populated in the following v4 schema snapshots available to be indexed by AnVIL Azul:
* ANVIL_CMG_UWash_GRU_20221020_ANV4_202211041542
* ANVIL_CMG_UWash_DS_EP_20221020_ANV4_202211041549
* ANVIL_CMG_UWASH_HMB_20221020_ANV4_202211041555
* ANVIL_CMG_UWASH_DS_NBIA_20221020_ANV4_202211041605
* ANVIL_CMG_UWASH_DS_BDIS_20221020_ANV4_202211041609

Examples are not included here as this is controlled data.

**Comment by theathorn** [comment]
Not strictly required for stakeholder demo but would be NTH.

**Comment by hannes-ucsc** [comment]
For demo, show the effects of this change and https://github.com/databiosphere/azul/issues/4618 on hits, facets, sorting, filtering, summary and manifests.

**Comment by NoopDog** [comment]
@theathorn this is now on [anvil dev](https://anvil.gi.ucsc.edu/explore/datasets)

**Comment by NoopDog** [comment]
Complete
