### ISSUE TITLE
Use project_title instead of project_short_name to display Project Name

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#301]
On the main landing page for the Browser (currently the Project view), I believe the `project_short_name` is what is being displayed under the Project Name column. The `project_short_name` is a short code or label for the project, while the `project_title` is the official title or name of the project ([project schema descriptions](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/core/project/project_core.json)). The `project_title` can be thought of as what someone might title a publication relating to the project. In the screenshot below, one of the Project Names is "BM_PC", which is not informative at all.

I think it's best to display the `project_title` for Project Name, as this is more descriptive, more user-friendly, and more informative than the `project_short_name`.

If the `project_title` text is longer than the column, it should wrap to the next line instead of end with an ellipse. 

![screen shot 2018-10-26 at 13 42 47](https://user-images.githubusercontent.com/10993501/47566944-125e7e00-d925-11e8-886d-e91c23cf7311.png)

┆Issue Number: HCAB-264

**Comment by hannes-ucsc** [comment]
@malloryfreeberg What's the purpose of the `project_short_name` field?

I asked the @NoopDog to switch from title to `project_short_name` because the integration tests all share the same title and were impossible to distinguish. Should we display the ~title~ short name on hover?

One thing to consider is that titles are very long and don't lend themselves to being displayed in table columns or the facet chooser popup. This is why I'd really like to know what the supposed use for `project_short_name` is.

**Comment by hannes-ucsc** [comment]
Note my edits above.

**Comment by malloryfreeberg** [comment]
> What's the purpose of the project_short_name field?

The purpose of the `project_short_name` field is to allow contributors a quick way to reference different projects rather than to encapsulate the essence of a project. The short name helps users reference projects in casual conversation if a single lab is contributing multiple projects (e.g. "How's it going with the submission of the Tissue Sensitivity project?"), and also is specifically used to reference a project within the metadata itself. This field is used as a linking field across multiple spreadsheet tabs and help the ingest importer make correct links. The `project_short_name` could also be an institutional code that doesn't have any meaning to an outsider.

> One thing to consider is that titles are very long and don't lend themselves to being displayed in table columns or the facet chooser popup

I understand that it's difficult to display a longer value in the facet chooser or the table, but (1) I don't think the `project_title` or `project_short_name` should actually be a facet. When we have hundreds or thousands of projects in the HCA, what's the point of having this field be in the facet list?  (2) When a user is viewing a table of projects, it seems that one of the most basic pieces of information they'd want to see is the title of the project. The title usually contains relevant information about the data and the motivation or reason for the study, key things that can help a user decide if they want to keep looking at the project or move on.

> I asked the @NoopDog to switch from title to project_short_name because the integration tests all share the same title and were impossible to distinguish

I don't think the Browser should be optimized for displaying the integration tests, since they will ultimately not end up in the HCA/DCP/Browser. If we can switch to displaying `project_title`, what we can do in the meantime is ask the maintainer of the integration test metadata (I think it's @parthshahva?) to generate a unique `project_title` alongside the `project_short_name` to help developers when looking at the Browser. 

> Should we display the short name on hover?

I don't think we need to display the `project_short_name` field at all. It contains no extra information not in the `project_title`.

**Comment by theathorn** [comment]
Wrap the title and display the short name on tool tip.

**Comment by NoopDog** [comment]
@malloryfreeberg these updates have been promoted to staging. Would love to have your feedback.

 https://staging.data.humancellatlas.org/explore/projects

Thanks,
D

**Comment by malloryfreeberg** [comment]
Project titles look good.

It's a little cumbersome to have the pop-up with the short name. The pop-up covers one or more of the projects below so that I can't read it. This might just be a separate usability issue, though.

**Comment by NoopDog** [comment]
What is the short name used for besides to differentiate duped titles of test projects?

**Comment by malloryfreeberg** [comment]
The `project_short_name` is used by ingest to create links between metadata in bundles. It contains no extra information not in the `project_title`.

**Comment by hannes-ucsc** [comment]
I think we should keep displaying short name somewhere. You say that it contains no extra information but that depends on the audience. Technically, string A adds no extra information in relation to string B only if A is a sub string of B. This is not the case for short name and title. The short name is sometimes completely different to the project title. The relation may be obvious to the wranglers. In fact, it's been mind boggling to me in how many different ways we refer to projects: UUID, code name ("treutlein"), short name and title. I'm advocating for some sanity here by displaying all available human-readable project references in the UI.

**Comment by malloryfreeberg** [comment]
Fair points.

As I said above, the pop-up covering other text is a usability issue and not high priority right now.

**Comment by hannes-ucsc** [comment]
@malloryfreeberg, tool tips are always going to obscure some other part of the UI. The team feels that this is not an issue.

Independently, I feel that we haven't yet hit the sweet spot on this one. The short name is too cryptic for external users but the titles are too long. We could fix this by 

a) shortening titles in the metadata

b) introduce `project_short_title` or similar

c) fix 'project_short_name' in the metadata to make it less cryptic
