### ISSUE TITLE
LungMAP Data Browser references "DCP Generated Matrices"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#3028]
In the LungMAP Data Browser click on the "Matrices" download button for any project:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/220fe1d0-bec1-4c54-8946-9b75e5e6436c)

The links (e.g. "uniform pipelines", "quality control metrics") don't actually work (they just open another instance of the "projects" view).

We should just remove the whole "DCP Generated Matrices" section for LungMAP).

**Comment by MillenniumFalconMechanic** [comment]
Closing, will resolve in React re-write.
