### ISSUE TITLE
Files count doesn't match Data file counts

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#303]
In the Project view, the total number of files in the upper banner doesn't match the number of files listed under the Data (Raw, Processed) column. Below are two examples:

- - -
1. cerebral organoids: FILES = **99**; Data = **24** (18 fastq + 6 bam)

should be: 18 fastq + 6 bam (I'm actually not 100% sure about how many bams there should be, but I think it's 1 bam per experiment and there were 6 experiments in this project) so the Data count is accurate, but the FILES count is very high.

![screen shot 2018-10-26 at 14 41 16](https://user-images.githubusercontent.com/10993501/47570113-3a51df80-d92d-11e8-985b-a118ca71c2bf.png)

- - -
1. human pancreas: FILES = **50,798**; Data = **200** (100 fastq + 100 bam)

should be: 2,544 fastq + 2,544 bam (if it's 1 bam per experiment) so the Data counts are too low. I can confirm that all the primary and secondary bundles for this dataset are in the Data Store and are indexed.

![screen shot 2018-10-26 at 14 40 41](https://user-images.githubusercontent.com/10993501/47570086-29a16980-d92d-11e8-843c-cca4712dd93c.png)

- - -
Remaining questions: 

1. Is the FILES sum counting additional analysis files? What is the end user goal of having this count?
1. Why are the counts of bam files shown? What about the matrix files or other analysis output files?
1. Why are there check marks in the Raw and Processed Data columns and I have to hover to get the count? Why not just have the file counts in those columns?
1. A user might want to know separately the size of the raw data (which tends to be big) and the processed data (which tends to be small) so they can determine whether they have capacity to download all of the data files or just the processed data. Is this possible in the Browser right now?

┆Issue Number: HCAB-266

**Comment by hannes-ucsc** [comment]
Re 1: There are data files that aren't fastqs or bams. Like matrix files, for example. Those files make up the difference to 99. To make `num(files) == num(fastq) + num(bams)` we'd have to ignore all other data files, which I don't think is a good idea.

Re 2: This duplicates https://github.com/DataBiosphere/azul/issues/486 which is fixed and deployed to `dev`, and only `dev` at the moment.

**Comment by hannes-ucsc** [comment]
> 3. Is the FILES sum counting additional analysis files? What is the end user goal of having this count?

Yes. The goal is to make the user aware of the number of all files. What would the benefit be of not including these files in the count?

> 4. Why are the counts of bam files shown? What about the matrix files or other analysis output files?

Matrix files are first class citizens and should definitely be included in the pop-up.

> 5. Why are there check marks in the Raw and Processed Data columns and I have to hover to get the count? Why not just have the file counts in those columns?

We should consider this.

> 6. A user might want to know separately the size of the raw data (which tends to be big) and the processed data (which tends to be small) so they can determine whether they have capacity to download all of the data files or just the processed data. Is this possible in the Browser right now?

Yes. Via the files tab.

**Comment by hannes-ucsc** [comment]
DataBiosphere/azul#486 is out on staging now so the cap on # of files to 100 is fixed.

There are two fastqs (read1 and read2), and two bams (qc and rsem) per experiment so the number should be 5144 for both. Do you concur, @malloryfreeberg?

**Comment by malloryfreeberg** [comment]
1. Got it 👍 
1. Ok. There should be 5,088 raw fastq files (2,544 read1 + 2,544 read2). If there are 2 bams per pair of files, then there should be 2 * 2,544 = 5,088 bams.
1. Showing the total file count just seems awkward as it doesn't add up from anywhere else in the Browser, and someone not familiar with what all the output files are (like myself) might be confused or worried about why they are downloading so many "extra" files. This point could probably use further discussion - I'm happy to make a new issue about this and punt it till after the CBeta.
1. Agreed 👍 I'd rank fastqs and matrix files as most important, followed by bam.
1. Cool 👍 happy to punt this till after the CBeta.
1. I see file sizes broken down by file type when I click "Request File Manifest", but not just in the File tab. Is this the intended behavior? I looked at both the staging and dev Browsers.

**Comment by hannes-ucsc** [comment]
3: https://github.com/HumanCellAtlas/data-browser/issues/321
4: https://github.com/HumanCellAtlas/data-browser/issues/322
5: https://github.com/HumanCellAtlas/data-browser/issues/323

> 6. I see file sizes broken down by file type when I click "Request File Manifest", but not just in the File tab. Is this the intended behavior? I looked at both the staging and dev Browsers.

I don't think anyone put much thought into this. First of all, each file should have its size displayed in a file size column. We don't have a good vehicle in the current UI to display a file type summary,

**Comment by hannes-ucsc** [comment]
Follow-up tickets have been created.

Feel free to create a ticket for item 6, @malloryfreeberg.
