### ISSUE TITLE
List Organ part in Project page under Organ (if available)

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#304]
For projects that have the field `specimen_from_organism.organ_part.text` or `organoid.model_organ_part.text` available, display this on the Project page.

An example for the type II diabetes pancreas dataset is below.

![screen shot 2018-10-26 at 14 47 21](https://user-images.githubusercontent.com/10993501/47570593-6de13980-d92e-11e8-9eee-4e9d572956be.png)

- - -
For many organs, knowing the more specific part of the organ that the data are from is key.

┆Issue Number: HCAB-267

**Comment by hannes-ucsc** [comment]
@malloryfreeberg, should we continue to treat the `organ_part` field as an independent facet or should we combine the fields `organ` and `organ_part` into a single facet, for example, by concatenating `organ` and `organ_part`

**Comment by malloryfreeberg** [comment]
> should we continue to treat the organ_part field as an independent facet

For now, yes. I like that when you select an Organ facet, the Organ part facet is reduced to only the relevant terms. This is a useful feature. In the future, we could even dynamically populate the Organ part field with the actually ontology terms that are value child terms of the select parent Organ term. But this is a longer-term goal :)

I don't think concatenating the organ and organ part fields is a good idea. Sometime that doesn't work. Just as a random example, if we had `"organ": "brain"` and `"organ_part": "brain gray matter"`, then concatenating would get you "brain brain gray matter" :)

The feature request in the ticket is simply to additionally display the Organ Part on the Project summary page. The current faceting approach is acceptable.
