### ISSUE TITLE
Remove or clarify File Type on Project page

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#305]
On the summary page for a project, what is the end user goal for listing the file extensions associated with the project? In the example below, I don't think it's useful to tell a user that a "txt" file or a "result" file is available because it doesn't give any information about what is in those files or what they can be used for. 

- - -
![screen shot 2018-10-26 at 14 52 56](https://user-images.githubusercontent.com/10993501/47570781-e5af6400-d92e-11e8-89b3-5ede0b55e125.png)

--

Ideally, the project summary page would contain context about what the files are that are available. Something like:

```
18 Raw FASTQ read files (fastq.gz)
12 Alignment BAM and BAI files (bam, bai)
 1 Gene-by-cell count matrix file (mtx)
...
```

If having a clarified description of files available is not a quick enhancement, I would suggest removing this field from the summary. 

### Added 2018-10-29
From #307 :

Also, when I click "Request File Manifest", I am shown a list of file extensions with what I think are file counts and total sizes. I have no idea what type of information is in files such as those with csv, txt, results, tsv, pdf, jpeg, unknown, etc.

![screen shot 2018-10-26 at 15 05 22](https://user-images.githubusercontent.com/10993501/47571642-f4971600-d930-11e8-88a4-c82a94748934.png)

┆Issue Number: HCAB-268

**Comment by hannes-ucsc** [comment]
I agree that more information about each file type is desirable. @malloryfreeberg Is this information about what each file type means available in the metadata? I'd feel uncomfortable hard-coding assumptions about their meaning in the UI.

However, I disagree that we should remove the list of file types if we can't provide a description of each type. What is the downside of displaying them in that case?

**Comment by malloryfreeberg** [comment]
> Is this information about what each file type means available in the metadata?

Unfortunately, it is not at the moment. The metadata team has discussed adding a field for just this purpose to supplementary files and have an [open ticket](https://github.com/HumanCellAtlas/metadata-schema/issues/542) for it, but we could/should easily extend this to all file entities. This use case would be a good motivation for adding such a field.

Implementing a `file_description` or `file_content` field would require data contributors to tell us about their raw and supplementary files, and the green box to tell us about their analysis files. We'd have to coordinate this schema update.

> What is the downside of displaying them in that case?

The downside I see is that users might be confused about what is available and don't know what is in each file type (except maybe fastq). Maybe this is OK for the CBeta. 

Would it be possible to display the actual filenames instead of the file formats? At least that way users would see things like `barcodes.tsv`, `genes.tsv`, `raw_barcodes.tsv`, and `raw_genes.tsv` instead of just `tsv`.

@gabsie ?

**Comment by hannes-ucsc** [comment]
> Would it be possible to display the actual filenames instead of the file formats? At least that way users would see things like barcodes.tsv, genes.tsv, raw_barcodes.tsv, and raw_genes.tsv instead of just tsv.

File names could be different from bundle to bundle. Usually the file name created by Green have a UUID in them.

When a file extension is too generic (tsv or pdf are a good examples) we could require a sub extension like `.genes.tsv1`. But this convention does not eliminate the need for a metadata field that describes the file type.

**Comment by hannes-ucsc** [comment]
@theathorn I would like to mark this ticket as being blocked by https://github.com/HumanCellAtlas/metadata-schema/issues/542 but somehow that doesn't work. Can you fix this?

**Comment by NoopDog** [comment]
We have a similar issue here that was opened a while back:  https://github.com/HumanCellAtlas/data-browser/issues/242

**Comment by malloryfreeberg** [comment]
> I would like to mark this ticket as being blocked by HumanCellAtlas/metadata-schema#542 but somehow that doesn't work. Can you fix this?

It appears that the data-browser repo and the metadata-schema repo are not in the same ZenHub workspace. Maybe they should be?

**Comment by theathorn** [comment]
Beta-2 feedback requesting clarification of file types.

**Comment by NoopDog** [comment]
Obsolete
