### ISSUE TITLE
Set Estimated Cell Count to Unspecified, not zero

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#306]
In a project summary page of a project which has no metadata for estimated cell count, the cell count is annotated as zero. This is inaccurate (obviously there aren't zero cells in the data). I suggest putting in the "Unspecified" placeholder [agreed upon](https://user-images.githubusercontent.com/10993501/47571393-56a34b80-d930-11e8-8af9-af9614ab683a.png) for when metadata are missing.

- - -
![screen shot 2018-10-26 at 14 52 56](https://user-images.githubusercontent.com/10993501/47571424-6884ee80-d930-11e8-8172-343c804494d4.png)

┆Issue Number: HCAB-269

**Comment by hannes-ucsc** [comment]
@malloryfreeberg, how should we aggregate the cell count over all cell suspensions belonging to a particular project? Specifically, what is the expected result for `Unspecified + 1`?

**Comment by malloryfreeberg** [comment]
I think `Unspecified + 1 = Unspecified`.

In *most* cases, users either specify all the counts or they don't. A single project having a mix will be rare. That being said, one of the CBeta datasets will be mixed as the contributors had estimated cell counts for all their cell suspensions except one (which they left blank).

**Comment by hannes-ucsc** [comment]
In the short term we should implement `Unspecified + 1 = Unspecified` as @malloryfreeberg suggests. In the long term, we could become fancy, e.g. (Python code)

```
(1,n) + 1 = (2,n)
(1,n) + "Unspecified" = (1, n+1)
```

**Comment by NoopDog** [comment]
@malloryfreeberg this was addressed as part of some other ticket. 
Will close. Please re-open if this is not working as you expect. 

![Screen Shot 2019-07-31 at 7.55.13 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/1b3dc22b-d1f3-4047-95f3-18c7a2a30a55)
