### ISSUE TITLE
Warn users when selecting empty fastq files from two LungMAP projects

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#3064]
This is a short-term workaround until we can implement the full solution in #3032.
There are two LungMAP projects with null DRS URIs:
  - [Human distal airways contain a multipotent secretory cell that can regenerate alveoli](https://data-browser.lungmap.net/explore/projects/f899709c-ae2c-4bb9-88f0-131142e6c7ec)
  - [Single-cell multiomic profiling of human lungs reveals cell-type-specific and age-dynamic control of SARS-CoV2 host genes](https://data-browser.lungmap.net/explore/projects/20037472-ea1d-4ddb-9cd3-56a11a6f0f76)
For these 2 projects if the user selects "Export Selected Data" then on the "Select File Types" for download or Terra, dis-allow the selection of fastq files and add a note stating "these are managed access files only available via dbGaP".

**Comment by NoopDog** [comment]
"Fastq files for human subjects are not available for export. For access, please apply to DbGaP. "

 If fastq and human.
