### ISSUE TITLE
Use Preservation method, not Storage method, as facet

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#308]
Under the Method facet, it looks like the field `specimen_from_organism.preservation_storage.storage_method` is being used as a facet. 

I think the point of the facet is to differentiate between "fresh" and "frozen" samples. In which case, the field `specimen_from_organism.preservation_storage.preservation_method` should be used as the facet.

- - -
![screen shot 2018-10-26 at 15 11 30](https://user-images.githubusercontent.com/10993501/47572042-ee556980-d931-11e8-9fcd-46841398ac39.png)

┆Issue Number: HCAB-271

**Comment by theathorn** [comment]
@hannes-ucsc If you merge the PR to extract "preservation method" instead of "storage method" from the metadata then we should also change the facet title in the Data Browser's "Method" drop-down from "Storage Method" to "Preservation Method".

**Comment by frano-m** [comment]
@hannes-ucsc, @malloryfreeberg  Currently the facet is "preservation method".  The title was changed a while ago because someone requested that we change the name from "preservation method" to "storage method" but the facet data itself was unchanged.

Currently it is pointing to here:
![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/14192aee-9a41-40fe-b2ed-6a127cda99d2)

@malloryfreeberg is this what you are expecting?  And would you like the title to revert back to "Preservation Method"?

**Comment by hannes-ucsc** [comment]
The `termFacet` entry is currently called `preservationMethod` but is being taken from the `storage_method` field of the metadata. The `hits` entry is called `storageMethod` and is also taken from the `storage_method` metadata field.

When PR DataBiosphere/azul#526 resolving DataBiosphere/azul#503 lands, the `termFacet` entry will remain to be called `preservationMethod` but it will be taken from the the `preservation_method` metadata field. The `hits` entry will be called `preservationMethod` and be taken from the same field.

**Comment by frano-m** [comment]
Ok great thanks @hannes-ucsc for the explanation...

**Comment by hannes-ucsc** [comment]
To me the directive was very straight-forward: consistently use preservation method. Now that @theathorn asked @malloryfreeberg for clarification, I will hold off merging DataBiosphere/azul#526 resolving DataBiosphere/azul#503 until @malloryfreeberg gives her ok.

**Comment by malloryfreeberg** [comment]
Hi @hannes-ucsc @frano-m Thanks for confirming this. Yes, I believe the best field to facet on is `preservation_method`. It would be great to maintain consistency of the user-friendly name and use "Preservation Method".

> The title was changed a while ago because someone requested that we change the name from "preservation method" to "storage method"

Out of curiosity, what was the reason for this change? Was it based on user feedback? This would be good to know to feed back into our metadata standard in case we need to rethink how we use the `preservation_method` and `storage_method` fields. Thanks!

**Comment by hannes-ucsc** [comment]
> what was the reason for this change?

I don't know. It must have been from before my time.

@theathorn, do you know?

@theathorn : No, I don't know. Maybe @NoopDog remembers..
