### ISSUE TITLE
Use the ontology labels for fields that are faceted

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#309]
In general, values in `.text` fields should _not_ be used as facets because these are free text fields in the ontology schemas that users can enter anything they wish. The standardized string for these fields is in the `.ontology_label`  field and these are the fields that should be used to facet.

I understand that as of now, the `.ontology_label` field is not available for most ontologized fields, but until we get the ontology lookup service incorporated into metadata validation, faceting on `.text` will continue to show multiple strings for the same value.

In the below example, "10x v2", "10X v2 sequencing", and "Chromium 3' Single Cell v2" are all referring to the same Library Construction Approach. Also, "Illumina NextSeq 500" and "Illumina NextSeq500" are the same Instrument. Users need a unified way to refer to a single value and select it from a list of values. 

- - -
![screen shot 2018-10-26 at 15 11 30](https://user-images.githubusercontent.com/10993501/47572385-b995e200-d932-11e8-9e5b-a268adaf1d9e.png)

┆Issue Number: HCAB-272

**Comment by hannes-ucsc** [comment]
See also https://github.com/HumanCellAtlas/metadata-api/issues/31

@malloryfreeberg, the indexer extracts the `.text` field because it is usually the only one that is required. Both, `.ontology` and `.ontology_label` are often optional which is why we favored the `.text` field. Would the following algorithm be preferrable?

1) Use `ontology_label` if present 
2) Otherwise use `ontology` if present and lookup the label using the ontology service
3) Otherwise use `text` if present
4) Otherwise fail

Since we are not able to implement ontology service lookup in the short term, would the following algorithm be a sufficient fall-back in the interim?

1) Use `ontology_label` if present 
2) Otherwise use `text` if present
3) Otherwise use `ontology` if present
4) Otherwise fail

**Comment by malloryfreeberg** [comment]
I will let our resident ontologist @daniwelter give her opinion, but I think the second (short-term) approach seems reasonable at this time. It is certainly reasonable to facet on the `.text` field now since it's the only required field. I'm thinking how to incrementally improve the Browser, though, and doing an ifelse on the various ontology fields is a good next step.

There hopefully will be an ontology breakout at our F2F where maybe this topic can be discussed.

**Comment by daniwelter** [comment]
I agree with @malloryfreeberg - as nice as it would be to immediately go for the full ontology look-up, I appreciate that that takes time to implement, so starting with version 2 of the algorithm would be a good starting point. We will try to submit as many datasets as possible with complete ontology mappings and I've actually started adding ontology_label columns to our priority datasets.

**Comment by hannes-ucsc** [comment]
@daniwelter, @malloryfreeberg 

If we wanted to implement either of the above algorithms generically for all fields for which an ontology exists, would it be safe to apply it to every property whose name is `text`? Are there textual fields that are not called `text` but that have sibling `ontology_label` and `ontology`?

**Comment by malloryfreeberg** [comment]
Great question!

I just had a scan through the metadata schemas, and it's true that the `text` field only exists in the ontology schemas where they have the sibling fields `ontology` and `ontology_label`. 

However,

I would not be comfortable making this assumption in general about the metadata schemas. The safer option is to introspect the schemas to determine which fields are ontologized (e.g. a field that references an ontology schema).

In order to enable the algorithm to function generally for all ontologized field in the **short term**, I think it would be ok to apply it to all properties named `text`. 

I'll also note (and I didn't know this until today) that this topic will be heavily discussed with @daniwelter and @simonjupp at the F2F, so it would be great if you could be at that sessions, @hannes-ucsc :)

**Comment by daniwelter** [comment]
+1 on everything @malloryfreeberg said.

**Comment by theathorn** [comment]
Solved by humancellatlas/metadata-api#31.
