### ISSUE TITLE
Allow filtering on donors by an age range

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#310]
I think users would expect to be able to filter on donor age by entering a range, not selecting discrete numbers and units from two lists. As it works now, I have no way to filter for data representing donors who are, for example, age 0-18 years old.

- - -
![screen shot 2018-10-26 at 15 24 59](https://user-images.githubusercontent.com/10993501/47572662-738d4e00-d933-11e8-89f0-6e1e2e7ee9fd.png)

┆Issue Number: HCAB-273

**Comment by hannes-ucsc** [comment]
Azul has a parsing heuristic in place that converts free-form age ranges found in the metadata (like "1-2 weeks") to a pair of values: the minimum and maximum age in seconds. We're not exposing this currently on the service side but we could easily do so.

**Comment by theathorn** [comment]
See also #139.

**Comment by malloryfreeberg** [comment]
> See also #139.

Being able to select multiple ranges would be a nice extra feature, but in the first instance the selection of a single range needs to be sorted.

> Azul has a parsing heuristic in place that converts free-form age ranges found in the metadata (like "1-2 weeks") to a pair of values

I would suggest removing the organism age and organism age units from the facet list in favor of implementing a filter feature that can utilize this parsing heuristic. Users should not be restricted to searching over the actual values being entered in the metadata. It also makes the list of potential values in the Organism Age facet list very long.

I'm not sure what the priorities are for the demo, but I would not demo the organism age selection facet as it is now. Certainly this should be updated for the CBeta release.

**Comment by hannes-ucsc** [comment]
In the short-term, we're doing #324 for mitigation.

**Comment by hannes-ucsc** [comment]
/

**Comment by zperova** [comment]
If we need a quick fix to show age for the demo, could we display the Developmental stage (that's ontology) instead of Organism age and Organism age unit? That provides information but doesn't look as ridiculous as the long list of useless numbers the browser shows now (sorry, I know work has been put into it but that just doesn't look good or is useful in the current state).

**Comment by theathorn** [comment]
We are implementing #324 to mitigate in the short term.

**Comment by zperova** [comment]
@theathorn  I do not think this is a good solution even in the short term if the result of https://github.com/HumanCellAtlas/data-browser/issues/324 would be the same long list of numbers but with the age unit next to it. It is not useful as it is now and won't be any more useful if it has an age unit in the same column.

**Comment by theathorn** [comment]
Show a drop down box with age unit (days, weeks, months, years) and a min and max text box where the users enters numeric values, followed by a "Go" button.

Initially do a "loose" match where the user selected value (e.g. 12 - 20 years) intersects the sample data range (e.g. 10 -16 years).
