### ISSUE TITLE
Library construction, experimental approach, etc - use the same term

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#313]
Hi there, 
here are three different names we use in those three places. Let's use one for the moment, if we're referring to the same thing. @malloryfreeberg - is that Library Construction? 

and then we additionally check with feedback if that's what it needs to be.

![screen shot 2018-10-26 at 18 17 12](https://user-images.githubusercontent.com/19713125/47582851-78f79200-d94d-11e8-8108-1877e7101952.png)
![screen shot 2018-10-26 at 18 16 45](https://user-images.githubusercontent.com/19713125/47582852-78f79200-d94d-11e8-8f25-ad4024ae0e3d.png)
![screen shot 2018-10-26 at 18 16 02](https://user-images.githubusercontent.com/19713125/47582853-79902880-d94d-11e8-97e4-382b9a209e96.png)

┆Issue Number: HCAB-276

**Comment by malloryfreeberg** [comment]
"Library construction approach" is the `user_friendly` term for this field (`library_construction_approach`) in the [metadata schema](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/protocol/sequencing/library_preparation_protocol.json#L76).

**Comment by theathorn** [comment]
@malloryfreeberg : Use "Library Construction Approach" everywhere or can we contract to "Library Construction"?

**Comment by malloryfreeberg** [comment]
@theathorn the consequences of contracting to "Library Construction" is that now the Browser is hard-coding a special case, introducing discordance between the Browser and the metadata spreadsheet, dictionary, and JSON that users will see, and if the metadata evolve then the Browser won't automatically evolve. 

My (strong) opinion is for keeping the term what it is in the metadata, but ultimately it's up to you and the Browser team.

**Comment by zperova** [comment]
@theathorn I second using the metadata term, as this will ultimately generalize to the imaging datasets we will start ingesting soon. Will be less work for you and the Browser team in the long-term.

**Comment by NoopDog** [comment]
We are only trying to save space in the table. That comes second to messaging the right content, Happy to go with Library Construction Approach.

**Comment by NoopDog** [comment]
@malloryfreeberg @gabsie this update is now on:

https://staging.data.humancellatlas.org/explore/projects 

Does this look ok to close?

Cheers,
D

**Comment by malloryfreeberg** [comment]
Looks great! Thank you!
