### ISSUE TITLE
Enable S3 Block Public Access setting

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#3143]
..for the buckets specified [here](https://github.com/DataBiosphere/azul/issues/4713#issuecomment-1450704918).

**Comment by hannes-ucsc** [comment]
We need this urgently. It's keeping an important SecurityHub finding unaddressed and its causing us extra work when we have to triage unauthorized errors that stem from potential attackers scanning the bucket for writable objects or other holes in the bucket ACL.

**Comment by NoopDog** [comment]
Ok then, I have updated the buckets to be all private and selected the "No public access" setting. Please take a look and see if there is anything else to be done here or if this ticket can be closed.

Cheers and Thanks,
D

**Comment by hannes-ucsc** [comment]
Finding shows as fixed.
