### ISSUE TITLE
Search for pancreas - not giving results

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#315]
I tried searching for "pancreas" but nothing was displayed or changed, and I wasn't notified of anything wrong.

Pancreas is there as an organ, so the general search should catch that and lead me to results. (p.s. it should catch it without me going and selecting it from suggested items, but just with me hitting Enter, I would think)

![screen shot 2018-10-26 at 19 21 43](https://user-images.githubusercontent.com/19713125/47585277-b9a6d980-d954-11e8-9db6-eb233681dedd.png)

┆Issue Number: HCAB-278

**Comment by NoopDog** [comment]
Hi @gabsie can you give a bit more info on this one? What environment and what browser are you using?

In dev and staging on chrome i see this:

<img width="855" alt="screen shot 2018-10-27 at 6 50 46 am" src="https://user-images.githubusercontent.com/3239697/47591978-cce99180-d9b4-11e8-9102-59b81aacf817.png">

**Comment by NoopDog** [comment]
If I search for something that is not there I see this:

<img width="681" alt="screen shot 2018-10-27 at 6 53 37 am" src="https://user-images.githubusercontent.com/3239697/47592071-205bdf80-d9b5-11e8-9b96-e62b0f9a8724.png">

**Comment by frano-m** [comment]
@NoopDog I think what is happening is if the user types in `pancreas` but then does not select the drop down item, but then presses search, it will result in no action.  We will need to capture this type of event... where there is a correct match but user hasn't selected the match...

**Comment by gabsie** [comment]
> @NoopDog I think what is happening is if the user types in `pancreas` but then does not select the drop down item, but then presses search, it will result in no action. We will need to capture this type of event... where there is a correct match but user hasn't selected the match...

Yes, Fran - that's what I meant. Hitting enter should take me there :)

**Comment by NoopDog** [comment]
@gabsie this has been modified and deployed to all environments and should be fairly bullet proof.  Please take a look and see if this has any funny / confusing states. The changes are:

1. Search button is dimmed and search bar says "loading" util the server returns the drop down contents.

1. Typing anything automatically narrows the search bar contents and selects the first match.

1. Pressing enter submits any selected item.

1. You can use the up down arrow keys to select or change the selected item.

1. You can click on any item and it will be selected and submitted.

1. If you type in a search that does not match anything, we show the full list of items to select from.

1. Match is a partial match over any facet term.
