### ISSUE TITLE
Files count and sum of files don't match in Request File Manifest

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#317]
When I click "Request File Manifest", I am shown a list of file extensions with what I think are file counts and total sizes.

Value for FILES (78.5k) is much larger than the sum of what I think are file counts in the middle column (342 files I summed from the example below)

- - -
![screen shot 2018-10-26 at 15 05 22](https://user-images.githubusercontent.com/10993501/47571642-f4971600-d930-11e8-88a4-c82a94748934.png)

- - -
Replaces #307

┆Issue Number: HCAB-280

**Comment by theathorn** [comment]
As commented in #265 we should add column titles for the rows of displayed data (file format, file count, files size) in the "Request File Manifest" dialogue.
Except that the 2nd column is only "file count" if the user has previously selected the "Files" tab. If the user selected the "Projects" tab it's a count of Projects, and similarly it's a count of Specimens if the Specimens tab was selected. This seems counter-intuitive. I think it should always be "file count" regardless of how the user got here.
