### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#3175]
When the Azul service returns HTTP error status codes an error message should be displayed. Currently the results from the last successful response are displayed on the first occurrence of an error response, and subsequent error responses lead to a hang with the progress indicator circling for ever.

https://user-images.githubusercontent.com/5143256/228329814-ef997f84-d6d1-4e24-a74c-6e327ffd7157.mov

﻿

**Comment by NoopDog** [comment]
@hannes-ucsc Thanks for opening this. We will prioritize this and let you know when it's fixed. 

Cheers,
D
