### ISSUE TITLE
Downloads of MA-files are broken

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#3177]
… because the request to `/fetch/repository/files` is made without passing the requisite access token. Downloads of public files work. For reproduction, I've re-enabled the file download column in `anvilprod`. The screenshot below shows that I am logged in, and that a filter on a mock-MA snapshot has been set (so that the files tab only show mock-MA files). It shows that the request to the `/fetch/repository/files` is made without the `Authorization` header and that Azul returns a 404, as it should, for inaccessible files.

<img width="1722" alt="Screen Shot 2023-03-29 at 9 45 51 PM" src="https://user-images.githubusercontent.com/5143256/228732336-72421f50-66af-449e-9a2f-ab0a51b078a5.png">

**Comment by NoopDog** [comment]
@hannes-ucsc Good catch. Thanks for opening this. We will prioritize this and let you know when it's fixed.  Love the dark mode.

Cheers,
D

**Comment by NoopDog** [comment]
Complete
