### ISSUE TITLE
Empty/missing files listed in Request File Manifest

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#318]
When I click "Request File Manifest", I am shown a list of file extensions with what I think are file counts and total sizes.

Why are there file extensions (last 3) with no size? are they empty? do they not exist?

- - -
![screen shot 2018-10-26 at 15 05 22](https://user-images.githubusercontent.com/10993501/47571642-f4971600-d930-11e8-88a4-c82a94748934.png)

- - -
Replaces #307

┆Issue Number: HCAB-279

**Comment by theathorn** [comment]
Please research to see if we have zero length files in DSS or if this an indexing issue.
