### ISSUE TITLE
Adhere to one way of spelling (UK or US) for consistency.

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#319]
I suggest to adhere to one way of spelling (either UK or US) but allow to search for both. Currently, both are present - "esophagus" in the list of organs and "oesophagus" in the search field:

![screenshot 2018-10-29 at 15 31 20](https://user-images.githubusercontent.com/38244059/47662187-60c48480-db92-11e8-95b9-189e63753de0.png)

┆Issue Number: HCAB-281

**Comment by theathorn** [comment]
I'm pretty sure the search drop down (British English) is actively derived from the currently available metadata while the human body term (US English) is probably hard-coded.
@malloryfreeberg and @zperova is the user-supplied metadata using UK or US English or a mixture of both (depending on who is submitting the data)? If both, then we are likely to end up with both spellings as separate "organs" if we continue to use a ".text" field for the facet.

**Comment by zperova** [comment]
@theathorn it's hard to say now as there only that many organs that differ in spelling and we have a limited number of datasets at the moment. Ontology terms seem to follow US English (quick check for what came to mind right now), but I am not sure whether this depends on who added it. Since the data suppliers are both in Europe and the US I imagine that the future datasets will be a mixture of both. We should use the ontology_label as a facet not the free text.

**Comment by theathorn** [comment]
On next PM agenda..

**Comment by theathorn** [comment]
Decision from the PM meeting on 11/15/18:
The Data Portal and Data Browser will standardize on US English.
