### ISSUE TITLE
Remove protocol_id as a faceted field

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#320]
It appears that in the Browser, the value in `*_protocol.protocol_core.protocol_id` is being used as a facet. This field contains a unique identifier for a protocol, and is not meaningful to be used as a facet. Currently it contains arbitrary IDs for all protocols types (from collection to dissociation to differentiation to sequencing). Users can put anything in this field including stuff that is vague like "assay_1". 

What is the intended purpose of this facet? I can think of a few use cases for wanting to facet on attributes of the protocols, but I can help figure out what the appropriate metadata field should be used if I can get some idea of what the usage is meant to be.

![screen shot 2018-10-29 at 16 59 55](https://user-images.githubusercontent.com/10993501/47666711-27911200-db9c-11e8-9629-78d95e689e95.png)

┆Issue Number: HCAB-282

**Comment by theathorn** [comment]
@briandoconnor Do you know the reason this facet was included in the Browser?

**Comment by hannes-ucsc** [comment]
I think the protocol ID was used because it was the only required field at that time and looked like it was useful. This may have been a while ago, using example v5 metadata. 

@malloryfreeberg which protocol field should we use as a facet?

**Comment by NoopDog** [comment]
Also @malloryfreeberg should we move protocols into their own facet by the type of protocol? Currently we have dissociation , enrichment etc. all in the same facet. I have raised this before a while back and I believe the answer was that support in the metadata was coming. 

Also, how can show the link from these to the protocol definition (at protocols.io or elsewhere)

**Comment by NoopDog** [comment]
>What is the intended purpose of this facet? I can think of a few use cases for wanting to facet on attributes of the protocols, but I can help figure out what the appropriate metadata field should be used if I can get some idea of what the usage is meant to be.

I believe the intended use case is so that the user can understand and limit possible sources of batch effects or sources of variation between data sets. e.g. make sure the same or similar protocols were used in each step along the way.

**Comment by adriennes** [comment]
Just throwing out there that while there's general interest in controlling for protocols as @NoopDog described, the protocol names in this list are NOT meaningful in this context, and can't be used in this way by people browsing the data.

**Comment by NoopDog** [comment]
Yes, exact. How can we make this meaningful?

1) Separate facet per protocol type.
2) Protocol IO name and identifier etc.

What else?

**Comment by NoopDog** [comment]
@adriennes and @malloryfreeberg : are you suggesting we remove this facet until we can make it meaningful?

**Comment by malloryfreeberg** [comment]
This issue is complicated, so I'm going to try to put down my thoughts here in a semi-organized way :)

Currently, all 11 protocol type schema (except imaging_preparation_protocol) contain a required field that ends in either `_method` or `_approach`. These fields are more-or-less general terms for the kind or type of protocol, and are the only ones I would expect to facet on in the first instance. For example, the `library_preparation_protocol.library_construction_approach` field will contain values like "Smart-seq2" and "10x v2 sequencing", which are very high-level values that a user might want to facet on.

Most of these fields are also ontologized so they have a `text` free text field and will eventually have an `ontology_label` field (the standardized text) that could be used for faceting. The required fields and their JSON types are:

```
analysis_protocol.computational_method	(free text)
aggregate_generation_protocol.aggregate_formation_method	(free text)
collection_protocol.collection_method	(ontology)
differentiation_protocol.differentiation_method	(free text)
dissociation_protocol.dissociation_method	(ontology)
enrichment_protocol.enrichment_method	(ontology)
ipsc_induction_protocol.ipsc_induction_method	(enum)
library_preparation_protocol.library_construction_approach	(ontology)
sequencing_protocol.sequencing_approach	(ontology)
imaging_preparation_protocol	(no required method field yet)
imaging_protocol.imaging_target.assay_type	(ontology)
```

Many of the protocol types are intermediate protocols - *e.g.* enrichment of a biomaterial - and contain useful information to know, but aren't necessarily things that users will want to facet on. As @adriennes said, while some protocol information is of "general interest in controlling for protocols", most of this information is not something that needs to be supported as a facet, at least in the early phases.

I would suggest that if we want something about protocols to be faceted now, we should restrict the facet to be on the main protocol separation - SS2 vs 10x - which would be from the `library_preparation_protocol.library_construction_approach` field. Anything else is secondary and could potentially be useful to facet on later, but I think determining what protocol metadata should be a facet deserves much more discussion and user research.

In the first instance of faceting for imaging-based experiments, my gut would be to facet on `imaging_protocol.imaging_target.assay_type` (which contains values like MERFISH). @zperova can clarify this point, but as we don't have any real imaging data yet, again this is a secondary need in the current phase.

**Comment by hannes-ucsc** [comment]
Thank you for the detailed explanation, @malloryfreeberg.

We will remove the protocol facet.

**Comment by achave11-ucsc** [comment]
This is addressed by DataBiosphere/azul#545

No action is required to remove protocol from the `More` tab @NoopDog please confirm to close this ticket.

**Comment by theathorn** [comment]
Protocol still show up in the Explore search bar in dev.

**Comment by achave11-ucsc** [comment]
@theathorn changes have not been deploy to other main deployments, only dev. It is only visible in [dev-hca-url](https://dev.data.humancellatlas.org/explore/projects)

**Comment by theathorn** [comment]
HumanCellAtlas/azul#516  is not deployed to dev yet..
