### ISSUE TITLE
Data Explorer stuck in `Loading…` the Projects tab

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/data-browser#3228]
… for the https://dev.singlecell.gi.ucsc.edu/explore/projects endpoint.
<img width="1203" alt="Screen Shot 2023-05-02 at 12 34 25 PM" src="https://user-images.githubusercontent.com/19215510/235767466-edda5b1a-5556-4635-9e05-25f942468f35.png">

After looking at the browser's requests, via enabling inspection, one can see the following two request being made to Azul:
```
https://service.dev.singlecell.gi.ucsc.edu/index/catalogs
https://service.dev.singlecell.gi.ucsc.edu/health/progress?catalog=dcp2
```
Note that the `dcp2` catalog has been deprecated in favor of the [`dcp3` catalog](https://github.com/DataBiosphere/azul/commit/0c25becbedb9ff27dadeb031a9d88af52f57c850#diff-57f7fca531676471cf9d124c0d4cbd7f235092ad460f014f7b92d5514c2efde2R254).

Furthermore, one can get the rows in the browser to re-appear by clicking around to the `Samples` or `Files` tab, which then removes the filter and allow for the default catalog (`dcp3`) to populate the browser's rows. After this, all the data seems to be available and searchable. 
<img width="943" alt="Screen Shot 2023-05-02 at 12 42 18 PM" src="https://user-images.githubusercontent.com/19215510/235769547-d80c38ce-10e8-47bf-a7ef-1a9884c907d5.png">

**Comment by NoopDog** [comment]
The default catalog on dev has been changed to dcp3, and the site loads again.
Cheers,
D
https://dev.singlecell.gi.ucsc.edu/explore/projects

**Comment by dsotirho-ucsc** [comment]
@achave11-ucsc to verify fix

**Comment by achave11-ucsc** [comment]
Fix verified, all works as expected, thanks @NoopDog and team.
