### ISSUE TITLE
Add File Size column to Files view

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#328]
In the Files view, I don't see an indication of size of each of the files listed. A user might want to know separately the size of the raw data files (which tend to be big), processed data files (which tend to be medium), or auxiliary files (which tend to be small) so they can determine whether they have capacity to download all or a subset of the files.

I see file sizes broken down by file type when I click "Request File Manifest", but not just in the Files view.

To note, there isn't a file size metadata field, but I think the Data Store keeps track of file sizes.

![](https://user-images.githubusercontent.com/10993501/47712717-5c4ea900-dc30-11e8-94c5-e764d15fc36d.png)

- - -
Issue initially brought up in #303

┆Issue Number: HCAB-289

**Comment by NoopDog** [comment]
Yup file size to the file table is in the current sprint.

**Comment by hannes-ucsc** [comment]
Duplicates #297
