### ISSUE TITLE
Remove "Laboratory" facet

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#329]
In the Browser under "More" is a "Laboratory" facet. 

![screen shot 2018-10-30 at 14 48 18](https://user-images.githubusercontent.com/10993501/47727254-012ead80-dc54-11e8-8a92-fa9983e57159.png)

I would argue this is not a meaningful field to facet on for the following reasons:

1. It contains a mix of interpretations of what "laboratory" is like the name of a PI (e.g. "Teichmann lab") or a department in an institute (e.g. "Department of Biology") or the wrangler group ("HCA DCP").
1. It isn't required in the metadata, so many times it is "Unspecified". 
1. I don't believe users will facet on this field but would rather just be curious about it later on. 
1. It is taken from the project contacts so it represents the Laboratory of all people involved in the project including where the sample was taken from, where the sample was processed, where the experiment was done, where the sample was sequenced, where the computational person did any analysis, etc.

At this time, I suggest removing this field as a facet.

An alternate field to facet on would be `institution`, which is required. In general, I'm not sure how I feel about showing even this field as a facet as it might lead to bias in what data users download. Data from a more "prestigious" institute might be preferentially used, meaning we help users assign merit based on this and not on scientific attributes. I think this question needs user feedback from @gabsie and @adriennes .

┆Issue Number: HCAB-290

**Comment by theathorn** [comment]
It's already been removed from the Search boxes..

**Comment by theathorn** [comment]
Verified Laboratory facet has been removed from the "More" drop down.

**Comment by hannes-ucsc** [comment]
Shouldn't Azul also remove this facet from its index and the response? I don't want to end up with data-browser blacklisting certain facets while Azul is still doing work to index them and returning them in the service response.

**Comment by theathorn** [comment]
@hannes-ucsc See DataBiosphere/azul#574.
