### ISSUE TITLE
Direct download exceeds max # of retries in Chrome on Window

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#331]
For Windows + Chrome url: https://staging.data.humancellatlas.org/explore/files?filter=%5B%7B%22facetName%22%3A%22organ%22%2C%22terms%22%3A%5B%22pancreas%22%5D%7D%2C%7B%22facetName%22%3A%22fileFormat%22%2C%22terms%22%3A%5B%22bai%22%5D%7D%5D

Clicking on the download icon for the first file in the list (beginning with "f79eaea4.." results in red "x" download failure.

┆Issue Number: HCAB-292

**Comment by MillenniumFalconMechanic** [comment]
~~Hi @theathorn, I am unable to reproduce on Windows 10/Chrome 70. Can you take another look and let me know if you're still getting an error during download?~~

Update: I am able now able to reproduce this.

**Comment by hannes-ucsc** [comment]
@theathorn could you verify that this is fixed in `dev`?

**Comment by theathorn** [comment]
Verified fixed.
