### ISSUE TITLE
[DX] Display facet term count on facet selector

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3323]
#### Depends On
[Display facet term count on facet selector](https://github.com/clevercanary/data-explorer/issues/370)

#### Approach
Configure for HCA, AnVIL DX, AnVIL Catalog and NCPI Catalog.

**Comment by frano-m** [comment]
Closed by https://github.com/clevercanary/data-explorer/pull/388.
