### ISSUE TITLE
[AnVIL DX] Add additional detail to dataset detail pages

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3325]
#### Approach
Add the following dataset values to the right-hand channel on the dataset detail page, similar to [HCA project detail page](https://hca-data-portal.dev.clevercanary.com/explore/projects/74b6d569-3b11-42ef-b6b1-a0454522b4a0):

* Identifier
* Consent group
* Organism type
* Diagnosis
* Data modality
* Phenotypic sex
* Reported ethnicity

**Comment by hunterckx** [comment]
Done
