### ISSUE TITLE
[DX] AC-10 Concurrent Session Control

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3339]
Adding this as a placeholder for any Browser items required for [AC-10 CONCURRENT SESSION CONTROL](https://github.com/databiosphere/azul/issues/3836).

**Comment by NoopDog** [comment]
Hi, @bvizzier-ucsc @hannes-ucsc is there any front-end work required for this ticket, or can it be closed?

**Comment by MillenniumFalconMechanic** [comment]
Hi @bvizzier-ucsc, @hannes-ucsc, checking in to see if the updates related to this ticket (#2720 and #2721) are still applicable.

**Comment by hannes-ucsc** [comment]
I don't understand why this ticket exists or what work it covers. The front-end work required to implement FedRAMP control AC-10 (Epic #DataBiosphere/azul#3836) is tracked in #2720 and #2721.

**Comment by nolunwa-ucsc** [comment]
I agree and it was discussed in the Thursday Compliance meeting
