### ISSUE TITLE
Searching for "10x" from Portal page returns "Organ: brain" data

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#334]
This might be a Portal ticket; please move if I've posted in the wrong repo.

As a user, I would like to be able to search for all 10x data in the HCA. If I enter "10x" in the Portal search bar and hit enter:

- - -
![screen shot 2018-10-31 at 09 51 46](https://user-images.githubusercontent.com/10993501/47780102-9f715080-dcf2-11e8-9b8a-1b542bb2bcc7.png)

- - -
I am taken to the Browser where my results are displayed for the search `Organ: brain`:

- - -
![screen shot 2018-10-31 at 09 52 23](https://user-images.githubusercontent.com/10993501/47780136-b31cb700-dcf2-11e8-8508-04b9147fe509.png)

- - -
### I would like to be able to search for all 10x data (or any other data with a keyword) directly from the main Portal page.

┆Issue Number: HCAB-294

**Comment by theathorn** [comment]
I think this issue may duplicate https://app.zenhub.com/workspace/o/humancellatlas/data-portal/issues/285.

Currently entering no data or invalid data in the search bar defaults to the first item in the dropdown which happens to be "Organ: brain". And "10x" doesn't match any of the facets presented in the home page search but *is* present in the Explore search box under "Library Construction Approach". The home page search presents a subset of facets available in the Explore search (I think maybe they should be the same).
See https://app.zenhub.com/workspace/o/humancellatlas/data-portal/issues/289.
