### ISSUE TITLE
Diseases to Known diseases in Project summary page

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#335]
Further to issue #274 

* [ ] Add "Known Diseases" facet to Donor drop-down (`donor_organism.diseases` in metadata)
* [ ] Change "Diseased" to "Known Diseases" in project summary page

![](https://user-images.githubusercontent.com/10993501/47785417-98e9d580-dd00-11e8-8ee0-a459125100df.png)

**Question**: Which field - `specimen_from_organism.diseases` or `donor_organism.diseases` is being displayed in the main Browser table?

┆Issue Number: HCAB-295

**Comment by zperova** [comment]
What should be displayed is `specimen_from_organism.diseases` not the `donor_organism.diseases` as you can have both normal and "diseased" samples from the same organism.

**Comment by hannes-ucsc** [comment]
> specimen_from_organism.diseases or donor_organism.diseases

We take both, but this can be changed easily.

Long term I feel that Azul's current strategy of picking some properties from donor and associating them with specimens is wrong. Until recently we also pulled up cell counts from cell suspension into specimens and undoing it fixed two important bugs.

**Comment by hannes-ucsc** [comment]
For a quick fix right now, we should change the indexer to stop looking at `donor_organism.diseases` when populating specimen objects, correct?

In the long run, we should 1) introduce donors as inner entities (to facet on) and 2) as top-level entities (to have a separate donor tab), correct?

**Comment by malloryfreeberg** [comment]
I think it might be ok to have facet on both. If we decide to do this, then it just needs to be clear what is a "donor" disease and what is a "specimen" (aka sample) disease. I can imagine a scenario where a data consumer might want to eliminate donor confounders and only select data from donors with no known diseases. I can imagine another scenario where a data consumer doesn't care about whether a donor has known diseases but specifically doesn't want data from tissues that are diseased. 

Whatever we choose, we just have to be clear what the field/facet is.

**Comment by malloryfreeberg** [comment]
> change the indexer to stop looking at `donor_organism.diseases` when populating specimen objects

Yes, this sounds like a good idea.

> In the long run, we should 1) introduce donors as inner entities (to facet on) and 2) as top-level entities (to have a separate donor tab), correct?

At this point I'm not entirely sure what would be the best way to convey known donor diseases information. A whole new donor tab might not be necessary. But, we can discuss :)

**Comment by zperova** [comment]
I don't have an objection of faceting on both taken it is clear which one is which. For a quick fix, please use only the `specimen_from_organism.diseases`

**Comment by hannes-ucsc** [comment]
@malloryfreeberg https://github.com/DataBiosphere/azul/issues/527 is deployed to `dev` which is currently being reindexed. You should not see any donor diseases anymore. Could you verify the resolution?

It looks like this ticket needs more work on top of the donor disease issue so it can't be closed yet.

**Comment by malloryfreeberg** [comment]
LGTM in dev

Is the plan to display "Unspecified" when there is no `specimen_from_organism.diseases` metadata? See #274 for a running discussion of "normal" versus "Unspecified" for `diseases`. Happy to make a new ticket for this.

**Comment by hannes-ucsc** [comment]
Thank you for verifying, @malloryfreeberg. New tickets, if necessary, are appreciated.

**Comment by hannes-ucsc** [comment]
> Is the plan to display "Unspecified" when there is no specimen_from_organism.diseases metadata?

Sorry, I had missed this question earlier. Yes. This should already be the case. The absence of an optional metadata property must always result in that property being set to `None` aka `null` in Azul's index and displayed as `"Unspecified"` in the the browser UI (note that I am using Python and Javascript literals here for precision, the actual browser page should display *Unspecified*). The same applies for mandatory properties that are present but whose value is `null`, if the schema allows that.
