### ISSUE TITLE
[AnVIL DX] Indicate user already has access on dataset detail page

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3366]
#### Depends On
- [x] https://github.com/clevercanary/cc-design/issues/39
- [x] https://github.com/clevercanary/data-explorer/issues/209

#### Approach
- If the user is not authenticated, show the currently implemented "Request Access" button on the top right.
- If the user is authenticated, use the `accessible` flag on the returned dataset to display the chip as per the [mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1008-17264&t=p9XoH8DWZrFPC5DH-0). If the user has access, display a green "Access Granted" chip. If the user does not have access, display an orange "Access Required" chip.

**Comment by NoopDog** [comment]
<img width="1367" alt="image" src="https://github.com/DataBiosphere/data-browser/assets/3239697/322aaf9d-febe-41ff-b700-2fa444515d90">

<img width="1394" alt="image" src="https://github.com/DataBiosphere/data-browser/assets/3239697/2d0d485e-b7f0-4d68-b882-1d94ac7c561c">

Complete
