### ISSUE TITLE
Project filter doesn't filter results

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#337]
I tried to filter the Browser (Project view) by one of the pilot datasets, but the Browser still displays all of the projects.

- - -
![screen shot 2018-10-31 at 13 58 02](https://user-images.githubusercontent.com/10993501/47792989-259e8e80-dd15-11e8-8e63-9cc0cbeea595.png)

- - -
Also after selecting the project, nothing happens when I click on the Specimens or Files tabs. Below is a shot of the JS console, if it helps.

- - -
![screen shot 2018-10-31 at 14 00 19](https://user-images.githubusercontent.com/10993501/47793074-567ec380-dd15-11e8-8b86-c743e90e856a.png)

- - -
Same behavior noticed if I try to filter on another facet (Organ:blood).

┆Issue Number: HCAB-297

**Comment by zperova** [comment]
I see the same issue in the JS console when I click on any of the organs on the main Portal page except Pancreas, Brain, Skin of Body and Embryo - these are the only ones that give me a clickable dataset entry. For the other ones I get this: 
![screenshot 2018-10-31 at 15 04 02](https://user-images.githubusercontent.com/38244059/47799328-f2163100-dd21-11e8-8c34-be1d83ce3757.png)

It shows that there is one project but doesn't display it.

**Comment by hannes-ucsc** [comment]
Occurs on `dev` and `staging`.

**Comment by NoopDog** [comment]
Thanks for spotting this.

This should be fixed on all environments. Please review.
@theathorn @hannes-ucsc

**Comment by hannes-ucsc** [comment]
Confirmed fix in both `dev` and `staging`
