### ISSUE TITLE
Organ number does not match the number of organs in the list

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#339]
The blue summary panel on the front page of the Browser says there are 11 organs, but there are only 10 organs in the list below: 
![screenshot 2018-10-31 at 14 41 14](https://user-images.githubusercontent.com/38244059/47795949-479b0f80-dd1b-11e8-8455-74ced6676a75.png)

┆Issue Number: HCAB-299

**Comment by theathorn** [comment]
@zperova The home page human diagram represents a pre-selected set of "common" organs and is not constructed dynamically from the complete set of organs in the live data sets. The search box is dynamically constructed and will show all available organs in the data set. Making the human diagram dynamically construct a picture for a new organ in the data set is probably not feasible, though we could add more organs to the "common organs" list.

**Comment by zperova** [comment]
@theathorn Thanks for the explanation. It makes sense  - once we have datasets for "all" the organs in the HCA the list below will show only a few example ones. At the moment this mismatch looks like an oversight though.
