### ISSUE TITLE
Wrong numbers in the blue summary bar on the front page of the Browser

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#340]
The number of cells in the blue summary bar on the front page of the Browser does not match the numbers of cells given per organ below it. 
Summary bar says there are 81.9k cells in the Atlas in total, while the number for the Bone marrow alone is 283.7k. For the Embryo it shows 0. 

![screenshot 2018-10-31 at 14 45 34](https://user-images.githubusercontent.com/38244059/47796672-b7f66080-dd1c-11e8-9378-9ae1b546d4b9.png)

If I do an empty search to display everything in the HCA, it returns a different number in `estimated cells` (and this number seems to match what one would expect the sum of cells from each project to be):
![screenshot 2018-10-31 at 14 59 00](https://user-images.githubusercontent.com/38244059/47797246-e163bc00-dd1d-11e8-94a7-db88c7c5ab9c.png)

┆Issue Number: HCAB-300

**Comment by theathorn** [comment]
I think this ticket belongs in data-portal..

**Comment by zperova** [comment]
@theathorn sorry, should I make one there instead of this one?

**Comment by theathorn** [comment]
@zperova No problem - I will take care of this, thanks.

**Comment by theathorn** [comment]
Moved to HumanCellAtlas/data-portal#290.
