### ISSUE TITLE
[DX] Implement search over all facets

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3413]
#### Depends On
- [ ] https://github.com/DataBiosphere/findable-ui/issues/13

#### Approach
* Configure for HCA DB, AnVIL DX, AnVIL Catalog and NCPI Catalog.

**Comment by NoopDog** [comment]
Complete
<img width="413" alt="image" src="https://github.com/DataBiosphere/data-browser/assets/3239697/6983f6fe-6b9d-44e2-9a62-7ea38d5c0c19">
