### ISSUE TITLE
Direct download fails on staging

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#342]
@briandoconnor reported the following failure

![image](https://user-images.githubusercontent.com/5143256/47867395-9c439680-ddbe-11e8-9e88-3fdc5c818d67.png)

```
223ff08c-e87d-49dc-b788-4e2b7b85b500    2018-10-24T221617.847057Z    application/json; dcp-type=data    be2bcd24-43e8-4178-bf8a-82242299175e.zarr!.zattrs    b096f91a13bc04571f762c71c1687ba6f2f6c7ca    148    b8c12054-2787-4aea-938c-bcff54d7271b    2018-10-24T221538.948704Z    False
```

I am jumping to conclusions with the title a little bit but S3 _can_ fail with 5xx errror and on Slack I've seen reports of 5xx against the DSS buckets at roughly the same time. This is my best guess about the cause ATM.

We should retry 5xx with exponential back-off.

┆Issue Number: HCAB-301

**Comment by theathorn** [comment]
@hannes-ucsc This could be related to #331 being worked on by @MillenniumFalconMechanic.

**Comment by briandoconnor** [comment]
What's interesting is this problem seems consistent.  The second hit on the list always in my testing produces a "X" and a failed download.  And there are others on the list that fail too.

**Comment by hannes-ucsc** [comment]
@briandoconnor if you can reproduce this consistently (I can't repro at all), could you open the inspector (right click on page, Inspect) and switch to the Network tab? It should show the requests being made. If it does, a screenshot of that would be helpful.

**Comment by shiroyuki** [comment]
@hannes-ucsc Currently, there is a bucket policy to automatically delete objects after 24 hours. Should we temporarily increase the auto-deletion period?

**Comment by hannes-ucsc** [comment]
@shiroyuki which bucket are you referring to?

**Comment by hannes-ucsc** [comment]
I think my initial hypothesis about the cause was wrong. I think browser support for `Retry-After` is sparse and downloads are likely to fail if the file isn't already checked out. DataBiosphere/azul#531  addresses this by proxying DSS file requests and implementing Retry-After on the server side. I've successfully downloaded a 3G file using Firefox against my own deployment with the fix for 531 in place.

**Comment by hannes-ucsc** [comment]
@briandoconnor, @theathorn: I verified the fix in `dev`.
