### ISSUE TITLE
Develop link from Explore tab is broken

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#346]
Click on Explore and then Develop and you get a page-not-found error for:
https://dev.data.humancellatlas.org/develop/development-guides/pipeline-development-guide
It should be:
https://dev.data.humancellatlas.org/develop/development-guides/development-guides-overview

┆Issue Number: HCAB-303

**Comment by NoopDog** [comment]
@theathorn this is ready to test on staging. https://staging.data.humancellatlas.org/explore/projects

Thx
D
