### ISSUE TITLE
Project short name facet "CD4+ cytotoxic T lymphocytes" doesn't show the project

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#349]
Faceting on a specific project (`"project_short_name": "CD4+ cytotoxic T lymphocytes"`) fails to display the project in the Project view. "1M Immune Cells" project shown as a control.

![](https://user-images.githubusercontent.com/10993501/48071302-0174fe80-e1a8-11e8-9488-d696aeccbbe6.png)

┆Issue Number: HCAB-304

**Comment by NoopDog** [comment]
I think its the + in the file name that is messing us up. Will take a look. Thanks.

**Comment by theathorn** [comment]
Verified in dev.
