### ISSUE TITLE
Automate deployment of Indexer

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#35]
As a developer I would like to easily deploy the indexer for Orange (something like this https://github.com/HumanCellAtlas/data-store/blob/master/Makefile). Be able to configure it.

DONE: Run `make deploy` (and take any parameters/configuration as necessary) and then the indexer should be deployed with required components (i.e. ElasticSearch)

┆Issue Number: HCAB-95

**Comment by caaespin** [comment]
UPDATE: @theathorn  will connect @jyotheeshwar with AWS support

**Comment by kozbo** [comment]
UPDATE: ticket filed with AWS

**Comment by hannes-ucsc** [comment]
Fixed by https://github.com/DataBiosphere/cgp-dss-azul-indexer/commit/a3a109ab60babbb16ae866b36b3f6a0807411133
