### ISSUE TITLE
Update portal search index to support ontology querying

### ISSUE THREAD

**Issue by daniwelter** [DataBiosphere/data-browser#352]
As per the discussion in the Semantic searching breakout at the November DCP meeting, the HCA ontologists and the Orange team will work towards injecting additional ontology info into Azul index using OLS python client https://pypi.org/project/ebi-ols-client/. This will allow semantic querying (eg parent/child relationships, partonomy) of ontology-annotated terms in the data browser.

┆Issue Number: HCAB-306

**Comment by NoopDog** [comment]
Obsolete
