### ISSUE TITLE
Identify suitable top-level organ/system categories for anatograms

### ISSUE THREAD

**Issue by daniwelter** [DataBiosphere/data-browser#353]
As per discussions at the November DCP meeting, the anatograms on the front page of the browser should be driven by a set of 15-20 pre-determined ontology-based organs and organ systems. An appropriate list for these needs to be derived in collaboration between the Orange team, the HCA ontologists and the UX team. Once a suitable list has been identified, the anatograms need to be updated accordingly.

This issue requires semantic searching to be available in the data browser.

┆Issue Number: HCAB-307

**Comment by NoopDog** [comment]
Obsolete
