### ISSUE TITLE
Disable download of partial matrix files

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#355]
In the browser UI we only expose files of file type "matrix" which are the "xxx.zarr!.zattrs" files.
The associated matrix files with file type "unknown" (xxx.zarr!.zgroup, xxx...zarray, etc.) files are not indexed.
It makes no sense to allow the user to download the zattrs file alone.
For now we should gray out and deselect the "matrix" file type option in the "Request File Manifest" dialog.
In the future we may want to allow the download of all associated matrix files as a single zip file, or equivalent.

┆Issue Number: HCAB-309

**Comment by brianraymor** [comment]
The Expression Matrix Service team reached the same conclusion and support this change. Would it be possible to simply remove the "matrix" file option rather than graying it out (which might suggest that it's simply not implemented **now** but will be in the future).

**Comment by theathorn** [comment]
To allow browser download of related matrix input files see https://github.com/HumanCellAtlas/metadata-schema/issues/623.

For now can we just hide ".matrix" files in the UI and just key off their presence to enable the "Request Expression Matrix" button?

**Comment by theathorn** [comment]
Solution was to remove file type "matrix" selection from the Request File Manifest dialog so none of the zarr/zarray files will appear in the manifest.
