### ISSUE TITLE
Indicate in UI that data indexing is in progress and so search results may be incomplete

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#356]
When azul indexing is in progress, the indexes are updated continuously.
Users may see partial data and assume that something is wrong ("some of my data is missing!").
Azul can provide an API that indicates whether indexing is in progress or idle.
The UI can then display e.g. a spinning progress circle with hover over  text of "data indexing in progress - results may be incomplete".

Look at the /health endpoint
https://service.dev.explore.data.humancellatlas.org/health

See the unindexed documents  and unindexed bundles if either of these are non zero then azul is indexing and we should show the banner.

When should we check? Can we do this on load for starters. Then we can see if we want to do this on a timer or on click.

{
   "up":true,
   "elastic_search":{
      "up":true
   },
   "queues":{
      "up":true,
      "azul-documents-dev":{
         "up":true,
         "messages":{
            "delayed":0,
            "invisible":0,
            "queued":0
         }
      },
      "azul-documents-dev.fifo":{
         "up":true,
         "messages":{
            "delayed":0,
            "invisible":0,
            "queued":0
         }
      },
      "azul-fail-dev":{
         "up":true,
         "messages":{
            "delayed":0,
            "invisible":0,
            "queued":12
         }
      },
      "azul-fail-dev.fifo":{
         "up":true,
         "messages":{
            "delayed":0,
            "invisible":0,
            "queued":77
         }
      },
      "azul-notify-dev":{
         "up":true,
         "messages":{
            "delayed":0,
            "invisible":0,
            "queued":0
         }
      }
   },
   "indexer":{
      "up":true
   },
   "unindexed_bundles":0,
   "unindexed_documents":0
}

┆Issue Number: HCAB-310

**Comment by theathorn** [comment]
@frano-m This is ready to go - azul updated.

**Comment by NoopDog** [comment]
@theathorn this is deployed to dev. How can we demo this? Should we re-index dev?

**Comment by theathorn** [comment]
@hannes-ucsc Please test this during a re-indexing phase.

**Comment by hannes-ucsc** [comment]
I can confirm that it is working. A few thoughts: the black bar is visually very loud. Maybe too loud. It doesn't disappear on subsequent clicks on tabs, etc. I don't know if that was the intention. The language should be more affirmative. If indexing is currently in progress, the results ARE incomplete.

**Comment by hannes-ucsc** [comment]
@theathorn, what do you think?

![Screen Shot 2019-03-10 at 11.18.52 PM.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/4f6e11c3-632e-4301-9f49-f88b575cfe4e)

**Comment by theathorn** [comment]
@hannes-ucsc, @NoopDog : I think this is OK for now. If new data is being indexed then searches on existing projects will return complete results, so "Search results may be incomplete" seems correct. We can adjust the banner as necessary based on user feedback.
