### ISSUE TITLE
Display of contact emails in Project summary page

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#357]
As a corresponding contributor to a project, I do not want my email address to be scrapable in the Browser by potentially malicious tools.

![screen shot 2018-11-12 at 12 04 42](https://user-images.githubusercontent.com/10993501/48349117-3935e780-e67b-11e8-84d7-d91da13ed12b.png)

Currently, corresponding contributor emails are viewable in a form that could easy be scraped by tools. They should be masked somehow.

┆Issue Number: HCAB-311

**Comment by theathorn** [comment]
It's not easily scrapable because it's not embedded in javascript or HTML served by the server, it's in the JSON response returned by Azul and dynamically rendered on the client.
