### ISSUE TITLE
"Download manifest" button bug behaviour when one project is selected

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#361]
Hello,

When one project is selected (see screenshot) - the Download manifest button still has all projects selected. This should be corrected to reflect user expectations to only get that one project.
Let me know if questions!
p.s. this is a project link we send out to individual projects so that they can view their data:
https://staging.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22project%22%2C%22terms%22%3A%5B%221M+Immune+Cells%22%5D%7D%5D

Gabby

![screen shot 2018-11-16 at 11 38 18](https://user-images.githubusercontent.com/19713125/48619451-73adc600-e994-11e8-9361-d5581c69e989.png)

┆Issue Number: HCAB-312

**Comment by NoopDog** [comment]
Hi @gabsie We had the fix for this on develop and I just now promoted it to staging. Can you take a look and see if it looks like you expect now? Refresh your browser and give your demo link a try.

**Comment by gabsie** [comment]
Oh that's cool, thanks @NoopDog! 
Gabs
