### ISSUE TITLE
Remove Laboratory from Contact Display

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#362]
In order to improve clarity and avoid redundancy, I suggest removing display the `laboratory` field for corresponding contributors ("Contacts" on the Project summary page) and instead just display the `contact_name`, `institution`, and `email` fields. 

Sometimes the `laboratory` field is filled in with the PI's name and honorific, leading to:

![screen shot 2018-11-16 at 11 38 55](https://user-images.githubusercontent.com/10993501/48619559-cf784f00-e994-11e8-979f-d8a057fe587c.png)

Sometimes the `laboratory` field is filled with the surname of the PI, leading to:

![screen shot 2018-11-16 at 11 39 10](https://user-images.githubusercontent.com/10993501/48619586-e323b580-e994-11e8-80c2-b0034666c34a.png)

I think it is sufficient to just display `contact_name`, `institution`, and `email` fields for the Contact.

Thoughts @gabsie @adriennes ?

┆Issue Number: HCAB-313

**Comment by NoopDog** [comment]
Hi @malloryfreeberg is the "lab name" collected inconstantly or are you saying its displayed inconsistently?

**Comment by malloryfreeberg** [comment]
@NoopDog Collected inconsistently. 

The field description currently is:

```
        "laboratory": {
            "description": "Name of lab or department within the institute where the individual works.",
            "type": "string",
            "user_friendly": "Laboratory/Department",
            "example": "Department of Biology"
        },
```

So some people put in things like "Department of Biology" but others put in things like "Basu lab" or "Basu".

**Comment by NoopDog** [comment]
@malloryfreeberg looks like Laboratory is also one of the facets. Should we remove it from the facet list too? Or, maybe we can update the data to have this populated consistently?


![Screen Shot 2018-11-20 at 11.13.44 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/ea08f15a-7904-4d1d-8a77-b597acc9958f)

Cheers,
D

**Comment by theathorn** [comment]
See #329 to remove Laboratory from the facet list.

**Comment by theathorn** [comment]
Verified with Project "Comparison, calibration, and benchmarking of high-throughput single cell RNA-Seq techniques for unbiased cell-type classification".
