### ISSUE TITLE
[AnVIL DX] Update AnVIL Explorer header

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#3628]
https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL?type=design&node-id=1047-17305&mode=design&t=2X3YEVhiYfDDi9kA-4

<img width="1202" alt="image" src="https://github.com/DataBiosphere/data-browser/assets/3239697/383104dd-9931-4f25-9443-132e50d23f3c">

**Comment by frano-m** [comment]
Also see https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL?type=design&mode=design&t=sgqmDGRVd7GMr2b4-0.
