### ISSUE TITLE
Download manifest button hides with a smaller screen - responsive behaviour

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#363]
Hi, 
I don't know what the policy is for the responsiveness and the manifest buttons, but the buttons are not visible even at relatively decent desktop widths.
I think they should still be visible, because the csv files are fine for downloading, right?
Or even if an action is not possible for a mobile device, the action should be to alert people about their device capabilities when they attempt to do something, but not hide possible actions from users.
Open to thoughts.
Gabs
![screen shot 2018-11-16 at 11 38 40](https://user-images.githubusercontent.com/19713125/48620747-110af900-e999-11e8-80a2-10437d125ce0.png)

┆Issue Number: HCAB-314

**Comment by NoopDog** [comment]
HI @gabsie thanks for opening this.  I thought we had a ticket for this one but I can't find it. Yes, we need to use the device type and not just the browser window size to decide when to show the buttons vs the message.
