### ISSUE TITLE
Enable server-side encryption for all S3 objects

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#3647]
While investigating https://github.com/DataBiosphere/azul/issues/4715 it was discovered that the following buckets contain unencrypted objects:

HCA dev:
- data-browser.dev.lungmap.net (753 unencrypted objects)

HCA prod:
- archive-preview.humancellatlas.org (501 unencrypted objects)
- data-browser.lungmap.net (753 unencrypted objects)

Please enable server-side encryption for all the objects in these buckets.

![Screen Shot 2023-09-07 at 3 59 03 PM](https://github.com/DataBiosphere/data-browser/assets/46407464/80ef3d5d-aa87-4390-9fc4-6d16e30fe390)

![Screen Shot 2023-09-07 at 3 59 16 PM](https://github.com/DataBiosphere/data-browser/assets/46407464/71b56349-b4bc-4add-9b99-0098e597eaec)

**Comment by hannes-ucsc** [comment]
Server-side encryption has now been enabled for all buckets but it only affects object written after it was enabled on a bucket. The unencrypted objects need to be deleted or overwritten.

@bvizzier-ucsc, can anything be done to get CleverCanary to respond to this? It would be helpful to have a timeline for 
resolution.

Edit: this comment was interpreted by some to imply a criticism of CleverCanary. I'd like to clarify that this interpretation was not intended.

**Comment by NoopDog** [comment]
Hi @dsotirho-ucsc can let us know the urgency of this request? Are there any timelines associated with this we should be aware of? This will help us prioritize this work.  cc @bvizzier-ucsc

**Comment by NoopDog** [comment]
Also, @dsotirho-ucsc I just did a dev and prod deployment for lungmap.

Can you let me know if this fixed the issue for:

- data-browser.dev.lungmap.net and
- data-browser.lungmap.net

Cheers and Thanks,
D

**Comment by hannes-ucsc** [comment]
@NoopDog, please direct priority and scheduling questions at me and @bvizzier-ucsc. Thank you!

To answer your question, this is a medium-severity finding so it has a 90 day remediation target. The finding is from last year so we're already way past the deadline, luckily not in a currently compliant deployment. If you could fix this ASAP that would help limit the damage to our track record wrt timely mediation in the eyes of the AO and the yearly 3PAO. 

It just requires reading and writing the objects again so it should be real easy to fix (< 10min) with `aws s3 sync`.

**Comment by NoopDog** [comment]
@hannes-ucsc Scheduling questions I will direct exclusively to @bvizzier-ucsc. I would prefer if any tickets assigned to us already contained the information required for Ben and me to prioritize against our other tasks. 

The data-browser.dev.lungmap.net and data-browser.lungmap.net buckets should already be fixed. If you or @dsotirho-ucsc can verify that would be great. 

 Also if you can fix archive-preview.humancellatlas.org in 10 minutes that would be great. Woud you be able to claim this ticket?
 
 Cheers and Thanks,
D

**Comment by hannes-ucsc** [comment]
@bvizzier-ucsc has a lot on his plate and I would like to help where I can so if you could also include me in scheduling questions, that would be helpful. Thank you!

> Also if you can fix archive-preview.humancellatlas.org in 10 minutes that would be great. Woud you be able to claim this ticket?

Sorry, not at this moment. If it takes you considerably longer than 10min, let us know and we'll see what we can do to help.

**Comment by hannes-ucsc** [comment]
Triaging to discuss the expected timeline with @bvizzier-ucsc.

**Comment by bvizzier-ucsc** [comment]
@NoopDog Am I remembering correctly that the unencrypted files in this bucket can be deleted?

**Comment by bvizzier-ucsc** [comment]
This is a bucket owned and populated by the front end team.  The proper function needs to be validated by them once the change is made.

**Comment by NoopDog** [comment]
Not deleted just encrypted

**Comment by hannes-ucsc** [comment]
I just did it myself. It really just entailed `aws s3 sync <bucket_uri> . && aws s3 sync . <bucket_uri>`. Thanks anyway.
