### ISSUE TITLE
Unwrap project title and span across entire table

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#366]
Project titles tend to be long, sometimes so long that they wrap over four or five lines, artificially increasing the row height, and limiting the number of rows that fit on a screen.

We could solve this by making each project take up two table rows. The first row could have only one cell for the title, spanning the entire width of the table. The second row would contain the cells for the remaining columns. The first cell in the second row would contain the project short name.

cc @malloryfreeberg

┆Issue Number: HCAB-317

**Comment by hannes-ucsc** [comment]
Connected to #365

**Comment by theathorn** [comment]
Looks OK now.
