### ISSUE TITLE
Update HCA environment config for new environments

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3682]
#### Open Access Envs
- cc-dev - Clever Canary dev environment for non-managed access implementation 
- dev - open access dev environment
- prod - open access prod environment to be deployed in Oct 2023

#### Managed or Mock Managed Access Envs

- cc-ma-dev Clever Canary mock managed access dev environment
- ma-dev - mock managed access dev environment for CGL pen testing
- ma-prod  - managed access prod for managed access go live

**Comment by frano-m** [comment]
Complete.
