### ISSUE TITLE
[AnVIL DX] Project specific markdown pages in explorer

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3683]

**Comment by frano-m** [comment]
See [layout mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1286-25159&mode=dev).

For pages i.e. `Guides` and `TOS` [see mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=3737-32860&mode=design&t=lcT6gp68V8iX3sL3-4).
