### ISSUE TITLE
Switch to PUT for manifest requests

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#3694]
We occasionally receive GET requests from search engines or other crawlers, malicious as well as benevolent ones, for manifests without any filters. These take several minutes to prepare and put a heavy load on the ES backend. It was a mistake to use GET for expensive requests. REST suggests to use POST or PUT for things that create server-side state or have other side-effects. POST would be used for non-idempotent operations, and PUT for idempotent ones. Since we cache already generated manifest, we switched to PUT. For backwards compatibility, we left `GET /fetch/manifest/files` in place, but deprecated it. We would like to removed as soon as possible since it is still requested without filters by the above types of bots.

Please switch the data browser (the original and the rewrite) to `PUT /fetch/manifest/files` instead. Note that any redirects return by that PUT should be followed with GET. It is my uneducated guess that this is a trivial change and my hope that this can be done quickly and non-bureaucratically.

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description for CC.

**Comment by hannes-ucsc** [comment]
Description updated.

**Comment by dsotirho-ucsc** [comment]
Assignee to follow up with CC

**Comment by bvizzier-ucsc** [comment]
@NoopDog Please review review assign to the appropriate pipeline.

**Comment by NoopDog** [comment]
Is there any urgency to this request? Seems like this has been working fine for many years with only the occasional hiccup and is low priority. 

We can prioritize this after the current AnVIL and HCA go-live efforts.  Meanwhile, if you want to make the PUT manifest operational (leaving the GET in place) we can let you know when this is completed so you can remove the GET interface.

**Comment by hannes-ucsc** [comment]
> Is there any urgency to this request?

There is some level of urgency with every request that we make. We would like to remove the deprecated GET endpoint by the end of this year. Considering that this is a trivial change, that should be feasible, despite the other priorities. If it is not trivial, please explain why.

> Seems like this has been working fine for many years with only the occasional hiccup and is low priority.

It has not been working fine. I described what the impact is.

**Comment by hannes-ucsc** [comment]
This is a sketch of the change, to back up my claim that it's trival:

```diff
diff --git a/packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts b/packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts
--- packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts
+++ packages/data-explorer-ui/src/hooks/useRequestFileLocation.ts
@@ -29,10 +29,11 @@
  * Returns fetch request options.
  * @param accessToken - Access token.
  * @returns fetch request options.
  */
-function createFetchOptions(accessToken: string | undefined): RequestInit {
+function createFetchOptions(accessToken: string | undefined, method: string): RequestInit {
   return {
+    method: method,
     headers: accessToken ? { Authorization: "Bearer " + accessToken } : {},
   };
 }
 
@@ -42,12 +43,13 @@
  * @param accessToken - Access token.
  * @returns @see FileLocation
  */
 export const getFileLocation = async (
+  method: string,
   url: string,
   accessToken: string | undefined
 ): Promise<FileLocation> => {
-  const options = createFetchOptions(accessToken);
+  const options = createFetchOptions(accessToken, method);
   const res = await fetch(url, options);
   const jsonRes: FileLocationResponse = await res.json();
   return {
     commandLine: jsonRes.CommandLine,
@@ -71,12 +73,13 @@
   accessToken: string | undefined,
   resolve: ResolveFn,
   reject: RejectFn,
   active: MutableRefObject<boolean>,
-  retryAfter = 0
+  retryAfter = 0,
+  method = 'GET'
 ): void => {
   setTimeout(() => {
-    getFileLocation(url, accessToken).then((result: FileLocation) => {
+    getFileLocation(url, accessToken, method).then((result: FileLocation) => {
       if (result.status === FILE_LOCATION_PENDING) {
         if (!active.current) {
           reject({
             location: "",
@@ -130,9 +133,9 @@
   const run = useCallback(() => {
     if (url) {
       runAsync(
         new Promise<FileLocation>((resolve, reject) => {
-          scheduleFileLocation(url, token, resolve, reject, active);
+          scheduleFileLocation(url, token, resolve, reject, active, method='PUT');
         })
       );
     }
   }, [runAsync, token, url]);
```

**Comment by dsotirho-ucsc** [comment]
Assignee to obtain ETA from CC.

**Comment by NoopDog** [comment]
Thanks for the sketch. We will work with @bvizzier-ucsc to schedule this for after the React app release so we don't have to change both the Angular app and the React app.
Cheers, 
D

**Comment by NoopDog** [comment]
@BruceRodrigues this can be exercised from the

1. The export selected data flow Projects>Export>Request File Manifest e.g. https://data.humancellatlas.dev.clevercanary.com/explore/export/download-manifest

2. Each project's [metadata tab](https://data.humancellatlas.dev.clevercanary.com/explore/projects/53c53cd4-8127-4e12-bc7f-8fe1610a715c/project-metadata) see file manifest.

The ask is 

>Please switch the data browser (the original and the rewrite) to PUT /fetch/manifest/files instead. Note that any redirects return by that PUT should be followed with GET

**Comment by NoopDog** [comment]
This is implemented in the React data browser deployed to https://explore.data.humancellatlas.org/

The GET version of the API is still being used by 

- https://data-browser.lungmap.net. This is still on the Angular version.
- prod https://prod.anvil.gi.ucsc.edu/explore/datasets. This change has not yet been deployed to this environment.

**Comment by achave11-ucsc** [comment]
Triaging to discuss with @bvizzier-ucsc.

**Comment by hannes-ucsc** [comment]
What's the plan for 1) moving the LungMAP production instance to the rewrite of the data browser and 2) deploying this change to the anvilprod instance?

**Comment by achave11-ucsc** [comment]
Assignee (@bvizzier-ucsc) to discuss with CC.

**Comment by bvizzier-ucsc** [comment]
@NoopDog Can you confirm where this is deployed?

Is this in the update for the AnVIL Managed Access Beta?
And, I assume, we need to schedule an update for LungMAP that includes this change.

**Comment by NoopDog** [comment]
This change is merged to main on data-browser and will be available wherever main is deployed.

Once deployed using main on the data browser-repo, the new environments for AnVIL Explorer dev and prod will have this change.


We are working on updating LungMap to use the new Data Explorer and hope to have that live late next week. 
@bvizzier-ucsc

**Comment by hannes-ucsc** [comment]
> Once deployed using main on the data browser-repo, the new environments for AnVIL Explorer dev and prod will have this change.

The agreed-upon procedure for deploying the Data Browser for AnVIL is for Clever Canary to request a deployment from our operator on the #team-boardwalk channel on Slack. Was this done after the PR addressing this issue was merged?

**Comment by NoopDog** [comment]
Hi @hannes-ucsc, No, because main is not compatible with the existing environments. Main now expects the `/explore`basePath has been removed.  I have updated, https://github.com/DataBiosphere/data-browser/issues/3805 to indicate that the new environments need to be deployed using the latest code.

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by achave11-ucsc** [comment]
Assignee to create blockers.

**Comment by hannes-ucsc** [comment]
Lungmap appears to have been updated to `main`. I am assuming we can now close this and move forward with a PR that completes the resolution for DataBiosphere/azul#5533, by removing the support for `GET /fetch/manifest/files` and GET `/manifest/files`.

**Comment by NoopDog** [comment]
We still have one instance of the Angular UI used to validate new DCP catalogs. We are hoping to be able to remove this instance in the next week or two. You may want to hold until this instance is also removed.
@bvizzier-ucsc @hannes-ucsc

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "I don't think that instance is used to generate manifests, but I'll double check."

**Comment by hannes-ucsc** [comment]
13 manifest requests in the last 4 months on that instance

<img width="1291" alt="image" src="https://github.com/DataBiosphere/data-browser/assets/5143256/eb3b3ead-c327-4081-981e-55ff67bea993">


compared to > 33k on the regular instance

<img width="1275" alt="image" src="https://github.com/DataBiosphere/data-browser/assets/5143256/4e09f9c0-22d0-434a-84b5-ad729f9e12e2">

I don't want this to enter another blocked/waiting cycle on CC and am happy to accept the risk of breaking that instance for the rare case that an internal user uses it to request a manifest, from now until when the instance is completely removed in two weeks.
