### ISSUE TITLE
Automate deployment of the WebService

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#37]
As a system administrator I need to have an automated way of deploying the webservice on AWS Lambda.

DOD: I type `make deploy` on the terminal, the script takes any necessary arguments, and creates an instance of the webservice via chalice on AWS Lambda (serverless deployment)
Repo: https://github.com/DataBiosphere/cgp-dashboard-service

**Comment by theathorn** [comment]
Can DNAStack do this?
