### ISSUE TITLE
Cleanup Github team and permissions

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3718]
There is a Data Biosphere team [Clever Canary Developers](https://github.com/orgs/DataBiosphere/teams/clever-canary-developers/members). I have added everyone from CC that was already in Data Biosphere and given this team write access to Data Portal, Data Browser and findable-ui
 
 
Everyone from CC Except Mim and myself can now be removed from [Azul Triagers](https://github.com/orgs/DataBiosphere/teams/azul-triagers) if required

 Invite the following CC developers to DataBiosphere so I can add them to the Clever Canary Developers team.
[BruceRodrigues](https://github.com/BruceRodrigues)
[esthermcdade](https://github.com/esthermcdade)
[alexfomin](https://github.com/alexfomin)
I have asked Alex and Esther to add their names to their GitHub profiles.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
