### ISSUE TITLE
Incorrect link for DCP CLI instructions

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#373]
The issue is - when I go to download a file manifest, the file downloads fine but a window populates to redirect you to HCA CLI instructions: 
Screen Shot 2018-11-28 at 8.42.47 AM.png

When you use this button, it takes you to this page, which doesn't work: 
https://staging.data.humancellatlas.org/learn/userguides/accessing-data/ 

I believe it should be taking me to this page (thanks to Matt who sent it to me): 
https://staging.data.humancellatlas.org/learn/userguides/accessing-data/using-the-cli-to-access-data

┆Issue Number: HCAB-321

**Comment by theathorn** [comment]
The link https://prod.data.humancellatlas.org/learn/userguides/accessing-data/using-the-cli-to-access-data doesn't work in dev, staging or prod.

**Comment by gabsie** [comment]
I'm sorry, I went and created another ticket for this in the data-portal repo, following the beta-tester reporting on this: https://github.com/HumanCellAtlas/data-portal/issues/306 
Feel free to merge etc.
