### ISSUE TITLE
dcp33 new datasets generating a "Not Found" when selected.

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/data-browser#3782]
The wrangling teams are working to validate [dcp33](https://explore.data.humancellatlas.org/projects?catalog=dcp33).  However, they have found that if they click on the link in the dataset list for a new dataset, it is displaying a "Not Found."

![image](https://github.com/DataBiosphere/azul/assets/15311001/1d4ade79-83eb-45b7-8e50-dc8ec84e2440)

I have checked all of the new datasets in dcp33 and I am seeing the same behavior:

```
1c5eaabf-075b-4b7a-a9e6-07792c2034b3
1ffa2223-28a6-4133-a5a4-badd00faf4bc
21ea8ddb-525f-4f1f-a820-31f0360399a2
2af52a13-65cb-4973-b513-39be38f2df3f
3d49e5e5-976f-44cb-b6b9-079016c31c56
4ef86852-aca0-4a91-8522-9968e0e54dbe
5bd01deb-01ee-4611-8efd-cf0ec5f56ac4
645b20c9-5ed0-4500-86b5-7aef770d010a
73011a86-4755-48ac-9f70-a28903b4ad77
7f9766ff-bb12-4279-b340-78d140bdd7ba
849ed38c-5917-43c4-a8f9-0782241cf10c
8a666b76-daaf-4b1f-9414-e4807a1d1e8b
91674dcf-8641-40e6-978d-c1706feffba8
94023a08-611d-4f22-a8c9-90956e091b2e
95f07e6e-6a73-4e1b-a880-c83996b3aa5c
9c20a245-f2c0-43ae-82c9-2232ec6b594f
9f17ed7d-9325-4723-a120-b00e48db20c0
c7a7fde7-aa8c-4ef0-9424-612b7cd2cdb4
cc35f94e-e93b-4dbd-a08c-702978d9046f
```
Updated datasets appear to be functioning as expected.

[Reference Slack thread.](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1700069831020579?thread_ts=1698068019.262469&cid=C9XD6L0AD)

**Comment by NoopDog** [comment]
Thanks, will take a look.

**Comment by NoopDog** [comment]
Hi @bvizzier-ucsc, this issue is fixed and deployed to prod.
