### ISSUE TITLE
Communicate HCA managed-access pilot environment front-end hosting setup to Azul team

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3804]
The HCA managed access front-end hosting setup is very similar to the current [HCA Data Explorer setup](https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-east-1#/distributions/EYL2CSEQ4Z28Q) in `platform-hca-portal' which can be used as a model.

**No Archive Preview**
One difference the managed-access pilot will have is that it does not need the `/archive-preview*` behavior and its associated bucket. As a reminder, the archive preview functionality allows users to view the contents of an archive file e.g., zip format, without downloading the file. For the full MA implementation, the archive preview functionality must be integrated with ingest/TDR/Azul so that access controls can be applied to the archive preview contents. Until then, the archive preview functionality will be removed from the Explorer.

**Origins**
This leaves a single default origin configured like the [non-managed-access example](https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-east-1#/distributions/EYL2CSEQ4Z28Q/origins/edit/wve-data.humancellatlas.org.explore).

**Behaviors**
This also leaves a single default behavior configured like the [example](https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-east-1#/distributions/EYL2CSEQ4Z28Q/behaviors/1/edit).

**Viewer request CloudFront function**
This setup requires a [secure-bucket-path- mapper
](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/functions/wve-secure-bucket-path-mapper) CloudFront function

**Viewer Response CloudFront function**
This setup requires an [add-response-headers](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/functions/wve-add-response-headers) CloudFront function as well. Once the environments are setup, we will iterate on the Cloudfront function code to add the CSP and additional cache control headers.

**Building and Deploying**
Building and deploying the HCA Data Explorer can be accomplished with a script similar to https://github.com/DataBiosphere/data-browser/blob/main/explorer/cgl-explore.data.humancellatlas.prod.clevercanary.com-deploy.sh adapted to run in the CI/CD environment.

**Environments**
The setup needs to be applied to a dev and prod environment.

Dev: https://ma-pilot.explore.dev.singlecell.gi.ucsc.edu/
Prod: https://ma-pilot.explore.data.humancellatlas.org/

**Comment by dsotirho-ucsc** [comment]
Assignee to review description.

**Comment by hannes-ucsc** [comment]
Many of the links in the description point to specific AWS console pages. These links don't work unless one knows the account ID and credentials to that account. What is the account ID?

**Comment by NoopDog** [comment]
platform-hca-portal

**Comment by dsotirho-ucsc** [comment]
Assignee to request access to `platform-hca-portal`.

**Comment by hannes-ucsc** [comment]
We decided to have CC create the pilot site in deployment zone `platform-hca-prod`. Azul team will take over deployment from there. For now, there is nothing else to do for me here.

**Comment by achave11-ucsc** [comment]
Assignee to resume work once pilot site exists.

**Comment by NoopDog** [comment]
Pilot sites exist at:

https://ma-pilot.explore.data.humancellatlas.org in `platform-hca-prod` and
https://ma-pilot.explore.data.dev.singlecell.gi.ucsc.edu in `platform-hca-dev`

These URLs have been sent to @bvizzier-ucsc in slack last year but I wanted to make sure they are in the ticket as well.

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Added blocker. I think the pilot site is pointless. It is public (as opposed to private) and upstream HCA partners are taking forever to figure out the trivial and rather bureaucratic aspects of MA for HCA so I'm not holding my breath for getting the pilot snapshots anytime soon.

@bvizzier-ucsc can correct me if I am wrong.

If we scrap the pilot site we can just enable the login now (along with any other MA features) on the production site of DB for HCA and take over the management of that site now. When we get the pilot snapshots we can index them in Azul `prod`. Again, the pilot site is public, too, so exposing the pilot snapshots on the production site does not increase the risk of violating any MA terms. It does increase the visibility of the login stuff (and other MA features) but I don't think that's a problem.

**Comment by bvizzier-ucsc** [comment]
HCA management would like to keep the Pilot site separate from the production site so that it is easier for stakeholders to see and understand the differences between the managed access UI as compared to the current production site. 

Edit:  If all goes as planned, in a few months the managed access site can become the production site.  The dual site is expected to be temporary.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
If the task at hand was "to communicate", I consider this done.
