### ISSUE TITLE
Allow user-friendly name for Expression Matrix output files

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#385]
@brianraymor wrote:
Laura pinged the matrix team with some demo feedback _It looks like the filenames are uuid.loom which strikes me as very unhelpful if you download a file like that and then forget about it you won't necessarily be able to work out what it contained after the fact Is there a good place to put this feedback? Would you have a way of putting say the project shortname or something in so people have a handle on what the file is? I know the short name isn't always short_ -

Would it make sense for the Data Browser to implement a _save/download as ..._ feature?

┆Issue Number: HCAB-325

**Comment by theathorn** [comment]
Add the ability to pass a user-specified name for the output file to the matrix service.

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog Not implemented by Matrix team. Please see https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/matrix-service/162.

**Comment by brianraymor** [comment]
I also communicated the decision on the data-browser slack channel  - https://humancellatlas.slack.com/archives/CD0PLMWJZ/p1550024946006600

**Comment by NoopDog** [comment]
Is it possible for us to do this without them? Like we put the url on the screen and say right click, save as if you want to rename it? Check out the AWS bucket download flow. Is something like this possible with no work from the matrix team?

<img width="636" alt="screen shot 2019-03-07 at 10 53 17 am" src="https://user-images.githubusercontent.com/3239697/53981479-778e6100-40c7-11e9-8a76-3a4488468d9d.png">

<img width="624" alt="screen shot 2019-03-07 at 10 53 34 am" src="https://user-images.githubusercontent.com/3239697/53981499-837a2300-40c7-11e9-9ecd-a162052522a1.png">


<img width="574" alt="screen shot 2019-03-07 at 10 53 45 am" src="https://user-images.githubusercontent.com/3239697/53981513-8aa13100-40c7-11e9-8b2d-1847e684fe63.png">


<img width="1032" alt="screen shot 2019-03-07 at 10 53 54 am" src="https://user-images.githubusercontent.com/3239697/53981523-90971200-40c7-11e9-8f24-087607afad22.png">

**Comment by brianraymor** [comment]
That's certainly how I download large music purchases from the EU and UK. It's unfortunate that the browser vendors (for security reasons) have broken many of their third party extensions that managed pause-resume and retry like https://www.downthemall.net/.

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog  @frano-m See branch `matrix-file-name`.

**Comment by frano-m** [comment]
@NoopDog  https://github.com/HumanCellAtlas/data-browser/pull/537
