### ISSUE TITLE
[AnVIL DX] Review handling of expired NIH account linkage

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3861]
Regarding why you still have auth when your linkage is expired, I think we must be still sending the auth token to Azul in this case and they are using it without issue. I will create a ticket to re-examine what we do when the NIH linkage is expired. Seems we should not send the auth token in this case.

https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1705610449746239

**Comment by MillenniumFalconMechanic** [comment]
Working as desired.
