### ISSUE TITLE
Add analysis portal to new LungMap dataset

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/data-browser#3864]
Project
 https://data-browser.lungmap.net/explore/projects/4ae8c5c9-1520-4371-9827-6935661f6c84

Analysis Portal
https://singlecell.broadinstitute.org/single_cell/study/SCP1157/bronchiolitis-obliterans-syndrome-lungmap

**Comment by NoopDog** [comment]
Do you have url(s) for the analysis portals?
