### ISSUE TITLE
[AnVIL Catalog] Build AnVIL Catalog off of the DUOs API instead of Terra workspaces

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3868]
#### Need
Terra ingest/data workspaces in GCP are being retired. As an alternate source of the workspace related information we can use the  [DUOs API](https://consent.dsde-dev.broadinstitute.org/#/Dataset/get_api_dataset_v2__id_) instead. We may still need the dbGaP API for some of the fields.

AnVIL Catalog Mapping
https://docs.google.com/document/d/1HxPhJlzhYfoLTaeLZXJsc_RQN7DAibq3KtwNkPSHOI0/edit#heading=h.zgake2jchq9a

DUOS APP Home Page
https://duos.broadinstitute.org/home

Current AnVIL Catalog Script
https://anvil.terra.bio/#workspaces/anvil-datastorage/Clever_Canary_AnVIL_Dataset_Catalog_Dev/analysis/launch/Copy%20of%20Create%20Dataset%20Catalog%20Report%20From%20Terra%20APIs.ipynb

#### Approach

- [ ] Review DUOs API and determine what additional DUOs API fields would be needed to match the current dataset catalog display.
- [ ] Determine how to request anvil-only studies and see study metadata from DUOS.
- [ ] Review DUOs Auth capabilities, login with dev account and make requests to get the list of anvil datasets and the dataset metadata.
- [ ] Build the current consortia, study, and workspace lists
- [ ] Run the Catalog locally off of the new lists.
- [ ] Determine deployment architecture to allow for the catalog to refresh as DUOS is updated.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
