### ISSUE TITLE
[AnVIL Catalog] Hard code GREGoR consortia workspace sizes

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#3909]
For reasons, Terra can't give us the workspace size of the GREGoR workspaces for now.

We are requested to hardcode the values.

 Could you update the workspaces on the catalog with the associated sizes? Thanks!

[AnVIL_GREGOR_RELEASE_01_GRU](https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GREGOR_RELEASE_01_GRU): 59.43 TB
[AnVIL_GREGOR_RELEASE_01_HMB](https://anvil.terra.bio/#workspaces/anvil-datastorage/AnVIL_GREGOR_RELEASE_01_HMB): 6.22 TB

I think we can do this when reading in the datasets json.

**Comment by hunterckx** [comment]
Done
