### ISSUE TITLE
Health check endpoints

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#397]
Add route 53 health check as per https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md

┆Issue Number: HCAB-334

**Comment by sampierson** [comment]
Does this issue even make sense?  If the data browser is a JS app with no server side component, there is nowhere to put a health-check endpoint.

**Comment by NoopDog** [comment]
Exact thats why this is not implemented. It is not super clear what the goal is and how to meet the HCA  alerting requirements with this. For the data portal we quickly did this:

https://dev.data.humancellatlas.org/health/ but the portal does have individual pages.

Not sure what we could test on the browser. That the index.html page loads? We could create a separate health.html page and load that just to check cloudfront and S3 but that wont tell if actual site is working. 

We could have some testing endpoint run the JS and then look for something in the dom etc.

Not sure what the goal is here and what level of effort is justified.

**Comment by theathorn** [comment]
Superseded by #398.
