### ISSUE TITLE
Generate Alarm when Data Browser is down

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#398]
See "Alerts (AKA Alarms)" in https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/README.md

┆Issue Number: HCAB-333

**Comment by sampierson** [comment]
Does this issue even make sense? If the data browser is a JS app with no server side component, what does "down" mean?

**Comment by NoopDog** [comment]
We would test that the index.html page is accessible. Thats it. We would not parse the JS and  test some feature of the app.  It's not much but its something. It's harder to actually test that the UI is usable. Looks like we can add this easily to the graphana setup now that it is going.

**Comment by sampierson** [comment]
Please excuse my ignorance - I've not been keeping up with the Browser & Portal.   It was my understanding that the Browser was a JS app downloaded from S3 that is kicked off by a page in the Portal.  So is index.html a portal page?

**Comment by NoopDog** [comment]
Hi Sam,

Portal and browser each have their own index.html that when downloaded requests the JS for their respective apps. The Browser is a true single page app. The Portal is a hybrid that has pages for each actual page, but also has some JS to prefetch the pages to minimize the load time experience for the user.

In any case the plan is to monitor:

data.humancellatlas.org/explore - which maps to index.html of the  Data Browser

and

data.humancellatlas.org/  - which maps to the index.html of the Data Portal.

If either of those do not respond with 200 it will generate an alarm.

**Comment by jessebrennan** [comment]
This should have been closed with https://github.com/DataBiosphere/azul/pull/731
