### ISSUE TITLE
Create ES JSON mapping to allow for deletion events

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#40]
The current, very unstructured format of the schema on ES won't allow for deletion (or efficient) deletion of data associated with Bundles. 

As an admin, I would like be able to delete data in ES associated with a bundle without getting rid of data present in any other bundle.

DOD: General schema for the Browser index on a google doc; structure allows for deletion of data associated with a Bundle is structurally possible without disrupting existing data from any of the existing documents. Unit test to test the schema behaves as appropriate.

Document to track ES Mapping: https://docs.google.com/document/d/1OWuPZHQnAGdGK8koJdLbnIZ6TT7F6WonZ6cEKfxsR8U/edit

┆Issue Number: HCAB-97

**Comment by caaespin** [comment]
UPDATE: Working through the structure with Hannes. Versioning strategy changed.

**Comment by theathorn** [comment]
Schema is there - need unit test.
