### ISSUE TITLE
Use `verbatim.pfb` manifest format for exports to Terra in AnVIL

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#4015]
For AnVIL deployments, please use the new `verbatim.pfb` manifest format instead `terra.pfb` when exporting to Terra.

This change can be deployed to `anvildev` when the Azul [blocker](https://github.com/DataBiosphere/azul/issues/6040) is in the *Merged lower* or *Lower* column on ZenHub.

This change can be deployed to `anvilprod` when the Azul [blocker](https://github.com/DataBiosphere/azul/issues/6040) is in the *Merged stable* or *Stable* column on ZenHub.

**Comment by hannes-ucsc** [comment]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1714610940600589?thread_ts=1714591293.244639&cid=C705Y6G9Z

**Comment by dsotirho-ucsc** [comment]
Assignee to discuss general availability of this feature with stakeholders.

**Comment by bvizzier-ucsc** [comment]
The decision has been made to remove both the `verbatim` and `manifest` feature flags.

**Comment by dsotirho-ucsc** [comment]
To be continued in #4086
