### ISSUE TITLE
Downloading a manifest doesn't seem to work right in Safari

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#404]
@jodihir commented on [Thu Dec 13 2018](https://github.com/HumanCellAtlas/data-portal/issues/316)

One of the beta testers used Safari to try to download a manifest and expected tsv/csv, and it opened as an html file.

---

@jodihir commented on [Thu Dec 13 2018](https://github.com/HumanCellAtlas/data-portal/issues/316#issuecomment-447120667)

trying to add to feedback repo, not this one.

┆Issue Number: HCAB-338

**Comment by NoopDog** [comment]
This is blocked by https://github.com/DataBiosphere/azul/issues/655 (but i cant seem to link it)

**Comment by theathorn** [comment]
@jodihir Please verify in Dev, Integration or Staging.
