### ISSUE TITLE
Files tab allows single file download of zarr matrix files

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#405]
Request File Manifest hides the "matrix" file type but the Files tab enables single file download icon for these files. We should either remove/disable the icon for these type of files (preferred) or not show zarr files at all in the Files view.

┆Issue Number: HCAB-339

**Comment by brianraymor** [comment]
I would vote to **not** show .zattrs in FIles. It's especially confusing because you can use the _matrix file format_ filter to just get a list of them in that context. If the browser simply disables the download glyph, then users may be confused or frustrated based on current beta experiences in discovering matrices.

**Comment by hannes-ucsc** [comment]
Hiding these files just masks our underlying inability to correctly serve these files. It makes zero sense that a bundle includes a matrix but we hide it and force the user to go though the matrix service.

In the short term, the easiest place to filter these files out is in Azul itself. I don't think the UI should contain this type of business logic.

**Comment by NoopDog** [comment]
Yes, I feel we need a more robust way to determine which analysis bundles are matrixable.  Using the "matrix" file was a temp measure just to get us going end to end and is not meant to be something that users will understand or figure out.

Also, the data matrix files that are created are standard outputs from our data processing pipeline so why would we hide these from the user? Seems to me they should be properly labeled with the appropriate file types so people can use them if they want. 

We can enhance the UI to signify the two different modes of getting matrix info but I feel first we need a reliable way to tag the matrixable analysis bundles and also to properly expose the non concatenated matrix info in the files tab.

**Comment by theathorn** [comment]
Short term: on the File tab we will remove the file download icon for matrix file types.

**Comment by NoopDog** [comment]
Sort term fix is deployed to all environments. - Download icon is hidden for "matrix" files. 

![Screen Shot 2018-12-20 at 12.05.16 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/ec38ee0a-0637-4534-a944-337e63214299)
