### ISSUE TITLE
File Size does not sort correctly

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/data-browser#406]
Have only tested this in integration: https://integration.data.humancellatlas.org/explore/files

If you click on the `File Size` tab, the files do not sort by size correctly, it looks like it's purely sorting by the number regardless of the unit (so `100mb`, then `102b`, then `105kb`, etc.).

┆Issue Number: HCAB-340

**Comment by theathorn** [comment]
Azul issue.
