### ISSUE TITLE
[HCA DX] Validate custom events are accessible on the GA4 Query Explorer for the HCA Explorer dev and prod sites

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4110]
#### Need
Custom events are to be included in analytics reports.

#### Approach
Add a custom dimension in GA for every custom parameter specified in the Findable [README](https://github.com/DataBiosphere/findable-ui/blob/main/src/common/analytics/readme-analytics.md) in the [HCA Explorer Google Tag Manager](https://tagmanager.google.com/#/container/accounts/4492049679/containers/10468455/workspaces/59/tags).

For any parameter that is missing, follow the [CC Google Analytics Design Document](https://docs.google.com/document/d/1ahuBH17Fo-6o-OqZveHbfEibPIoVpDVZKFH4RaWYxHg/edit#heading=h.ln679hz19und) (specifically the [Configuring a Custom Event](https://docs.google.com/document/d/1ahuBH17Fo-6o-OqZveHbfEibPIoVpDVZKFH4RaWYxHg/edit#heading=h.sz065rinf1gi) and [Custom Events](https://docs.google.com/document/d/1ahuBH17Fo-6o-OqZveHbfEibPIoVpDVZKFH4RaWYxHg/edit#heading=h.4evmyisg5ewe) sections).

#### Definition of Done
Confirm every custom parameter is visible in analytics reports for `data.humancellatlas.org - GA4` and `data.humancellatlas.dev.clevercanary.com - GA4`. Specifically, document the parameters below with checkboxes to indicate they have been checked:

_data.humancellatlas.org - GA4_
* tag - entity_selected
  - [x] entity_name
* tag - entity_table_paginated
  - [x] entity_name
  - [x] pagination_direction
* tag - entity_table_sorted
  - [x] entity_name
  - [x] column_name
  - [x] sort_direction
* tag - filter_selected
  - [x] filter_name
  - [x] filter_value
* tag - bulk_download_requested
  - [x] catalog
  - [x] current_query
  - [x] index
  - [x] tool_name

_data.humancellatlas.dev.clevercanary.com - GA4_
* tag - entity_selected
  - [x] entity_name
* tag - entity_table_paginated
  - [x] entity_name
  - [x] pagination_direction
* tag - entity_table_sorted
  - [x] entity_name
  - [x] column_name
  - [x] sort_direction
* tag - filter_selected
  - [x] filter_name
  - [x] filter_value
* tag - bulk_download_requested
  - [x] catalog
  - [x] current_query
  - [x] index
  - [x] tool_name

**Comment by mrtopsyt** [comment]
Currently the `bulk_download_requested` event in Findable is only associated with a UA tag, should this be updated?

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic Everything seems to be working here!

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten!
