### ISSUE TITLE
[AnVIL Catalog] Validate custom events are accessible on the GA4 Query Explorer for dev and prod

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4112]
#### Need
Custom events are to be included in analytics reports.

#### Approach
Add a custom dimension in GA for every custom parameter specified in the following tags in the [AnVIL Catalog Google Tag Manager](https://tagmanager.google.com/#/container/accounts/6001018596/containers/113037385/workspaces/6).

For any parameter that is missing, follow the [CC Google Analytics Design Document](https://docs.google.com/document/d/1ahuBH17Fo-6o-OqZveHbfEibPIoVpDVZKFH4RaWYxHg/edit#heading=h.ln679hz19und) (specifically the [Configuring a Custom Event](https://docs.google.com/document/d/1ahuBH17Fo-6o-OqZveHbfEibPIoVpDVZKFH4RaWYxHg/edit#heading=h.sz065rinf1gi) and [Custom Events](https://docs.google.com/document/d/1ahuBH17Fo-6o-OqZveHbfEibPIoVpDVZKFH4RaWYxHg/edit#heading=h.4evmyisg5ewe) sections).

#### Definition of Done
Confirm every custom parameter is visible in analytics reports for `AnVIL Dataset Catalog - GA4` and `AnVIL Dataset Catalog CC Staging - GA4`. Specifically, document the parameters below with checkboxes to indicate they have been checked:

_AnVIL Dataset Catalog - GA4_
* tag - entity_selected
  - [x] entity_name
* tag - entity_table_sorted
  - [x] entity_name
  - [x] column_name
  - [x] sort_direction
* tag - filter_selected
  - [x] filter_name
  - [x] filter_value

_AnVIL Dataset Catalog CC Staging - GA4_
* tag - entity_selected
  - [x] entity_name
* tag - entity_table_sorted
  - [x] entity_name
  - [x] column_name
  - [x] sort_direction
* tag - filter_selected
  - [x] filter_name
  - [x] filter_value

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic This one should be all working now!

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten!
