### ISSUE TITLE
Create tests for main table export button

### ISSUE THREAD

**Issue by mrtopsyt** [DataBiosphere/data-browser#4117]
Create a test to do the following on at least two tabs each:
- Check that the sidebar values on the export menu match the values on the main table
- Attempt to download the smallest possible file from the export menu and check that:
  - Checkboxes and loading screens show properly
  - The download url downloads a file
  - The "Download Manifest" button downloads a file

**Comment by NoopDog** [comment]
@jpaten, if you have any WIP associated with this, can you please push it to a draft PR? Thanks!

**Comment by mrtopsyt** [comment]
Note - Current draft PR had a failure when expecting loading text to be visible, potentially because the text had disappeared before the locator evaluated? Check if there's a way to workaround this, otherwise remove checks that loading screen text is correct.

**Comment by mrtopsyt** [comment]
@NoopDog I've created a draft PR with my WIP! Still has a couple of issues before it's ready to be merged though.
