### ISSUE TITLE
GA4 Access Setup

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#4118]
#### Validate GA4 Query Explorer Access
One easy way to explore the GA4 Analytics API is to use the tool at https://ga-dev-tools.google/ga4/query-explorer/.

Logging in with your CC email, can you confirm you have access to these two accounts:

<img width="900" alt="360016878-1b72d9a0-6552-41b8-ba41-ce8daafa3836" src="https://github.com/user-attachments/assets/1915ac01-dcb6-4c60-8eb4-2ff79575b0b1">

Please also list the properties you have access to under these accounts. 

#### Validate Google Tag Manager Access
@jpaten, you should have HCA and AnVIL [Tag Manager](https://tagmanager.google.com/) access now.  Can you verify?

**Comment by mrtopsyt** [comment]
I have access to both of those accounts, with the following properties. I also have access to the tag manager for both.
<img width="808" alt="Screenshot 2024-08-21 at 10 46 36 PM" src="https://github.com/user-attachments/assets/0658c2e4-b21e-4763-90df-6e1f6bfca59b">
<img width="824" alt="Screenshot 2024-08-21 at 10 48 27 PM" src="https://github.com/user-attachments/assets/97dd1911-765b-4353-9171-dea5940409cf">
<img width="888" alt="Screenshot 2024-08-21 at 10 49 35 PM" src="https://github.com/user-attachments/assets/a6a8a3dc-55bb-48b1-a644-e8886baefb69">

**Comment by MillenniumFalconMechanic** [comment]
Excellent, thanks Jonah!
