### ISSUE TITLE
[HCA DX] Allow user to filter by access facet

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4133]
Similar to [AnVIL DX mocks](https://www.figma.com/proto/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1008-16881&scaling=min-zoom&page-id=1008%3A14844&starting-point-node-id=1047%3A16475):

<img width="412" alt="Screen Shot 2023-05-18 at 11 13 12 AM" src="https://github.com/DataBiosphere/data-browser/assets/2446424/49a7bcd4-b436-4bb6-9969-a2d50fcff003">

See implementation for [AnVIL DX](https://github.com/DataBiosphere/data-browser/issues/3364).

**Comment by NoopDog** [comment]
HI @frano-m can  you move "Access" to under "Project" like 
<img width="380" alt="image" src="https://github.com/user-attachments/assets/26bf6706-e94f-4167-bb95-d7687e67658e">
