### ISSUE TITLE
[HCA DX] Add data use restriction facet and column

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4136]
### Background
See [Azul ticket](https://github.com/DataBiosphere/azul/issues/6131).

### Need
Using the `projects.dataUseRestriction` value returned from Azul, corresponding columns and facets are to be displayed as follows.

#### Data use restriction column
- "Projects" entity after the "Access" column
- "Files" entity after the "File Size" column
 
#### Data use restriction filter
- "Project" section after the "Biological Network" filter

### Approach
* Convert `null` values to "".

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic one question - you clarified on Wednesday that the column on the Projects entity should only appear on the Managed Access config. Should the column also only appear on that config, or can that appear on the regular dev and prod configs?
