### ISSUE TITLE
[AnVIL DX] Determine files name and size fields being used

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4142]
As per @dsotirho-ucsc:

> Our [/index/files](https://service.explore.anvilproject.org/index/files?catalog=anvil7&size=1) endpoint (for AnVIL) currently returns two duplicated fields under hits[].files[]: file_name duplicates name, and file_size duplicates size.
Could you please confirm which of these the Data Browser uses? We would like to remove the duplication and not break the Data Browser in the process ;)
Note: This is not an issue for the [/index/files](https://service.azul.data.humancellatlas.org/index/files?catalog=dcp40&size=1) endpoint for HCA, which only returns the short versions (name and size).
Thanks!

For example, see `name` and `file_name` in the files response:
![Untitled](https://github.com/user-attachments/assets/c15ac0dd-0539-462c-8ca8-d117c5f8d6c2)

**Comment by frano-m** [comment]
@MillenniumFalconMechanic and @dsotirho-ucsc, I can confirm AnVIL CMG uses `name` and `size`. Thanks!

**Comment by frano-m** [comment]
@MillenniumFalconMechanic and @dsotirho-ucsc, after double checking 🙄, I can confirm AnVIL CMG uses `file_name` and `file_size`.

**Comment by NoopDog** [comment]
Complete!
