### ISSUE TITLE
Flag overcomplicated tests for potential simplification

### ISSUE THREAD

**Issue by mrtopsyt** [DataBiosphere/data-browser#4166]
### Need
Playwright tests have been found to be flaky in certain instances, and some are too complicated for the results to be useful

### Approach
- Examine the Playwright tests for AnVIL-CMG and AnVIL-Catalog and identify tests that have any one of the following issues:
  - Data dependence of any kind, even if trivial (i.e. assuming that a row is nonempty or that there will be multiple filters)
  - Testing multiple nontrivial elements in one case
  - Places where one test can be broken into two for simplicity
  - Slow tests
  - Any other potential code smells or test issues
- Focus on reducing the number of queries made to Azul, since current tests are causing too much stress

**Comment by mrtopsyt** [comment]
Hi! I found the following places where I think it would be possible to reduce calls to the backend or where there is potential data dependence:

- Sort tests (`testSortAzul`)
  - Currently tries sorting each pre-selected column on each tab twice, leading to a larger number of backend calls than most other tests
  - Could either just reduce the number of sorts made, or ensure that the sort categories that are checked on one tab are not checked on other tabs so each column gets sorted once
  - Also fails if the text of a cell in the top row is empty either before or after sorting, which may not be guaranteed
  - **Handling in #4210**
- Filter tests
  - `testFilterPersistence`
    - Current test requires that the first filter value it tries has text, which may not be guaranteed
    - Could be fixed by checking the first nonempty filter value instead of just the first filter value
    - **Handling in #4211**
  - General
    - No tests that involve selecting filters run on the "Donors" tab, which should potentially be addressed by changing the tab that one such test runs on

**Comment by NoopDog** [comment]
Hi @jpaten please ticket out the ones we approved yesterday. Have this ticket link to the new tickets. Let @MillenniumFalconMechanic review the ticket before you start to work on it.  Thanks!

**Comment by mrtopsyt** [comment]
Holding on Sharding for now, discussed it but decided it wasn't worthwhile for now due to backend limitations

**Comment by MillenniumFalconMechanic** [comment]
Superseded by individual tickets above.
