### ISSUE TITLE
Flag Playwright tests for possible use of test-ids

### ISSUE THREAD

**Issue by mrtopsyt** [DataBiosphere/data-browser#4167]
### Need
E2E tests contain elements that are overly implementation or data dependent, leading to flakiness

### Approach
Flag any Playwright locators where a regex, css locator, or otherwise undesirable feature is used and where a test-id could be more reliable

**Comment by mrtopsyt** [comment]
I think it would make sense to add the following test-ids to Findable components. I checked briefly to check if I think any of these would lead to unintended consequences, but I'm obviously not super familiar with Findable so there might be some mistakes!

| Component                                  | test-id name                          | Purpose                                                                                                                                                                                  |
|--------------------------------------------|---------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `FilterLabel`                              | `filter-label`                        | To avoid the current `filterRegex` matching an element of the data table                                                                                                                 |
| `HighlightedLabel`                         | `filter-text`                         | To allow the text of a filter to be easily queried                                                                                                                                       |
| `VariableSizeListItem`, in `Typography`     | `filter-count`                        | To allow the count of a filter to be easily queried                                                                                                                                      |
| `VariableSizeListItem` in `ListItemButton` | `filter-button`                       | To allow filter options to be reliably selected                                                                                                                                          |
| `FilterTag`                                | `filter-tag`                          | To allow filter tags to easily be selected, without inadvertently selecting a filter menu or an element of the data table                                                                |
| `KeyValuePairs` in `Key`                   | `project-details-header`              | To allow the correct Details element to be selected                                                                                                                                      |
| `KeyValuePairs` in `Value`                 | `project-details-value`               | To allow the value of a Details element to be queried                                                                                                                                    |
| `KeyValuePairs` in `KeyValue`              | `project-details-element`             | To allow Details elements to be selected                                                                                                                                                 |
| `NTagCell`                                 | The value of all elements in the NTag | To allow the text of NTag cells to be reliably queried without also testing whether the tooltip is functioning, improving modularity. Could also be a name or label instead of a test-id |

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten, thanks so much for adding the detail above! For each row, would you be able to add a link to examples in the code where you think the test ID could be used?

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic @frano-m ! I've gone through and annotated examples of where the test ids could simplify my existing code

| Component                                      | test-id name                          | Purpose                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Usage Link |
| ---------------------------------------------- | ------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| `FilterLabel`                                  | `filter-label`                        | To avoid the current `filterRegex` matching an element of the data table                                                                                                                 | Would replace calls to [`filterRegex`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L363), which is used to match a filter button based on its text, such as in [`testFilterPresence`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L383) |
| `VariableSizeListItem`, in, `HighlightedLabel` | `filter-text`                         | To allow the text of a filter value to be easily queried                                                                                                                                 | In [`testFilterPersistence`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L455), where the name of a filter needs to be determined so it can be selected again                                                                                                                     |
| `VariableSizeListItem`, in `Typography`        | `filter-count`                        | To allow the count of a filter to be easily queried                                                                                                                                      | in [`testFilterCounts`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L524), where the number of entries associated with a filter value needs to be determined                                                                                                                      |   |
| `VariableSizeListItem` in `ListItemButton`     | `filter-button`                       | To allow filter values to be reliably selected, such as in [`testFilterCounts`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L536)              | <-- |
| `FilterTag`                                    | `filter-tag`                          | To allow filter tags to easily be selected, without inadvertently selecting a filter menu or an element of the data table                                                                | To replace [`getFilterTagLocator`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L561), used in [`testFilterTags`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L596)                                                                      |
| `KeyValuePairs` in `Key`                       | `project-details-header`              | To allow the correct Details table to be selected                                                                                                                                        | To replace the proximity locator in [`testBackpageDetails`](https://github.com/DataBiosphere/data-browser/blob/8c900ad671774540992e2823a8f7128169aad770/explorer/e2e/testFunctions.ts#L1046)                                                                                                                                                                |            |
| `KeyValuePairs` in `Value`                     | `project-details-value`               | To allow the value of a Details element to be queried                                                                                                                                    | To replace the proximity locator in [`testBackpageDetails`](https://github.com/DataBiosphere/data-browser/blob/8c900ad671774540992e2823a8f7128169aad770/explorer/e2e/testFunctions.ts#L1046)                                                                                                                                                                 |            |
| `KeyValuePairs` in `KeyValue`                  | `project-details-element`             | To allow Details elements to be selected                                                                                                                                                 | To replace the proximity locator in [`testBackpageDetails`](https://github.com/DataBiosphere/data-browser/blob/8c900ad671774540992e2823a8f7128169aad770/explorer/e2e/testFunctions.ts#L1046)                                                                                                                                                                 |            |
| `NTagCell`                                     | The value of all elements in the NTag | To allow the text of NTag cells to be reliably queried without also testing whether the tooltip is functioning, improving modularity. Could also be a name or label instead of a test-id | To reduce reliance on [`hoverAndGetText`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L936), used where the values of NTag cells needs to be read, such as in [`testSortCatalog`](https://github.com/DataBiosphere/data-browser/blob/main/explorer/e2e/testFunctions.ts#L225)                                                              |

**Comment by MillenniumFalconMechanic** [comment]
| Component | Comment
| ------------ | -------------
|FilterLabel | `button-filter-category`
|VariableSizeListItem, in, HighlightedLabel | `button-filter-category-value-label`
|VariableSizeListItem, in Typography| `button-filter-category-value-count`
|VariableSizeListItem in ListItemButton| `button-filter-category-value`
| FilterTag|`tag-selected-category-value`

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten!
