### ISSUE TITLE
[HCA DX] Remove deprecated UA tags, triggers and variables from GTM

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4175]
#### Need
The HCA GTM container still has configuration objects (tags, triggers and variables) that are specific to UA; these need to be removed.

#### Definition of Done
- [ ] All UA-specific objects are removed from GTM.
- [ ] Remove any UA-specific values from GA.

**Comment by mrtopsyt** [comment]
The following UA tags were removed:

- Bulk Download Copy to Clipboard
  - Entity Type
  - Entity URL
  - Tool Name
  - Index
  - Catalog
- Bulk Download Request (implemented in GA4)
  - Entity Type
  - Tool Name
  - Index
  - Catalog
- Cohort Manifest Copy to Clipboard
  - Entity Type
  - Entity URL
  - Catalog
- Cohort Manifest Download
  - Entity Type
  - Entity URL
  - Catalog
- Chort Manifest Request
  - Entity Type
  - Catalog
- DB Page View
- Entity Return to Tab
  - Current Query
  - Catalog
- Entity Select Tab (already implemented as entity_selected)
  - Current Query
  - Catalog
- Export Copy to Clipboard
  - Entity Type
  - Entity URL
  - Tool Name
  - Index
  - Catalog
- Export Launch
  - Entity Type
  - Entity URL
  - Tool Name
  - Catalog
- Export Request
  - Entity Type
  - Tool Name
  - Catalog
- File Download
  - Entity URL
  - Related Entity ID
  - Related Entity Type
  - Current Query
  - Catalog
- Portal Link
  - Entity URL
  - Current Query
  - Source
  - Catalog
- Portal Page View
- Project Download/Copy Full Manifest
  - Entity ID
  - Entity URL
  - Related Entity ID
  - Related Entity Type
  - Related Entity URL
  - Catalog
- Project Download/Copy Manifest/Matrix
  - Entity ID
  - Entity URL
  - Related Entity ID
  - Related Entity Type
  - Related Entity URL
  - Catalog
- Project Request/Copy curl
  - Entity ID
  - Catalog
  - Tool Name
  - Term
- Project View Accession
  - Entity ID
  - Related Entity ID
  - Related Entity Type
  - Related Entity URL
  - Catalog
- Project View Deprecated
  - Entity URL
  - Current Query
  - Entity ID
  - Catalog
- Project View External Resource
  - Entity URL
  - Related Entity ID
  - Related Entity Type
  - Current Query
  - Entity ID
  - Related Entity URL
  - Catalog
- Project View Withdrawn
  - Entity URL
  - Current Query
  - Entity ID
  - Related Entity URL
  - Catalog
- Request/Copy/Launch Project Terra
  - Entity ID
  - Catalog
  - Tool Name
  - Term
- Search
  - Entity Type
  - Current Query
  - Facet
  - Term
  - Source
  - Min
  - Max
  - Entity ID
  - Index
  - Catalog
- Search Metadata Click
  - Entity Type
- Search Metadata Enter Text
  - Entity Type
- Search Result Page
  - Current Query
  - Index
  - Catalog
- Search Result Sort
  - Entity Type
  - Current Query
  - Source
  - Direction
  - Index
  - Catalog
- Support Request Create
  - Source
  - Catalog
- Survey Launch
- View Catalog
  - Entity Type
  - Catalog
- View Matrix Archive Preview
  - Entity Id
  - Related Entity ID
  - Related Entity Type
  - Catalog

**Comment by MillenniumFalconMechanic** [comment]
LGTM, thanks @jpaten!
