### ISSUE TITLE
[AnVIL Catalog] Update GTM outbound link configuration

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4176]
#### Need
Outbound links should track the source URL.

#### Definition of Done
Additional outbound link information is accessible in the query manager for prod and staging:
- [x] AnVIL Dataset Catalog - GA4
- [x] AnVIL Dataset Catalog CC Staging - GA4

**Comment by mrtopsyt** [comment]
Currently it's working on Prod but seems not to on staging - for now here's a screenshot of the current output, I'll update when it's working on staging!

![Image](https://github.com/user-attachments/assets/f132ea92-7a0a-43a1-b4bc-f143862a2148)

**Comment by jpaten** [comment]
Now working on Staging too!
![Image](https://github.com/user-attachments/assets/bfe9f7d1-d2e8-44da-a37b-8ab7fa9befd1)

**Comment by mrtopsyt** [comment]
Staging:

![Image](https://github.com/user-attachments/assets/d5a99283-64f3-451a-b079-d6da6c4cd93b)

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
