### ISSUE TITLE
[NCPI Catalog] Update GTM outbound link configuration 

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4177]
#### Need
Outbound links should track the source URL.

#### Definition of Done
Additional outbound link information is accessible in the query manager for prod and staging:
- [x] NCPI Dataset Catalog - GA4 (https://ncpi-data.org/)
- [x] NCPI Dataset Catalog CC Staging - GA4 (https://ncpi-data.dev.clevercanary.com/)

**Comment by mrtopsyt** [comment]
Working on both Catalog & Prod @MillenniumFalconMechanic 

Prod:
<img width="485" alt="Screenshot 2024-10-14 at 4 04 22 PM" src="https://github.com/user-attachments/assets/0d12b028-6ba1-451d-a073-ffff272bf68c">


Staging:
<img width="517" alt="Screenshot 2024-10-14 at 4 04 00 PM" src="https://github.com/user-attachments/assets/0e3f42a1-a1d0-42cd-b25b-3974de1198f0">

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
