### ISSUE TITLE
[AnVIL DX] Update GTM outbound link configuration

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4178]
#### Need
Outbound links should track the source URL and capture the fragment if any.

#### Definition of Done
Additional outbound link information is accessible in the query manager for prod and staging:
- [ ] AnVIL DX - GA4
- [x] AnVIL DX CC Staging - GA4

**Comment by mrtopsyt** [comment]
Working on prod & staging @MillenniumFalconMechanic 

Prod:
![Image](https://github.com/user-attachments/assets/ccb211ad-a6c8-47c6-a5a0-4c01307b10e4)

Staging:
![Image](https://github.com/user-attachments/assets/b69c5b5b-aca1-43d2-80da-47b90d1aa854)

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
