### ISSUE TITLE
[LungMAP DX] Update GTM outbound link configuration

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4179]
#### Need
Outbound links should track the source URL and capture the fragment if any.

#### Definition of Done
Additional outbound link information is accessible in the query manager for prod and staging:
- [x] data-browser.lungmap.net - GA4
- [x] data-browser.dev.lungmap.net - GA4

**Comment by mrtopsyt** [comment]
Working on prod:

<img width="532" alt="Screenshot 2024-10-15 at 6 01 48 PM" src="https://github.com/user-attachments/assets/53567941-a4b0-46af-8b43-997fcdcb7c38">

**Comment by mrtopsyt** [comment]
Finally working on staging!
<img width="739" alt="Screenshot 2024-10-18 at 9 46 51 AM" src="https://github.com/user-attachments/assets/3918a9a6-d24b-4855-b191-dc1528cafc41">

**Comment by MillenniumFalconMechanic** [comment]
Thank you!
