### ISSUE TITLE
[HCA DX] Track clicks on "Export" button

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4180]
#### Need
We need to add tracking of the cohort export button to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the export button is performing as expected.

#### Approach
* Add a `button-cohort-export` ID to the cohort export button. (See https://github.com/DataBiosphere/findable-ui/issues/218.)
* Use GTM's built-in click variables to enable click tracking.
* Create trigger that fires on "Click - All Elements" / "Some Clicks" to target only the export button.

#### Definition of Done
Clicks on export data button are accessible in the query explorer for both prod and staging:
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic Seems to be working!

Prod:
![Image](https://github.com/user-attachments/assets/187fd9ed-58a2-477f-8db1-9ec0055a344a)

Staging:
![Image](https://github.com/user-attachments/assets/cb5b0f4f-3cb1-41ac-b9e6-c21b61c27dbf)

**Comment by MillenniumFalconMechanic** [comment]
Thank you!
