### ISSUE TITLE
[HCA DX] Track clicks on "Analyze in Terra" export method button

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4181]
#### Need
We need to add tracking of the cohort "Analyze in Terra" button to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the Terra button is performing as expected.

#### Approach
* Add a `button-analyze-in-terra` ID to the "Analyze in Terra" button.
* Use GTM's built-in click variables to enable click tracking.
* Create trigger that fires on "Click - All Elements" / "Some Clicks" to target only the export button.

#### Definition of Done

- [x] Merge [Findable PR](https://github.com/DataBiosphere/findable-ui/pull/220)
- [x] Release findable version [13.0.1](https://github.com/DataBiosphere/findable-ui/releases/tag/v13.0.1)
- [x] Update data-browser to new findable version
- [x] Update ids in data-browser
- [x] Deploy data-browser
- [x] Create GTM tags
- [x] Deploy GTM version

Clicks on "Analyze in Terra" data button are accessible in the query explorer for both prod and staging:
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten, could you remind me if there is a PR for this ticket (or possibly provide a link to the GTM version I need to review)?

**Comment by mrtopsyt** [comment]
So sorry! I think I mis-tagged this PR (https://github.com/DataBiosphere/data-browser/pull/4201), so it got associated with #4191 rather than this. It's merged now, and #4191 should only require changes to findable-ui, so I don't think you need to take any action for this PR. I do still need a review on [GTM Version 57](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions?containerDraftId=72) in order for this event to run on Prod.

**Comment by NoopDog** [comment]
So can this be closed ? What are the next steps?  @jpaten

**Comment by NoopDog** [comment]
Ok so review on [GTM Version 57](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions?containerDraftId=72) is the next step for @MillenniumFalconMechanic ?


@jpaten is there any ticket e.g. findable update this ticket is blocked for completion on or is the only remaining task publishing the GTM version?

**Comment by mrtopsyt** [comment]
Hi @NoopDog! Sorry for missing this earlier. I added a checklist to the ticket. The only current TODO is to deploy the current Data Browser version to prod. Sorry, I missed this earlier!

**Comment by mrtopsyt** [comment]
Hi @NoopDog! The changes are now showing on Data Browser, so the only step is waiting for the event to propagate to the Query Explorer

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic This event is now showing on Query Explorer!

**Comment by NoopDog** [comment]
Woot!

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten !
