### ISSUE TITLE
Set the data retention for all GA properties to the max (14 months)

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#4183]
#### Need
We want to be able to see year-over-year trends. Let's make sure all properties and all environments are set to keep the data for as long as possible which is 14 months for the free version.

https://support.google.com/analytics/answer/7667196?hl=en

#### Approach
1. Enumerate all sites with a list of checkboxes below
2. Set the data retention for each site.

#### Properties

- [x] AnVIL Portal
  - [x] Prod
  - [x] Staging
- [x] AnVIL Catalog
  - [x] Prod
  - [x] Staging
- [x] AnVIL DX
  - [x] Prod
  - [x] Staging
- [x] NCPI Catalog
  - [x] Prod
  - [x] Staging
- [x] HCA Portal + DX
  - [x] Prod
  - [x] Staging
- [x] Lungmap DX
  - [x] Prod
  - [x] Staging

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic @NoopDog Done!

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten!
