### ISSUE TITLE
[HCA DX] Upgrade support request tag, trigger, and variables to GA4 conventions

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4188]
#### Need
The support request GTM configuration currently has some configuration objects that are in the deprecated UA-4. For example:

* The `tag - support_request_create` [tag](https://tagmanager.google.com/#/container/accounts/4492049679/containers/10468455/workspaces/69/tags) contains a reference to `Event Action` and `Event Label` parameters.

<img width="572" alt="image" src="https://github.com/user-attachments/assets/ca4a9305-36cc-4817-a893-53eda85621e1">

* The  `Support Request Create` trigger name should follow GA4 naming conventions.
* The `Source` and `Catalog` variable names should follow GA4 naming conventions.

#### Approach
~~Document the changes required to update the support request configuration objects to match GA4 conventions. Once changes are reviewed, proceed with updates and confirm support request events are tracked correctly in staging and prod. (Note that support requests are shared in the HCA community Slack channel; clearly mark any support requests as tests and use `dave@clevercanary.com` as the submitter email.)~~ Completed; see [comment](https://github.com/DataBiosphere/data-browser/issues/4188#issuecomment-2406605702).

Add tracking to "Send" button on support request form by adding a `button-support-request` test ID to the button, and standard click event configuration in GTM. 

#### Definition of Done
- [x] Document the changes required to update the support request configuration objects to match GA4 conventions.
- [x] Merge [Findable PR]
- [x] Release findable version [13.0.1](https://github.com/DataBiosphere/findable-ui/releases/tag/v13.0.1)
- [x] Update data-browser to new findable version
- [x] Update data-portal to new findable version (https://github.com/DataBiosphere/data-portal/issues/2478)
- [x] Deploy data-browser with new findable version
- [x] Deploy data-portal with new findable version
- [x] Create GTM tags

- [x] Check support request events in query explorer for data.humancellatlas.org - GA4.
- [x] Check support request events in query explorer for data.humancellatlas.dev.clevercanary.com - GA4.

**Comment by mrtopsyt** [comment]
Currently, this event is not implemented, as the HCA Portal uses the `SupportRequest` component in Findable, which does not have tracking implemented. Note that on GA4, there are no calls to Support Request in the past month (and very very few over the past year). To resolve this while keeping the tracking functionality, the following would need to be done:

- Add an event model to findable-ui with the name `support_request_create` containing `source` and `catalog` as parameters
- Add optional props to `SupportRequestProps` to pass the relevant data needed to fill the `source` and `catalog` parameters
- Call the event in findable in `SupportRequestForm` (see the TODO in `supportRequestForm.tsx`)
- Pass the relevant props in the Data Portal next site so the event can be called
- Update the names of the GTM variables and triggers to match other GA4 events, and add consts where relevant.

**Comment by mrtopsyt** [comment]
In order to successfully track requests from both the Data Explorer and the HCA Portal, https://github.com/DataBiosphere/data-portal/issues/2478 needs to be merged.

**Comment by mrtopsyt** [comment]
Corresponding GTM version is [59](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions?containerDraftId=72)

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic, I confirmed in Preview mode on GTM that this runs and that it showed on Realtime mode on the prod and dev site. I have not yet confirmed that it works on Query Explorer

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic Confirmed working on staging and prod!

#### Staging

![Image](https://github.com/user-attachments/assets/38ff7ff9-8619-4623-9b98-7624afcddf03)

#### Prod

![Image](https://github.com/user-attachments/assets/63587e89-b7a7-4724-9d66-da6d18977ccc)

**Comment by MillenniumFalconMechanic** [comment]
Would you mind updating the tag and trigger to `x - support_request_created`?

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic Updated on version [63](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions)

**Comment by MillenniumFalconMechanic** [comment]
LGTM, thanks Jonah!
