### ISSUE TITLE
[HCA DX] Track clicks on "Request File Manifest" export method button

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4196]
#### Need
See similar "Analyze in Terra" [ticket](https://github.com/DataBiosphere/data-browser/issues/4181).

#### Definition of Done

- [x] Merge [Findable PR](https://github.com/DataBiosphere/findable-ui/pull/220)
- [x] Release findable version [13.0.1](https://github.com/DataBiosphere/findable-ui/releases/tag/v13.0.1)
- [x] Update data-browser to new findable version
- [x] Update ids in data-browser (#4201)
- [x] Deploy data-browser
- [x] Create GTM tags
- [x] Deploy GTM Version to Live

Clicks on "Request File Manifest" data button are accessible in the query explorer for both prod and staging:
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten, the [corresponding PR](https://github.com/DataBiosphere/data-browser/issues/4196) has been merged and deployed to dev.

**Comment by mrtopsyt** [comment]
Thanks @MillenniumFalconMechanic! I'll work on the GTM configuration now.

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic, would you be able to review version 60 on [GTM](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions?containerDraftId=72)

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten, [version 60](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions?containerDraftId=72) LGTM!

**Comment by mrtopsyt** [comment]
@MillenniumFalconMechanic This event is now showing up on Query Explorer!

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten!
