### ISSUE TITLE
Update sort tests to reduce the number of API calls and data dependence

### ISSUE THREAD

**Issue by mrtopsyt** [DataBiosphere/data-browser#4210]
#### Need
Currently the `testSortAzul` function in `testFunctions.ts`, which runs the table sort tests, leads to a large number of backend calls and has the potential of failing if the table contains any blank cells. The current test is as follows:
- Load the specified tab
- For each default/pre-enabled column that is marked as the test configuration as "sortable":
  - Check that the first cell in the column is not blank and is visible 
  - Click the column header to sort it
  - Check that the first cell in the column is not blank and is visible
  - Click the column header to sort it in the inverse direction
  - Check that the first cell in the column is not blank and is visible
- Pass the test if this succeeds for each default column

#### Approach
- Sort every sortable default column on each tab once, to reduce the number of API calls made
- Remove the check that the first cell in the sorted column is not blank to reduce data dependence
- Add a check that the "sorted" icon (with test id `SouthRoundedIcon`) is only visible on the sorted column

**Comment by MillenniumFalconMechanic** [comment]
Approach LGTM, thanks Jonah!
