### ISSUE TITLE
Update filter persistence test to remove data dependence

### ISSUE THREAD

**Issue by mrtopsyt** [DataBiosphere/data-browser#4211]
#### Need
Currently the `testFilterPersistence` function in `testFunctions.ts` fails if the first filter value does not have associated text.
The current test runs as follows:
- Go to the specified "first" tab
- Click the specified filter
- Click the first filter value. If the first filter option is blank, print a warning and fail. 
  - This is necessary under the current structure because without test ids, there is no way of selecting a filter without text in future steps
- Record the name of this filter
- Expect at least one table cell to be visible
- For each specified "other" tab
  - Click the tab
  - Select the same filter as before
  - Expect the filter value with the name that was recorded earlier to be checked
- Click the specified "first" tab
- Expect at least one table cell to be visible
- Click the same filter as before
- Check that the filter option is still checked
- If no issues are encountered, pass the test
#### Approach
- Change the test to continue to check filter values until it finds the first filter value that has associated text. Fail if after a specified number of filters is checked, none has text

**Comment by MillenniumFalconMechanic** [comment]
Approach LGTM, thanks Jonah!
