### ISSUE TITLE
[HCA DX] Track clicks on "Request curl Command" export method button

### ISSUE THREAD

**Issue by mrtopsyt** [DataBiosphere/data-browser#4225]
#### Need
We need to add tracking of the cohort "Request curl Command" button to monitor user interactions and optimize conversions. This tracking will allow us to analyze the conversion funnel more accurately, ensuring that the Terra button is performing as expected.

#### Approach
* Add a `button-request-curl-command` ID to the "Request curl Command" button.
* Use GTM's built-in click variables to enable click tracking.
* Create trigger that fires on "Click - All Elements" / "Some Clicks" to target only the export button.

#### Definition of Done

- [x] Add tracking id in data-browser (#4232)
- [x] Deploy data-browser (#4247)
- [x] Create GTM tags
- [x] Deploy GTM version

Clicks on "Request curl Command" data button are accessible in the query explorer for both prod and staging:
- [x] data.humancellatlas.org - GA4
- [x] data.humancellatlas.dev.clevercanary.com - GA4

**Comment by mrtopsyt** [comment]
Version [#61](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions) on GTM

**Comment by MillenniumFalconMechanic** [comment]
#61 LGTM, thanks @jpaten!

**Comment by mrtopsyt** [comment]
Working on prod and staging!

Prod
![Image](https://github.com/user-attachments/assets/76a2015d-46a4-4d4b-9f25-076b9748fe7b)

Staging
![Image](https://github.com/user-attachments/assets/d6666494-53a5-4eaf-8eaa-a11943dbaa8f)

**Comment by MillenniumFalconMechanic** [comment]
Thanks @jpaten! Are the unchecked checkboxes in the description still outstanding?

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! Whoops, I forgot to check those, thanks for catching that!

**Comment by MillenniumFalconMechanic** [comment]
LGTM, thanks Jonah!
