### ISSUE TITLE
[AnVIL DX] Document data mappings

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4233]
#### Approach
* Create `AnVIL Explorer Data Cross Walk` spreadsheet containing tab per entity with the columns:
  * UI Column Name
  * Azul API Respons
  * TDR 
* Complete Column Name and Azul API Response Key columns for each entity by inspecting the config and code.
* Include values returned by Azul with no corresponding UI column (`UI Column Name` will be empty for these values).

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! Please see a [completed spreadsheet](https://docs.google.com/spreadsheets/d/1rR3yH4wjnUcg7XEq_G8dvI1iCucp4a6dMlUHeCeEPgw/edit?usp=sharing) matching these specs!

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten! Looks good, thank you! We made a couple of small edits. ~~Two~~ Three q's:

1. Would you be able to sort each tab by Azul response key, alpha?
2. Is the `drs_uri` on the files tab a top-level field? (It looks odd!)
3. Would you be able to add the values in the Azul response that are not included in the UI (e.g. `datasets. data_use_permission`)? I'll update the ticket description to reflect this ask.

**Comment by mrtopsyt** [comment]
Complete filter tab with headers currently present on the sheet

**Comment by mrtopsyt** [comment]
TODO: Sort unused api responses alphabetically (do not change api responses that have headers associated)

**Comment by mrtopsyt** [comment]
Sheet is now sorted as specified

**Comment by MillenniumFalconMechanic** [comment]
Thanks Jonah!
