### ISSUE TITLE
Let the Data Column in the Projects and Samples tabs be open for narrower browser sizes.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#427]
User feedback is that he switch in the data column for responsiveness is confusing.
I have seen us search for the data column as well.

Lets keep it open on extra wide, desktop, and maybe even tablet with a scroll?

┆Issue Number: HCAB-351

**Comment by frano-m** [comment]
For consistency, and in response to user feedback about the different structure of the table at different screen widths, we will show the data column at all times.  The table scrolls on devices anyway and there is a good chance that user will not discover the "hover/click" state over the ticks when in using mobile...

![image.png](https://images.zenhubusercontent.com/5ac463024b5806bc2bcd91dd/24f2caf1-0460-4ebf-9217-10a24ec8ed2c)
