### ISSUE TITLE
[HCA DX] Update naming convention of export method-related tags and triggers

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#4272]
#### Need
GTM [tags](https://tagmanager.google.com/#/container/accounts/4492049679/containers/10468455/workspaces/75/tags) and [triggers](https://tagmanager.google.com/#/container/accounts/4492049679/containers/10468455/workspaces/75/triggers) related to selecting cohort export methods should follow the naming convention `${gtmObjectType} - index_${exportName}_selected`. For example, `tag - index_analyze_in_terra_selected` or `trigger - index_bulk_download_selected`.

**Comment by mrtopsyt** [comment]
- Rename `export_data_click` to `export_data_clicked`
- Rename `outbound_link_click` to `outbound_link_clicked`
- Rename `index_${exportType}_export_method` to `index_${exportType}_selected`

**Comment by mrtopsyt** [comment]
Hi @MillenniumFalconMechanic! Here are the versions for your review

- HCA: [Version 65](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions/65)
- AnVIL Portal: [Version 21](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/31178385/versions/21) (also removed unused search tags)
- AnVIL Catalog [Version 11](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/113037385/versions/11)
- NCPI Catalog [Version 10](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/115134560/versions/10)
- AnVIL DX [Version 10](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/122744496/versions/10)

**Comment by MillenniumFalconMechanic** [comment]
Hi @jpaten! It looks like AnVIL Portal needs to have its trigger updated but everything else LGTM. Thank you!

- HCA: [Version 65](https://tagmanager.google.com/#/versions/accounts/4492049679/containers/10468455/versions/65) - LGTM
- AnVIL Portal: [Version 21](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/31178385/versions/21) (also removed unused search tags) - **`trigger - outbound_link_click` still needs to be updated?**
- AnVIL Catalog [Version 11](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/113037385/versions/11) - LGTM
- NCPI Catalog [Version 10](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/115134560/versions/10) - LGTM
- AnVIL DX [Version 10](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/122744496/versions/10) - LGTM

**Comment by mrtopsyt** [comment]
Updated AnVIL Portal as [Version 22](https://tagmanager.google.com/#/versions/accounts/6001018596/containers/31178385/versions/22)

**Comment by MillenniumFalconMechanic** [comment]
LGTM, thanks @jpaten!
