### ISSUE TITLE
Create proposal for integrating download flows for different matrix types (10x vs SS2)

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#435]
Proposal under development is here: 
https://docs.google.com/document/d/1q3DJ8Y9YAmE9SW46OKkloSwUZEvpkRhKypN_q1ymD0s/edit

┆Issue Number: HCAB-356

**Comment by theathorn** [comment]
This may no longer be needed now we are replacing Cellranger with Optimus?
See #548 and databiosphere/azul#896.

**Comment by NoopDog** [comment]
@theathorn we have now a concrete proposal for this flow that we are getting usability feedback on and refining. 

Requesting to then close this ticket and open additional ones for further refinement/usability testing and implementation of the updates.

The summary of the effort is here and this contains the links to the invision mocks as well.

https://docs.google.com/document/d/1T5N4f080OqA1Iq4WJGY_jqJREdfuxBzff3zDmA4lVto/edit#heading=h.ys4noxgxkvd8
