### ISSUE TITLE
Update Official Functional Requirements for Projects Tab from Meetings Notes/Discussions

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#44]
https://docs.google.com/document/d/1y5bxYR5Y_Xtf4omFFIwzVTBarCn3e87Hqp0kYKo6Nv0/edit#heading=h.n7st6w4y6gg2

┆Issue Number: HCAB-28

**Comment by theathorn** [comment]
@NoopDog status on this?

**Comment by NoopDog** [comment]
@theathorn  the document is updated here:
https://docs.google.com/document/d/1y5bxYR5Y_Xtf4omFFIwzVTBarCn3e87Hqp0kYKo6Nv0/edit#heading=h.alni1vc17ju
