### ISSUE TITLE
Upgrade Angular CLI to latest for Angular 5 (1.7.4)

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#442]
┆Issue Number: HCAB-360

**Comment by theathorn** [comment]
How is this different from #401?

**Comment by NoopDog** [comment]
This took the number of warnings from `npm audit` down to 5 or so from 70. Seems all the security warnings are from the Angular CLI which is not deployed.  This is as far as I can upgrade it without also doing the Angular upgrade. So.. It was a quick and easy way to get rid of most of the security warnings.  401 would upgrade the CLI to 7.x but we only moved it to 1.7.4 (the big jump in numbers is due to a change in how they did versioning)
