### ISSUE TITLE
404 Page for Data Browser

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#444]
Go to a project tab like https://dev.data.humancellatlas.org/explore/projects/f78e4798-2744-4613-9df4-a6866e1da805

Modify the url to garbage like https://dev.data.humancellatlas.org/explore/projects/f78e4798-2744-4613-9df4-JUNK

Then refresh.. we get a blank page instead of a 404 page.

┆Issue Number: HCAB-361

**Comment by MillenniumFalconMechanic** [comment]
@frano-m 404 page is located at `/not-found`.
