### ISSUE TITLE
Backward paging is broken

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#446]
Initial state. Request lacks search parameters. First page is displayed:

<img width="1682" alt="screen shot 2019-01-30 at 8 53 20 pm" src="https://user-images.githubusercontent.com/5143256/52031969-d151a900-24d3-11e9-97e5-1da8b9487379.png">

Response contains paging info with values for `search_after` but none for `search before`:

<img width="1676" alt="screen shot 2019-01-30 at 8 53 37 pm" src="https://user-images.githubusercontent.com/5143256/52031971-d151a900-24d3-11e9-9569-1be043585c28.png">

Click on `>`. Request has correct value for `search_after`. Second page is displayed.

<img width="1677" alt="screen shot 2019-01-30 at 8 54 02 pm" src="https://user-images.githubusercontent.com/5143256/52031973-d151a900-24d3-11e9-8f72-745628edc034.png">

Response has paging info with both `search_after` and `search_before` set.

<img width="1677" alt="screen shot 2019-01-30 at 8 54 51 pm" src="https://user-images.githubusercontent.com/5143256/52031974-d151a900-24d3-11e9-9ba3-590bbb70b9e5.png">

Click on `<`. First page should be displayed but request parameter `search_before` is set to `search_after` value from previous response. This is wrong. To get to page _n-1_, you need to pass the `search_before` from page _n_ as request the parameter `search_before`.

<img width="1682" alt="screen shot 2019-01-30 at 8 55 27 pm" src="https://user-images.githubusercontent.com/5143256/52031975-d151a900-24d3-11e9-9cab-e55e8a7a5482.png">

The result is a page that starts with the last item from page 2.

<img width="1679" alt="screen shot 2019-01-30 at 8 55 46 pm" src="https://user-images.githubusercontent.com/5143256/52031976-d1ea3f80-24d3-11e9-802c-d38ac6de9996.png">

I'm looking forward to my pint of chilled Discretion Brewery Shimmer Pilsner.

┆Issue Number: HCAB-363

**Comment by NoopDog** [comment]
Thank you kind sir.  Yes we broke this just a day or so ago refactoring the pagination and were confused when testing by the lack of a default sort order.  I have just pushed up a fix for this to dev and will test this out there. Thanks for checking this as carefully as we should have. 

one chilled Discretion Brewery Shimmer Pilsner coming up.

**Comment by hannes-ucsc** [comment]
Verified fixed in `dev`
