### ISSUE TITLE
Update UI to use new paging API

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#45]
┆Issue Number: HCAB-29

**Comment by theathorn** [comment]
@NoopDog Status?

**Comment by NoopDog** [comment]
@caaespin @hannes-ucsc can you add the final on the paging api to this ticket or the link to the doc that has it? I can't seem to find the latest spec on this. Thanks!

**Comment by caaespin** [comment]
@NoopDog will document it shortly. In the meantime:

To move forward:
GET /repository/files?search_after=<search_after>&search_after_uid=<search_after_uid>

To move backwards
GET /repository/files?search_before=<search_before>&search_before_uid=<search_before_uid>

You get these values (search_after, search_after_uid, search_before, search_before_uid) from the backend itself on the pagination section.
