### ISSUE TITLE
M1.2: Provide availability monitoring and downtime alerting of data browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#451]
@morrisonnorman commented on [Fri Dec 07 2018](https://github.com/HumanCellAtlas/dcp/issues/231)

Relates to:
M1.2: Provide availability monitoring and downtime alerting of data browser.
[See DCP-General Availability Document](https://docs.google.com/document/d/14gVAMscd0d8KgWqOO11Y1kSp4ztVavZXA7zrtrhyiW0/edit#)

---

@morrisonnorman commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/231#issuecomment-446205823)

@theathorn Please can you comment on the status of this epic and link any open issues from your team board. Thanks!

---

@theathorn commented on [Tue Dec 11 2018](https://github.com/HumanCellAtlas/dcp/issues/231#issuecomment-446430123)

Issues linked.

┆Issue Number: HCAB-368

**Comment by sampierson** [comment]
Closing in favor of HumanCellAtlas/dcp#281 (health endpoints) and HumanCellAtlas/dcp#65 (alerting)
