### ISSUE TITLE
M3.2: Ensure good availability (95% uptime outside of planned maintenance) of the data browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#456]
@tburdett commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/dcp/issues/204)

┆Issue Number: HCAB-374

**Comment by sampierson** [comment]
I'm closing this epic tickets.  Availability is something you architect for up front, then measure in operation and correct as necessary.
