### ISSUE TITLE
M3.6: Ensure that the data browser recovers from downtime responsively (to meet 95% uptime objective, and to avoid more than 24 hours constant downtime)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#457]
@tburdett commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/dcp/issues/205)

┆Issue Number: HCAB-373

**Comment by sampierson** [comment]
I'm closing this epic tickets.  Availability is something you architect for up front, then measure in operation and correct as necessary.
