### ISSUE TITLE
M3.10: Ensure graceful failure, and report user friendly error messages, from the data browser if the data store or matrix service is not available when required

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#458]
@tburdett commented on [Tue Dec 04 2018](https://github.com/HumanCellAtlas/dcp/issues/214)

┆Issue Number: HCAB-376

**Comment by MillenniumFalconMechanic** [comment]
@frano-m Error page is located at `/error`. The error page displays a generic message if you hit that page directly, or a more detailed page if you are redirected there by an error in the app (eg [http://localhost:4200/projects/46c58e08-4518-4e45-acfe-bdab2434975dx](http://localhost:4200/projects/46c58e08-4518-4e45-acfe-bdab2434975dx)).
