### ISSUE TITLE
Track Progress on Resolving GreenBox  "Once Cell per Bundle" Problem for SmartSeq2 Pipeline Output. 

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#46]
One cell per bundle output for SmartSeq2 data will be challenging for the search, download and wrangling experience after the files are downloaded. We were planning on making downloads create a directory per bundle, this may not be practical. 

Greebox is looking for ways to group cells from a single sequencer run into a more compact format. 

We should track progress on this and make sure we understand the ramifications for orange box for any progress or lack of progress on this issue.

**Comment by theathorn** [comment]
Is this: https://docs.google.com/document/d/1T5YrLNCtv7_PbvNRiD-1FDT0a-rBFE_57nhTxY-PV8M/edit#heading=h.93bxgjvsvr4u

**Comment by theathorn** [comment]
@NoopDog please discuss with @hannes-ucsc

**Comment by theathorn** [comment]
This is the "large number of bundles" or "1 cell per bundle" issue.
Need to track what Ingest implements.
