### ISSUE TITLE
MVP for improved metadata access

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#464]
As a user I want a simpler, more accessible way to see the metadata associated with my faceted search query.
There are multiple issues with the current approach:
  - The JSON files provided by the cli download manifest command are hard to navigate.
  - There are many files whose inter-relationship is not clear.
  - The first-level directory names are bundle UUIDs, which have no meaning to the user.
Proposed improvements:
  - Add all indexed metadata fields to the file manifest
  - Show all available metadata fields in the Projects detail page
  - Generate a per-project metadata tsv file that can be downloaded directly from the Data Browser Projects tab

┆Issue Number: HCAB-381

**Comment by malloryfreeberg** [comment]
Completing my AI here:

As there are only two SmartSeq2 datasets in prod that were successfully analyzed by the pipelines, we should use these. They are pancreas6decades (project UUID: `e8642221-4c2c-4fd7-b926-a68bce363c88`) and neuron_diff (project UUID: `f8880be0-210c-4aa3-9348-f5a423e07421`).

 The fetal-maternal-interface dataset was recently pushed, but I'm not sure if it was all successfully analyzed. So we should not use this one.

pinging @simonjupp @mckinsel @NoopDog @hannes-ucsc who have the remaining AIs from Kevin's email. Please let me know if there is anything else I can help with.

Browser links:
pancreas: https://prod.data.humancellatlas.org/explore/projects/e8642221-4c2c-4fd7-b926-a68bce363c88
neurodiff: https://prod.data.humancellatlas.org/explore/projects/f8880be0-210c-4aa3-9348-f5a423e07421

**Comment by simonjupp** [comment]
The corresponding tsv files for each project are here https://github.com/HumanCellAtlas/hca_bundles_to_csv/tree/master/beta_2_examples
