### ISSUE TITLE
Obtain a Mapping of Bundle Files and Fields to Metadata Schema Fields and a Sample Bundle for any Pipeline Changes.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#47]
It would be very helpful for us to have a mapping from the Bundle JSON to the Metadata and also from the UI Screen elements to the Metadata so we can be sure:

1. We have all the metadata we need to meet the UI Requirements.
1. We know where to find that data in the bundles.

Green box team says they can help with this but we should help as well by setting the example of what we want, starting it out and getting folks to chime in and review.

┆Issue Number: HCAB-101

**Comment by theathorn** [comment]
Superseded by #116.
