### ISSUE TITLE
The project navigation doesn't work how I expected

### ISSUE THREAD

**Issue by lauraclarke** [DataBiosphere/data-browser#471]
I was trying to find INSDC/GEO accessions for a project (which isn't possible currently) but it also highlighted a couple of oddities with respect to how project navigation works from my perspective that I wanted to highlight and understand if the behaviour was correct

I have created a document with screenshots to highlight the issues here
https://docs.google.com/document/d/1EBpjT8-KCdi39lsOnkPkI2f5nr7pylKAd9bP0b6nAqY/edit?usp=sharing

the headline problems are

When going from the organ page to the project summary table to a project, the URL does not change to refer to the specific project you are on but remains listing https://prod.data.humancellatlas.org/explore/projects

The expected behaviour of the project-specific URL only seems to work when you go direct to explore from the front page and not via the organ diagram

when on a project summary page and selecting the select project link under the project title you are taken to the project summary table still listing all projects. The project I had chosen (Single cell transcriptome analysis of human pancreas reveals transcriptional signatures of ageing and somatic mutation patterns.) is a long way down this list so I only noticed it was selected at all when I pasted the screenshot into the above document.

thanks

┆Issue Number: HCAB-386

**Comment by NoopDog** [comment]
@lauraclarke I created #486 for the browser url not updating when you select a project.

The project list is intentionally does not restrict projects by the projectID. If it did, you could never select more than one project. The project list is selected by other facets, but not the projectID. 

I have created #487 for us to think about how we can improve the display of the selected project.

Cheers,
Dave

**Comment by NoopDog** [comment]
@theathorn  I have split this into two tickets so I think we can close this one.
