### ISSUE TITLE
Spike on electron.js for access to users file system

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#475]
┆Issue Number: HCAB-392

**Comment by theathorn** [comment]
Using the electron.js framework would allow the creation of a standalone client Data Browser app with direct access to the user's local file system thus allowing a more seamless file download experience.
Note: this sounds like a major undertaking and not every user would want an app installed on their system so we would probably still need to maintain the in-browser app.

**Comment by NoopDog** [comment]
no longer required
