### ISSUE TITLE
Clickable metadata field names on Project details page

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#476]
Link the metadata filed names (e.g. Organ) to the corresponding entry in the Metadata Dictionary.

┆Issue Number: HCAB-391

**Comment by NoopDog** [comment]
Rather than linking through we will implement the hover similar to the column definitions. The longer term we will read in the appropriate bits of the metadata description and display on hover or click in a way that does not take you off site and gives you a  choice to go off site to learn more.
