### ISSUE TITLE
Always show label on facet counts and make the label more prominent.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#489]
![Screen Shot 2019-02-26 at 10.49.05 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/2223e7df-0c62-4b6d-91bd-7d8b89f3b45a)

Its to hard to tell this is 1 project and not one file.

┆Issue Number: HCAB-399

**Comment by frano-m** [comment]
Now also added to mobile view...
