### ISSUE TITLE
Option to copy a manifest download URL

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#499]
From @matthewspeir:
It would be nice, if like the matrix service, there was an option to copy a file URL so that I could directly download the file to my server.

┆Issue Number: HCAB-406

**Comment by theathorn** [comment]
Signed URL with lifetime of 1-2 hours.

**Comment by NoopDog** [comment]
@hannes-ucsc what is the lifetime of this URL? I see @theathorn says 1-2 hours. Is that the requirement or how long these urls actually last?

So

1) How long do the current URLs last?
2) How long should they last. Seems 1-2h is kind of short. Would 24h be a problem?

We need to message this on the UI and we also need to be sure the URL lasts long enough to be useful.

Cheers,
D

**Comment by NoopDog** [comment]
Hi @hannes-ucsc please see the question above. How long do these urls last? Thanks, D

**Comment by NoopDog** [comment]
@matthewspeir as this is being in response to your feedback, how long do you feel the urls would need to last to be useful? These are signed S3 urls that expire after some time.  Cheers and Thanks, D

**Comment by matthewspeir** [comment]
Hmm. For myself, a few hours seems reasonable. I often was immediately downloading the manifest, though I can imagine people needing a little longer than that. Maybe 12hrs would be sufficient? 

Additionally, if it's easy and quick enough to regenerate a manifest download link, then I don't think having them expire quickly is an issue.

**Comment by hannes-ucsc** [comment]
> Hi @hannes-ucsc please see the question above. How long do these urls last? Thanks, D

[One day](https://github.com/DataBiosphere/azul/blob/c7d39b7b709384be5d3a211b4ee988ce065f7595/terraform/s3.tf.json.template.py#L17) at the moment.

Feel free to file a ticket requesting an increase of the expiration time if so desired.
