### ISSUE TITLE
Ensure secrets do not leak into source code

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/data-browser#501]
Verify that all developers are using Git Secrets.

https://github.com/awslabs/git-secrets
https://cloud.google.com/blog/products/gcp/help-keep-your-google-cloud-service-account-keys-safe
https://docs.google.com/document/d/1_7deaZd2XbjUetVJs8EsQg6JbW_MEX2iFgXpnR_PyYs/edit#heading=h.4f1e34ah25ia

┆Issue Number: HCAB-408

**Comment by NoopDog** [comment]
Dave:

CC-ONE:hca-data-browser dave$ git secrets --list
secrets.providers git secrets --aws-provider
secrets.patterns (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
secrets.patterns ("|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)("|')?\s*(:|=>|=)\s*("|')?[A-Za-z0-9/\+=]{40}("|')?
secrets.patterns ("|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?("|')?\s*(:|=>|=)\s*("|')?[0-9]{4}\-?[0-9]{4}\-?[0-9]{4}("|')?
secrets.allowed AKIAIOSFODNN7EXAMPLE
secrets.allowed wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
secrets.patterns [-]----BEGIN.PRIVATE.KEY-----
CC-ONE:hca-data-browser dave$ git status
On branch develop
nothing to commit, working tree clean
CC-ONE:hca-data-browser dave$

**Comment by MillenniumFalconMechanic** [comment]
Mim:

Mims-MacBook-Pro:data-browser mim$ git secrets --install
✓ Installed commit-msg hook to .git/hooks/commit-msg
✓ Installed pre-commit hook to .git/hooks/pre-commit
✓ Installed prepare-commit-msg hook to .git/hooks/prepare-commit-msg
Mims-MacBook-Pro:data-browser mim$ git secrets --register-aws
OK
Mims-MacBook-Pro:data-browser mim$ git secrets --add '[-]----BEGIN.PRIVATE.KEY-----'
Mims-MacBook-Pro:data-browser mim$ git secrets --list
secrets.providers git secrets --aws-provider
secrets.patterns (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
secrets.patterns ("|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)("|')?\s*(:|=>|=)\s*("|')?[A-Za-z0-9/\+=]{40}("|')?
secrets.patterns ("|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?("|')?\s*(:|=>|=)\s*("|')?[0-9]{4}\-?[0-9]{4}\-?[0-9]{4}("|')?
secrets.allowed AKIAIOSFODNN7EXAMPLE
secrets.allowed wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
secrets.patterns [-]----BEGIN.PRIVATE.KEY-----
Mims-MacBook-Pro:data-browser mim$

**Comment by frano-m** [comment]
Fran:

Frans-MacBook-Pro:data-browser franmcdade$ git secrets --install
✓ Installed commit-msg hook to .git/hooks/commit-msg
✓ Installed pre-commit hook to .git/hooks/pre-commit
✓ Installed prepare-commit-msg hook to .git/hooks/prepare-commit-msg
Frans-MacBook-Pro:data-browser franmcdade$ git secrets --register-aws
OK
Frans-MacBook-Pro:data-browser franmcdade$ git secrets --add ‘[-]----BEGIN.PRIVATE.KEY-----’
Frans-MacBook-Pro:data-browser franmcdade$ git secrets --list
secrets.providers git secrets --aws-provider
secrets.patterns (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
secrets.patterns ("|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)("|')?\s*(:|=>|=)\s*("|')?[A-Za-z0-9/\+=]{40}("|')?
secrets.patterns ("|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?("|')?\s*(:|=>|=)\s*("|')?[0-9]{4}\-?[0-9]{4}\-?[0-9]{4}("|')?
secrets.allowed AKIAIOSFODNN7EXAMPLE
secrets.allowed wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
secrets.patterns ‘[-]----BEGIN.PRIVATE.KEY-----’

**Comment by NoopDog** [comment]
Readme is updated with info about git-secrets

**Comment by hannes-ucsc** [comment]
Confirmed
