### ISSUE TITLE
It's impossible to generate a manifest for primary bundles only

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#502]
Even if you filter by `fastq` as the file format, copy-forward makes it so that the manifest mentions analysis bundles, too, since they also reference the primary input fastq files.

Other than eliminating copy-forward, I don's see a way to implement this. When the Azul indexer encounters an analysis bundle, the copy-forwarded files are not easily distinguishable from the ones that are unique to the analysis bundle. We'd have to apply some serious domain knowledge about the make-up of those bundles to do that. That's obviously brittle and not desirable.

The analysis bundle references the input bundle and we could try to load the input bundle and subtract its manifest from that of the analysis bundle, essentially undoing copy-forward.

┆Issue Number: HCAB-409

**Comment by hannes-ucsc** [comment]
Originally reported in https://github.com/HumanCellAtlas/data-browser/issues/498

**Comment by theathorn** [comment]
Dedupe is implemented in the CLI and reduces the impact of this issue.

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
