### ISSUE TITLE
A developer onboarding and offboarding process is followed

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/data-browser#503]
As a DCP stakeholder
I want an onboarding and off-boarding process to be followed for developers
so we maintain the integrity of the DCP source code when people leave the team.

We need to follow an onboarding and off-boarding process both:
- at the DCP level - that addresses things such as GitHub organization access and PaaS access
- and at the component/ team level, that addresses specific needs for that component

Onboarding and offboarding documents should be linked to from the [DCP Ops Wiki Home](https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home)

┆Issue Number: HCAB-410

**Comment by theathorn** [comment]
Obsolete DCP/1 issue - will open separate tickets for DCP/2 compliance work.
