### ISSUE TITLE
Review HCA repositories and verify that the list of readers/writers is following principle of least access

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/data-browser#507]
The HumanCellAtlas GitHub teams have been restructured.
To ease the transition to this structured world, everyone is currently in a team called "HCA" that has WRITE access to all repos.  We want to move away from this.

Each component team lead needs to audit the GitHub teams that have access to their repos.
Ensure only appropriate teams (e.g. CZI, UCSC, etc) have write access to your component's repos.
Ensure that you approve of any collaborators.
Then remove access from team HCA.

┆Issue Number: HCAB-413

**Comment by NoopDog** [comment]
Initial state

![Screen Shot 2019-06-05 at 7.47.26 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d8dd8728-cd38-4c48-ab66-98d50d0c958b)

**Comment by NoopDog** [comment]
Removed DNA Stack, HCA general 112 members
Added Clever Canary team.

![Screen Shot 2019-06-05 at 7.50.24 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/729d3afe-50ba-4d9d-81d9-cabf4dee717c)

**Comment by NoopDog** [comment]
Hannes will create Azul group and hand this ticket back to Dave.

**Comment by theathorn** [comment]
Hannes will create Azul team.

**Comment by NoopDog** [comment]
HCA Team is removed.
Orange Team is added.

@theathorn is there anything else that needs to be done here or can this be closed?

Cheers,
Dave

![Screen Shot 2019-06-06 at 11.38.35 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e566e896-960f-4487-b575-fe2a5d087dca)
