### ISSUE TITLE
Source code static & dynamic analysis

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/data-browser#508]
As a dcp developer
I want to run static analysis tools on my code
to help not ship code with gaping security holes in it.

There has been talk of running `trufflehog`, a tool to find embedded secrets in code before it is pushed.
The DevSecOps team needs to decide what static analysis tools to encourage/mandate.
Then we update the tickets in the component repos with these instructions.

┆Issue Number: HCAB-414

**Comment by sampierson** [comment]
This issue has now been unblocked.  It has been decided that 'Trufflehog' is the only analysis tool we will utilize at this time.  Please setup analysis of your repos using Trufflehog.  See commentary in https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/91 for more details and advice on how to do this.

**Comment by MillenniumFalconMechanic** [comment]
#916.
