### ISSUE TITLE
Follow Progress of ICA Bundle Correction and Re Import the New Bundles into the Data Browser

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#51]
https://docs.google.com/document/d/1VnCsOIK7U3DWmXdmmZpxbFlvVL8jd0NJU09cRt0kxpE/edit#heading=h.6wb53dnhnx6u

ICA spleen data is being re ingest bundled, submitted and run. We need to be sure this gets back into the index so we can support review how this now looks on our platform.

┆Issue Number: HCAB-31

**Comment by theathorn** [comment]
No longer relevant.
