### ISSUE TITLE
Manually deploying a new build in Gitlab requires permissions for project settings

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/data-browser#517]
┆Issue Number: HCAB-420

**Comment by achave11-ucsc** [comment]
After this is resolved, another walk through is required.

**Comment by NoopDog** [comment]
This is how gitlab works.

Additional permissions are required to manually refresh the synced repo. @theathorn lets close this in favor of doing a better job of syncing gitlab and github so the gitlab does not poll github every half hour but instead gets notified by github when a commit has happened. (in favor of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/653)
