### ISSUE TITLE
Tertiary portal development tutorial

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#519]
[I, @hannes-ucsc did not create this issue. @briandoconnor did on JIRA. Unito synced this using my credentials.]

I think Tim’s idea of having a Red Box tutorial on setting up a new site that consumes events from Blue and builds a web app from the events is a good one. Trevor, do you want to pick a date in, say, the fall?  Given your roadmap it seems like you would be ready to give a tutorial after you finish the following:

* GA 
* handoff is working (to Terra and generically to red boxes)
* for Data Store, when we have JMESPath on generic events working and listing endpoints so Red Boxes no longer need to use ElasticSearch (since that's likely to be deprecated in favor of the upcoming query service)

Trevor and Kevin, can you think of any dependencies before we can give a tutorial to red box devs on eventing and handoff?

What do you both think for a date/location?

┆Issue Number: HCAB-421

**Comment by NoopDog** [comment]
Not required
