### ISSUE TITLE
Half line "more data" indicator not working consistently

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#520]
Here its not working on the files tab. 
![Screen Shot 2019-03-13 at 4.21.49 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/37df0893-0d8c-44bd-b3b6-3bcc8b20f1b4)

Here it is working on the methods tab 
![Screen Shot 2019-03-13 at 4.23.40 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d14a7508-ea8d-4da4-b4e9-dd75e17b2ee8)

┆Issue Number: HCAB-422

**Comment by hannes-ucsc** [comment]
LGTM
