### ISSUE TITLE
Make accessions on project page linkable.  

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#539]
Geo Series
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSExxx

But see
https://identifiers.org/

<img width="670" alt="Screen Shot 2019-03-31 at 5 13 29 PM" src="https://user-images.githubusercontent.com/3239697/55297180-5b38c800-53d8-11e9-9048-a9b838779bb4.png">

mallory.freeberg [8:56 AM]
I would love to be able to encode in the schema the format for each field’s URL, replacing some part of it with the value provided by the contributor to get the right link
So like for ArrayExpression accession field:
```"array_express_accessions": {
            "description": "An ArrayExpress accession.",
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^E-....-.*$"
            },
            "example": "E-AAAA-00",
            "user_friendly": "ArrayExpress accession",
            "guidelines": "Enter accession if project has been archived. Accession must start with E-.",
            "url": "https://www.ebi.ac.uk/arrayexpress/experiments/VALUE/"
        },
```
Then we take what’s in the `url` field, replaces VALUE with the value in the metadata, and bingo: have the URL to link in the Browser (edited) 

The other option is to use identifiers.org. This service takes a prefix (in this case “arrayexpress”) and an identifier (in this case the value supplied by the contributor) and then looks up the URL to the archive. So instead of the above example, we might have:
```"array_express_accessions": {
            "description": "An ArrayExpress accession.",
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^E-....-.*$"
            },
            "example": "E-AAAA-00",
            "user_friendly": "ArrayExpress accession",
            "guidelines": "Enter accession if project has been archived. Accession must start with E-.",
            "identifier": "arrayexpress"
        },
```
Here’s the website: http://identifiers.org/

mallory.freeberg [12:14 PM]
Currently the metadata doesn't collect any other info besides the accession. Maybe we can start by just having the links, and then show to some beta or other testers and see if they want more description. I have a feeling linking to the accession and users being able to click right to it may be enough.

Dave Rogers [5:16 PM]
For starters is there a base url that can be used for each accession type?

mallory.freeberg [2:17 AM]
Yes, that’s what is used by identifiers.org. I think we could hard-code the base URL ourselves, but the identifiers service specifically handles this and will account for any changes in the URL. I think it might be safer to use identifiers.org, but perhaps we could discuss on a call or a public slack channel to get more input

**Comment by mshadbolt** [comment]
@NoopDog I did some investigating and have some URLs you can use if you want to resolve the accessions on the project page to URLs, I am providing how to do it with identifiers.org as it gives a nice compact url where you always know that the lead part is `https://identifiers.org/`, then there is an resource dependent prefix, i.e. `arrayexpress:`, then then the accession, e.g.
`https://identifiers.org/arrayexpress:E-MTAB-7407`.

All INSDC accessions can be resolved with the `ena.embl:` prefix. 

Also keep in mind this field can be an array at the project level so the start url will need to be appended to each accession where there are multiple values for a single project.

Each accession is listed below. Let me know if you need any further help with this.

**ArrayExpress:**
`https://identifiers.org/arrayexpress:` + `project.array_express_accessions`

All INSDC accessions can be resolved with the `ena.embl` prefix
`https://identifiers.org/ena.embl:` + `project.insdc_project_accessions` `https://identifiers.org/ena.embl:` + `project.insdc_study_accessions` 

Will also work with sample, run and experiment accessions i.e. `insdc_sample_accession` || `insdc_run_accessions` || `insdc_experiment`

**GEO series accessions**
`https://identifiers.org/geo:`+`project.geo_series_accessions`

**BioStudies accessions**
`https://identifiers.org/biostudies:` + `project.biostudies_accessions`

**BioSamples accessions**
`https://identifiers.org/biosample:` + `$BIOMATERIAL_TYPE.biomaterial_core.biosamples_accession`

**Comment by mshadbolt** [comment]
Also I see above that Mallory was suggesting that we incorporate these prefixes into the json schema, would that be preferable and make the linking easier to automate? If so I can look at making a ticket to this for the `metadata-schema` repo.

**Comment by lauraclarke** [comment]
Just wanted to add an extra request to this, as well as making them clickable, it probably makes sense to hide the undefined accessions, projects are highly unlikely all four accessions or a contributor might not supply all four accessions even if they exist, it would be better to hide the ones which are unspecified rather than show them as unspecified

**Comment by NoopDog** [comment]
Thanks @mshadbolt for the detail. @lauraclarke what would you prefer? Would you like  to add the links directly to the metadata or have us build them out in the browser? Looks fairly simple for us to build them out and could get that going fairly soon. Or, perhaps you would like to update the schema to give us the full url. Do you have a preference?

**Comment by lauraclarke** [comment]
I think having them built out in the browser is better as it gives us more flexibility

**Comment by NoopDog** [comment]
@mshadbolt @lauraclarke thanks for your help working this out. It's on prod.

Looks like there is at least one array express accession that does not resolve. (https://identifiers.org/arrayexpress:E-GEOD-84133) This is on https://data.humancellatlas.org/explore/projects/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc

Generally though it's working assuming the above is a data problem. 

Feel free to start a new ticket with anything that you see that might need to change. 
Cheers,
Dave

**Comment by lauraclarke** [comment]
Thanks for getting this implemented and letting us know @NoopDog this looks great. Sounds like when we start to make updates we need to remove this accession from this project entry as it isn't part of ArrayExpress for whatever reason
