### ISSUE TITLE
Add Estimated Cell Count to Table

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#54]
Estimated cell count is in the cell suspension biomaterial at the level of the Sequencing Run

Calculated cell count is in the analysis bundle for the input bundle.

What is the use case for cell count? Would be good to know how the cell count is used.

┆Issue Number: HCAB-105

**Comment by theathorn** [comment]
Of limited value and may be confusing. To be resolved by Jenn in conversation with Mallory, etc.

**Comment by theathorn** [comment]
Jenn says most labs collect this data and it's important to know.
