### ISSUE TITLE
Add link in the project view to get per-project level Matrix Service output

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-browser#546]
As an end user I would like to quickly be able to find and download the matrix output for a project so that I can run my analysis or visualization tools on the data.

Definition of Done:
Add link to the matrix output on the project view page (or provide a similar solution)
Note that the output does not exist for every project.

**Comment by kozbo** [comment]
note that this is not required for Beta 2 since users can always generate their own matrix files. So put this low on the priority list.  Also, the links provided by Calvin may not cover all the types of output that a user may want.

**Comment by theathorn** [comment]
The road-mapping label F has a deliverable of "Links on project pages to the matrix service for this project".
This can be achieved by providing a button on the Project Detail page which will call the Matrix Service with a manifest for that selected project only. There may be an optimization issue if the wait time for the matrix output is "too long", but that's a separate issue.

**Comment by theathorn** [comment]
@kozbo Hannes, Dave and I don't think this means linking to pre-canned matrix service output files anymore. We propose a button on the Project Details page to launch the matrix service for that project.

**Comment by kozbo** [comment]
Agreed

**Comment by theathorn** [comment]
Now planning for the Matrix Service to pre-generate per-project matrix output files.

**Comment by theathorn** [comment]
Requires https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/matrix-service/293

Location of each matrix ouput file is s3://url.data.humancellatlas.org/projects/$uuid.$extension

There will be one file for each possible extension (loom, csv, mtx, etc.) so we should enable the user to select their desired format.

**Comment by theathorn** [comment]
@NoopDog and @MillenniumFalconMechanic: @mckinsel states: "We have two of them in s3://hca-prepared-matrices".

I think these should be for:
  - project_uuid=cddab57b-6868-4be4-806f-395ed9dd635a (human pancreas)
  - project_uuid=2043c65a-1cf8-4828-a656-9e247d4e64f1 (125 day neuron diff)

**Comment by NoopDog** [comment]
What is the url http website for this bucket?
Also just confirming there is one for .loom, .csv, and .mtx

The s3 bucket needs to be setup as a website so we can download the data with http.

https://docs.aws.amazon.com/AmazonS3/latest/dev/HowDoIWebsiteConfiguration.html

**Comment by mckinsel** [comment]
Hey @NoopDog , I really really think it does not need to be configured that way. A link like this should work: https://hca-prepared-matrices.s3.amazonaws.com/Single+cell+transcriptome+analysis+of+human+pancreas/63910278-7763-4aeb-8b3a-15c0e199abd2.csv.zip

**Comment by NoopDog** [comment]
Ok great. Can you key the file by the project UUID only so we do not have to try to exactly match your url slug algorithm? Also, can you then set the file name in the content disposition header to force download and to set the file name to the slugged project short name using something like:

```
Content-Disposition: attachment; filename="filename.jpg"
```
Also for the metadata tsv downloads we also post pended the timestamp the tsv was created. This could be helpful for the matrix files as well.

This gives a file name like:

"Single cell transcriptome analysis of human pancreas 2019-05-22 16.52.tsv"

(I would have not used the spaces but thats how the TSV downloads any how)

**Comment by theathorn** [comment]
@NoopDog Two projects have now been copied to the Browser S3 bucket as per databiosphere/azul#1098 so you should be good to go on this ticket.

**Comment by NoopDog** [comment]
Ok great, as discussed on the call @GPelayo please update the links to the new ones with zip file removed for loom and the request id removed from the file name.

Thanks!
