### ISSUE TITLE
Add facet to select secondary analysis workflow type

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#548]
A project (or any user selection of facets) could contain secondary analysis files from different workflows (e.g. Optimus vs Cellranger vs SS2).
The user should be able to filter on any one of these before requesting the Matrix Service.

The metadata is available in analysis_protocol:

For Optimus  it looks like:

{
    "computational_method": "Optimus",
    "describedBy": "https://schema.integration.data.humancellatlas.org/type/protocol/analysis/8.0.7/analysis_protocol",
    "protocol_core": {
        "protocol_id": "optimus_v1.0.0"
    },
    "protocol_type": {
        "text": "analysis"
    },
    "schema_type": "protocol",
    "provenance": {
        "document_id": "4de28c2b-7be2-4ed8-bd07-cef99cd0a10b",
        "submission_date": "2019-04-09T22:45:00.828Z",
        "update_date": "2019-04-09T22:45:05.852Z"
    }
}

For cellranger it looks like:

{
    "computational_method": "10x",
    "describedBy": "https://schema.staging.data.humancellatlas.org/type/protocol/analysis/8.0.3/analysis_protocol",
    "protocol_core": {
        "protocol_id": "cellranger_v1.0.2"
    },
    "protocol_type": {
        "text": "analysis"
    },
    "schema_type": "protocol",
    "provenance": {
        "document_id": "71470c53-1b86-4e6d-9707-55a0f70745a4",
        "submission_date": "2019-02-14T19:15:10.720Z",
        "update_date": "2019-02-14T19:15:15.466Z"
    }
}

and for smartseq2:

{
    "computational_method": "SmartSeq2SingleCell",
    "describedBy": "http://schema.staging.data.humancellatlas.org/type/protocol/analysis/8.0.3/analysis_protocol",
    "protocol_core": {
        "protocol_id": "smartseq2_v2.1.0"
    },
    "protocol_type": {
        "text": "analysis"
    },
    "schema_type": "protocol",
    "provenance": {
        "document_id": "7a56f120-c055-4b63-acdf-8cc80c3555c1",
        "submission_date": "2018-10-24T23:35:47.320Z",
        "update_date": "2018-10-24T23:35:51.714Z"
    }
}

**Comment by theathorn** [comment]
Also need to fix the hover over text for "Request Expression Matrix" to not be specific to SS2.

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog How do we determine between not specified versus not applicable?
