### ISSUE TITLE
Make target molecule type an explicit facet

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#552]
Currently the target molecule type can be inferred from the experiment structure metadata but it is not explicit.  Consider making this an explicit field.

For example we could computed a value based on the imaging method as some methods target proteins and some transcripts. 

## Use Case

TODO we need a use case or two to support this

## Example fields and possible values.

TODO can what would we call this and what might be possible values.

**Comment by NoopDog** [comment]
@zperova can you add some detail to this and indicate some use cases and possible values for the "molecule type" field. 

@malloryfreeberg is there already work to define a metadata field for molecule type to the schema? If  so can you point us to it.

**Comment by malloryfreeberg** [comment]
@NoopDog what exactly do you mean by "target molecule"? 

For sequencing, we have the 'input_nucleic_acid_molecule` field (https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/protocol/sequencing/library_preparation_protocol.json#L54), which is required and so far has mostly been filled in with "polyA RNA". Is that what you mean by "target molecule"?

For imaging, it's a little more complex (@zperova can probably clarify).

**Comment by NoopDog** [comment]
Hi @zperova can you add some context to this. I tried to copy the info from our slack conversation but looks like I missed the important bit.

**Comment by zperova** [comment]
@malloryfreeberg @NoopDog this might not be very relevant at the moment but I was thinking of a way to distinguish the image-based transcriptomics experiments (first datasets we are starting to receive now) and protein experiments (that we do not yet have). There is no field in the imaging schema that is similar to what @malloryfreeberg mentions, maybe we should consider adding such a field, and this will solve the problem.

**Comment by NoopDog** [comment]
Obsolete
