### ISSUE TITLE
Download of metadata TSV file per sample

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#559]
From Project Leads Q2 roadmap:
"Establish a first iteration of metadata accessible for download and demonstrate downloading that metadata through the data browser for a project and additionally for a sample".

For Q2: Provide documentation for user to grep the per-project metadata.tsv file for the required sample.
For Q3: Provide a "download sample metadata" link on the Samples tab, similar to the "download project metadata" link on the Project Details page.

**Comment by NoopDog** [comment]
Obsolete
