### ISSUE TITLE
Add subgraphs tab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#561]
Add a bundles tab - useful for internal and external users.

**Comment by theathorn** [comment]
@NoopDog Could we implement this as a hidden tab at a well know URL such as https://prod.data.humancellatlas.org/explore/bundles?

**Comment by theathorn** [comment]
@hannes-ucsc votes to implement now as a regular tab.

**Comment by matthewspeir** [comment]
It was my understanding that bundles were supposed to be a way of internally structuring data that users wouldn't have to know, think about, or understand. Have sentiments around that changed recently and we've decided to start exposing bundles to users? (I realize we already sort of do this through downloads that are separated by bundle id, but even that I'm not really a huge fan of.) If we do end up adding this tab, we need to add documentation to the data portal that describes what bundles are, how they're structured, and maybe why they're structured that way.

@theathorn so, I wouldn't say I object to having a bundles tab, I guess I'm just not understanding what the use of such a tab would be to the end-user? Like I said before, it's possible that I've also misunderstood current sentiment about exposing bundles to users and our expectations for users understanding them.

**Comment by adriennes** [comment]
Second everything that @matthewspeir said.  What is the user value of this tab?

**Comment by theathorn** [comment]
Bundles are exposed by the Data Store API and are very obvious to any non-superficial user.
This tab would also be useful to devs and data operations personnel in tracking which bundles belong to which projects.
@hannes-ucsc can elaborate further.

**Comment by adriennes** [comment]
Based on our past user feedback, I strongly recommend that we don't surface bundles more strongly in the UI.  Perhaps we can add documentation in the API section to address questions about bundles, and it might make sense to have a dev site view that includes a bundles tab for internal users - but I think this will add unnecessary complexity to average data consumers.  

To make sure we're all talking about the same thing, though, it might be helpful to do a quick mock-up of what/where you're thinking of adding this.

**Comment by zperova** [comment]
I don't think bundles should be exposed to users. To aid the devs and data operations personnel in tracking, we need to have a dev site view (or enhance the existing tracker). The Browser is a user-facing tool and should not have anything that is meant for inner-workings of our system.

**Comment by lauraclarke** [comment]
Just want to add a +11 to Matt, Zina and Adrienne's comments.

**Comment by gabsie** [comment]
I think this calls for inserting user stories and clear user problems when writing a request for a feature or a ticket. There's obviously a problem/need that @hannes-ucsc is trying to address, but maybe it is for a persona or context, which are not priorities specifically for the browser.

The world would probably be in a much less contentious state if everyone just started with a problem you're trying to solve. Instead of jumping in with 'NO-s', everyone else would instead jump in with ideas on how to solve it in a way fitting the problem :)

**Comment by claymfischer** [comment]
I agree with Matthew, Adrienne, Zina, Laura and Gabby's comments.

**Comment by matthewspeir** [comment]
Excellent point @gabsie. As I said, I'm not outright opposed to adding a bundles tab, just trying to understand why. 

Based on
>Bundles are exposed by the Data Store API and are very obvious to any non-superficial user.

It seems to me that the core problem is exposing bundles to users. I'm not sure that even wider exposure is going to help reduce that confusion. I would argue that if we don't expose bundles to users, then we don't have to worry about them not understanding them. 

As an alternative, I would propose that we expose files, not bundles, through the DSS API. If we show files, then we don't have to add a new tab and we don't have to create complex documentation around bundles to help people understand them. We already support file browsing in the Data Browser, and the files listed are fairly standard file formats (e.g. fastq or BAM) that we can either quickly document ourselves or point to external documentation with more detail. As mentioned by others, having a dev site where we have a bundles tab would be a fair compromise to support DCP developers, but not burden external users with understanding bundles. 

I'm sure showing files to users in the DSS API has its own issues that I'm not thinking of at the moment. Or maybe there are technical reasons as to why it can't be done. I'd be curious to know if this is something the DSS API team have already discussed. In any case, I'm not tied to any of these things, I'm just trying to think of alternatives to a bundles tab.

**Comment by lauraclarke** [comment]
Thanks @matthewspeir  this is useful thinking

It would be useful to know what goal @hannes-ucsc and @theathorn have in mind by exposing bundles, what is the task doing this will enable, is there an alternative solution?

**Comment by hannes-ucsc** [comment]
Bundles are not an implementation detail of the DCP. They are an integral part of the DCP data model. Without a bundle manifest, one cannot resolve the entity references in `links.json` and therefore construct experimental graph. Bundles are exposed to users of the CLI and the DSS REST API. Until we remove bundles from the DCP data model, bundles need to be represented in the data browser. The more we attempt to hide them, the more users will be confused when the eventually encounter them, and they will when they use the CLI or the DSS rest API.

**Comment by lauraclarke** [comment]
What is the scientific goal of the user you are expecting to use this tab?
What scientific concept does that tab represent?

**Comment by hannes-ucsc** [comment]
To deserialize the experimental metadata graph from the JSON files in the data store, a user needs to be aware of the bundles in the data store. If users need to be aware of bundles, bundles should be exposed in the Data Browser. Even if being able to deserialize the metadata graph is not a scientific goal, surely it is a use case for the DCP. The Data Browser has a general audience, not just scientists.

**Comment by NoopDog** [comment]
Bundles have been sunset. - closing

**Comment by theathorn** [comment]
Superseded by DCP/2 - closing.

**Comment by theathorn** [comment]
May still be relevant with regards to showing subgraphs, but lower priority for now.

**Comment by MillenniumFalconMechanic** [comment]
Hi @theathorn, is there an Azul blocker for this?

**Comment by theathorn** [comment]
Azul work is complete.
This might help as an internal debugging tool, by providing a "hidden" tab, or similar.

**Comment by hannes-ucsc** [comment]
I prefer it not to be hidden. Subgraphs are an important first-class citizen.

**Comment by MillenniumFalconMechanic** [comment]
Not required at the moment.

**Comment by hannes-ucsc** [comment]
I'd like to discuss this with @theathorn and Clever Canary at the next product team meeting.

**Comment by theathorn** [comment]
We still implement this as a SubGraphs tab. Q: visible to everyone or developers only? A: Start with developers only and demo to stakeholders for feedback.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
