### ISSUE TITLE
Inconsistent counts/sizes between browser view and file manifest view

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#567]
I was looking at the Census of Immune Cells project in the prod browser, and noticed some inconsistencies in the display of file counts and sizes between the browser view and the file manifest view (images below).

1. The browser view indicates 762 fastq files (this is correct), but the file manifest view indicates only 378 fastq.gz files with a total size of ~588GB. The 762 fastq files actually are ~1.2TB.

1. The browser view indicates 254 BAM files (this is correct), but the file manifest view indicates only 126 BAMs. 

1. The browser indicates there are 16 donors in the project (this is correct), but the file manifest view indicates only 8 donors. 

It seems that maybe about half of the data is not being represented in the file manifest view?

### browser view

![Screen Shot 2019-04-25 at 12 10 58](https://user-images.githubusercontent.com/10993501/56732007-ee54eb80-6753-11e9-8cb2-21342344b12d.png)

### file manifest view

![Screen Shot 2019-04-25 at 12 10 54](https://user-images.githubusercontent.com/10993501/56732012-f3b23600-6753-11e9-94cd-868f864be189.png)

**Comment by theathorn** [comment]
@malloryfreeberg It seems like you probably had an additional filter (beyond the project selection) applied? The counts on the project don't change according to the filter but the manifest should show the additional filter(s).

**Comment by malloryfreeberg** [comment]
I see. So if I select just the Census of Immune Cells project:

![Screen Shot 2019-04-30 at 11 21 28](https://user-images.githubusercontent.com/10993501/56955760-2b492580-6b3a-11e9-9267-ae8b73ff7d3c.png)

It's not obvious to me that I will only get a manifest for that project. The Request File Manifest button is under a line that groups it with the display below and not with the filter list under the search bar, which is I guess what made me think I needed to filter down what was in the display below the bar.

So, I selected one of the organs in the Census of Immune Cells project ("immune system"):

![Screen Shot 2019-04-30 at 11 20 07](https://user-images.githubusercontent.com/10993501/56955860-6fd4c100-6b3a-11e9-841b-7c05dbe74616.png)

which must be what limited what goes into the file manifest as about half the project is immune cells.

This may be a minor nit in the usability of the Request File Manifest button, but it wasn't obvious to me that the button is based on the filter list.

**Comment by NoopDog** [comment]
First problem is that the list of filters was accidentally removed from the manifest download pop up. We are adding that back. 

Second issue, that its not clear that the export manifest is over the selected files, we are making major changes to this section that we will review with the team this sprint.

**Comment by malloryfreeberg** [comment]
@NoopDog Thanks for letting me know there are already solutions planned.

I'm happy for this ticket to be closed if there are other tickets tracking the work.
