### ISSUE TITLE
Check that join criteria between manifest, matrix output, and TSV converter works

### ISSUE THREAD

**Issue by mweiden** [DataBiosphere/data-browser#568]
## User Story

* As a user of the data browser,
* I want to be able to join rows in the manifest, metadata TSV, and Matrix Service output,
* so that I can make inferences across metadata outputs.

## Acceptance Criteria

When a user downloads a manifest, a matrix, and the metadata for a given project we need to make sure a researcher can join between all three files successfully. Test this manually.

**Comment by theathorn** [comment]
This may already exist but at a minimum needs testing to confirm.

**Comment by GPelayo** [comment]
In order for these files to have an accurate join between these three files, all of these files need to have columns/fields representing the `bundle_uuid`, `bundle_version`, `file_uuid`, and `file_version`. The manifest contains all four of these fields and there's already ticket (https://github.com/DataBiosphere/azul/issues/945) for adding these fields to the metadata tsv.  For the matrix output files, these fields need to be added the cell metadata file.

**Comment by mckinsel** [comment]
The notion of `file_uuid` and `file_version` does not make sense for the matrix service. Information about a cell can be spread across multiple files.

**Comment by hannes-ucsc** [comment]
Not many files though, right? Could we use the `||` joiner to combine all source files into a single column value? At least that's how the full metadata TSV handles these cardinality issues.

**Comment by theathorn** [comment]
Closing in favor of humancellatlas/matrix-service#291.

**Comment by hannes-ucsc** [comment]
To clarify, all the Azul outputs i.e., manifest and metadata TSVs are joinable. What the matrix service does is beyond our control but we opened HumanCellAtlas/matrix-service#291 to propose that they add bundle and file references to their output.
