### ISSUE TITLE
Add Cell Ranger pipeline files to matrix counts on the projects page

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#571]
Currently, the Cell Ranger output files are not listed in the project page outputs. We can add these counts now that Cell Ranger is here to stay to help indicate that this data is available.

![Screen Shot 2019-04-26 at 9.51.55 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/847a4ea8-0b8f-4271-8687-a1e20e3786fd)

This data is available in the project hits file summary but  is not currently displayed.

**Comment by NoopDog** [comment]
@kbergin for the cell ranger 10x data what files count as "matrix" files besides the h5 and mtx files? If we were going to count "matrix" files for 10x cell ranger pipelines which files would we count? Thanks, D

**Comment by kbergin** [comment]
@barkasn @kishorikonwar

**Comment by theathorn** [comment]
No longer required as per https://docs.google.com/document/d/1ZtuDWQOj7AQ3q8EAz2YGwZzVVcQhaLNVG4v3Umtg9qQ/edit?ts=5cdeef35.
In the future we hope that any new pipelines will set the "matrix" file format appropriately.
