### ISSUE TITLE
Download Manifest Crashes for Large File Sets

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#58]

**Comment by theathorn** [comment]
Trevor Heathorn [5:06 PM]
Does manifest file contain file uuids or bundle uuids (+ timestamps) or both?

caaespin [5:07 PM]
I think it should be at a minimum a list of file uuids. But brian was saying it should have more stuff to allow people to open it in excel and stuff like that

So it should be made so it can pull out whatever fields from each elasticsearch result

**Comment by hannes-ucsc** [comment]
We think we saw that yesterday again.
