### ISSUE TITLE
Make "data.humancellatlas.org" the user facing URL

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#621]
# URL Update Goals

1. preview.data.humancellatlas.com goes to the preview site.
1. data.humancellatlas.com goes to the prod data portal.
1. data.humancellatlas.com/explore goes to the prod data browser.
1. prod.data.humancellatlas.com/* redirects to data.humancellatlas.com/*
1. HTTPS works for all sites.
1. HTTP redirects to HTTPS for all sites.

# URL Update Plan

## Data Portal

- [ ] Update .gitlab-ci.prod-env.yml 
- export GATSBY_EXPLORE_URL=https://prod.data.humancellatlas.org/explore/ to
- export GATSBY_EXPLORE_URL=https:/data.humancellatlas.org/explore/

## Data Browser
- [ ] Update environment.prod.ts

  portalURL: "https://prod.data.humancellatlas.org", to 
  portalURL: "https://data.humancellatlas.org", 

  projectMetaURL: "https://prod.data.humancellatlas.org", to
  projectMetaURL: "https://data.humancellatlas.org",

## CloudFront
- [ ] https://console.aws.amazon.com/cloudfront/home?region=us-west-1#distribution-settings:E3QDNPF7XH7O7G

Change alternate domain name (CNAMEs) from  prod.data.humancellatlas.org to data.humancellatlas.org

## Preview Site

- [ ]  Update metadata spreadsheet and project data file manifest link for all 3 projects

## Google Analytics
https://analytics.google.com/analytics/web/#/a116656225w189346193p185740629/admin/property/settings

- [ ]  Update property name and default url

 ## Google Tag Manager
No change required

## Route 53
1) Update data.humancellatlas.org route 53 record to alias to cloudfront:  https://console.aws.amazon.com/cloudfront/home?region=us-west-1#distribution-settings:E3QDNPF7XH7O7G

2) update prod.data.humancellatlas.org route 53 record to redirect A – IPv4 address to data.humancellatlas.org

**Comment by theathorn** [comment]
Trevor Heathorn [Today at 11:29 AM]
Parth Shah Regarding our July transition to just "data.humancellatlas.org" for production, are you the right person to assist with DNS redirecting "prod.data." and "preview.data." to just "data."?

Parth Shah  [3 hours ago]
Sure happy to help

**Comment by theathorn** [comment]
@jahilton is coordinating this effort. Don't do anything until you get the go ahead..

**Comment by theathorn** [comment]
Note: we will only redirect "prod.data" to "data" for now and leave "preview.data" as is.

**Comment by jahilton** [comment]
We have the Green Light here

**Comment by NoopDog** [comment]
@parthshahva I have updated a plan for this for the data portal, browser, preview site and google analytics. Can you provide a plan for the Route 53 update?

Also, @parthshahva when do you want to do this? I can do later this evening if that suits you. 

@jahilton Yes there will be about a half our down time once we start updating the apps and config.

@hannes-ucsc I believe there is nothing for Azul to do here. Is that your interpretation?

**Comment by parthshahva** [comment]
route 53 steps updated

**Comment by NoopDog** [comment]
Thanks @parthshahva when do you want to do this?

**Comment by parthshahva** [comment]
Discussed on slack. We are starting this now
