### ISSUE TITLE
Redundant requests to the /health endpoint

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#637]
One page load, three requests:

<img width="774" alt="Screen Shot 2019-05-16 at 12 42 52 PM" src="https://user-images.githubusercontent.com/5143256/57882318-46719180-77d8-11e9-83b2-041d4b7670e1.png">

Probably only when the /health returns something other than 200. Are you making retries?

**Comment by NoopDog** [comment]
Looks like this is only happening when we get a non 200 response.
Will take a look at why the 503 causes the extra hit. 

<img width="551" alt="Screen Shot 2019-05-16 at 12 52 42 PM" src="https://user-images.githubusercontent.com/3239697/57882832-8422ea00-77d9-11e9-8eb7-f5c8d05aa28e.png">

**Comment by MillenniumFalconMechanic** [comment]
We are retrying twice if we receive an error response. I can take out the retry for the `/health` end point, if you would prefer.

**Comment by NoopDog** [comment]
Hi @hannes-ucsc checkout the question above. Are you requesting that we remove the retry on the health check endpoint?

Cheers, 
D

**Comment by hannes-ucsc** [comment]
> Are you requesting that we remove the retry on the health check endpoint?

Yes. There is no point in retrying the health check endpoint and it is actually expensive.

**Comment by NoopDog** [comment]
The update for this has been deployed through to staging.  Let us know if this looks ok to close.

**Comment by hannes-ucsc** [comment]
Fixed. Took indexer down and only saw one 503 request:

<img width="1676" alt="Screen Shot 2019-05-22 at 7 50 29 PM" src="https://user-images.githubusercontent.com/5143256/58222447-ed6b9700-7cca-11e9-804a-54e206a16f18.png">
