### ISSUE TITLE
Imaging project is displayed with organ `Unspecified`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#640]
<img width="549" alt="Screen Shot 2019-05-16 at 2 53 14 PM" src="https://user-images.githubusercontent.com/5143256/57889720-64e08880-77ea-11e9-8dda-0c54ee72cadc.png">

The value in the Organ column seems to be taken from `hits[*].projectSummary.organSummaries` which is not correct because that element of the response is backed by cell suspensions and the `organ`/`modelOrgan` found in samples associated with them. Imaging data sets have no cell suspensions. The correct algorithm is to use `hits[*].samples[0].(organ|modelOrgan)` because it works for imaging and non-imaging datasets.

Furthermore, `hits[*].projectSummary.organSummaries` will go away (https://github.com/DataBiosphere/azul/issues/1021).

**Comment by NoopDog** [comment]
Hi @hannes-ucsc this is fixed on dev. 

I have updated the source for  the organ and organPart fields on the project,  sample, and files tab.

We currently do not display modelOrgan on the UI but this is in progress:
https://github.com/HumanCellAtlas/data-browser/issues/586

I also crated a separate ticket to update the project details page for the organ and organPart
https://github.com/HumanCellAtlas/data-browser/issues/643

Let us know if you feel we can close this

Cheers and thanks,
D

**Comment by hannes-ucsc** [comment]
Appears to be fixed:

<img width="538" alt="Screen Shot 2019-05-20 at 8 25 02 PM" src="https://user-images.githubusercontent.com/5143256/58066285-794fb880-7b3d-11e9-9535-9d9bad61c20a.png">
