### ISSUE TITLE
Project counts do not filter according to the query.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/data-browser#646]
![Screenshot from 2019-05-17 11-49-49](https://user-images.githubusercontent.com/20567496/57957719-244c4200-78b2-11e9-9ee6-3ab5a4f60b7b.png)

Was just browsing `prod` and it looks like there is some dissonance between the number of fastqs shown (~200k) and total files (~60k).

Talking with Dave, he suggested it’s because the project numbers are not filtered, but if they're filtered by pancreas it should match.

**Comment by theathorn** [comment]
The current design is that the counts under the "Data" columns are per-project and don't change with the selected facets, unlike the summary counts at the top.

**Comment by DailyDreaming** [comment]
@theathorn It's a bit confusing.

**Comment by hannes-ucsc** [comment]
> It's a bit confusing.

This behavior is consistent across the UI.  Nowhere in the UI do the values displayed in the cells of the  main result table change in response to the filters. The filters affect which rows are displayed not whats in each row. I could see a use case for adjusting the cell values to the filters. But I could also see a use case for not adjusting them: For example, a user may want to see how many BAMs are in projects that also contains fastqs.  If we were to display the # of BAMs as 0 when the user selects `fastq` in the file type facet, that use case would not be possible, or harder to achieve (one  would  have to fixate on each  project and deselect the file type facet again.
