### ISSUE TITLE
Refactor the indexer as an extensible framework for other projects. 

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#65]
As a developer I would like to have a clear framework I can start off to easily implement my own specialty indexers, add facets to it, and deploy for my own project. 

DOD: We have a framework that can be used to implement other project indexers and specify their own particular faceted search. At deployment time, I can specify via an environmental variable or a flag which project indexer to use. Flag takes precedence over environmental variable. 

Things to consider: the indexer framework should be able to run various indexers in a single run. (e.g. For HCA, the indexer will run the indexing operation of the `file_indexer, sample_indexer, and project_indexer`). Give me an interface I should adhere to so that the indexer can call my specialty indexers. 

So we have `bundle -> {indexer} -> {transformer_modules} -> [files_es_documents, samples_es_documents, ..etc] ->goes back to the {indexer} -> the indexer then reads if there is any existing document in ElasticSearch that matches the criteria, and updates the document as appropriate and updates the Document in ElasticSearch`. Make sure you implement optimistic locking (see  https://www.elastic.co/blog/elasticsearch-versioning-support), retry the merging of old and new again. 

NOTE: Remember to discuss how to deal with a bundle changing donor, and how to update the remaining indexers as appropriate.

┆Issue Number: HCAB-114

**Comment by kozbo** [comment]
UPDATE: convert to Chalice compatible framework, double check with Carlos today.
