### ISSUE TITLE
File download menu is selection is confusing

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/data-browser#651]
When you get the file download menu, none of the file types are selected.  One would expect a manifest for this would only get the metadata or maybe do nothing at all.

Instead, selecting nothing means everything and selecting everything means everything.

I would suggest it defaults to everything selected and have clear-all and select-all buttons, 
along with being able to select/deselect individual files.

Selecting no files would either get only the metadata or produce an error.

**Comment by NoopDog** [comment]
We reviewed this with the HCA UX team in a "Design Crit" session and have a few ideas to address. Mocks will be out in the next few weeks referencing the "checkbox problem".

Tracking this in 
https://github.com/HumanCellAtlas/data-browser/issues/691
