### ISSUE TITLE
Handle /projects and /summary API updates due to imaging bundle support - cellCountSummaries and organTypes

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/data-browser#656]
Changes due to https://github.com/DataBiosphere/azul/issues/885
- New facet `assayType`
- Summary field `organSummaries` renamed to `cellCountSummaries`
- Summary field `organCount` removed
- New summary field `organTypes` (value is a list of unique organ values used in the cell suspension(s))

**Comment by NoopDog** [comment]
Hi @danielsotirhos regarding:

> Summary field organSummaries renamed to cellCountSummaries
> Summary field organCount removed
> New summary field organTypes (value is a list of unique organ values used in the cell suspension(s))

Is this a change just on the /summary API or are there any other changes on the /projects /samples /files APIs?

Cheers,
Dave

**Comment by NoopDog** [comment]
Created a separate ticket https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/659 for the Assay Type facet. Adding assay type wont block Azul 885

**Comment by dsotirho-ucsc** [comment]
Hi @NoopDog ,

> Is this a change just on the /summary API or are there any other changes on the /projects /samples /files APIs?
> 

This affects:
- `/summary` response
- `/projects` response (Specifically the `projectSummary` under each "hit")

Cheers!

**Comment by NoopDog** [comment]
Ok then!
Thanks @danielsotirhos

**Comment by NoopDog** [comment]
HI @danielsotirhos a few questions regarding 

cellCountSummaries and
organTypes 

1) Are they both specific to cellSuspension or is only organTypes specific to cell suspension? (your notes above say that (organTypes value is a list of unique organ values used in the cell suspension(s))

2) Do we have estimated cell counts for the imaging studies?

For context we are trying to get just a list of organs and cell counts for that organ regardless of if the count came from a  cell suspension or an imaging study.

**Comment by dsotirho-ucsc** [comment]
`organTypes` is compiled using sample's effective_organ (either the 'organ' value or 'model_organ' value depending on the type of sample (eg. specimen, cell_line, or organoid)

`cellCountSummaries` is compiled using the inherited organ(s) and cell count from the cell suspension.

Imaging bundles don't have cell counts. (Cell counts are a property from cell suspensions, and imaging bundles don't have cell suspensions)

**Comment by NoopDog** [comment]
Ok so use organTypes.length for count of organs.  Note that this will include model organ in the organ count.

**Comment by NoopDog** [comment]
This is looking good on dev. We are ready to deploy to integration. 
Cheers,
Dave
