### ISSUE TITLE
Add "maintenance mode" banner to prod during data re-ingestion period

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#663]
In "prod" environment only, add a non-dismissable banner to the Data Browser stating "Warning: in maintenance mode for data re-ingestion" or similar.

We will remove this banner once re-ingestion, including Secondary Analysis files, matrix database, per-project matrix files, per-project metadata tsv files, and Azul indexing have been verified complete.

**Comment by theathorn** [comment]
@adriennes Is the suggested warning text OK? Need an answer today...

**Comment by adriennes** [comment]
@theathorn  - works for me.  It is temporary, so I think it's fine

**Comment by NoopDog** [comment]
@frano-m lets discuss this one and prioritize for first thing Monday. Cheers, D
