### ISSUE TITLE
Switch from /health to /health/progress

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#678]
Now that DataBiosphere/azul#1037 has landed with the fix for DataBiosphere/azul#971, could the Data Browser please switch from `/health` to `/health/progress`? The progress info is still part of `/health` (in fact, we made it so that key `foo` in the `/health` response is also reachable as `/health/foo`) but `/health` is relatively expensive now, so much so that we don't want to invoke it on every page load. `/health` should only be invoked by Route 53 as part of the periodic health check.

**Comment by hannes-ucsc** [comment]
DataBiosphere/azul#1037 actually broke backwards compatibility because it moved the `unindexed_bundles` and `unindexed_documents` to `progress.unindexed_bundles` and `progress.unindexed_documents`. Because of this, the data browser does not display the "reindexing in progress" banner anymore.

**Comment by NoopDog** [comment]
Hi @hannes-ucsc the update for this is deployed to dev, integration and staging.

I am seeing a 5-10 second response time for the /health/progress endpoint is this expected?

![Screen Shot 2019-06-12 at 8.15.44 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/e5fdf7c3-b085-4d5d-8076-1297984ca2ab)

**Comment by theathorn** [comment]
@GPelayo Is this 5-10s response time expected?

**Comment by hannes-ucsc** [comment]
@NoopDog 

> I am seeing a 5-10 second response time for the /health/progress endpoint is this expected?

Nope. See https://github.com/DataBiosphere/azul/issues/1084 for details.

**Comment by hannes-ucsc** [comment]
Not working in dev. There is a reindexing going on as I write this but no banner is displayed.

<img width="1381" alt="Screen Shot 2019-06-14 at 10 44 12 AM" src="https://user-images.githubusercontent.com/5143256/59492418-c9b8ee00-8e3d-11e9-9eb2-353d8d777616.png">


You may have missed [my earlier comment](https://github.com/HumanCellAtlas/data-browser/issues/678#issuecomment-501224891).

**Comment by NoopDog** [comment]
@MillenniumFalconMechanic there is still an issue with this one. See Hannes comment above.
