### ISSUE TITLE
Organ column for certain projects is incorrectly displayed as Unspecified

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#679]
For motivation see, https://github.com/HumanCellAtlas/data-browser/issues/674#issuecomment-500479452.

Now that PR https://github.com/DataBiosphere/azul/pull/1063 for https://github.com/DataBiosphere/azul/pull/1022 has landed on `dev`, one should use `hits.samples.effectiveOrgan`

For an immediate solution that works in all deployments,  one could alternatively use `hits.samples.modelOrgan` or, if that's not present fall back to `.organ`.

**Comment by NoopDog** [comment]
@hannes-ucsc I think this is covered by #586 where we specify creating an Organ/Effective Organ   column and displaying only the organ value for specimens and the Organ/Effective Organ value for Organoids and cell lines. 

I will close this and please feel free to comment over on https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-browser/586.
