### ISSUE TITLE
Create New File Indexer

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/data-browser#68]
Create a file indexer adhering to the new ElasticSearch mapping. 

DOD: The indexer creates an ElasticSearch document for each relevant file in the bundle, adhering to the new format (https://docs.google.com/document/d/1OWuPZHQnAGdGK8koJdLbnIZ6TT7F6WonZ6cEKfxsR8U/edit). Associates the samples, processes and protocols to each file respectively. Unit tests included.

┆Issue Number: HCAB-115

**Comment by theathorn** [comment]
A day or two left...

**Comment by theathorn** [comment]
Target complete 5/30.
