### ISSUE TITLE
Display metadata graph for a single bundle

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#687]
Initially we could do this on the bundles aka transactions aka assays tab. Add a button to each row. Clicking on the button could display a pop-up with a graphical rendering of the experimental graph in that bundle.

**Comment by hannes-ucsc** [comment]
Kudos to @tburdett for the idea.

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
