### ISSUE TITLE
Analysis for indicating projects with incomplete processing

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#688]
In the UI indicate whether or not a project has incomplete processing:
  - Secondary analysis bundle count does not match primary bundle count
  - Matrix Service has not processed this version of the project (what about updates?)
  - Azul index is out-of-date
  - Metadata tsv file has not been generated

Suggest using https://tracker.data.humancellatlas.org/ to get some of these statistics.
Incomplete project could be indicated by a different color of project title

**Comment by theathorn** [comment]
Also flag any project_uuid that appears in the Tracker but not in the Azul index.

**Comment by theathorn** [comment]
The Matrix Service interaction is covered by separate tickets.

Need more UX input to demonstrate this has worth while business value for the other components.

Open question as to whether the tracker API has sufficient scalability and robustness  and will be supported in the production environment.

Moving to Product Backlog for further consideration.

**Comment by NoopDog** [comment]
analysis concluded not to do this.
