### ISSUE TITLE
Get Data: Project Detail Page Updates Two Column Layout

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#689]
- [ ]  Updated layout
- [ ] Add File Counts

**Comment by NoopDog** [comment]
@fran, The update to the project detail page is deployed to dev and the PR merged.
Now that this is in hand I feel we need to refine(slightly) the requirements on how this works responsively.


On 13 and 15 inch MPB I feel this should fill the screen. (I think it might already on 13 inch but on 15 inch since the two columns are left justified there is a gap on the right.

On larger screens there is a large gap on the right.

I am proposing to center align the 2 column layout, just like we did the single column layout to avoid having the spacing  on the right.

For the 15'' we can maybe make the columns a bit wider and also the space between them wider to match, or if this looks silly, I guess just center it like the extra large screens and don't fill the page.

For we can probably keep 2 column in  horizontal tablet.

For vertical table and less we should stack as we do now.

Do you think the above will work out?

Cheers,
Dave

**Comment by frano-m** [comment]
@dave, I've got the columns wrapping to 3x for screens >1920
Underneath "File Counts" will be two more sections (currently not shown on dev).
I can implement this sooner if you prefer?

![image](https://user-images.githubusercontent.com/18710366/60552643-f6905f00-9d72-11e9-9219-0871cfd9bfc4.png)

**Comment by NoopDog** [comment]
This is interesting and looks nice, one concern I have is if this makes the  file downloads less visible as they are not on an end. Also View in Analysis Tool and Launch Workflow could get long er over time.

I agree it looks better left aligned however.

I guess let's go with this and see what feedback we get. It's easy enough to move around. 

Quick update, "Project Snapshot" title can be changed to "Project Details" as it's not really a snapshot in time.
