### ISSUE TITLE
Convert `filters` parameter from Python literal to JSON

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#696]

**Comment by theathorn** [comment]
@frano-m This needs coordinating with the blocking Azul changes before we deploy to dev.

**Comment by NoopDog** [comment]
@theathorn can we get an example of what the new query string is supposed to look like. Perhaps a before and after of the same  query?

**Comment by dsotirho-ucsc** [comment]
The changes to the query string only affect the `filter` parameter value.
The first change is that this value must now be valid JSON. This includes using valid JSON syntax (eg. using double quotes around strings) and valid JSON values (eg. false or null)
The second change is to remove the unneeded `"file"` key from the `filters` value

Before:
```
filter={"file":{"organ":{"is":["bone"]},"organPart":{"is":["bone marrow"]}}}
```
After:
```
filter={"organ":{"is":["bone"]},"organPart":{"is":["bone marrow"]}}
```

**Comment by NoopDog** [comment]
@danielsotirhos thanks for  the examples. @MillenniumFalconMechanic lets do this one next to un break dev.

**Comment by NoopDog** [comment]
@danielsotirhos does this affect how we send multiple  terms of the same facet or "Unspecified"  can you add an example of both multiple terms and unspecified please?

And just to confirm then, are expecting age to be not quoted as its a number?

Cheers and Thanks,
D

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog, I believe age should be quoted as it is possible to have an age range as a valid term value (eg "6-12").

**Comment by MillenniumFalconMechanic** [comment]
@danielsotirhos, it looks like I'm getting an error when I attempt to send unquoted null values.

For example, with the following filter value:

`filters: {"disease":{"is":[null]}}`

(Complete URL: `https://service.dev.explore.data.humancellatlas.org/repository/projects?filters=%7B%22disease%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&size=15&sort=projectTitle&order=asc`)

I am getting this error:

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 353, in get_project_data
    return repository_search('projects', project_id)
  File "/var/task/app.py", line 161, in repository_search
    return service.get_data(entity_type, pagination, filters, item_id, file_url)
  File "/var/task/azul/service/repository.py", line 80, in get_data
    return self._get_items(entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository.py", line 54, in _get_items
    response = self._get_data(entity_type, pagination, filters, file_url_func)
  File "/var/task/azul/service/repository.py", line 33, in _get_data
    entity_type=entity_type)
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 510, in transform_request
    es_response = es_search.execute(ignore_cache=True)
  File "/var/task/elasticsearch_dsl/search.py", line 639, in execute
    **self._params
  File "/var/task/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/task/elasticsearch/client/__init__.py", line 632, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/task/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/task/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/var/task/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'parsing_exception', 'No value specified for terms query')
```

Can you spot any problems with the filter value I am sending?

**Comment by dsotirho-ucsc** [comment]
This url works if you remove the `[` and `]` surrounding the `null`, so:
`?filters={"disease":{"is":null}}`
or as the full urlencoded path:
`https://service.dev.explore.data.humancellatlas.org/repository/projects?filters=%7B%22disease%22%3A%7B%22is%22%3Anull%7D%7D&size=15&sort=projectTitle&order=asc`

I believe `[null]` is intended to work after https://github.com/DataBiosphere/azul/issues/989 (in progress) is completed.
