### ISSUE TITLE
Collections Functional Spec

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/data-browser#7]
┆Issue Number: HCAB-87

**Comment by kozbo** [comment]
Work with Blue Box team on the spec

**Comment by briandoconnor** [comment]
Take a look at 
* Synapse
* Open Science Framework

For ideas but be careful of feature creep

**Comment by briandoconnor** [comment]
Laura and others mentioned wanting to store and share lists beyond what's in the blue and what comes from a query in blue.  E.g. gene lists, etc

**Comment by theathorn** [comment]
Already implemented.

**Comment by caaespin** [comment]
Already implemented:

https://github.com/HumanCellAtlas/data-store/pull/1214

**Comment by hannes-ucsc** [comment]
➤ Brian O&#39;Connor commented:

Hey [~hannes-ucsc] what did you want me to work on here?  Can you point to the specific functional spec you want me to take a look at?
