### ISSUE TITLE
Can't download manifest on a small screen (unless you zoom)

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/data-browser#705]
On a small screen, the download manifest submit button is off the bottom of the screen and it there is not scrolling. This prevents downloading unless one zooms out.

I would expect a scroll bar.
<img width="1174" alt="databrowser" src="https://user-images.githubusercontent.com/110053/61159583-84362200-a4ca-11e9-91b7-918ec0ebfdbe.png">

**Comment by NoopDog** [comment]
Thanks @diekhans I think this should be addressed in the upcoming changes to how we download data.

The specific screen is here:

https://chanzuckerberg.invisionapp.com/d/main#/console/17726124/367521677/preview

You can review the entire flow here:

https://chanzuckerberg.invisionapp.com/d/main#/console/17726124/367521669/preview

**Comment by theathorn** [comment]
Covered by other changes for Get Data.

**Comment by frano-m** [comment]
@MillenniumFalconMechanic confirmed this is covered by Get Data.

**Comment by NoopDog** [comment]
Thx @frano-m !

**Comment by NoopDog** [comment]
@diekhans we have verified this will be addressed by the upcoming get data flows. Will close this now and update you when the updated get data flows are deployed to dev.
