### ISSUE TITLE
Improve Contributor's section to correctly display data contributors.

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/data-browser#706]
As a user of the Data Browser I would like to be able to clearly see all the contributors of the dataset. 

This can be achieved by:

- Including all `project.contributors.name` in the list of Contributors
- Hiding names of wranglers/curators from the list of Contributors. This can be done by hiding any name that matches `project.contributors.project_role.ontology_label` = `data curator`

Currently, the Browser shows this, which is confusing:
![Screenshot 2019-07-15 at 09 44 15](https://user-images.githubusercontent.com/38244059/61204472-27fb1a00-a6e5-11e9-9204-0258adb33ccf.png)

**Comment by lauraclarke** [comment]
I would advocate for including project role in the display and keeping the HCA wrangler/other curator in the list so it is clear what role they played in this

**Comment by zperova** [comment]
I would appreciate having this fixed as soon as possible, as I have to send the link to the contributors, and they are very likely to share it.

**Comment by zperova** [comment]
@lauraclarke I believe the initial agreement was on having this information available upon downloading the project's files. I am not sure what value displaying the name of the wrangler/curator on the Browser brings to the Atlas at the stage of searching the datasets. Would it matter for a data user who wrangled a particular dataset?

**Comment by lauraclarke** [comment]
This is about people getting appropriate credit for their work. 

If the project role can be listed (and I feel it should be) then there is no reason not to display anyone listed as a curator as it is clear the role they played in the project getting into the DCP.

**Comment by zperova** [comment]
@lauraclarke I believe that with the [new layout](https://chanzuckerberg.invisionapp.com/share/CHSEDSO56SM#/screens/367521680_Explore_-_Get_Data_-_Project_Detail_-_New_-_Counts) of the Project page listing the roles should be possible. 
Do you agree @NoopDog?
I am all for giving appropriate credit for one's work.

**Comment by lauraclarke** [comment]
My feedback for the layout (new or old) is that unless you use superscript numbers/symbols to associate institution to person there is no way of telling who is from where. It would be nice for those links to be explicit

Otherwise, I like the update

**Comment by NoopDog** [comment]
Thanks @zperova 

Can you tell me what is confusing about the current display? This currently displays all of the contributors listed in the contributors list that we get down from Azul.

Looking at the code for the contributors list:

1. We exclude any contributors where correspondingContributor == true (as they are listed in the "Contact" section.

1. We exclude any contributors where the projectRole is "human cell atlas wrangler" as about a year or more ago it was felt that we did not want to add HCA folks as contributors as they are not contributors to the original project but only the ingest into the HCA DCP and so we would be confusing folks by adding HCA staff to the contributors section. 

Now, if we clearly display the role "Human Cell Atlas Wrangler" that could clear up the above concern. 

We could also have a separate section for "HCA Ingest Contributors" to further clarify if the HCA Staff member was part of the original research or part of the project ingest.

I will split this into three tickets then:

1) Show project role #732
2) Include HCA contributors on the project page #733
3) Associate contributors with their institute #731

Ok then, @zperova are you ok with closing this now that we have the other 3 tickets?

Cheers and thanks for looking into this.
Dave

**Comment by gabsie** [comment]
Hey, guys, I added my comment on [ticket 733](https://github.com/HumanCellAtlas/data-browser/issues/733).

**Comment by zperova** [comment]
@NoopDog yes, thank you. Happy to have this closed now.
