### ISSUE TITLE
Reindexing banner does not show up on staging

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#709]
![Screen Shot 2019-07-16 at 8 52 04 AM](https://user-images.githubusercontent.com/5143256/61309496-272abc80-a7a7-11e9-81dc-fa533f1118f4.png)

**Comment by NoopDog** [comment]
This code is not deployed to staging. On the next AZUL deploy to staging we will deploy this update. If you would like to  test this please test in dev or integration. Thanks!

**Comment by hannes-ucsc** [comment]
Thanks for the explanation. This works on integration. Since I prematurely promoted to staging, you might want to do the same.
