### ISSUE TITLE
Update subscription to DSS to only receive data adhering to compatible schemas

### ISSUE THREAD

**Issue by maniarathi** [DataBiosphere/data-browser#710]
This is required in order to receive data that adheres to a schema versions with which data browser is compatible.

**Comment by NoopDog** [comment]
This should be an Azul ticket I think.

**Comment by maniarathi** [comment]
Created https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/databiosphere/azul/1140! Thanks for the update!
