### ISSUE TITLE
Refreshing error page should revert back to normal UI once error is resolved

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#711]
If the service returns an error, the error page gets displayed. Refreshing the error page correctly updates the error description in case a new, different error is raised. Once no error is raised, the error description goes blank but the error page remains active. It would be desirable if refreshing the error page takes the user to the normal UI if the service returns no error. The screenshot below shows that state. The service returns success, no other JS error occurred (AFAICT) yet the UI is stuck on the error page.

<img width="1676" alt="Screen Shot 2019-07-16 at 12 02 43 PM" src="https://user-images.githubusercontent.com/5143256/61322117-d83e5080-a7c1-11e9-8e97-195bf7ea30a6.png">

**Comment by theathorn** [comment]
Add a "Go back to home page" button.
