### ISSUE TITLE
Enable the "Export to Terra (Beta)" button in dev/integration/staging/prod environments

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#729]
Wait for my go ahead - need some other issues in the Terra epic resolved first.

**Comment by NoopDog** [comment]
Sure, I would like to  do this when we deploy the get data updates so we dont get a row of 3 buttons. We are close on this.

**Comment by theathorn** [comment]
Not going to wait for any more Terra fixes related to BdBag processing.
Please enable the button and change the label to "Export to Terra (Beta)".
