### ISSUE TITLE
Associate contributors with their institute on the project detail page

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#731]
@frano-m  

Let's mock this with superscript on the contributors and numbers on the institutions and see how we can make this look.

We can keep our current layout but here is how these items are traditionally linked:

![Screen Shot 2019-07-24 at 8.57.45 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/da47abab-9246-4585-8a0f-ad1429c46b38)

**Comment by MillenniumFalconMechanic** [comment]
### Contributors
Sam Snead<sup>1</sup>, Tom Jones<sup>2</sup>, Michael Jordan<sup>3</sup>

### Collaborating Organizations
<sup>1</sup> Institute of Golf
<sup>2</sup> Institute of Music
<sup>3</sup> Institute of Basketball

**Comment by frano-m** [comment]
- update Publication type
