### ISSUE TITLE
Add back HCA contributors to the project detail page

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#733]
See discussion here:

https://github.com/HumanCellAtlas/data-browser/issues/706

**Comment by gabsie** [comment]
Hi,  @zperova, @lauraclarke @NoopDog 

I do not think that data curators/HCA data wranglers should be part of the Contributors for the project.
I think the point with Contributors section is to attribute the work on the data to the original data generators.
The amount of contribution between these two roles is incomparable, and I wouldn't even ask data contributors for feedback on this.

Are there other examples for repositories, e.g, where you see curators on the same level as data contributors?

We have to go back to: what is the purpose of this? What kind of user goal are we addressing with showing the wrangler names? 

If you do have to include the wrangler for traceability of the annotation (one goal), then this should belong to a separate entry, in a separate field, displayed in a way different to the data generators, so there is no confusion.

**Comment by lauraclarke** [comment]
While I agree that wranglers shouldn't be listed alongside contributors as though they were part of the whole project I do want to make sure that wranglers are publicly credited for the work they have done as without them the data would be fair less well presented in the browser and fair less useful to the whole community.

@NoopDog how difficult would it be to have a Curator section and a Contributor section?

**Comment by NoopDog** [comment]
@lauraclarke @gabsie @zperova, Simple to make a separate "HCA Data Wrangler" section. That seems to me a good way to give credit to wranglers but not overshadow the efforts of the original contributors. 

Do folks feel a separate section for HCA Wranglers is the way forward on this one?

**Comment by gabsie** [comment]
Yeah, I think this is a good way forward. :)
 'HCA Data Curator' instead of wrangler, maybe? @zperova @lauraclarke ?

**Comment by NoopDog** [comment]
Cool, I feel we have enough consensus to add this to the backlog. We will go with "HCA Data Curator" and can easily change if we find this confuses anyone.

**Comment by zperova** [comment]
@NoopDog yes, thank you, I think HCA Data Curator is a good way to go now

**Comment by NoopDog** [comment]
Looks like the wranglers are encoding the HCA Data Curators as:

>HCA Data curators and the names displayed should be the ones that have `data curator` ontology label and text `HCA` present in the `project_role.text` (edited) (Thanks for clarifying @zprova)


Looks however that like we can not currently tell who is an HCA Data Curator at the moment.

From Azul we have project.role = data curator but we do not have the: 

`HCA` present in the `project_role.text` part.

@hannes-ucsc how would you like to handle this? Some options are:

1. Create a separate " is HCA Data Curator"  flag on the contributor that is set to true if project_role.text  and the project_role is "data curator"

2. Create new fake role "HCA data curator" that is set in Azul if HCA is present in project_role.text and the project_role is "data curator"

3. Re-ingest all the projects with a more explicit project role like HCA data Curators ;)

4. Wait for AUDR 

5. Check in the browser if the org is UCSC or EMBL and then assume they are an HCA curator rather than a project curator. 

We can do 5 quite quickly and then create a ticket to have a more explicit role created for the wranglers to use when updating (and then modify the older project's contributors  with the role)

What easier option did I miss @zprova?

**Comment by zperova** [comment]
@NoopDog my preferred option would be:
- find `data curator` in `project.contributors.project_role.ontology_label` 
- find 'HCA data wrangler" or presence of 'HCA' or presence of 'Human Cell Atlas' in 'project.contributors.project_role'
- assign 'HCA data wrangler'

**Comment by hannes-ucsc** [comment]
Instead of looking for `HCA` or `Human Cell Atlas` or `HumanCellAtlas`, for that matter, could the heuristic consider the `institution` field, or the domain name in the `email` field? Any data curator from UCSC and EBI is a wrangler, right?

**Comment by NoopDog** [comment]
Nice, thanks. 

I think till we improve how this is modeled we can use the email addresses. We will proceed with that for now.

We should have a specific role for this in the ontology. 

@zperova can you create a ticket to add the role to the ontology and AUDR the projects to get this setup and link back to this one? 

Once the role is explicit, we will remove the heuristic on the email addresses. 

Thanks!
