### ISSUE TITLE
Maintenance mode banner now has super tiny text.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#738]
Let's revert this. I suppose this was an unintended consequence of the portal down message heading update.

![Screen Shot 2019-07-26 at 12.35.03 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d2bf2e90-d598-45b3-bf96-d35e0c3eea71) 

https://prod.data.humancellatlas.org/explore/projects

**Comment by theathorn** [comment]
We can remove the maintenance mode banner now.

**Comment by NoopDog** [comment]
aw yea? We will fix then, remove, so its not tiny when you ask us to add it back. ;)
