### ISSUE TITLE
Check metadata tsv download existence before showing download icon

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#741]
The metadata files are all supposed to be there but, it is possible the generation will lag behind the availability of the project in the data browser.

Now that we are checking the existence of matrix files, lets use the same approach to check if the metadata tsvs also exist and show the download icon if they do and the same "-" symbol if they do not.

This will make it easy to see what TSVs are missing and also avoid letting the user request for a file that is not there and get a 404 page.

**Comment by theathorn** [comment]
Won't fix - superseded by automatic metadata tsv generation.
