### ISSUE TITLE
Add "Help" links for each download type in Get Data flow

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#745]
Add Help links for manifest, matrix and Terra downloads/exports.

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog Can you please provide the Help links for the manifest and matrix downloads, as well as the Terra export.

**Comment by NoopDog** [comment]
Terra
https://data.humancellatlas.org/guides/consumer-vignettes/export-to-terra

Manifest
https://data.humancellatlas.org/guides/consumer-vignettes/intro-to-downloading-and-analyzing

We dont have one for matrix yet but can proceed with the other two.

>Note:  Make the URLS relative to the environment!
