### ISSUE TITLE
Browser: verify that you have met the SLA for redaction

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-browser#750]

**Comment by NoopDog** [comment]
Hi @kozbo @theathorn  are there browser specific requirements for this or should this be an Azul ticket. Thanks. D

**Comment by theathorn** [comment]
Superseded by https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/databiosphere/azul/1186
