### ISSUE TITLE
Remove redundant prefix component/file naming conventions

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/data-browser#759]
We have a number of components named with "HCA" or "File" prefixes, making it difficult to identify files quickly, and reduces readability of code.

"HCA" is no longer necessary as the code base has forked from its origins with no intention to merge back. We therefore do not need to mark components as HCA-specific, as all components are now considered HCA-specific.

"Files" is no longer applicable as we are browsing entities such as projects and samples, in addition to files.

**Comment by NoopDog** [comment]
superseded by dx
