### ISSUE TITLE
Integration with Single Cell Portal (SCP)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#761]
See https://docs.google.com/document/d/1HBOPe6h_RjxltfbPenKsNmoN3MVAtkhVKJ_LGG1DBkA/

7/31/19 from Jean Chang at The Broad:

Embed project visualization from SCP (manual handoff where SCP runs a pipeline and generates visualization in a study, and the DCP Data Browser links to the study via accessioning).

We propose choosing one of the following projects for the above work:
Ischaemic sensitivity of human tissue by single cell RNA seq
https://prod.data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7
OR
Assessing the relevance of organoids to model inter-individual variation
https://prod.data.humancellatlas.org/explore/projects/005d611a-14d5-4fbf-846e-571a1f874f70

Jean will supply us with SCP study accession URLs for each project and we will hard code those into the Data Browser via a "Visualize in SCP" link on the Project Details page.

**Comment by theathorn** [comment]
From Jean Chang:

I will send a URL next week for an unpopulated study. If we run into any issues, I can certainly set up another project - for now we're planning to set up one study for this work.

We plan to have the study complete before the end of the quarter. If an unpopulated study is a blocking issue for your team, please let me know so we can coordinate more closely.

**Comment by theathorn** [comment]
From Jean Chang:

Here's the permanent URL for the unpopulated study: https://portals.broadinstitute.org/single_cell/study/SCP495


I plan to work with data from the project titled "Ischaemic sensitivity of human tissue by single cell RNA seq".

https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7

**Comment by theathorn** [comment]
From Jean Chang:

The URL for Single Cell Portal has been updated. We can now be found at https://singlecell.broadinstitute.org/single_cell

The URL for the handoff study (https://singlecell.broadinstitute.org/single_cell/study/SCP495) has changed accordingly (If using the old URL, it will be re-directed to the new URL). Please have the "Visualize in SCP" link on the Project Details page for "Ischaemic sensitivity of human tissue by single cell RNA seq" use the new URL.

**Comment by theathorn** [comment]
10/4 update from @theathorn:
From the PM meeting: for the "Ischaemic sensitivity" project the submitter states that it is not complete and they will be adding more data. This is an exception rather than a rule for the HCA. We are looking at ways to indicate such incomplete projects in the DCP - further discussion is needed.

Vicky, in the short term it sounds like we should not enable the SCP link for this project. Do you have an alternative project(s) that we could enable? Or we should go straight to Phase 2?

10/7 update from Vicky Horst: 
I think we should focus on enabling the automated handoff [get_entities] as the next goal. We are looking to the general policy for HCA data and its implications on SCP studies.

**Comment by theathorn** [comment]
From the SCP integration doc: SCP will provide an endpoint of their choice to receive the generic project hand-off (e.g. https://singlecell.broadinstitute.org/single_cell/study/hca/<hca_project_uuid>).

From Vicky: ETA for this implementation from The Broad is by the end of Q1 2020.

**Comment by NoopDog** [comment]
Obsolete
