### ISSUE TITLE
add a link to the data release policy to all project pages

### ISSUE THREAD

**Issue by jahilton** [DataBiosphere/data-browser#775]
# Why
As a user I would like to understand the policies surrounding the data that I am interested in using

# Definition of Done
 - a link appears on every project page that leads to https://drive.google.com/file/d/1kLR0OpEFqS9DdSqFZmM4b2ATFyvwpPum/view

**Comment by NoopDog** [comment]
Hi @jahilton any objection to having the google doc contents be an actual page on the data portal rather than a link to the google doc?

Also, is this doc "ready to go" or is this still in review?

Cheers,
Dave

**Comment by jahilton** [comment]
No objections to copying the content of that doc to a portal page - and that sounds more aesthetically pleasing
That changes specifications for https://github.com/HumanCellAtlas/data-portal-content/issues/304

The doc is 'ready to go'

**Comment by lauraclarke** [comment]
@jahilton @NoopDog quick comment I propose not making it a  page in its own right now as there are a lot of language inconsistencies with how we refer to things and there are features stated that the DCP has which we don't.

I think getting the link up asap so we are providing an MVP for people to understand this policy but then we ask the folks who work on the portal content to come up with an improved text which fits DCP terminology that we can then get approval for from the HCA Science organising committee before it is an official page on the DCP website as that approval process might take longer than we need the MVP in place for

**Comment by jahilton** [comment]
Excellent point @lauraclarke. We anticipate/hope for some updates in the near future so the link to the doc makes it more flexible, rather than changing the text in multiple places.

**Comment by NoopDog** [comment]
Should the document be marked as "draft" or "in progress" then?

**Comment by lauraclarke** [comment]
No,  because from an HCA scientific leadership perspective the document is at v1 and not in draft

Think of what we want to do as v1.1

**Comment by theathorn** [comment]
MVP could link to a PDF doc.
