### ISSUE TITLE
Remove references to Smart-seq2 from Request Expression Matrix button

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#777]
1) If I select a project (e.g "1.3 Million Brain Cells from E18 Mice") the "Request Expression Matrix" button is grayed out but the button text says "Request Smart-seq2 Expression Matrix".

2) The hover over text needs to be reworked to be more generic. The verbiage about Smart-seq2 and 10x no longer apply.

**Comment by frano-m** [comment]
@NoopDog with the new "get data" can this ticket be closed?

**Comment by NoopDog** [comment]
Not required as updated get data flows are deployed.
