### ISSUE TITLE
Add "Copy to clipboard" option to download matrix dialog

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#778]
If I click on the icon to download a project matrix file I can select the output format but there's no option to "Copy to clipboard" which I do get if I regenerate the matrix by selecting "Request Expression Matrix" dialog.

**Comment by MillenniumFalconMechanic** [comment]
![Screen Shot 2019-08-29 at 9.36.23 AM.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/8832c67c-9dc2-4ba5-b7bf-97cbe08dcab8)
