### ISSUE TITLE
Add "Library Construction Method" and "Species" to get Data Summary

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#780]
List the library construction approaches and species  in the query results.
We can add a +10 more in a future ticket when these get big.

**Comment by MillenniumFalconMechanic** [comment]
```
Projects                                          1
Species                                           Homo sapiens
Library Construction Method                       Smart-seq2, 10X v2 sequencing
Donors                                            8
Specimens                                         8
...
```

Let long lists wrap to next line.

**Comment by NoopDog** [comment]
![Screen Shot 2019-08-27 at 11.26.41 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/345102da-b6f8-4f15-a5c3-c8ab64e88843)
