### ISSUE TITLE
Update Matrix service get data text to set expectation of matrix generation time

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#782]
“This can take several minutes to an hour or more. Please leave this browser window open during processing.”

**Comment by parthshahva** [comment]
@NoopDog is it possible to store the request ids in local storage so that the users do not have to keep the browser open? Might be a simple view to see all matrices you have requested. Just thinking of a compromise between not having a concept of a user and the users having to keep the browser open

**Comment by NoopDog** [comment]
Yes, great idea for us to think through. The above messaging hopefully will let us at least start  the user testing formally known as "Beta 2".

We could surface a list of requested matrices in the last 30 days and their status and keep the links etc.

Like it.

**Comment by NoopDog** [comment]
From @adrienne

Perhaps some kind of visual change to the browser tab (when done)

**Comment by NoopDog** [comment]
This did not make it into the commit it seems.
