### ISSUE TITLE
Show file size on matrix downloads

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#820]
is this possible? Maybe we can get this from the head request?

**Comment by NoopDog** [comment]
HI @theathorn is this something we want to implement? I believe that Azul has the file size info for all files. The file size would need to be added to the project matrices API.

**Comment by MillenniumFalconMechanic** [comment]
* Bind the `size` values contained in `matrices` and `contributorMatrices` for both project list and project detail responses. Note, updates to tree-flattening functionality should not be necessary.
* Add a “Size” column to the end of both the DCP and Contributor Generated Matrices tables.
* Re-use FileSizePipe for transforming the file size for display.
