### ISSUE TITLE
Decidua on Homepage next to human body map - 0 cells

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#822]
Hi!

I was quickly checking the Homepage human body diagram before preparing the email for beta participants.
 
There's 'Decidua' for an organ there, but it says 0 cells. It still goes to a project, though.

Maybe it would be good to know why this is. Is there a mistake, or is there a scientific reason?

I'll copy here @zperova and @NoopDog 

Gabs

**Comment by zperova** [comment]
@NoopDog where does that number come from? Is that estimated cell count? I would imagine if it is unspecified that would possibly render it 0 in the landing page?

**Comment by theathorn** [comment]
Decidua will not be in the new home page by Adrienne - so closing this ticket.
FYI: This is fetal-maternal project with an unspecified cell count for this organ.
