### ISSUE TITLE
Label "matrix" files as zarray -  matrix or otherwise disambiguate them with the matrix files from the matrix service.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#826]
The "matrix" files in the file type dropdown are being confused as matrix files that would be downloaded from the matrix service.

We need to do a better job of indicating what these actually are.

**Comment by ambrosejcarr** [comment]
+1. I cam across this expecting to generate a bug report for the below project that passes the matrix filter but doesn't have a matrix that's downloadable: 

![image](https://user-images.githubusercontent.com/5239152/64530156-763e2b00-d2da-11e9-8972-0d40c3385333.png)

The immediately downloadable matrix is _much_ more salient than the data export.

**Comment by theathorn** [comment]
Superseded by #1420?

**Comment by NoopDog** [comment]
Sure
