### ISSUE TITLE
Add filters to the URL parameters of the get data page so it is linkable

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#833]
So from 

/explore/getdata

to  

/explore/getdatafilter=%5B%7B%22facetName%22%3A%22projectId%22%2C%22terms%22%3A%5B%22005d611a-14d5-4fbf-846e-571a1f874f70%22%5D%7D%5D

**Comment by MillenniumFalconMechanic** [comment]
#### App Load

##### ProjectsCanActivateGuard
* Rename to indicate applicable to any route (eg `FilterCanActivateGuard`)
* Generalize `URLTree` returned so it can handle any route (and not just projects)
* Implement both `canActivate` and `canActivateChild` interfaces
* Update `canActivate` and `canActivateChild` specs on routes
* Update specs
* See `CatalogCanActivateGuard` for examples
* See #1438

#### Internal Navigation

##### [routerLink] and router.navigate
* Add `queryParamHandling: merge` for template and explicit calls to `navigate`
* See #1439

#### Internal State Changes

* TODO
