### ISSUE TITLE
Expose full manifest in Export Selected Data flow

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#841]
Now that Azul has the ability to generate a full manifest (aka Full Metadata TSV) for any set of filters, we should expose that functionality in the Export Selected Data screen as a third option in addition to the compact manifest (aka File Manifest).

**Comment by NoopDog** [comment]
Nice!

**Comment by theathorn** [comment]
Talk to @hannes-ucsc . It's confusing to have a "manifest for the CLI" and "full metadata tsv" on the same page. Can we consolidate these concepts?

**Comment by hannes-ucsc** [comment]
#912 duplicates this but has more meat.

**Comment by hannes-ucsc** [comment]
> Can we consolidate these concepts?

I don't think so. They serve different purposes. The full manifest is complete and verbatim but not harmonized, so a renamed MD property would show up as two columns with one column populated in some rows and the other column populated in the remaining rows. The compact manifest is partial but harmonized. The old trade-off.
