### ISSUE TITLE
Manifest download icon not moving to checkmark on Firefox.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#843]
on Firefox.

For the dynamic manifest download TSV flow.
Initiate a download.
When the URL is ready, Firefox asks the user where to download it to or open.
At this point the manifest icon has gone from swirl to blank.
Downloading the file and closing the download modal leaves the icon blank instead of moving to a check.

**Comment by hannes-ucsc** [comment]
Same on Safari
