### ISSUE TITLE
Make the 'project_supplementary_links' field available on the project overview page

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#848]
Requested by Marion Shadbolt (mshadbolt@ebi.ac.uk).

**Comment by theathorn** [comment]
Would need Azul to index.

**Comment by mshadbolt** [comment]
Does that mean I need to create another ticket in azul? This has been requested by multiple contributors so would be good to see it progress.

**Comment by theathorn** [comment]
Created DataBiosphere/azul#1338.
