### ISSUE TITLE
Status page for broken subgraphs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#849]
Data Browser to provide details of bundles that failed to index (mainly for Data Ops) via a bundles status page.

**Comment by NoopDog** [comment]
Bundles are sunset, closing.

**Comment by NoopDog** [comment]
Reopening, to explore relevance to DCP2

**Comment by theathorn** [comment]
Paging required? Not initially - refine later. Limit response size.

**Comment by melainalegaspi** [comment]
This was relevant for DCP1, not DCP2.
