### ISSUE TITLE
Process=>protocol field change to metadata

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#85]
Metadata v6: fields in type/process schemas will be moving to type/protocol schemas on Monday 4 June.

https://humancellatlas.slack.com/files/U6CB89VLJ/FAX897Y8P/HCA_Metadata_Standard_Proposed_Major_Update____process_schema_fields_to___protocol_schemas

**Comment by caaespin** [comment]
@theathorn to ask Metadata group for example bundles, and metadata schema versions that will be used.

Reassign once we have test bundle and metadata schema versions
