### ISSUE TITLE
Manifest download icons completely missing

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#854]
<img width="1173" alt="Screen Shot 2019-09-07 at 12 27 28 AM" src="https://user-images.githubusercontent.com/5143256/64471413-5b1ac200-d106-11e9-9cdb-ebeb849eaf25.png">

Firefox, `dev` deployment.

**Comment by hannes-ucsc** [comment]
Same on Safari

**Comment by NoopDog** [comment]
This is a known issue we are working through on develop. The build is working differently on develop at the moment verses locally and we are working at figuring out why.  This is a WIP build for #723

**Comment by NoopDog** [comment]
Hi @theathorn this is on dev, not prod so I don't believe this should be an urgent ticket. Dev is ours to break no? It is however what we are working on after #870
