### ISSUE TITLE
Pagination is not working correctly

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-browser#855]
I believe that pagination is still not working correctly.

"Profiling of CD34+ cells from human bone marrow to understand hematopoiesis" shows up on both pages, and "1M immune cells" shows up on neither. The latter is particularly problematic, as it's one of our "flagship" studies.

**Comment by theathorn** [comment]
I'm not seeing this currently on prod.
"Census of Immune Cells" and "Profiling of CD34+ calls" both show up once.
There are 15 projects on the first page (including 2 integration tests) and 9 on the second page, which corresponds to the 22 entries in https://tracker.data.humancellatlas.org/ (which doesn't show  integration tests).
Ambrose, can you re-check? Try refreshing your browser. If issue persists please report the browser version ans OS you are using.

**Comment by ambrosejcarr** [comment]
Ah, you're right. Refresh fixed it. Thanks.
