### ISSUE TITLE
Search by contributor name

### ISSUE THREAD

**Issue by mshadbolt** [DataBiosphere/data-browser#856]
I think it is important that a user can search the projects in the browser by author name to get a list of all the projects a certain author has contributed to. Currently searching in the search bar by author name does not give any results.

**Comment by theathorn** [comment]
Would require Azul to index.

**Comment by NoopDog** [comment]
@theathorn is there a blocking Azul ticket for this?

**Comment by theathorn** [comment]
Added blocker.

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
