### ISSUE TITLE
Improve discoverability of bulk export

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-browser#857]
I find the "export selected data" wording misleading. It would be clearer to me to name the button "bulk download" and have a small `?` or `instructions` tooltip below that you can hover to reveal instructions such as: 

```
To download custom sets of data files from the data store, filter and select the 
projects and file types you want to download. Then click the above "bulk download" 
button to get a manifest that can be used with the data coordinate platform 
command line interface to download the requested files.
```

I'm sure this text could be dramatically improved upon.

**Comment by MillenniumFalconMechanic** [comment]
Superseded by #764.
