### ISSUE TITLE
Searched project name and project name don't match

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-browser#860]
When you search in the search bar, the name of the immune cell study is "1M Immune Cells", but the project name that shows up in the project list is "Census of Immune Cells". In this case, the two names are close enough that I could guess, but I suspect that these should correspond.

**Comment by ambrosejcarr** [comment]
Oh, that's very interesting. Thank you for the context. My gut reaction is "only index one name for the project" but admit I haven't thought through all the potential impacts of this. Interested to hear what @jahilton thinks. 

Generally, my desire would be to have one authoritative name for each project. Using the system from the outside, and not having obvious access to the declarations made by the schema, it wasn't clear to me which it should be.

**Comment by jahilton** [comment]
It is my understanding that the short 'nicknames' are for internal DCP use (tracking by the wranglers), but when there's no consistent way to get short name from long name, I don't see any value added to the user, only the potential to introduce confusion as @ambrosejcarr has noted.
