### ISSUE TITLE
Integration test shows up in prod

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-browser#861]
Just a dumb question, but should the integration test be showing up in prod? 

https://data.humancellatlas.org/explore/projects/4d4a41ef-c655-40c3-9ee8-5ce3ecd06774

**Comment by theathorn** [comment]
All bundles show up in prod. They do (or should) get deleted at the end of the test
Azul has no indication that "integration test" bundles are different from any other.
If they weren't indexed then what would be the point of the test?
Should we be running integration tests in prod at all?
What are your views @jahilton ?

**Comment by theathorn** [comment]
They'll also be (temporarily) visible via the DSS and Query Service APIs, so this is not just a Data Browser issue.

**Comment by jahilton** [comment]
My views...
The Integration Test projects shouldn't be visible to the user via DSS, Browser, or any API. Could throw a false positive for anyone pinging for new submissions. They only appear for a short time, so it's not a _major_ concern.

I don't know enough about the integration tests to know whether they should stop running or a new test should be considered to replace them.
Maybe this is another use case for a public on/off switch for projects. These tests could still run, but the public wouldn't be aware.

**Comment by theathorn** [comment]
@parthshahva Who "owns" the integration tests? Is this an item for the DevSecOps or TechArch meetings?
I'm concerned that it would be a considerable effort to "hide" integration tests from any public view.

**Comment by parthshahva** [comment]
The integration tests are owned by Tech Arch and all components. I have managed a lot of the codebase as well but am not an explicit owner. With the DCP architecture in mind, the only real way to make this work while keeping the tests useful would be a public on/off switch or staging area concept.

**Comment by theathorn** [comment]
@jahilton This needs a policy decision between Data Ops and Tech Arch.

**Comment by jahilton** [comment]
Once the project-completion RFC Phase 1 is implemented, we can have these tests submitted as 'unreleased'. Not much we can do until then, unfortunately, unless we think they could be displayed more obviously as test data (they seem pretty obvious to me).

**Comment by NoopDog** [comment]
Closing as we are switching to a release snapshot that presumably will not contain integration tests
