### ISSUE TITLE
Fetch Manifest TSV Full does not error if null is provided for a project UUID.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#869]
I am expecting that the project UUID is validated as a proper UUID that corresponds to an existing project. 

Request
https://service.explore.data.humancellatlas.org/fetch/manifest/files?filters=%7B%22projectId%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&format=full

Response
{"Status": 301, "Location": "https://service.explore.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMmQxMGZjYjMtOTgyYi00NmQ2LTkzODEtMGEyNGQ1YWEyYjYwIiwgInJlcXVlc3RfaW5kZXgiOiAxfQ==", "Retry-After": 1}

There is a bug in the browser project detail page that exposes this bug on the server. We will stop sending null as the project UUID ASAP but wanted to record that we currenly get a TSV back if we send  null as the project ID.

**Comment by NoopDog** [comment]
I mean to open this in azul. @theathorn is it easy to move?

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/databiosphere/azul/1265
