### ISSUE TITLE
Project Entity Page UX

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#88]
┆Issue Number: HCAB-41

**Comment by happyimadesignr** [comment]
Design completed, need to get feedback from PMs and team. https://chanzuckerberg.invisionapp.com/share/P4M7U14RT29#/306181276_2-3_Explore_-_Project_Detail

**Comment by happyimadesignr** [comment]
Hey @adriennes, I'm going to put you on this ticket for synthesizing feedback.

@NoopDog should be able to make tweaks from here, correct?

**Comment by NoopDog** [comment]
Correct Jenn thanks!
