### ISSUE TITLE
Link to Data Release Policy on main HCA website (instead of pdf)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#881]
From @lauraclarke :

The link https://www.humancellatlas.org/data-release-policy/ might be better than a straight pdf link, keeps us up to date with the policy as it changes

An interesting proposal from the contributor was a pop up when someone wants to download something so they definitely see it. Might be worth considering how best to ensure visibility of the policy on downloads for the next iteration.

**Comment by theathorn** [comment]
Update link on Project Details page.

Consider adding the link to the file download dialog.

**Comment by zperova** [comment]
@theathorn @NoopDog 

our contributor wants to submit a large (2 million cells) unpublished dataset and make an announcement of such submission at the Single Cell genomics meeting on September 23-26 2019. Could you please give an estimate of how long it will take to implement such a pop-up window?

An alternative solution might be a check box prior to download along the lines "I have read the Data Release Policy" (or the main statements from it) and the link to the policy.

**Comment by lauraclarke** [comment]
We should talk through with UX (and review with users) what is the right line between making sure users don't miss the data reuse policy when they download data vs getting an explicit acknowledgement of the data reuse policy. This isn't something I have seen other services which such an open data reuse statement do before

While this has come up for discussion again other places the data reuse policy should be linked are

https://data.humancellatlas.org/guides/data-lifecycle
https://data.humancellatlas.org/about/data-use-agreement

**Comment by NoopDog** [comment]
For https://data.humancellatlas.org/about/data-use-agreement

Should the text below be a replacement of or in addition to the text already there?
@theathorn @lauraclarke 

## Data Use Policy
For information regarding data sharing and data use, please see our [Data Release Policy](https://www.humancellatlas.org/data-release-policy/)

**Comment by theathorn** [comment]
I presume we want to keep the Creative Commons license and add a link to the Data Release Policy.

**Comment by lauraclarke** [comment]
Yeah, we need to consider how to better associate the cc-by license with the data as well as the data re-use policy

**Comment by NoopDog** [comment]
Ok is this ok then? (on staging) 

https://staging.data.humancellatlas.org/about/data-use-agreement

Feel free to use the "improve this page" link at the bottom of the page to update the content as you like.

**Comment by NoopDog** [comment]
We can do this on the data portal which will highlight the data use policy without over highlighting it.

<img width="1317" alt="Screen Shot 2019-09-17 at 1 12 46 PM" src="https://user-images.githubusercontent.com/3239697/65076327-9e1e3600-d94d-11e9-8910-0e73ddaf9dd7.png">

This is similar to how we do the cookies notice. Do folks feel this would suffice?

**Comment by lauraclarke** [comment]
That feels like a good first start. I wonder if the phrasing could be better

something like When using data from this website please follow the data use policy

I wonder if there is a better polite phrase than please, which sounds a little passive

**Comment by zperova** [comment]
Could it be in the same style as when one accepts cookies on a website? 
"By downloading any data I accept the HCA Data Use Policy."

**Comment by lauraclarke** [comment]
I like that phrasing. Might be good to have consistent wording between this message and whatever on the download pages if possible

**Comment by MillenniumFalconMechanic** [comment]
The following updates are also required, on the project detail page:
* Update Data Release Policy text to match https://github.com/HumanCellAtlas/data-browser/issues/881#issuecomment-532608184
* Update Data Release Policy link to be https://www.humancellatlas.org/data-release-policy/
