### ISSUE TITLE
Default "Species" selection for Matrix Service requests to "Homo sapiens"

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#891]
The AWG has determined that the Matrix Service should default to returning human-only data.

For the "Request Expression Matrix" dialog, if more than one species is available with the current selection criteria, then show one checkbox per species with only "Homo sapiens" selected by default.

There should be some accompanying text stating something like "More than one species is available. If you want data for other than homo sapiens then please check the appropriate box".

**Comment by brianraymor** [comment]
@theathorn - do you think that this (and any other changes related to mouse) should be included in _DCP Support for 10X and SS2 Mouse data_ per the [comment](https://github.com/HumanCellAtlas/dcp/issues/44#issuecomment-525947439)?

**Comment by theathorn** [comment]
From John Marioni of the AWG: "I am fine with defaulting to human and having mouse available as a specific request.".
