### ISSUE TITLE
Matrix service integration with Data Browser

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/data-browser#9]
This needs to be scoped but users would expect integration

┆Issue Number: HCAB-6

**Comment by theathorn** [comment]
@briandoconnor status on this?

**Comment by theathorn** [comment]
From 7/30 Data Browser meeting:

Proposed plan:
 - Create new button that would post the URL to the matrix server
    - The URL is all the matrix service needs to retrieve the manifest
    - Redirected to a page that gives stats, and a URL to check with, maybe ability to input an email address
    - No time estimation
    - Page can spin and wait, using the 301/302 retry after logic.
     - Matrix service could support the basic call in a few weeks (Sprint 8?)
 - Returns???
    - Won’t be available in “interactive time”
    - Signed URL will get returned
    - If the user submits a request that has already been requested (same url), and the work is the same as a previous request, then cached results will be returned.
    - Matrix service does not have plans to support email notification right now, but it could possibly be added (Marcus Kinsella)

Matrix Spec: https://docs.google.com/document/d/12gfF3UEgRZ0YJiBoScLMtcW6Cthv0_MZHQwj4WMYKPA/edit#heading=h.gk7s93eg9jfq

**Comment by theathorn** [comment]
Update from 8/27 meeting with @mckinsel, @brianraymor and @NoopDog:
- Marcus has pull request for mock API out for review (https://github.com/HumanCellAtlas/matrix-service/pull/28)
- "Version 0" (targeted for demo in Oct) will have Data Browser call Matrix APIs described below:
- MatrixRequest "post" json will contain bundle fqids as input
- MatrixRequest will not require any user-specified inputs; output file will be concatenated matrices only (very useful for SmartSeq2 one cell/bundle inputs)
- MatrixFormat ("zarr", "parquet", "loom", "anndata", "singlecellexperiment") will use default value for Version 0
- MatrixRequest API reply will return a "request ID" and "key" (eventually will be a link url to results)
- Matrix "get" API used by UI to poll for completion status by providing "request ID" as input
- need secondary analysis bundles generated by green box to test with (currently not present in prod)
- TBD: call Matrix service APIs directly from browser or via azul webservice?

**Comment by briandoconnor** [comment]
@brianraymor said "Hi Brian - Wanted to call your attention to the outcome of the Matrix-Portal discussion yesterday which eliminates _handoff_ - https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/9 - since you had a number of related comments in the Matrix Service charter."

Does this mean this ticket is no longer on the roadmap?  

I understand if this can't be done via the Data Browser since it's async.  Until there's a user login and state saved for a user that could associate their account with matrix service jobs running.  But is a temp workaround having a manifest file from the Orange Box Data Browser be used by the HCA command line to generate a matrix?  Could the portal at least generate a URL for the running matrix job and hand that back to the user?

**Comment by theathorn** [comment]
@NoopDog Please review Marcus' PR for the Matrix API.

**Comment by frano-m** [comment]
Skin complete - API TBC

**Comment by theathorn** [comment]
Use .zarray file type in links.json metadata in bundle to indicate presence of matrix-able data.
Select matrix files in Data Browser to enable "Matrix Service".
Request manifest returns url in response that can be passed to Matrix Service.
