### ISSUE TITLE
Make it clear to users that downloaded data is under a CC-BY license

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#902]
Add a reference to the "Creative Commons Attribution 4.0" license to the "Export Data" dialog.

Maybe link to https://data.humancellatlas.org/about/data-use-agreement

**Comment by theathorn** [comment]
From @lauraclarke:

I think the citation widget gives people a way to meet cc-by attribution needs

They will need to be able to add attribution to whenever they reuse something, at the project level seems a good starting point, Ultimately we might want a way for someone to give us any identifier and getting an appropriate attribution text for that identifier in our system

A paper which might be useful in considering solutions https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0213090

And a blog post https://nlmdirector.nlm.nih.gov/2019/06/11/socio-legal-barriers-to-data-reuse/

**Comment by NoopDog** [comment]
Proposing the following text to be added the various places above:

@lauraclarke will how does the text below look? We would put this on the bottom of every download dialog (like the ones listed above).

"Data downloaded from the HCA DCP is governed by the [HCA Data Release Policy](https://www.humancellatlas.org/data-release-policy/) and licensed under the  [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/).  For more information please see our [Data Use Agreement](https://staging.data.humancellatlas.org/about/data-use-agreement)."

**Comment by lauraclarke** [comment]
Looks good to me
