### ISSUE TITLE
Ability to see new datasets in the Data Browser

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#909]
**Theme:** Explore HCA data
**User goal:** See what are the new datasets in the HCA 
**Which type of user is this for:**

- [x] Researcher with a pipette
- [x] Researcher with a keyboard
- [x] Analysis road - builder
- [x] Guardian of data
- [x] Stakeholder
- [x] Funder
Other

**User story:** As a visitor to the HCA data portal, I would like to see which data is new, so I can decide if I have have visited/used it before or not.
As a stakeholder for the DCP, I would like to know how many new datasets have made it to the system, so that I know the pace of how the project is going.
As a data contributor, I would like to go and easily find my dataset on the portal after I have submitted it, so that I feel proud it's made it to the platform.
As a data guardian, I would like to easily find the new datasets we have worked on in the last couple of weeks, so that I can check them and inform the contributors.

**Background/Problem:**
Recently there have been multiple new datasets added to the Portal, however the interface doesn't have a way of showing this new information to site visitors.

**Acceptance Criteria**

- [ ] Suggestions/ideas for implementation - from wranglers/UX/portal team
- [ ] Design
- [ ] Evaluation - with internal team members at minimum
- [ ] Production

**Comment by theathorn** [comment]
Need to know last updated time for any bundle in the project (Azul ticket).
Add "Last Updated" column in DB that is sortable and make that the default (latest at top).

**Comment by theathorn** [comment]
[Slack thread](https://humancellatlas.slack.com/archives/C01360XN04S/p1606847537186100).
