### ISSUE TITLE
Allow creation of full manifest for any selection, as we do for compact ones

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/data-browser#912]
I'm using the new names for manifest formats in the description below. Compact is the manifest primarily used for downloading with the CLI. The full manifest is the one that is currently only available per-project. Azul already has the ability to generate a full manifest for any subset of data files, not just all data files in a given project.

Can we add a button to the Export data dialog

<img width="637" alt="Screen Shot 2019-10-02 at 3 24 10 PM" src="https://user-images.githubusercontent.com/5143256/66086380-c0f14280-e528-11e9-84bc-ff4c9ba19434.png">

The button should appear under a heading containing

> Request full manifest for the current selection. A full manifest contains one row per data file. Each row contains all metadata properties from all entities associated with that data file. It can be large. It can also be used with the HCA Command Line Interface (HCA CLI) to download the selected data files.

For consistency, we may also reword the section for the compact manifest to say

> Request a _compact_ ~file~ manifest for the currently ~query~ _selection_ for use with the HCA Command Line Interface (HCA CLI) to download the selected data (e.g. fastqs, BAMs) and metadata.

This was inspired by second paragraph in @mshadbolt's [comment](https://github.com/HumanCellAtlas/dcp-cli/issues/450#issuecomment-537405908) on Humancellatlas/dcp-cli#450

**Comment by theathorn** [comment]
If the full manifest works with the CLI do we need to have a compact manifest at all?
It seems confusing to have both...

**Comment by hannes-ucsc** [comment]
The full manifest is expensive to create and very unwieldy to use. I think we should still support both. Why is it confusing to have more than one flavor of a thing? 

Maybe the new heading should just read:

> Request full manifest for the current selection. A full manifest contains one row per data file. Each row contains all metadata properties from all entities associated with that data file. It can be large.

**Comment by theathorn** [comment]
More substantive version of #841.

**Comment by theathorn** [comment]
> The UI should always offer both flavors (full and compact) in close proximity to each other, and display a description explaining the difference between them when the user hovers over each alternative.

(@hannes-ucsc)

**Comment by NoopDog** [comment]
Is this still valid in the 2.0 world? Perhaps we can figure out a way to have a single format or list the metadata in a separate file type from the manifest.

**Comment by mshadbolt** [comment]
Is there a plan for how we will be presenting metadata to consumers in the 2.0 world? 

I thought I had heard that all downloads will happen via the browser rather than a cli so not sure if there will still be a manifest generated by consumers that want to download?

**Comment by theathorn** [comment]
Also see #954.

**Comment by NoopDog** [comment]
Obsolete, as the full manifest is deprecated.
