### ISSUE TITLE
Keep recent matrix service requests in local storage and list for users

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#914]
So they don't have to keep the browser window open while waiting for a matrix to complete.

**Comment by ESapenaVentura** [comment]
+1 to @NoopDog 

Also, a more future-oriented request, would it be possible to give a job id and give the possibility to the user to come back for the matrix with that job id? Or even better, to automatically e-mail (if the user provides an email in the request for the matrix) the user when the matrix is done?

**Comment by NoopDog** [comment]
Closing as matrix service is being sunset.
