### ISSUE TITLE
Add a data citation section to the project details page

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#916]
Text should be something like "To cite this project please copy this link" where the link is a stable project URL (e.g. https://data.humancellatlas.org/explore/projects/cc95ff89-2e68-4a08-a234-480eca21ce79).

The citation should also call out the Data Use Agreement (https://data.humancellatlas.org/about/data-use-agreement) and the most recent publication along with a list of authors to acknowledge.

I see that "Publications", "Contributors", "Accessions" and "Data Release Policy" are already on the project details page. Maybe these could be grouped together along with the data citation link in a "Citation" section?

An example: https://www.repository.cam.ac.uk/handle/1810/290242

**Comment by MillenniumFalconMechanic** [comment]
#508.

**Comment by MillenniumFalconMechanic** [comment]
Completed.
