### ISSUE TITLE
Resolve Chalice redeploy error

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#93]
Matt Weiden [2:43 PM]
after reviewing the emails, it’s possible that there might be something wrong with your credentials setup
do those credentials work with other CLI commands?

I would re-watch the video in this instruction segment

Matt Weiden [2:47 PM]
added this Perl snippet: Untitled 
Watch the video and follow along using data below.
​
Login link `https://hca-id.signin.aws.amazon.com/console` user `<username>` password `<password>`
​
Assume Role: account `109067257620` role `dcp-admin` name `dcp-admin @ hca-prod` color RED.

Matt Weiden [2:57 PM]
the other config is below
```[profile hca]
role_arn = arn:aws:iam::861229788715:role/dcp-admin
source_profile = hca-id```
you probably have this correct, but it is important to sanity check this

caaespin [3:05 PM]
it’s just the final redeployment step in chalice which is causing the pain - deleting the role on AWS (which is done by the chalice library itself).

The problem is being reported by Jyo. I know he only has developer rights, so i don’t know if that could factor in the problem

Matt Weiden [3:05 PM]
OK, deleting a role is probably not a permission he has
deletion is generally restricted just to admins
you may need to deploy for him

caaespin [3:07 PM]
Hmm I would have imagined that developers could redeploy whenever needed. What’s even more interesting is that they can create a role (via chalice), but not delete it afterwards in order to update

Matt Weiden [3:07 PM]
The way that IAM permissions work, I wouldn’t be surprised
and remember there is no permission `iam:Redeploy`
deployment is built out of subcommands to different AWS resources
one of those is probably `iam:DeleteRole` which is admin only

┆Issue Number: HCAB-135

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/cgp-dss-azul-indexer/commit/a3a109ab60babbb16ae866b36b3f6a0807411133 potentially fixes this. We need @jvlasblom to try again with the new code. Please reopen if not fixed.
