### ISSUE TITLE
"Hide" spatio temporal kidney project

### ISSUE THREAD

**Issue by jahilton** [DataBiosphere/data-browser#944]
We have discovered that some data submitted should not have been released (GDPR concerns). The plan is to completely tombstone the existing project, re-ingest the 'OK' data, and re-use the project uuid.
project uuid: abe1a013-af7a-45ed-8c26-f3793c24a1f4

We _know_ that the project page url is in a publication.

ASAP, we'd for the project url (https://data.humancellatlas.org/explore/projects/abe1a013-af7a-45ed-8c26-f3793c24a1f4) to show a page of "Project update in progress. We apologize for the inconvenience." (or something similar)
Once re-ingest is complete, we'll show the new version of the project.

**Comment by jahilton** [comment]
@HumanCellAtlas/data-ops

**Comment by NoopDog** [comment]
@theathorn should we use the same technique we used for the redirect page to give the "Project update in progress" notice here? @MillenniumFalconMechanic
