### ISSUE TITLE
Review Data Browser queries and query roadmap

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#953]
General review of the queries offered and how this matches what users are trying to do.

lets review issues from:

https://github.com/HumanCellAtlas/data-browser/issues/993
https://github.com/HumanCellAtlas/data-browser/issues/992

**Comment by theathorn** [comment]
Not sure what this is exactly - close if no longer relevant.

**Comment by MillenniumFalconMechanic** [comment]
This was for an Oversight meeting that was canceled. Closing.
