### ISSUE TITLE
Add option for downloading 'compact' or 'full' metadata TSV

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/data-browser#954]
Allow user to select between "full" manifest (currently an icon per project in the "Metadata" column) and "compact" manifest (currently in Export Selected Data" dialog).

**Comment by NoopDog** [comment]
@hannes-ucsc @theathorn is this still relevant with DCP2.0? Is there an opportunity to end up with a single metadata tsv format in the 2.0 world?

**Comment by theathorn** [comment]
@hannes-ucsc Since the HCA CLI and Matrix Service are deprecated for DCP/2, can we consolidate to a single 'full" metadata tsv?

**Comment by MillenniumFalconMechanic** [comment]
Obsolete.
