### ISSUE TITLE
Correct "Sample Id" and "Sample Type" display in Files tab of the Reprogrammed_Dendritic_Cells project

### ISSUE THREAD

**Issue by jlzamanian** [DataBiosphere/data-browser#980]
See explore data page for the "[Single cell profiling of human induced dendritic cells generated by direct reprogramming of embryonic fibroblasts](https://data.humancellatlas.org/explore/files?filter=%5B%7B%22facetName%22%3A%22projectTitle%22%2C%22terms%22%3A%5B%22Single+cell+profiling+of+human+induced+dendritic+cells+generated+by+direct+reprogramming+of+embryonic+fibroblasts%22%5D%7D%2C%7B%22facetName%22%3A%22projectId%22%2C%22terms%22%3A%5B%5D%7D%5D)" project.

The "Sample Id" column in the files tab has been randomly populated from 2 entries in the Azul field. 

Where the field contains "Specimen1", Sample Id should be "Specimen1".
Where the field contains "Cell_line_2", "Specimen1", Sample Id should be "Cell_line_2".
Where the field contains "Specimen1", "Cell_line_1", Sample Id should be "Cell_line_1".

For this project, the "Sample Type" column should list cellLines before specimen when both are present because cellLines is the most experimentally relevant information.

See discussion in the data-browser slack channel on 11/13/19 starting 1:46 PM.

Note that the Sample Id column in the Samples tab is displaying correctly.

**Comment by jlzamanian** [comment]
Since the current display of Sample Type is inconsistent between the samples tab (shows a single final sample type entry) and the files tab (shows both the intermediate and final entries), we need to confirm with the wranglers which is the preferred display.

**Comment by jlzamanian** [comment]
On further examination, this display issue is likely due to an incorrect project linking graph structure. The project will need to be re-ingested to fix the linking. 

Re-ingestion of the project is not currently on the sprint schedule and will likely not happen until Q1 2020. If possible, we'd like the display issue corrected in the meantime.

**Comment by theathorn** [comment]
@lauraclarke  Metadata for this project should be corrected during the re-import of data into the DCP/2 Terra Data Repo for MVP.

**Comment by theathorn** [comment]
The issue described appears to be fixed.
Noting that the "Sample Id" for some specimens is a value such as "specimen_from_organism_116965f3-f094-4769-9d28-ae675c1b569c" as opposed to "Specimen1" (see #1514).
