### ISSUE TITLE
Integration with Seven Bridges

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#985]
- 7B to support a "list of user selected files" hand-off, similar to the Terra demo
  - DCP will implement a hand-off button/link in the Data Browser (similar to Terra hand-off)
  - 7B to discuss the desired format of the file list: Avro/PFB vs tsv manifest vs BdBag (all using pre-signed URL)
  - DCP to implement support for DRS 1.0
  - 7B will support 202 return with "retry after" as per DRS 1.0 spec

**Comment by NoopDog** [comment]
Obsolete we can re-open if this becomes a requirement
