### ISSUE TITLE
Only expose required metadata fields via the browser interface.

### ISSUE THREAD

**Issue by ambrosejcarr** [DataBiosphere/data-browser#989]
Hi! there are discussions in HumanCellAtlas/ingest-central#609 that revealed that we're exposing metadata fields that aren't required via the data portal. My sense is that if it's important enough for us to share via the browser, we should require it to be filled in by submitters. 

The only example of this I can see is the "selected cell type" column, which in many cases its value is "unspecified". 

I can understand why it might not be required from a contribution stand-point. Because some people _don't_ pre-select, we don't want to bother them with a field that's irrelevant. However, if we need that data to present it properly for our users, I think that's a valid reason to require this field. 

N.B. I have [other issues](https://github.com/HumanCellAtlas/ingest-central/issues/609#issuecomment-549863858) with the "selected cell type" field, and suggest we discuss replacing it.

**Comment by MillenniumFalconMechanic** [comment]
@NoopDog, let's review and determine how many non-required fields are currently showing.

**Comment by NoopDog** [comment]
closing, obsolete
